TYPE=VIEW
query=select distinct `_functionalci`.`id` AS `id`,`_functionalci`.`name` AS `name`,`_functionalci`.`description` AS `description`,`_functionalci`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `organization_name`,`_functionalci`.`business_criticity` AS `business_criticity`,`_functionalci`.`move2production` AS `move2production`,`_webapplication`.`webserver_id` AS `webserver_id`,`WebServer_webserver_id_functionalci`.`name` AS `webserver_name`,`_webapplication`.`url` AS `url`,`_functionalci`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`WebServer_webserver_id_softwareinstance`.`status` = \'inactive\'),0),0) AS `obsolescence_flag`,`_functionalci`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`WebServer_webserver_id_functionalci`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`FunctionalCI_system_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `webserver_id_friendlyname`,coalesce((`WebServer_webserver_id_softwareinstance`.`status` = \'inactive\'),0) AS `webserver_id_obsolescence_flag` from ((`itop`.`functionalci` `_functionalci` join `itop`.`organization` `Organization_org_id_organization` on((`_functionalci`.`org_id` = `Organization_org_id_organization`.`id`))) join (`itop`.`webapplication` `_webapplication` join (`itop`.`functionalci` `WebServer_webserver_id_functionalci` join (`itop`.`softwareinstance` `WebServer_webserver_id_softwareinstance` join `itop`.`functionalci` `FunctionalCI_system_id_functionalci` on((`WebServer_webserver_id_softwareinstance`.`functionalci_id` = `FunctionalCI_system_id_functionalci`.`id`))) on((`WebServer_webserver_id_functionalci`.`id` = `WebServer_webserver_id_softwareinstance`.`id`))) on((`_webapplication`.`webserver_id` = `WebServer_webserver_id_functionalci`.`id`))) on((`_functionalci`.`id` = `_webapplication`.`id`))) where (coalesce((`_functionalci`.`finalclass` = \'WebApplication\'),1) and coalesce((`WebServer_webserver_id_functionalci`.`finalclass` = \'WebServer\'),1))
md5=f02f29e82f593b021ca1e637037d286f
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:05
create-version=1
source=SELECT DISTINCT `_functionalci`.`id` AS `id`, `_functionalci`.`name` AS `name`, `_functionalci`.`description` AS `description`, `_functionalci`.`org_id` AS `org_id`, `Organization_org_id_organization`.`name` AS `organization_name`, `_functionalci`.`business_criticity` AS `business_criticity`, `_functionalci`.`move2production` AS `move2production`, `_webapplication`.`webserver_id` AS `webserver_id`, `WebServer_webserver_id_functionalci`.`name` AS `webserver_name`, `_webapplication`.`url` AS `url`, `_functionalci`.`finalclass` AS `finalclass`, CAST(CONCAT(COALESCE(`_functionalci`.`name`, \'\')) AS CHAR) AS `friendlyname`, COALESCE(COALESCE((`WebServer_webserver_id_softwareinstance`.`status` = \'inactive\'), 0), 0) AS `obsolescence_flag`, `_functionalci`.`obsolescence_date` AS `obsolescence_date`, CAST(CONCAT(COALESCE(`Organization_org_id_organization`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`, COALESCE((`Organization_org_id_organization`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`WebServer_webserver_id_functionalci`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`FunctionalCI_system_id_functionalci`.`name`, \'\')) AS CHAR) AS `webserver_id_friendlyname`, COALESCE((`WebServer_webserver_id_softwareinstance`.`status` = \'inactive\'), 0) AS `webserver_id_obsolescence_flag` FROM `functionalci` AS `_functionalci`INNER JOIN `organization` AS `Organization_org_id_organization` ON `_functionalci`.`org_id` = `Organization_org_id_organization`.`id`INNER JOIN (`webapplication` AS `_webapplication` INNER JOIN (`functionalci` AS `WebServer_webserver_id_functionalci` INNER JOIN (`softwareinstance` AS `WebServer_webserver_id_softwareinstance` INNER JOIN `functionalci` AS `FunctionalCI_system_id_functionalci` ON `WebServer_webserver_id_softwareinstance`.`functionalci_id` = `FunctionalCI_system_id_functionalci`.`id`) ON `WebServer_webserver_id_functionalci`.`id` = `WebServer_webserver_id_softwareinstance`.`id`) ON `_webapplication`.`webserver_id` = `WebServer_webserver_id_functionalci`.`id`) ON `_functionalci`.`id` = `_webapplication`.`id` WHERE (COALESCE((`_functionalci`.`finalclass` IN (\'WebApplication\')), 1) AND COALESCE((`WebServer_webserver_id_functionalci`.`finalclass` IN (\'WebServer\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_functionalci`.`id` AS `id`,`_functionalci`.`name` AS `name`,`_functionalci`.`description` AS `description`,`_functionalci`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `organization_name`,`_functionalci`.`business_criticity` AS `business_criticity`,`_functionalci`.`move2production` AS `move2production`,`_webapplication`.`webserver_id` AS `webserver_id`,`WebServer_webserver_id_functionalci`.`name` AS `webserver_name`,`_webapplication`.`url` AS `url`,`_functionalci`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`WebServer_webserver_id_softwareinstance`.`status` = \'inactive\'),0),0) AS `obsolescence_flag`,`_functionalci`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`WebServer_webserver_id_functionalci`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`FunctionalCI_system_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `webserver_id_friendlyname`,coalesce((`WebServer_webserver_id_softwareinstance`.`status` = \'inactive\'),0) AS `webserver_id_obsolescence_flag` from ((`itop`.`functionalci` `_functionalci` join `itop`.`organization` `Organization_org_id_organization` on((`_functionalci`.`org_id` = `Organization_org_id_organization`.`id`))) join (`itop`.`webapplication` `_webapplication` join (`itop`.`functionalci` `WebServer_webserver_id_functionalci` join (`itop`.`softwareinstance` `WebServer_webserver_id_softwareinstance` join `itop`.`functionalci` `FunctionalCI_system_id_functionalci` on((`WebServer_webserver_id_softwareinstance`.`functionalci_id` = `FunctionalCI_system_id_functionalci`.`id`))) on((`WebServer_webserver_id_functionalci`.`id` = `WebServer_webserver_id_softwareinstance`.`id`))) on((`_webapplication`.`webserver_id` = `WebServer_webserver_id_functionalci`.`id`))) on((`_functionalci`.`id` = `_webapplication`.`id`))) where (coalesce((`_functionalci`.`finalclass` = \'WebApplication\'),1) and coalesce((`WebServer_webserver_id_functionalci`.`finalclass` = \'WebServer\'),1))
