TYPE=VIEW
query=select distinct `_attachment`.`id` AS `id`,`_attachment`.`expire` AS `expire`,`_attachment`.`temp_id` AS `temp_id`,`_attachment`.`item_class` AS `item_class`,`_attachment`.`item_id` AS `item_id`,`_attachment`.`item_org_id` AS `item_org_id`,`_attachment`.`contents_mimetype` AS `contents`,`_attachment`.`contents_data` AS `contents_data`,`_attachment`.`contents_filename` AS `contents_filename`,cast(concat(coalesce(`_attachment`.`item_class`,\'\'),coalesce(\' \',\'\'),coalesce(`_attachment`.`temp_id`,\'\')) as char charset utf8mb4) AS `friendlyname` from `itop`.`attachment` `_attachment` where 1
md5=031658e620f68d59cf0e78f13dd91ed1
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:04
create-version=1
source=SELECT DISTINCT `_attachment`.`id` AS `id`, `_attachment`.`expire` AS `expire`, `_attachment`.`temp_id` AS `temp_id`, `_attachment`.`item_class` AS `item_class`, `_attachment`.`item_id` AS `item_id`, `_attachment`.`item_org_id` AS `item_org_id`, `_attachment`.`contents_mimetype` AS `contents`, `_attachment`.`contents_data` AS `contents_data`, `_attachment`.`contents_filename` AS `contents_filename`, CAST(CONCAT(COALESCE(`_attachment`.`item_class`, \'\'), COALESCE(\' \', \'\'), COALESCE(`_attachment`.`temp_id`, \'\')) AS CHAR) AS `friendlyname` FROM `attachment` AS `_attachment` WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_attachment`.`id` AS `id`,`_attachment`.`expire` AS `expire`,`_attachment`.`temp_id` AS `temp_id`,`_attachment`.`item_class` AS `item_class`,`_attachment`.`item_id` AS `item_id`,`_attachment`.`item_org_id` AS `item_org_id`,`_attachment`.`contents_mimetype` AS `contents`,`_attachment`.`contents_data` AS `contents_data`,`_attachment`.`contents_filename` AS `contents_filename`,cast(concat(coalesce(`_attachment`.`item_class`,\'\'),coalesce(\' \',\'\'),coalesce(`_attachment`.`temp_id`,\'\')) as char charset utf8mb4) AS `friendlyname` from `itop`.`attachment` `_attachment` where 1
