TYPE=VIEW
query=select distinct `_functionalci`.`id` AS `id`,`_functionalci`.`name` AS `name`,`_functionalci`.`description` AS `description`,`_functionalci`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `organization_name`,`_functionalci`.`business_criticity` AS `business_criticity`,`_functionalci`.`move2production` AS `move2production`,`_databaseschema`.`dbserver_id` AS `dbserver_id`,`DBServer_dbserver_id_functionalci`.`name` AS `dbserver_name`,`_functionalci`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`DBServer_dbserver_id_softwareinstance`.`status` = \'inactive\'),0),0) AS `obsolescence_flag`,`_functionalci`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`DBServer_dbserver_id_functionalci`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`FunctionalCI_system_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `dbserver_id_friendlyname`,coalesce((`DBServer_dbserver_id_softwareinstance`.`status` = \'inactive\'),0) AS `dbserver_id_obsolescence_flag` from ((`itop`.`functionalci` `_functionalci` join `itop`.`organization` `Organization_org_id_organization` on((`_functionalci`.`org_id` = `Organization_org_id_organization`.`id`))) join (`itop`.`databaseschema` `_databaseschema` join (`itop`.`functionalci` `DBServer_dbserver_id_functionalci` join (`itop`.`softwareinstance` `DBServer_dbserver_id_softwareinstance` join `itop`.`functionalci` `FunctionalCI_system_id_functionalci` on((`DBServer_dbserver_id_softwareinstance`.`functionalci_id` = `FunctionalCI_system_id_functionalci`.`id`))) on((`DBServer_dbserver_id_functionalci`.`id` = `DBServer_dbserver_id_softwareinstance`.`id`))) on((`_databaseschema`.`dbserver_id` = `DBServer_dbserver_id_functionalci`.`id`))) on((`_functionalci`.`id` = `_databaseschema`.`id`))) where (coalesce((`_functionalci`.`finalclass` = \'DatabaseSchema\'),1) and coalesce((`DBServer_dbserver_id_functionalci`.`finalclass` = \'DBServer\'),1))
md5=3dc3d4f1b6ff0036513996003bec61f3
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:05
create-version=1
source=SELECT DISTINCT `_functionalci`.`id` AS `id`, `_functionalci`.`name` AS `name`, `_functionalci`.`description` AS `description`, `_functionalci`.`org_id` AS `org_id`, `Organization_org_id_organization`.`name` AS `organization_name`, `_functionalci`.`business_criticity` AS `business_criticity`, `_functionalci`.`move2production` AS `move2production`, `_databaseschema`.`dbserver_id` AS `dbserver_id`, `DBServer_dbserver_id_functionalci`.`name` AS `dbserver_name`, `_functionalci`.`finalclass` AS `finalclass`, CAST(CONCAT(COALESCE(`_functionalci`.`name`, \'\')) AS CHAR) AS `friendlyname`, COALESCE(COALESCE((`DBServer_dbserver_id_softwareinstance`.`status` = \'inactive\'), 0), 0) AS `obsolescence_flag`, `_functionalci`.`obsolescence_date` AS `obsolescence_date`, CAST(CONCAT(COALESCE(`Organization_org_id_organization`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`, COALESCE((`Organization_org_id_organization`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`DBServer_dbserver_id_functionalci`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`FunctionalCI_system_id_functionalci`.`name`, \'\')) AS CHAR) AS `dbserver_id_friendlyname`, COALESCE((`DBServer_dbserver_id_softwareinstance`.`status` = \'inactive\'), 0) AS `dbserver_id_obsolescence_flag` FROM `functionalci` AS `_functionalci`INNER JOIN `organization` AS `Organization_org_id_organization` ON `_functionalci`.`org_id` = `Organization_org_id_organization`.`id`INNER JOIN (`databaseschema` AS `_databaseschema` INNER JOIN (`functionalci` AS `DBServer_dbserver_id_functionalci` INNER JOIN (`softwareinstance` AS `DBServer_dbserver_id_softwareinstance` INNER JOIN `functionalci` AS `FunctionalCI_system_id_functionalci` ON `DBServer_dbserver_id_softwareinstance`.`functionalci_id` = `FunctionalCI_system_id_functionalci`.`id`) ON `DBServer_dbserver_id_functionalci`.`id` = `DBServer_dbserver_id_softwareinstance`.`id`) ON `_databaseschema`.`dbserver_id` = `DBServer_dbserver_id_functionalci`.`id`) ON `_functionalci`.`id` = `_databaseschema`.`id` WHERE (COALESCE((`_functionalci`.`finalclass` IN (\'DatabaseSchema\')), 1) AND COALESCE((`DBServer_dbserver_id_functionalci`.`finalclass` IN (\'DBServer\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_functionalci`.`id` AS `id`,`_functionalci`.`name` AS `name`,`_functionalci`.`description` AS `description`,`_functionalci`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `organization_name`,`_functionalci`.`business_criticity` AS `business_criticity`,`_functionalci`.`move2production` AS `move2production`,`_databaseschema`.`dbserver_id` AS `dbserver_id`,`DBServer_dbserver_id_functionalci`.`name` AS `dbserver_name`,`_functionalci`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`DBServer_dbserver_id_softwareinstance`.`status` = \'inactive\'),0),0) AS `obsolescence_flag`,`_functionalci`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`DBServer_dbserver_id_functionalci`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`FunctionalCI_system_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `dbserver_id_friendlyname`,coalesce((`DBServer_dbserver_id_softwareinstance`.`status` = \'inactive\'),0) AS `dbserver_id_obsolescence_flag` from ((`itop`.`functionalci` `_functionalci` join `itop`.`organization` `Organization_org_id_organization` on((`_functionalci`.`org_id` = `Organization_org_id_organization`.`id`))) join (`itop`.`databaseschema` `_databaseschema` join (`itop`.`functionalci` `DBServer_dbserver_id_functionalci` join (`itop`.`softwareinstance` `DBServer_dbserver_id_softwareinstance` join `itop`.`functionalci` `FunctionalCI_system_id_functionalci` on((`DBServer_dbserver_id_softwareinstance`.`functionalci_id` = `FunctionalCI_system_id_functionalci`.`id`))) on((`DBServer_dbserver_id_functionalci`.`id` = `DBServer_dbserver_id_softwareinstance`.`id`))) on((`_databaseschema`.`dbserver_id` = `DBServer_dbserver_id_functionalci`.`id`))) on((`_functionalci`.`id` = `_databaseschema`.`id`))) where (coalesce((`_functionalci`.`finalclass` = \'DatabaseSchema\'),1) and coalesce((`DBServer_dbserver_id_functionalci`.`finalclass` = \'DBServer\'),1))
