TYPE=VIEW
query=select distinct `_licence`.`id` AS `id`,`_licence`.`name` AS `name`,`_licence`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `organization_name`,`_licence`.`usage_limit` AS `usage_limit`,`_licence`.`description` AS `description`,`_licence`.`start_date` AS `start_date`,`_licence`.`end_date` AS `end_date`,`_licence`.`licence_key` AS `licence_key`,`_licence`.`perpetual` AS `perpetual`,`_softwarelicence`.`software_id` AS `software_id`,`Software_software_id_software`.`name` AS `software_name`,`_licence`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_licence`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(((`_licence`.`perpetual` = \'no\') and (isnull(`_licence`.`end_date`) = 0) and (`_licence`.`end_date` < date_format((now() - interval 15 month),\'%Y-%m-%d 00:00:00\'))),0) AS `obsolescence_flag`,`_licence`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Software_software_id_software`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`Software_software_id_software`.`version`,\'\')) as char charset utf8mb4) AS `software_id_friendlyname` from ((`itop`.`licence` `_licence` join `itop`.`organization` `Organization_org_id_organization` on((`_licence`.`org_id` = `Organization_org_id_organization`.`id`))) join (`itop`.`softwarelicence` `_softwarelicence` join `itop`.`software` `Software_software_id_software` on((`_softwarelicence`.`software_id` = `Software_software_id_software`.`id`))) on((`_licence`.`id` = `_softwarelicence`.`id`))) where coalesce((`_licence`.`finalclass` = \'SoftwareLicence\'),1)
md5=12e9b9ed2241cf461607a93fc284667c
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:05
create-version=1
source=SELECT DISTINCT `_licence`.`id` AS `id`, `_licence`.`name` AS `name`, `_licence`.`org_id` AS `org_id`, `Organization_org_id_organization`.`name` AS `organization_name`, `_licence`.`usage_limit` AS `usage_limit`, `_licence`.`description` AS `description`, `_licence`.`start_date` AS `start_date`, `_licence`.`end_date` AS `end_date`, `_licence`.`licence_key` AS `licence_key`, `_licence`.`perpetual` AS `perpetual`, `_softwarelicence`.`software_id` AS `software_id`, `Software_software_id_software`.`name` AS `software_name`, `_licence`.`finalclass` AS `finalclass`, CAST(CONCAT(COALESCE(`_licence`.`name`, \'\')) AS CHAR) AS `friendlyname`, COALESCE((((`_licence`.`perpetual` = \'no\') AND (ISNULL(`_licence`.`end_date`) = 0)) AND (`_licence`.`end_date` < DATE_FORMAT(DATE_SUB(NOW(), INTERVAL 15 MONTH), \'%Y-%m-%d 00:00:00\'))), 0) AS `obsolescence_flag`, `_licence`.`obsolescence_date` AS `obsolescence_date`, CAST(CONCAT(COALESCE(`Organization_org_id_organization`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`, COALESCE((`Organization_org_id_organization`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`Software_software_id_software`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Software_software_id_software`.`version`, \'\')) AS CHAR) AS `software_id_friendlyname` FROM `licence` AS `_licence`INNER JOIN `organization` AS `Organization_org_id_organization` ON `_licence`.`org_id` = `Organization_org_id_organization`.`id`INNER JOIN (`softwarelicence` AS `_softwarelicence` INNER JOIN `software` AS `Software_software_id_software` ON `_softwarelicence`.`software_id` = `Software_software_id_software`.`id`) ON `_licence`.`id` = `_softwarelicence`.`id` WHERE COALESCE((`_licence`.`finalclass` IN (\'SoftwareLicence\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_licence`.`id` AS `id`,`_licence`.`name` AS `name`,`_licence`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `organization_name`,`_licence`.`usage_limit` AS `usage_limit`,`_licence`.`description` AS `description`,`_licence`.`start_date` AS `start_date`,`_licence`.`end_date` AS `end_date`,`_licence`.`licence_key` AS `licence_key`,`_licence`.`perpetual` AS `perpetual`,`_softwarelicence`.`software_id` AS `software_id`,`Software_software_id_software`.`name` AS `software_name`,`_licence`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_licence`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(((`_licence`.`perpetual` = \'no\') and (isnull(`_licence`.`end_date`) = 0) and (`_licence`.`end_date` < date_format((now() - interval 15 month),\'%Y-%m-%d 00:00:00\'))),0) AS `obsolescence_flag`,`_licence`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Software_software_id_software`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`Software_software_id_software`.`version`,\'\')) as char charset utf8mb4) AS `software_id_friendlyname` from ((`itop`.`licence` `_licence` join `itop`.`organization` `Organization_org_id_organization` on((`_licence`.`org_id` = `Organization_org_id_organization`.`id`))) join (`itop`.`softwarelicence` `_softwarelicence` join `itop`.`software` `Software_software_id_software` on((`_softwarelicence`.`software_id` = `Software_software_id_software`.`id`))) on((`_licence`.`id` = `_softwarelicence`.`id`))) where coalesce((`_licence`.`finalclass` = \'SoftwareLicence\'),1)
