TYPE=VIEW
query=select distinct `_functionalci`.`id` AS `id`,`_functionalci`.`name` AS `name`,`_functionalci`.`description` AS `description`,`_functionalci`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `organization_name`,`_functionalci`.`business_criticity` AS `business_criticity`,`_functionalci`.`move2production` AS `move2production`,`_middlewareinstance`.`middleware_id` AS `middleware_id`,`Middleware_middleware_id_functionalci`.`name` AS `middleware_name`,`_functionalci`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`Middleware_middleware_id_softwareinstance`.`status` = \'inactive\'),0),0) AS `obsolescence_flag`,`_functionalci`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Middleware_middleware_id_functionalci`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`FunctionalCI_system_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `middleware_id_friendlyname`,coalesce((`Middleware_middleware_id_softwareinstance`.`status` = \'inactive\'),0) AS `middleware_id_obsolescence_flag` from ((`itop`.`functionalci` `_functionalci` join `itop`.`organization` `Organization_org_id_organization` on((`_functionalci`.`org_id` = `Organization_org_id_organization`.`id`))) join (`itop`.`middlewareinstance` `_middlewareinstance` join (`itop`.`functionalci` `Middleware_middleware_id_functionalci` join (`itop`.`softwareinstance` `Middleware_middleware_id_softwareinstance` join `itop`.`functionalci` `FunctionalCI_system_id_functionalci` on((`Middleware_middleware_id_softwareinstance`.`functionalci_id` = `FunctionalCI_system_id_functionalci`.`id`))) on((`Middleware_middleware_id_functionalci`.`id` = `Middleware_middleware_id_softwareinstance`.`id`))) on((`_middlewareinstance`.`middleware_id` = `Middleware_middleware_id_functionalci`.`id`))) on((`_functionalci`.`id` = `_middlewareinstance`.`id`))) where (coalesce((`_functionalci`.`finalclass` = \'MiddlewareInstance\'),1) and coalesce((`Middleware_middleware_id_functionalci`.`finalclass` = \'Middleware\'),1))
md5=ea7fca7507dbf8d69439b8b9b45abff6
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:05
create-version=1
source=SELECT DISTINCT `_functionalci`.`id` AS `id`, `_functionalci`.`name` AS `name`, `_functionalci`.`description` AS `description`, `_functionalci`.`org_id` AS `org_id`, `Organization_org_id_organization`.`name` AS `organization_name`, `_functionalci`.`business_criticity` AS `business_criticity`, `_functionalci`.`move2production` AS `move2production`, `_middlewareinstance`.`middleware_id` AS `middleware_id`, `Middleware_middleware_id_functionalci`.`name` AS `middleware_name`, `_functionalci`.`finalclass` AS `finalclass`, CAST(CONCAT(COALESCE(`_functionalci`.`name`, \'\')) AS CHAR) AS `friendlyname`, COALESCE(COALESCE((`Middleware_middleware_id_softwareinstance`.`status` = \'inactive\'), 0), 0) AS `obsolescence_flag`, `_functionalci`.`obsolescence_date` AS `obsolescence_date`, CAST(CONCAT(COALESCE(`Organization_org_id_organization`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`, COALESCE((`Organization_org_id_organization`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`Middleware_middleware_id_functionalci`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`FunctionalCI_system_id_functionalci`.`name`, \'\')) AS CHAR) AS `middleware_id_friendlyname`, COALESCE((`Middleware_middleware_id_softwareinstance`.`status` = \'inactive\'), 0) AS `middleware_id_obsolescence_flag` FROM `functionalci` AS `_functionalci`INNER JOIN `organization` AS `Organization_org_id_organization` ON `_functionalci`.`org_id` = `Organization_org_id_organization`.`id`INNER JOIN (`middlewareinstance` AS `_middlewareinstance` INNER JOIN (`functionalci` AS `Middleware_middleware_id_functionalci` INNER JOIN (`softwareinstance` AS `Middleware_middleware_id_softwareinstance` INNER JOIN `functionalci` AS `FunctionalCI_system_id_functionalci` ON `Middleware_middleware_id_softwareinstance`.`functionalci_id` = `FunctionalCI_system_id_functionalci`.`id`) ON `Middleware_middleware_id_functionalci`.`id` = `Middleware_middleware_id_softwareinstance`.`id`) ON `_middlewareinstance`.`middleware_id` = `Middleware_middleware_id_functionalci`.`id`) ON `_functionalci`.`id` = `_middlewareinstance`.`id` WHERE (COALESCE((`_functionalci`.`finalclass` IN (\'MiddlewareInstance\')), 1) AND COALESCE((`Middleware_middleware_id_functionalci`.`finalclass` IN (\'Middleware\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_functionalci`.`id` AS `id`,`_functionalci`.`name` AS `name`,`_functionalci`.`description` AS `description`,`_functionalci`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `organization_name`,`_functionalci`.`business_criticity` AS `business_criticity`,`_functionalci`.`move2production` AS `move2production`,`_middlewareinstance`.`middleware_id` AS `middleware_id`,`Middleware_middleware_id_functionalci`.`name` AS `middleware_name`,`_functionalci`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`Middleware_middleware_id_softwareinstance`.`status` = \'inactive\'),0),0) AS `obsolescence_flag`,`_functionalci`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Middleware_middleware_id_functionalci`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`FunctionalCI_system_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `middleware_id_friendlyname`,coalesce((`Middleware_middleware_id_softwareinstance`.`status` = \'inactive\'),0) AS `middleware_id_obsolescence_flag` from ((`itop`.`functionalci` `_functionalci` join `itop`.`organization` `Organization_org_id_organization` on((`_functionalci`.`org_id` = `Organization_org_id_organization`.`id`))) join (`itop`.`middlewareinstance` `_middlewareinstance` join (`itop`.`functionalci` `Middleware_middleware_id_functionalci` join (`itop`.`softwareinstance` `Middleware_middleware_id_softwareinstance` join `itop`.`functionalci` `FunctionalCI_system_id_functionalci` on((`Middleware_middleware_id_softwareinstance`.`functionalci_id` = `FunctionalCI_system_id_functionalci`.`id`))) on((`Middleware_middleware_id_functionalci`.`id` = `Middleware_middleware_id_softwareinstance`.`id`))) on((`_middlewareinstance`.`middleware_id` = `Middleware_middleware_id_functionalci`.`id`))) on((`_functionalci`.`id` = `_middlewareinstance`.`id`))) where (coalesce((`_functionalci`.`finalclass` = \'MiddlewareInstance\'),1) and coalesce((`Middleware_middleware_id_functionalci`.`finalclass` = \'Middleware\'),1))
