TYPE=VIEW
query=select distinct `_knownerror`.`id` AS `id`,`_knownerror`.`name` AS `name`,`_knownerror`.`cust_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `cust_name`,`_knownerror`.`problem_id` AS `problem_id`,`Problem_problem_id_ticket`.`ref` AS `problem_ref`,`_knownerror`.`symptom` AS `symptom`,`_knownerror`.`rootcause` AS `root_cause`,`_knownerror`.`workaround` AS `workaround`,`_knownerror`.`solution` AS `solution`,`_knownerror`.`error_code` AS `error_code`,`_knownerror`.`domain` AS `domain`,`_knownerror`.`vendor` AS `vendor`,`_knownerror`.`model` AS `model`,`_knownerror`.`version` AS `version`,cast(concat(coalesce(`_knownerror`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Problem_problem_id_ticket`.`ref`,\'\')) as char charset utf8mb4) AS `problem_id_friendlyname` from ((`itop`.`knownerror` `_knownerror` join `itop`.`organization` `Organization_org_id_organization` on((`_knownerror`.`cust_id` = `Organization_org_id_organization`.`id`))) left join `itop`.`ticket` `Problem_problem_id_ticket` on((`_knownerror`.`problem_id` = `Problem_problem_id_ticket`.`id`))) where coalesce((`Problem_problem_id_ticket`.`finalclass` = \'Problem\'),1)
md5=546925e026b5b9af5bd0360d7f698353
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:07
create-version=1
source=SELECT DISTINCT `_knownerror`.`id` AS `id`, `_knownerror`.`name` AS `name`, `_knownerror`.`cust_id` AS `org_id`, `Organization_org_id_organization`.`name` AS `cust_name`, `_knownerror`.`problem_id` AS `problem_id`, `Problem_problem_id_ticket`.`ref` AS `problem_ref`, `_knownerror`.`symptom` AS `symptom`, `_knownerror`.`rootcause` AS `root_cause`, `_knownerror`.`workaround` AS `workaround`, `_knownerror`.`solution` AS `solution`, `_knownerror`.`error_code` AS `error_code`, `_knownerror`.`domain` AS `domain`, `_knownerror`.`vendor` AS `vendor`, `_knownerror`.`model` AS `model`, `_knownerror`.`version` AS `version`, CAST(CONCAT(COALESCE(`_knownerror`.`name`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`Organization_org_id_organization`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`, COALESCE((`Organization_org_id_organization`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`Problem_problem_id_ticket`.`ref`, \'\')) AS CHAR) AS `problem_id_friendlyname` FROM `knownerror` AS `_knownerror`INNER JOIN `organization` AS `Organization_org_id_organization` ON `_knownerror`.`cust_id` = `Organization_org_id_organization`.`id`LEFT JOIN `ticket` AS `Problem_problem_id_ticket` ON `_knownerror`.`problem_id` = `Problem_problem_id_ticket`.`id` WHERE COALESCE((`Problem_problem_id_ticket`.`finalclass` IN (\'Problem\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_knownerror`.`id` AS `id`,`_knownerror`.`name` AS `name`,`_knownerror`.`cust_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `cust_name`,`_knownerror`.`problem_id` AS `problem_id`,`Problem_problem_id_ticket`.`ref` AS `problem_ref`,`_knownerror`.`symptom` AS `symptom`,`_knownerror`.`rootcause` AS `root_cause`,`_knownerror`.`workaround` AS `workaround`,`_knownerror`.`solution` AS `solution`,`_knownerror`.`error_code` AS `error_code`,`_knownerror`.`domain` AS `domain`,`_knownerror`.`vendor` AS `vendor`,`_knownerror`.`model` AS `model`,`_knownerror`.`version` AS `version`,cast(concat(coalesce(`_knownerror`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Problem_problem_id_ticket`.`ref`,\'\')) as char charset utf8mb4) AS `problem_id_friendlyname` from ((`itop`.`knownerror` `_knownerror` join `itop`.`organization` `Organization_org_id_organization` on((`_knownerror`.`cust_id` = `Organization_org_id_organization`.`id`))) left join `itop`.`ticket` `Problem_problem_id_ticket` on((`_knownerror`.`problem_id` = `Problem_problem_id_ticket`.`id`))) where coalesce((`Problem_problem_id_ticket`.`finalclass` = \'Problem\'),1)
