TYPE=VIEW
query=select distinct `_service`.`id` AS `id`,`_service`.`name` AS `name`,`_service`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `organization_name`,`_service`.`servicefamily_id` AS `servicefamily_id`,`ServiceFamily_servicefamily_id_servicefamily`.`name` AS `servicefamily_name`,`_service`.`description` AS `description`,`_service`.`status` AS `status`,`_service`.`icon_mimetype` AS `icon`,`_service`.`icon_data` AS `icon_data`,`_service`.`icon_filename` AS `icon_filename`,cast(concat(coalesce(`_service`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`ServiceFamily_servicefamily_id_servicefamily`.`name`,\'\')) as char charset utf8mb4) AS `servicefamily_id_friendlyname` from ((`itop`.`service` `_service` join `itop`.`organization` `Organization_org_id_organization` on((`_service`.`org_id` = `Organization_org_id_organization`.`id`))) left join `itop`.`servicefamily` `ServiceFamily_servicefamily_id_servicefamily` on((`_service`.`servicefamily_id` = `ServiceFamily_servicefamily_id_servicefamily`.`id`))) where 1
md5=092d923dbcae3444b9cdfb46854115e3
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:07
create-version=1
source=SELECT DISTINCT `_service`.`id` AS `id`, `_service`.`name` AS `name`, `_service`.`org_id` AS `org_id`, `Organization_org_id_organization`.`name` AS `organization_name`, `_service`.`servicefamily_id` AS `servicefamily_id`, `ServiceFamily_servicefamily_id_servicefamily`.`name` AS `servicefamily_name`, `_service`.`description` AS `description`, `_service`.`status` AS `status`, `_service`.`icon_mimetype` AS `icon`, `_service`.`icon_data` AS `icon_data`, `_service`.`icon_filename` AS `icon_filename`, CAST(CONCAT(COALESCE(`_service`.`name`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`Organization_org_id_organization`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`, COALESCE((`Organization_org_id_organization`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`ServiceFamily_servicefamily_id_servicefamily`.`name`, \'\')) AS CHAR) AS `servicefamily_id_friendlyname` FROM `service` AS `_service`INNER JOIN `organization` AS `Organization_org_id_organization` ON `_service`.`org_id` = `Organization_org_id_organization`.`id`LEFT JOIN `servicefamily` AS `ServiceFamily_servicefamily_id_servicefamily` ON `_service`.`servicefamily_id` = `ServiceFamily_servicefamily_id_servicefamily`.`id` WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_service`.`id` AS `id`,`_service`.`name` AS `name`,`_service`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `organization_name`,`_service`.`servicefamily_id` AS `servicefamily_id`,`ServiceFamily_servicefamily_id_servicefamily`.`name` AS `servicefamily_name`,`_service`.`description` AS `description`,`_service`.`status` AS `status`,`_service`.`icon_mimetype` AS `icon`,`_service`.`icon_data` AS `icon_data`,`_service`.`icon_filename` AS `icon_filename`,cast(concat(coalesce(`_service`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`ServiceFamily_servicefamily_id_servicefamily`.`name`,\'\')) as char charset utf8mb4) AS `servicefamily_id_friendlyname` from ((`itop`.`service` `_service` join `itop`.`organization` `Organization_org_id_organization` on((`_service`.`org_id` = `Organization_org_id_organization`.`id`))) left join `itop`.`servicefamily` `ServiceFamily_servicefamily_id_servicefamily` on((`_service`.`servicefamily_id` = `ServiceFamily_servicefamily_id_servicefamily`.`id`))) where 1
