TYPE=VIEW
query=select distinct `_lnkcontracttodocument`.`id` AS `id`,`_lnkcontracttodocument`.`contract_id` AS `contract_id`,`Contract_contract_id_contract`.`name` AS `contract_name`,`_lnkcontracttodocument`.`document_id` AS `document_id`,`Document_document_id_document`.`name` AS `document_name`,cast(concat(coalesce(`_lnkcontracttodocument`.`contract_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkcontracttodocument`.`document_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Contract_contract_id_contract`.`name`,\'\')) as char charset utf8mb4) AS `contract_id_friendlyname`,`Contract_contract_id_contract`.`finalclass` AS `contract_id_finalclass_recall`,if((`Document_document_id_document`.`finalclass` = \'Document\'),cast(concat(coalesce(\'Document\',\'\')) as char charset utf8mb4),cast(concat(coalesce(`Document_document_id_document`.`name`,\'\')) as char charset utf8mb4)) AS `document_id_friendlyname`,`Document_document_id_document`.`finalclass` AS `document_id_finalclass_recall`,coalesce((`Document_document_id_document`.`status` = \'obsolete\'),0) AS `document_id_obsolescence_flag` from ((`itop`.`lnkcontracttodocument` `_lnkcontracttodocument` join `itop`.`contract` `Contract_contract_id_contract` on((`_lnkcontracttodocument`.`contract_id` = `Contract_contract_id_contract`.`id`))) join `itop`.`document` `Document_document_id_document` on((`_lnkcontracttodocument`.`document_id` = `Document_document_id_document`.`id`))) where 1
md5=30760fe51a9b59d58c3b1fdf3b93c04e
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:07
create-version=1
source=SELECT DISTINCT `_lnkcontracttodocument`.`id` AS `id`, `_lnkcontracttodocument`.`contract_id` AS `contract_id`, `Contract_contract_id_contract`.`name` AS `contract_name`, `_lnkcontracttodocument`.`document_id` AS `document_id`, `Document_document_id_document`.`name` AS `document_name`, CAST(CONCAT(COALESCE(`_lnkcontracttodocument`.`contract_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`_lnkcontracttodocument`.`document_id`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`Contract_contract_id_contract`.`name`, \'\')) AS CHAR) AS `contract_id_friendlyname`, `Contract_contract_id_contract`.`finalclass` AS `contract_id_finalclass_recall`, IF((`Document_document_id_document`.`finalclass` IN (\'Document\')), CAST(CONCAT(COALESCE(\'Document\', \'\')) AS CHAR), CAST(CONCAT(COALESCE(`Document_document_id_document`.`name`, \'\')) AS CHAR)) AS `document_id_friendlyname`, `Document_document_id_document`.`finalclass` AS `document_id_finalclass_recall`, COALESCE((`Document_document_id_document`.`status` = \'obsolete\'), 0) AS `document_id_obsolescence_flag` FROM `lnkcontracttodocument` AS `_lnkcontracttodocument`INNER JOIN `contract` AS `Contract_contract_id_contract` ON `_lnkcontracttodocument`.`contract_id` = `Contract_contract_id_contract`.`id`INNER JOIN `document` AS `Document_document_id_document` ON `_lnkcontracttodocument`.`document_id` = `Document_document_id_document`.`id` WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_lnkcontracttodocument`.`id` AS `id`,`_lnkcontracttodocument`.`contract_id` AS `contract_id`,`Contract_contract_id_contract`.`name` AS `contract_name`,`_lnkcontracttodocument`.`document_id` AS `document_id`,`Document_document_id_document`.`name` AS `document_name`,cast(concat(coalesce(`_lnkcontracttodocument`.`contract_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkcontracttodocument`.`document_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Contract_contract_id_contract`.`name`,\'\')) as char charset utf8mb4) AS `contract_id_friendlyname`,`Contract_contract_id_contract`.`finalclass` AS `contract_id_finalclass_recall`,if((`Document_document_id_document`.`finalclass` = \'Document\'),cast(concat(coalesce(\'Document\',\'\')) as char charset utf8mb4),cast(concat(coalesce(`Document_document_id_document`.`name`,\'\')) as char charset utf8mb4)) AS `document_id_friendlyname`,`Document_document_id_document`.`finalclass` AS `document_id_finalclass_recall`,coalesce((`Document_document_id_document`.`status` = \'obsolete\'),0) AS `document_id_obsolescence_flag` from ((`itop`.`lnkcontracttodocument` `_lnkcontracttodocument` join `itop`.`contract` `Contract_contract_id_contract` on((`_lnkcontracttodocument`.`contract_id` = `Contract_contract_id_contract`.`id`))) join `itop`.`document` `Document_document_id_document` on((`_lnkcontracttodocument`.`document_id` = `Document_document_id_document`.`id`))) where 1
