TYPE=VIEW
query=select distinct `_lnkdatacenterdevicetosan`.`id` AS `id`,`_lnkdatacenterdevicetosan`.`san_id` AS `san_id`,`SANSwitch_san_id_functionalci`.`name` AS `san_name`,`_lnkdatacenterdevicetosan`.`datacenterdevice_id` AS `datacenterdevice_id`,`DatacenterDevice_datacenterdevice_id_functionalci`.`name` AS `datacenterdevice_name`,`_lnkdatacenterdevicetosan`.`san_port` AS `san_port`,`_lnkdatacenterdevicetosan`.`datacenterdevice_port` AS `datacenterdevice_port`,cast(concat(coalesce(`_lnkdatacenterdevicetosan`.`san_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`SANSwitch_san_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `san_id_friendlyname`,coalesce((`SANSwitch_san_id_physicaldevice`.`status` = \'obsolete\'),0) AS `san_id_obsolescence_flag`,cast(concat(coalesce(`DatacenterDevice_datacenterdevice_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `datacenterdevice_id_friendlyname`,`DatacenterDevice_datacenterdevice_id_functionalci`.`finalclass` AS `datacenterdevice_id_finalclass_recall`,coalesce((`DatacenterDevice_datacenterdevice_id_physicaldevice`.`status` = \'obsolete\'),0) AS `datacenterdevice_id_obsolescence_flag` from ((`itop`.`lnkdatacenterdevicetosan` `_lnkdatacenterdevicetosan` join (`itop`.`functionalci` `SANSwitch_san_id_functionalci` join `itop`.`physicaldevice` `SANSwitch_san_id_physicaldevice` on((`SANSwitch_san_id_functionalci`.`id` = `SANSwitch_san_id_physicaldevice`.`id`))) on((`_lnkdatacenterdevicetosan`.`san_id` = `SANSwitch_san_id_functionalci`.`id`))) join (`itop`.`functionalci` `DatacenterDevice_datacenterdevice_id_functionalci` join `itop`.`physicaldevice` `DatacenterDevice_datacenterdevice_id_physicaldevice` on((`DatacenterDevice_datacenterdevice_id_functionalci`.`id` = `DatacenterDevice_datacenterdevice_id_physicaldevice`.`id`))) on((`_lnkdatacenterdevicetosan`.`datacenterdevice_id` = `DatacenterDevice_datacenterdevice_id_functionalci`.`id`))) where (coalesce((`SANSwitch_san_id_functionalci`.`finalclass` = \'SANSwitch\'),1) and coalesce((`DatacenterDevice_datacenterdevice_id_functionalci`.`finalclass` in (\'NetworkDevice\',\'Server\',\'StorageSystem\',\'SANSwitch\',\'TapeLibrary\',\'NAS\',\'DatacenterDevice\')),1))
md5=b46ceaa1f0f31a6df9d1c77019bdc6fa
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:06
create-version=1
source=SELECT DISTINCT `_lnkdatacenterdevicetosan`.`id` AS `id`, `_lnkdatacenterdevicetosan`.`san_id` AS `san_id`, `SANSwitch_san_id_functionalci`.`name` AS `san_name`, `_lnkdatacenterdevicetosan`.`datacenterdevice_id` AS `datacenterdevice_id`, `DatacenterDevice_datacenterdevice_id_functionalci`.`name` AS `datacenterdevice_name`, `_lnkdatacenterdevicetosan`.`san_port` AS `san_port`, `_lnkdatacenterdevicetosan`.`datacenterdevice_port` AS `datacenterdevice_port`, CAST(CONCAT(COALESCE(`_lnkdatacenterdevicetosan`.`san_id`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`SANSwitch_san_id_functionalci`.`name`, \'\')) AS CHAR) AS `san_id_friendlyname`, COALESCE((`SANSwitch_san_id_physicaldevice`.`status` = \'obsolete\'), 0) AS `san_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`DatacenterDevice_datacenterdevice_id_functionalci`.`name`, \'\')) AS CHAR) AS `datacenterdevice_id_friendlyname`, `DatacenterDevice_datacenterdevice_id_functionalci`.`finalclass` AS `datacenterdevice_id_finalclass_recall`, COALESCE((`DatacenterDevice_datacenterdevice_id_physicaldevice`.`status` = \'obsolete\'), 0) AS `datacenterdevice_id_obsolescence_flag` FROM `lnkdatacenterdevicetosan` AS `_lnkdatacenterdevicetosan`INNER JOIN (`functionalci` AS `SANSwitch_san_id_functionalci` INNER JOIN `physicaldevice` AS `SANSwitch_san_id_physicaldevice` ON `SANSwitch_san_id_functionalci`.`id` = `SANSwitch_san_id_physicaldevice`.`id`) ON `_lnkdatacenterdevicetosan`.`san_id` = `SANSwitch_san_id_functionalci`.`id`INNER JOIN (`functionalci` AS `DatacenterDevice_datacenterdevice_id_functionalci` INNER JOIN `physicaldevice` AS `DatacenterDevice_datacenterdevice_id_physicaldevice` ON `DatacenterDevice_datacenterdevice_id_functionalci`.`id` = `DatacenterDevice_datacenterdevice_id_physicaldevice`.`id`) ON `_lnkdatacenterdevicetosan`.`datacenterdevice_id` = `DatacenterDevice_datacenterdevice_id_functionalci`.`id` WHERE (COALESCE((`SANSwitch_san_id_functionalci`.`finalclass` IN (\'SANSwitch\')), 1) AND COALESCE((`DatacenterDevice_datacenterdevice_id_functionalci`.`finalclass` IN (\'NetworkDevice\', \'Server\', \'StorageSystem\', \'SANSwitch\', \'TapeLibrary\', \'NAS\', \'DatacenterDevice\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_lnkdatacenterdevicetosan`.`id` AS `id`,`_lnkdatacenterdevicetosan`.`san_id` AS `san_id`,`SANSwitch_san_id_functionalci`.`name` AS `san_name`,`_lnkdatacenterdevicetosan`.`datacenterdevice_id` AS `datacenterdevice_id`,`DatacenterDevice_datacenterdevice_id_functionalci`.`name` AS `datacenterdevice_name`,`_lnkdatacenterdevicetosan`.`san_port` AS `san_port`,`_lnkdatacenterdevicetosan`.`datacenterdevice_port` AS `datacenterdevice_port`,cast(concat(coalesce(`_lnkdatacenterdevicetosan`.`san_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`SANSwitch_san_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `san_id_friendlyname`,coalesce((`SANSwitch_san_id_physicaldevice`.`status` = \'obsolete\'),0) AS `san_id_obsolescence_flag`,cast(concat(coalesce(`DatacenterDevice_datacenterdevice_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `datacenterdevice_id_friendlyname`,`DatacenterDevice_datacenterdevice_id_functionalci`.`finalclass` AS `datacenterdevice_id_finalclass_recall`,coalesce((`DatacenterDevice_datacenterdevice_id_physicaldevice`.`status` = \'obsolete\'),0) AS `datacenterdevice_id_obsolescence_flag` from ((`itop`.`lnkdatacenterdevicetosan` `_lnkdatacenterdevicetosan` join (`itop`.`functionalci` `SANSwitch_san_id_functionalci` join `itop`.`physicaldevice` `SANSwitch_san_id_physicaldevice` on((`SANSwitch_san_id_functionalci`.`id` = `SANSwitch_san_id_physicaldevice`.`id`))) on((`_lnkdatacenterdevicetosan`.`san_id` = `SANSwitch_san_id_functionalci`.`id`))) join (`itop`.`functionalci` `DatacenterDevice_datacenterdevice_id_functionalci` join `itop`.`physicaldevice` `DatacenterDevice_datacenterdevice_id_physicaldevice` on((`DatacenterDevice_datacenterdevice_id_functionalci`.`id` = `DatacenterDevice_datacenterdevice_id_physicaldevice`.`id`))) on((`_lnkdatacenterdevicetosan`.`datacenterdevice_id` = `DatacenterDevice_datacenterdevice_id_functionalci`.`id`))) where (coalesce((`SANSwitch_san_id_functionalci`.`finalclass` = \'SANSwitch\'),1) and coalesce((`DatacenterDevice_datacenterdevice_id_functionalci`.`finalclass` in (\'NetworkDevice\',\'Server\',\'StorageSystem\',\'SANSwitch\',\'TapeLibrary\',\'NAS\',\'DatacenterDevice\')),1))
