TYPE=VIEW
query=select distinct `_lnkconnectablecitonetworkdevice`.`id` AS `id`,`_lnkconnectablecitonetworkdevice`.`networkdevice_id` AS `networkdevice_id`,`NetworkDevice_networkdevice_id_functionalci`.`name` AS `networkdevice_name`,`_lnkconnectablecitonetworkdevice`.`connectableci_id` AS `connectableci_id`,`ConnectableCI_connectableci_id_functionalci`.`name` AS `connectableci_name`,`_lnkconnectablecitonetworkdevice`.`network_port` AS `network_port`,`_lnkconnectablecitonetworkdevice`.`device_port` AS `device_port`,`_lnkconnectablecitonetworkdevice`.`type` AS `connection_type`,cast(concat(coalesce(`_lnkconnectablecitonetworkdevice`.`networkdevice_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkconnectablecitonetworkdevice`.`connectableci_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`NetworkDevice_networkdevice_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `networkdevice_id_friendlyname`,coalesce((`NetworkDevice_networkdevice_id_physicaldevice`.`status` = \'obsolete\'),0) AS `networkdevice_id_obsolescence_flag`,cast(concat(coalesce(`ConnectableCI_connectableci_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `connectableci_id_friendlyname`,`ConnectableCI_connectableci_id_functionalci`.`finalclass` AS `connectableci_id_finalclass_recall`,coalesce((`ConnectableCI_connectableci_id_physicaldevice`.`status` = \'obsolete\'),0) AS `connectableci_id_obsolescence_flag` from ((`itop`.`lnkconnectablecitonetworkdevice` `_lnkconnectablecitonetworkdevice` join (`itop`.`functionalci` `NetworkDevice_networkdevice_id_functionalci` join `itop`.`physicaldevice` `NetworkDevice_networkdevice_id_physicaldevice` on((`NetworkDevice_networkdevice_id_functionalci`.`id` = `NetworkDevice_networkdevice_id_physicaldevice`.`id`))) on((`_lnkconnectablecitonetworkdevice`.`networkdevice_id` = `NetworkDevice_networkdevice_id_functionalci`.`id`))) join (`itop`.`functionalci` `ConnectableCI_connectableci_id_functionalci` join `itop`.`physicaldevice` `ConnectableCI_connectableci_id_physicaldevice` on((`ConnectableCI_connectableci_id_functionalci`.`id` = `ConnectableCI_connectableci_id_physicaldevice`.`id`))) on((`_lnkconnectablecitonetworkdevice`.`connectableci_id` = `ConnectableCI_connectableci_id_functionalci`.`id`))) where (coalesce((`NetworkDevice_networkdevice_id_functionalci`.`finalclass` = \'NetworkDevice\'),1) and coalesce((`ConnectableCI_connectableci_id_functionalci`.`finalclass` in (\'DatacenterDevice\',\'NetworkDevice\',\'Server\',\'PC\',\'Printer\',\'StorageSystem\',\'SANSwitch\',\'TapeLibrary\',\'NAS\',\'ConnectableCI\')),1))
md5=962233fbac6a5ee2bd79ebe904a9a395
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:05
create-version=1
source=SELECT DISTINCT `_lnkconnectablecitonetworkdevice`.`id` AS `id`, `_lnkconnectablecitonetworkdevice`.`networkdevice_id` AS `networkdevice_id`, `NetworkDevice_networkdevice_id_functionalci`.`name` AS `networkdevice_name`, `_lnkconnectablecitonetworkdevice`.`connectableci_id` AS `connectableci_id`, `ConnectableCI_connectableci_id_functionalci`.`name` AS `connectableci_name`, `_lnkconnectablecitonetworkdevice`.`network_port` AS `network_port`, `_lnkconnectablecitonetworkdevice`.`device_port` AS `device_port`, `_lnkconnectablecitonetworkdevice`.`type` AS `connection_type`, CAST(CONCAT(COALESCE(`_lnkconnectablecitonetworkdevice`.`networkdevice_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`_lnkconnectablecitonetworkdevice`.`connectableci_id`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`NetworkDevice_networkdevice_id_functionalci`.`name`, \'\')) AS CHAR) AS `networkdevice_id_friendlyname`, COALESCE((`NetworkDevice_networkdevice_id_physicaldevice`.`status` = \'obsolete\'), 0) AS `networkdevice_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`ConnectableCI_connectableci_id_functionalci`.`name`, \'\')) AS CHAR) AS `connectableci_id_friendlyname`, `ConnectableCI_connectableci_id_functionalci`.`finalclass` AS `connectableci_id_finalclass_recall`, COALESCE((`ConnectableCI_connectableci_id_physicaldevice`.`status` = \'obsolete\'), 0) AS `connectableci_id_obsolescence_flag` FROM `lnkconnectablecitonetworkdevice` AS `_lnkconnectablecitonetworkdevice`INNER JOIN (`functionalci` AS `NetworkDevice_networkdevice_id_functionalci` INNER JOIN `physicaldevice` AS `NetworkDevice_networkdevice_id_physicaldevice` ON `NetworkDevice_networkdevice_id_functionalci`.`id` = `NetworkDevice_networkdevice_id_physicaldevice`.`id`) ON `_lnkconnectablecitonetworkdevice`.`networkdevice_id` = `NetworkDevice_networkdevice_id_functionalci`.`id`INNER JOIN (`functionalci` AS `ConnectableCI_connectableci_id_functionalci` INNER JOIN `physicaldevice` AS `ConnectableCI_connectableci_id_physicaldevice` ON `ConnectableCI_connectableci_id_functionalci`.`id` = `ConnectableCI_connectableci_id_physicaldevice`.`id`) ON `_lnkconnectablecitonetworkdevice`.`connectableci_id` = `ConnectableCI_connectableci_id_functionalci`.`id` WHERE (COALESCE((`NetworkDevice_networkdevice_id_functionalci`.`finalclass` IN (\'NetworkDevice\')), 1) AND COALESCE((`ConnectableCI_connectableci_id_functionalci`.`finalclass` IN (\'DatacenterDevice\', \'NetworkDevice\', \'Server\', \'PC\', \'Printer\', \'StorageSystem\', \'SANSwitch\', \'TapeLibrary\', \'NAS\', \'ConnectableCI\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_lnkconnectablecitonetworkdevice`.`id` AS `id`,`_lnkconnectablecitonetworkdevice`.`networkdevice_id` AS `networkdevice_id`,`NetworkDevice_networkdevice_id_functionalci`.`name` AS `networkdevice_name`,`_lnkconnectablecitonetworkdevice`.`connectableci_id` AS `connectableci_id`,`ConnectableCI_connectableci_id_functionalci`.`name` AS `connectableci_name`,`_lnkconnectablecitonetworkdevice`.`network_port` AS `network_port`,`_lnkconnectablecitonetworkdevice`.`device_port` AS `device_port`,`_lnkconnectablecitonetworkdevice`.`type` AS `connection_type`,cast(concat(coalesce(`_lnkconnectablecitonetworkdevice`.`networkdevice_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkconnectablecitonetworkdevice`.`connectableci_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`NetworkDevice_networkdevice_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `networkdevice_id_friendlyname`,coalesce((`NetworkDevice_networkdevice_id_physicaldevice`.`status` = \'obsolete\'),0) AS `networkdevice_id_obsolescence_flag`,cast(concat(coalesce(`ConnectableCI_connectableci_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `connectableci_id_friendlyname`,`ConnectableCI_connectableci_id_functionalci`.`finalclass` AS `connectableci_id_finalclass_recall`,coalesce((`ConnectableCI_connectableci_id_physicaldevice`.`status` = \'obsolete\'),0) AS `connectableci_id_obsolescence_flag` from ((`itop`.`lnkconnectablecitonetworkdevice` `_lnkconnectablecitonetworkdevice` join (`itop`.`functionalci` `NetworkDevice_networkdevice_id_functionalci` join `itop`.`physicaldevice` `NetworkDevice_networkdevice_id_physicaldevice` on((`NetworkDevice_networkdevice_id_functionalci`.`id` = `NetworkDevice_networkdevice_id_physicaldevice`.`id`))) on((`_lnkconnectablecitonetworkdevice`.`networkdevice_id` = `NetworkDevice_networkdevice_id_functionalci`.`id`))) join (`itop`.`functionalci` `ConnectableCI_connectableci_id_functionalci` join `itop`.`physicaldevice` `ConnectableCI_connectableci_id_physicaldevice` on((`ConnectableCI_connectableci_id_functionalci`.`id` = `ConnectableCI_connectableci_id_physicaldevice`.`id`))) on((`_lnkconnectablecitonetworkdevice`.`connectableci_id` = `ConnectableCI_connectableci_id_functionalci`.`id`))) where (coalesce((`NetworkDevice_networkdevice_id_functionalci`.`finalclass` = \'NetworkDevice\'),1) and coalesce((`ConnectableCI_connectableci_id_functionalci`.`finalclass` in (\'DatacenterDevice\',\'NetworkDevice\',\'Server\',\'PC\',\'Printer\',\'StorageSystem\',\'SANSwitch\',\'TapeLibrary\',\'NAS\',\'ConnectableCI\')),1))
