TYPE=VIEW
query=select distinct `_licence`.`id` AS `id`,`_licence`.`name` AS `name`,`_licence`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `organization_name`,`_licence`.`usage_limit` AS `usage_limit`,`_licence`.`description` AS `description`,`_licence`.`start_date` AS `start_date`,`_licence`.`end_date` AS `end_date`,`_licence`.`licence_key` AS `licence_key`,`_licence`.`perpetual` AS `perpetual`,`_licence`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_licence`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(((`_licence`.`perpetual` = \'no\') and (isnull(`_licence`.`end_date`) = 0) and (`_licence`.`end_date` < date_format((now() - interval 15 month),\'%Y-%m-%d 00:00:00\'))),0) AS `obsolescence_flag`,`_licence`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from (`itop`.`licence` `_licence` join `itop`.`organization` `Organization_org_id_organization` on((`_licence`.`org_id` = `Organization_org_id_organization`.`id`))) where 1
md5=5b3c6970ee1fb7b859052378b31bf020
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:05
create-version=1
source=SELECT DISTINCT `_licence`.`id` AS `id`, `_licence`.`name` AS `name`, `_licence`.`org_id` AS `org_id`, `Organization_org_id_organization`.`name` AS `organization_name`, `_licence`.`usage_limit` AS `usage_limit`, `_licence`.`description` AS `description`, `_licence`.`start_date` AS `start_date`, `_licence`.`end_date` AS `end_date`, `_licence`.`licence_key` AS `licence_key`, `_licence`.`perpetual` AS `perpetual`, `_licence`.`finalclass` AS `finalclass`, CAST(CONCAT(COALESCE(`_licence`.`name`, \'\')) AS CHAR) AS `friendlyname`, COALESCE((((`_licence`.`perpetual` = \'no\') AND (ISNULL(`_licence`.`end_date`) = 0)) AND (`_licence`.`end_date` < DATE_FORMAT(DATE_SUB(NOW(), INTERVAL 15 MONTH), \'%Y-%m-%d 00:00:00\'))), 0) AS `obsolescence_flag`, `_licence`.`obsolescence_date` AS `obsolescence_date`, CAST(CONCAT(COALESCE(`Organization_org_id_organization`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`, COALESCE((`Organization_org_id_organization`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag` FROM `licence` AS `_licence`INNER JOIN `organization` AS `Organization_org_id_organization` ON `_licence`.`org_id` = `Organization_org_id_organization`.`id` WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_licence`.`id` AS `id`,`_licence`.`name` AS `name`,`_licence`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `organization_name`,`_licence`.`usage_limit` AS `usage_limit`,`_licence`.`description` AS `description`,`_licence`.`start_date` AS `start_date`,`_licence`.`end_date` AS `end_date`,`_licence`.`licence_key` AS `licence_key`,`_licence`.`perpetual` AS `perpetual`,`_licence`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_licence`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(((`_licence`.`perpetual` = \'no\') and (isnull(`_licence`.`end_date`) = 0) and (`_licence`.`end_date` < date_format((now() - interval 15 month),\'%Y-%m-%d 00:00:00\'))),0) AS `obsolescence_flag`,`_licence`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from (`itop`.`licence` `_licence` join `itop`.`organization` `Organization_org_id_organization` on((`_licence`.`org_id` = `Organization_org_id_organization`.`id`))) where 1
