TYPE=VIEW
query=select distinct `_logicalvolume`.`id` AS `id`,`_logicalvolume`.`name` AS `name`,`_logicalvolume`.`lun_id` AS `lun_id`,`_logicalvolume`.`description` AS `description`,`_logicalvolume`.`raid_level` AS `raid_level`,`_logicalvolume`.`size` AS `size`,`_logicalvolume`.`storagesystem_id` AS `storagesystem_id`,`StorageSystem_storagesystem_id_functionalci`.`name` AS `storagesystem_name`,cast(concat(coalesce(`StorageSystem_storagesystem_id_functionalci`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`_logicalvolume`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`StorageSystem_storagesystem_id_physicaldevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`_logicalvolume`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`StorageSystem_storagesystem_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `storagesystem_id_friendlyname`,coalesce((`StorageSystem_storagesystem_id_physicaldevice`.`status` = \'obsolete\'),0) AS `storagesystem_id_obsolescence_flag` from (`itop`.`logicalvolume` `_logicalvolume` join (`itop`.`functionalci` `StorageSystem_storagesystem_id_functionalci` join `itop`.`physicaldevice` `StorageSystem_storagesystem_id_physicaldevice` on((`StorageSystem_storagesystem_id_functionalci`.`id` = `StorageSystem_storagesystem_id_physicaldevice`.`id`))) on((`_logicalvolume`.`storagesystem_id` = `StorageSystem_storagesystem_id_functionalci`.`id`))) where coalesce((`StorageSystem_storagesystem_id_functionalci`.`finalclass` = \'StorageSystem\'),1)
md5=abadb8954fcd97a8870558566929d5aa
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:06
create-version=1
source=SELECT DISTINCT `_logicalvolume`.`id` AS `id`, `_logicalvolume`.`name` AS `name`, `_logicalvolume`.`lun_id` AS `lun_id`, `_logicalvolume`.`description` AS `description`, `_logicalvolume`.`raid_level` AS `raid_level`, `_logicalvolume`.`size` AS `size`, `_logicalvolume`.`storagesystem_id` AS `storagesystem_id`, `StorageSystem_storagesystem_id_functionalci`.`name` AS `storagesystem_name`, CAST(CONCAT(COALESCE(`StorageSystem_storagesystem_id_functionalci`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`_logicalvolume`.`name`, \'\')) AS CHAR) AS `friendlyname`, COALESCE(COALESCE((`StorageSystem_storagesystem_id_physicaldevice`.`status` = \'obsolete\'), 0), 0) AS `obsolescence_flag`, `_logicalvolume`.`obsolescence_date` AS `obsolescence_date`, CAST(CONCAT(COALESCE(`StorageSystem_storagesystem_id_functionalci`.`name`, \'\')) AS CHAR) AS `storagesystem_id_friendlyname`, COALESCE((`StorageSystem_storagesystem_id_physicaldevice`.`status` = \'obsolete\'), 0) AS `storagesystem_id_obsolescence_flag` FROM `logicalvolume` AS `_logicalvolume`INNER JOIN (`functionalci` AS `StorageSystem_storagesystem_id_functionalci` INNER JOIN `physicaldevice` AS `StorageSystem_storagesystem_id_physicaldevice` ON `StorageSystem_storagesystem_id_functionalci`.`id` = `StorageSystem_storagesystem_id_physicaldevice`.`id`) ON `_logicalvolume`.`storagesystem_id` = `StorageSystem_storagesystem_id_functionalci`.`id` WHERE COALESCE((`StorageSystem_storagesystem_id_functionalci`.`finalclass` IN (\'StorageSystem\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_logicalvolume`.`id` AS `id`,`_logicalvolume`.`name` AS `name`,`_logicalvolume`.`lun_id` AS `lun_id`,`_logicalvolume`.`description` AS `description`,`_logicalvolume`.`raid_level` AS `raid_level`,`_logicalvolume`.`size` AS `size`,`_logicalvolume`.`storagesystem_id` AS `storagesystem_id`,`StorageSystem_storagesystem_id_functionalci`.`name` AS `storagesystem_name`,cast(concat(coalesce(`StorageSystem_storagesystem_id_functionalci`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`_logicalvolume`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`StorageSystem_storagesystem_id_physicaldevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`_logicalvolume`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`StorageSystem_storagesystem_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `storagesystem_id_friendlyname`,coalesce((`StorageSystem_storagesystem_id_physicaldevice`.`status` = \'obsolete\'),0) AS `storagesystem_id_obsolescence_flag` from (`itop`.`logicalvolume` `_logicalvolume` join (`itop`.`functionalci` `StorageSystem_storagesystem_id_functionalci` join `itop`.`physicaldevice` `StorageSystem_storagesystem_id_physicaldevice` on((`StorageSystem_storagesystem_id_functionalci`.`id` = `StorageSystem_storagesystem_id_physicaldevice`.`id`))) on((`_logicalvolume`.`storagesystem_id` = `StorageSystem_storagesystem_id_functionalci`.`id`))) where coalesce((`StorageSystem_storagesystem_id_functionalci`.`finalclass` = \'StorageSystem\'),1)
