TYPE=VIEW
query=select distinct `_tape`.`id` AS `id`,`_tape`.`name` AS `name`,`_tape`.`description` AS `description`,`_tape`.`size` AS `size`,`_tape`.`tapelibrary_id` AS `tapelibrary_id`,`TapeLibrary_tapelibrary_id_functionalci`.`name` AS `tapelibrary_name`,cast(concat(coalesce(`_tape`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`TapeLibrary_tapelibrary_id_physicaldevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`_tape`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`TapeLibrary_tapelibrary_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `tapelibrary_id_friendlyname`,coalesce((`TapeLibrary_tapelibrary_id_physicaldevice`.`status` = \'obsolete\'),0) AS `tapelibrary_id_obsolescence_flag` from (`itop`.`tape` `_tape` join (`itop`.`functionalci` `TapeLibrary_tapelibrary_id_functionalci` join `itop`.`physicaldevice` `TapeLibrary_tapelibrary_id_physicaldevice` on((`TapeLibrary_tapelibrary_id_functionalci`.`id` = `TapeLibrary_tapelibrary_id_physicaldevice`.`id`))) on((`_tape`.`tapelibrary_id` = `TapeLibrary_tapelibrary_id_functionalci`.`id`))) where coalesce((`TapeLibrary_tapelibrary_id_functionalci`.`finalclass` = \'TapeLibrary\'),1)
md5=204df91d7d72cde81d89517404d00483
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:06
create-version=1
source=SELECT DISTINCT `_tape`.`id` AS `id`, `_tape`.`name` AS `name`, `_tape`.`description` AS `description`, `_tape`.`size` AS `size`, `_tape`.`tapelibrary_id` AS `tapelibrary_id`, `TapeLibrary_tapelibrary_id_functionalci`.`name` AS `tapelibrary_name`, CAST(CONCAT(COALESCE(`_tape`.`name`, \'\')) AS CHAR) AS `friendlyname`, COALESCE(COALESCE((`TapeLibrary_tapelibrary_id_physicaldevice`.`status` = \'obsolete\'), 0), 0) AS `obsolescence_flag`, `_tape`.`obsolescence_date` AS `obsolescence_date`, CAST(CONCAT(COALESCE(`TapeLibrary_tapelibrary_id_functionalci`.`name`, \'\')) AS CHAR) AS `tapelibrary_id_friendlyname`, COALESCE((`TapeLibrary_tapelibrary_id_physicaldevice`.`status` = \'obsolete\'), 0) AS `tapelibrary_id_obsolescence_flag` FROM `tape` AS `_tape`INNER JOIN (`functionalci` AS `TapeLibrary_tapelibrary_id_functionalci` INNER JOIN `physicaldevice` AS `TapeLibrary_tapelibrary_id_physicaldevice` ON `TapeLibrary_tapelibrary_id_functionalci`.`id` = `TapeLibrary_tapelibrary_id_physicaldevice`.`id`) ON `_tape`.`tapelibrary_id` = `TapeLibrary_tapelibrary_id_functionalci`.`id` WHERE COALESCE((`TapeLibrary_tapelibrary_id_functionalci`.`finalclass` IN (\'TapeLibrary\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_tape`.`id` AS `id`,`_tape`.`name` AS `name`,`_tape`.`description` AS `description`,`_tape`.`size` AS `size`,`_tape`.`tapelibrary_id` AS `tapelibrary_id`,`TapeLibrary_tapelibrary_id_functionalci`.`name` AS `tapelibrary_name`,cast(concat(coalesce(`_tape`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`TapeLibrary_tapelibrary_id_physicaldevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`_tape`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`TapeLibrary_tapelibrary_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `tapelibrary_id_friendlyname`,coalesce((`TapeLibrary_tapelibrary_id_physicaldevice`.`status` = \'obsolete\'),0) AS `tapelibrary_id_obsolescence_flag` from (`itop`.`tape` `_tape` join (`itop`.`functionalci` `TapeLibrary_tapelibrary_id_functionalci` join `itop`.`physicaldevice` `TapeLibrary_tapelibrary_id_physicaldevice` on((`TapeLibrary_tapelibrary_id_functionalci`.`id` = `TapeLibrary_tapelibrary_id_physicaldevice`.`id`))) on((`_tape`.`tapelibrary_id` = `TapeLibrary_tapelibrary_id_functionalci`.`id`))) where coalesce((`TapeLibrary_tapelibrary_id_functionalci`.`finalclass` = \'TapeLibrary\'),1)
