TYPE=VIEW
query=select distinct `_lnkcontacttoticket`.`id` AS `id`,`_lnkcontacttoticket`.`ticket_id` AS `ticket_id`,`Ticket_ticket_id_ticket`.`ref` AS `ticket_ref`,`_lnkcontacttoticket`.`contact_id` AS `contact_id`,`Contact_contact_id_contact`.`email` AS `contact_email`,`_lnkcontacttoticket`.`role` AS `role`,`_lnkcontacttoticket`.`impact_code` AS `role_code`,cast(concat(coalesce(`_lnkcontacttoticket`.`ticket_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkcontacttoticket`.`contact_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Ticket_ticket_id_ticket`.`ref`,\'\')) as char charset utf8mb4) AS `ticket_id_friendlyname`,`Ticket_ticket_id_ticket`.`finalclass` AS `ticket_id_finalclass_recall`,if((`Contact_contact_id_contact`.`finalclass` in (\'Team\',\'Contact\')),cast(concat(coalesce(`Contact_contact_id_contact`.`name`,\'\')) as char charset utf8mb4),cast(concat(coalesce(`Contact_contact_id_fn_Person_person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Contact_contact_id_contact`.`name`,\'\')) as char charset utf8mb4)) AS `contact_id_friendlyname`,`Contact_contact_id_contact`.`finalclass` AS `contact_id_finalclass_recall`,coalesce((`Contact_contact_id_contact`.`status` = \'inactive\'),0) AS `contact_id_obsolescence_flag` from ((`itop`.`lnkcontacttoticket` `_lnkcontacttoticket` join `itop`.`ticket` `Ticket_ticket_id_ticket` on((`_lnkcontacttoticket`.`ticket_id` = `Ticket_ticket_id_ticket`.`id`))) join (`itop`.`contact` `Contact_contact_id_contact` left join `itop`.`person` `Contact_contact_id_fn_Person_person` on((`Contact_contact_id_contact`.`id` = `Contact_contact_id_fn_Person_person`.`id`))) on((`_lnkcontacttoticket`.`contact_id` = `Contact_contact_id_contact`.`id`))) where 1
md5=c2b41134cb1ecf5f28b22b74c52391fc
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:06
create-version=1
source=SELECT DISTINCT `_lnkcontacttoticket`.`id` AS `id`, `_lnkcontacttoticket`.`ticket_id` AS `ticket_id`, `Ticket_ticket_id_ticket`.`ref` AS `ticket_ref`, `_lnkcontacttoticket`.`contact_id` AS `contact_id`, `Contact_contact_id_contact`.`email` AS `contact_email`, `_lnkcontacttoticket`.`role` AS `role`, `_lnkcontacttoticket`.`impact_code` AS `role_code`, CAST(CONCAT(COALESCE(`_lnkcontacttoticket`.`ticket_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`_lnkcontacttoticket`.`contact_id`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`Ticket_ticket_id_ticket`.`ref`, \'\')) AS CHAR) AS `ticket_id_friendlyname`, `Ticket_ticket_id_ticket`.`finalclass` AS `ticket_id_finalclass_recall`, IF((`Contact_contact_id_contact`.`finalclass` IN (\'Team\', \'Contact\')), CAST(CONCAT(COALESCE(`Contact_contact_id_contact`.`name`, \'\')) AS CHAR), CAST(CONCAT(COALESCE(`Contact_contact_id_fn_Person_person`.`first_name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Contact_contact_id_contact`.`name`, \'\')) AS CHAR)) AS `contact_id_friendlyname`, `Contact_contact_id_contact`.`finalclass` AS `contact_id_finalclass_recall`, COALESCE((`Contact_contact_id_contact`.`status` = \'inactive\'), 0) AS `contact_id_obsolescence_flag` FROM `lnkcontacttoticket` AS `_lnkcontacttoticket`INNER JOIN `ticket` AS `Ticket_ticket_id_ticket` ON `_lnkcontacttoticket`.`ticket_id` = `Ticket_ticket_id_ticket`.`id`INNER JOIN (`contact` AS `Contact_contact_id_contact` LEFT JOIN `person` AS `Contact_contact_id_fn_Person_person` ON `Contact_contact_id_contact`.`id` = `Contact_contact_id_fn_Person_person`.`id`) ON `_lnkcontacttoticket`.`contact_id` = `Contact_contact_id_contact`.`id` WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_lnkcontacttoticket`.`id` AS `id`,`_lnkcontacttoticket`.`ticket_id` AS `ticket_id`,`Ticket_ticket_id_ticket`.`ref` AS `ticket_ref`,`_lnkcontacttoticket`.`contact_id` AS `contact_id`,`Contact_contact_id_contact`.`email` AS `contact_email`,`_lnkcontacttoticket`.`role` AS `role`,`_lnkcontacttoticket`.`impact_code` AS `role_code`,cast(concat(coalesce(`_lnkcontacttoticket`.`ticket_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkcontacttoticket`.`contact_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Ticket_ticket_id_ticket`.`ref`,\'\')) as char charset utf8mb4) AS `ticket_id_friendlyname`,`Ticket_ticket_id_ticket`.`finalclass` AS `ticket_id_finalclass_recall`,if((`Contact_contact_id_contact`.`finalclass` in (\'Team\',\'Contact\')),cast(concat(coalesce(`Contact_contact_id_contact`.`name`,\'\')) as char charset utf8mb4),cast(concat(coalesce(`Contact_contact_id_fn_Person_person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Contact_contact_id_contact`.`name`,\'\')) as char charset utf8mb4)) AS `contact_id_friendlyname`,`Contact_contact_id_contact`.`finalclass` AS `contact_id_finalclass_recall`,coalesce((`Contact_contact_id_contact`.`status` = \'inactive\'),0) AS `contact_id_obsolescence_flag` from ((`itop`.`lnkcontacttoticket` `_lnkcontacttoticket` join `itop`.`ticket` `Ticket_ticket_id_ticket` on((`_lnkcontacttoticket`.`ticket_id` = `Ticket_ticket_id_ticket`.`id`))) join (`itop`.`contact` `Contact_contact_id_contact` left join `itop`.`person` `Contact_contact_id_fn_Person_person` on((`Contact_contact_id_contact`.`id` = `Contact_contact_id_fn_Person_person`.`id`))) on((`_lnkcontacttoticket`.`contact_id` = `Contact_contact_id_contact`.`id`))) where 1
