TYPE=VIEW
query=select distinct `_organization`.`id` AS `id`,`_organization`.`name` AS `name`,`_organization`.`code` AS `code`,`_organization`.`status` AS `status`,`_organization`.`parent_id` AS `parent_id`,`Organization_parent_id_organization`.`name` AS `parent_name`,`_organization`.`deliverymodel_id` AS `deliverymodel_id`,`DeliveryModel_deliverymodel_id_deliverymodel`.`name` AS `deliverymodel_name`,cast(concat(coalesce(`_organization`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`_organization`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`_organization`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_parent_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `parent_id_friendlyname`,coalesce((`Organization_parent_id_organization`.`status` = \'inactive\'),0) AS `parent_id_obsolescence_flag`,cast(concat(coalesce(`DeliveryModel_deliverymodel_id_deliverymodel`.`name`,\'\')) as char charset utf8mb4) AS `deliverymodel_id_friendlyname` from ((`itop`.`organization` `_organization` left join `itop`.`organization` `Organization_parent_id_organization` on((`_organization`.`parent_id` = `Organization_parent_id_organization`.`id`))) left join `itop`.`deliverymodel` `DeliveryModel_deliverymodel_id_deliverymodel` on((`_organization`.`deliverymodel_id` = `DeliveryModel_deliverymodel_id_deliverymodel`.`id`))) where 1
md5=67c69bc7e80e867936d7992de2a4dca4
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:04
create-version=1
source=SELECT DISTINCT `_organization`.`id` AS `id`, `_organization`.`name` AS `name`, `_organization`.`code` AS `code`, `_organization`.`status` AS `status`, `_organization`.`parent_id` AS `parent_id`, `Organization_parent_id_organization`.`name` AS `parent_name`, `_organization`.`deliverymodel_id` AS `deliverymodel_id`, `DeliveryModel_deliverymodel_id_deliverymodel`.`name` AS `deliverymodel_name`, CAST(CONCAT(COALESCE(`_organization`.`name`, \'\')) AS CHAR) AS `friendlyname`, COALESCE((`_organization`.`status` = \'inactive\'), 0) AS `obsolescence_flag`, `_organization`.`obsolescence_date` AS `obsolescence_date`, CAST(CONCAT(COALESCE(`Organization_parent_id_organization`.`name`, \'\')) AS CHAR) AS `parent_id_friendlyname`, COALESCE((`Organization_parent_id_organization`.`status` = \'inactive\'), 0) AS `parent_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`DeliveryModel_deliverymodel_id_deliverymodel`.`name`, \'\')) AS CHAR) AS `deliverymodel_id_friendlyname` FROM `organization` AS `_organization`LEFT JOIN `organization` AS `Organization_parent_id_organization` ON `_organization`.`parent_id` = `Organization_parent_id_organization`.`id`LEFT JOIN `deliverymodel` AS `DeliveryModel_deliverymodel_id_deliverymodel` ON `_organization`.`deliverymodel_id` = `DeliveryModel_deliverymodel_id_deliverymodel`.`id` WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_organization`.`id` AS `id`,`_organization`.`name` AS `name`,`_organization`.`code` AS `code`,`_organization`.`status` AS `status`,`_organization`.`parent_id` AS `parent_id`,`Organization_parent_id_organization`.`name` AS `parent_name`,`_organization`.`deliverymodel_id` AS `deliverymodel_id`,`DeliveryModel_deliverymodel_id_deliverymodel`.`name` AS `deliverymodel_name`,cast(concat(coalesce(`_organization`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`_organization`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`_organization`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_parent_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `parent_id_friendlyname`,coalesce((`Organization_parent_id_organization`.`status` = \'inactive\'),0) AS `parent_id_obsolescence_flag`,cast(concat(coalesce(`DeliveryModel_deliverymodel_id_deliverymodel`.`name`,\'\')) as char charset utf8mb4) AS `deliverymodel_id_friendlyname` from ((`itop`.`organization` `_organization` left join `itop`.`organization` `Organization_parent_id_organization` on((`_organization`.`parent_id` = `Organization_parent_id_organization`.`id`))) left join `itop`.`deliverymodel` `DeliveryModel_deliverymodel_id_deliverymodel` on((`_organization`.`deliverymodel_id` = `DeliveryModel_deliverymodel_id_deliverymodel`.`id`))) where 1
