TYPE=VIEW
query=select distinct `_lnkvirtualdevicetovolume`.`id` AS `id`,`_lnkvirtualdevicetovolume`.`volume_id` AS `volume_id`,`LogicalVolume_volume_id_logicalvolume`.`name` AS `volume_name`,`_lnkvirtualdevicetovolume`.`virtualdevice_id` AS `virtualdevice_id`,`VirtualDevice_virtualdevice_id_functionalci`.`name` AS `virtualdevice_name`,`_lnkvirtualdevicetovolume`.`size_used` AS `size_used`,cast(concat(coalesce(`_lnkvirtualdevicetovolume`.`volume_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`StorageSystem_storagesystem_id_functionalci`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`LogicalVolume_volume_id_logicalvolume`.`name`,\'\')) as char charset utf8mb4) AS `volume_id_friendlyname`,coalesce(coalesce((`StorageSystem_storagesystem_id_physicaldevice`.`status` = \'obsolete\'),0),0) AS `volume_id_obsolescence_flag`,cast(concat(coalesce(`VirtualDevice_virtualdevice_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `virtualdevice_id_friendlyname`,`VirtualDevice_virtualdevice_id_functionalci`.`finalclass` AS `virtualdevice_id_finalclass_recall`,coalesce((`VirtualDevice_virtualdevice_id_virtualdevice`.`status` = \'obsolete\'),0) AS `virtualdevice_id_obsolescence_flag` from ((`itop`.`lnkvirtualdevicetovolume` `_lnkvirtualdevicetovolume` join (`itop`.`logicalvolume` `LogicalVolume_volume_id_logicalvolume` join (`itop`.`functionalci` `StorageSystem_storagesystem_id_functionalci` join `itop`.`physicaldevice` `StorageSystem_storagesystem_id_physicaldevice` on((`StorageSystem_storagesystem_id_functionalci`.`id` = `StorageSystem_storagesystem_id_physicaldevice`.`id`))) on((`LogicalVolume_volume_id_logicalvolume`.`storagesystem_id` = `StorageSystem_storagesystem_id_functionalci`.`id`))) on((`_lnkvirtualdevicetovolume`.`volume_id` = `LogicalVolume_volume_id_logicalvolume`.`id`))) join (`itop`.`functionalci` `VirtualDevice_virtualdevice_id_functionalci` join `itop`.`virtualdevice` `VirtualDevice_virtualdevice_id_virtualdevice` on((`VirtualDevice_virtualdevice_id_functionalci`.`id` = `VirtualDevice_virtualdevice_id_virtualdevice`.`id`))) on((`_lnkvirtualdevicetovolume`.`virtualdevice_id` = `VirtualDevice_virtualdevice_id_functionalci`.`id`))) where (coalesce((`StorageSystem_storagesystem_id_functionalci`.`finalclass` = \'StorageSystem\'),1) and coalesce((`VirtualDevice_virtualdevice_id_functionalci`.`finalclass` in (\'VirtualHost\',\'Hypervisor\',\'Farm\',\'VirtualMachine\',\'VirtualDevice\')),1))
md5=872909cf74b12c23c287d7fe3868e3fc
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:07
create-version=1
source=SELECT DISTINCT `_lnkvirtualdevicetovolume`.`id` AS `id`, `_lnkvirtualdevicetovolume`.`volume_id` AS `volume_id`, `LogicalVolume_volume_id_logicalvolume`.`name` AS `volume_name`, `_lnkvirtualdevicetovolume`.`virtualdevice_id` AS `virtualdevice_id`, `VirtualDevice_virtualdevice_id_functionalci`.`name` AS `virtualdevice_name`, `_lnkvirtualdevicetovolume`.`size_used` AS `size_used`, CAST(CONCAT(COALESCE(`_lnkvirtualdevicetovolume`.`volume_id`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`StorageSystem_storagesystem_id_functionalci`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`LogicalVolume_volume_id_logicalvolume`.`name`, \'\')) AS CHAR) AS `volume_id_friendlyname`, COALESCE(COALESCE((`StorageSystem_storagesystem_id_physicaldevice`.`status` = \'obsolete\'), 0), 0) AS `volume_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`VirtualDevice_virtualdevice_id_functionalci`.`name`, \'\')) AS CHAR) AS `virtualdevice_id_friendlyname`, `VirtualDevice_virtualdevice_id_functionalci`.`finalclass` AS `virtualdevice_id_finalclass_recall`, COALESCE((`VirtualDevice_virtualdevice_id_virtualdevice`.`status` = \'obsolete\'), 0) AS `virtualdevice_id_obsolescence_flag` FROM `lnkvirtualdevicetovolume` AS `_lnkvirtualdevicetovolume`INNER JOIN (`logicalvolume` AS `LogicalVolume_volume_id_logicalvolume` INNER JOIN (`functionalci` AS `StorageSystem_storagesystem_id_functionalci` INNER JOIN `physicaldevice` AS `StorageSystem_storagesystem_id_physicaldevice` ON `StorageSystem_storagesystem_id_functionalci`.`id` = `StorageSystem_storagesystem_id_physicaldevice`.`id`) ON `LogicalVolume_volume_id_logicalvolume`.`storagesystem_id` = `StorageSystem_storagesystem_id_functionalci`.`id`) ON `_lnkvirtualdevicetovolume`.`volume_id` = `LogicalVolume_volume_id_logicalvolume`.`id`INNER JOIN (`functionalci` AS `VirtualDevice_virtualdevice_id_functionalci` INNER JOIN `virtualdevice` AS `VirtualDevice_virtualdevice_id_virtualdevice` ON `VirtualDevice_virtualdevice_id_functionalci`.`id` = `VirtualDevice_virtualdevice_id_virtualdevice`.`id`) ON `_lnkvirtualdevicetovolume`.`virtualdevice_id` = `VirtualDevice_virtualdevice_id_functionalci`.`id` WHERE (COALESCE((`StorageSystem_storagesystem_id_functionalci`.`finalclass` IN (\'StorageSystem\')), 1) AND COALESCE((`VirtualDevice_virtualdevice_id_functionalci`.`finalclass` IN (\'VirtualHost\', \'Hypervisor\', \'Farm\', \'VirtualMachine\', \'VirtualDevice\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_lnkvirtualdevicetovolume`.`id` AS `id`,`_lnkvirtualdevicetovolume`.`volume_id` AS `volume_id`,`LogicalVolume_volume_id_logicalvolume`.`name` AS `volume_name`,`_lnkvirtualdevicetovolume`.`virtualdevice_id` AS `virtualdevice_id`,`VirtualDevice_virtualdevice_id_functionalci`.`name` AS `virtualdevice_name`,`_lnkvirtualdevicetovolume`.`size_used` AS `size_used`,cast(concat(coalesce(`_lnkvirtualdevicetovolume`.`volume_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`StorageSystem_storagesystem_id_functionalci`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`LogicalVolume_volume_id_logicalvolume`.`name`,\'\')) as char charset utf8mb4) AS `volume_id_friendlyname`,coalesce(coalesce((`StorageSystem_storagesystem_id_physicaldevice`.`status` = \'obsolete\'),0),0) AS `volume_id_obsolescence_flag`,cast(concat(coalesce(`VirtualDevice_virtualdevice_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `virtualdevice_id_friendlyname`,`VirtualDevice_virtualdevice_id_functionalci`.`finalclass` AS `virtualdevice_id_finalclass_recall`,coalesce((`VirtualDevice_virtualdevice_id_virtualdevice`.`status` = \'obsolete\'),0) AS `virtualdevice_id_obsolescence_flag` from ((`itop`.`lnkvirtualdevicetovolume` `_lnkvirtualdevicetovolume` join (`itop`.`logicalvolume` `LogicalVolume_volume_id_logicalvolume` join (`itop`.`functionalci` `StorageSystem_storagesystem_id_functionalci` join `itop`.`physicaldevice` `StorageSystem_storagesystem_id_physicaldevice` on((`StorageSystem_storagesystem_id_functionalci`.`id` = `StorageSystem_storagesystem_id_physicaldevice`.`id`))) on((`LogicalVolume_volume_id_logicalvolume`.`storagesystem_id` = `StorageSystem_storagesystem_id_functionalci`.`id`))) on((`_lnkvirtualdevicetovolume`.`volume_id` = `LogicalVolume_volume_id_logicalvolume`.`id`))) join (`itop`.`functionalci` `VirtualDevice_virtualdevice_id_functionalci` join `itop`.`virtualdevice` `VirtualDevice_virtualdevice_id_virtualdevice` on((`VirtualDevice_virtualdevice_id_functionalci`.`id` = `VirtualDevice_virtualdevice_id_virtualdevice`.`id`))) on((`_lnkvirtualdevicetovolume`.`virtualdevice_id` = `VirtualDevice_virtualdevice_id_functionalci`.`id`))) where (coalesce((`StorageSystem_storagesystem_id_functionalci`.`finalclass` = \'StorageSystem\'),1) and coalesce((`VirtualDevice_virtualdevice_id_functionalci`.`finalclass` in (\'VirtualHost\',\'Hypervisor\',\'Farm\',\'VirtualMachine\',\'VirtualDevice\')),1))
