TYPE=VIEW
query=select distinct `_faqcategory`.`id` AS `id`,`_faqcategory`.`nam` AS `name`,cast(concat(coalesce(`_faqcategory`.`nam`,\'\')) as char charset utf8mb4) AS `friendlyname` from `itop`.`faqcategory` `_faqcategory` where 1
md5=d1a7d3a314223d534e41d1f8b4862200
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:07
create-version=1
source=SELECT DISTINCT `_faqcategory`.`id` AS `id`, `_faqcategory`.`nam` AS `name`, CAST(CONCAT(COALESCE(`_faqcategory`.`nam`, \'\')) AS CHAR) AS `friendlyname` FROM `faqcategory` AS `_faqcategory` WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_faqcategory`.`id` AS `id`,`_faqcategory`.`nam` AS `name`,cast(concat(coalesce(`_faqcategory`.`nam`,\'\')) as char charset utf8mb4) AS `friendlyname` from `itop`.`faqcategory` `_faqcategory` where 1
