TYPE=VIEW
query=select distinct `_lnkservertovolume`.`id` AS `id`,`_lnkservertovolume`.`volume_id` AS `volume_id`,`LogicalVolume_volume_id_logicalvolume`.`name` AS `volume_name`,`_lnkservertovolume`.`server_id` AS `server_id`,`Server_server_id_functionalci`.`name` AS `server_name`,`_lnkservertovolume`.`size_used` AS `size_used`,cast(concat(coalesce(`_lnkservertovolume`.`volume_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`StorageSystem_storagesystem_id_functionalci`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`LogicalVolume_volume_id_logicalvolume`.`name`,\'\')) as char charset utf8mb4) AS `volume_id_friendlyname`,coalesce(coalesce((`StorageSystem_storagesystem_id_physicaldevice`.`status` = \'obsolete\'),0),0) AS `volume_id_obsolescence_flag`,cast(concat(coalesce(`Server_server_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `server_id_friendlyname`,coalesce((`Server_server_id_physicaldevice`.`status` = \'obsolete\'),0) AS `server_id_obsolescence_flag` from ((`itop`.`lnkservertovolume` `_lnkservertovolume` join (`itop`.`logicalvolume` `LogicalVolume_volume_id_logicalvolume` join (`itop`.`functionalci` `StorageSystem_storagesystem_id_functionalci` join `itop`.`physicaldevice` `StorageSystem_storagesystem_id_physicaldevice` on((`StorageSystem_storagesystem_id_functionalci`.`id` = `StorageSystem_storagesystem_id_physicaldevice`.`id`))) on((`LogicalVolume_volume_id_logicalvolume`.`storagesystem_id` = `StorageSystem_storagesystem_id_functionalci`.`id`))) on((`_lnkservertovolume`.`volume_id` = `LogicalVolume_volume_id_logicalvolume`.`id`))) join (`itop`.`functionalci` `Server_server_id_functionalci` join `itop`.`physicaldevice` `Server_server_id_physicaldevice` on((`Server_server_id_functionalci`.`id` = `Server_server_id_physicaldevice`.`id`))) on((`_lnkservertovolume`.`server_id` = `Server_server_id_functionalci`.`id`))) where (coalesce((`StorageSystem_storagesystem_id_functionalci`.`finalclass` = \'StorageSystem\'),1) and coalesce((`Server_server_id_functionalci`.`finalclass` = \'Server\'),1))
md5=79cd2550de587fdc5862cc22212a4e56
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:06
create-version=1
source=SELECT DISTINCT `_lnkservertovolume`.`id` AS `id`, `_lnkservertovolume`.`volume_id` AS `volume_id`, `LogicalVolume_volume_id_logicalvolume`.`name` AS `volume_name`, `_lnkservertovolume`.`server_id` AS `server_id`, `Server_server_id_functionalci`.`name` AS `server_name`, `_lnkservertovolume`.`size_used` AS `size_used`, CAST(CONCAT(COALESCE(`_lnkservertovolume`.`volume_id`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`StorageSystem_storagesystem_id_functionalci`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`LogicalVolume_volume_id_logicalvolume`.`name`, \'\')) AS CHAR) AS `volume_id_friendlyname`, COALESCE(COALESCE((`StorageSystem_storagesystem_id_physicaldevice`.`status` = \'obsolete\'), 0), 0) AS `volume_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`Server_server_id_functionalci`.`name`, \'\')) AS CHAR) AS `server_id_friendlyname`, COALESCE((`Server_server_id_physicaldevice`.`status` = \'obsolete\'), 0) AS `server_id_obsolescence_flag` FROM `lnkservertovolume` AS `_lnkservertovolume`INNER JOIN (`logicalvolume` AS `LogicalVolume_volume_id_logicalvolume` INNER JOIN (`functionalci` AS `StorageSystem_storagesystem_id_functionalci` INNER JOIN `physicaldevice` AS `StorageSystem_storagesystem_id_physicaldevice` ON `StorageSystem_storagesystem_id_functionalci`.`id` = `StorageSystem_storagesystem_id_physicaldevice`.`id`) ON `LogicalVolume_volume_id_logicalvolume`.`storagesystem_id` = `StorageSystem_storagesystem_id_functionalci`.`id`) ON `_lnkservertovolume`.`volume_id` = `LogicalVolume_volume_id_logicalvolume`.`id`INNER JOIN (`functionalci` AS `Server_server_id_functionalci` INNER JOIN `physicaldevice` AS `Server_server_id_physicaldevice` ON `Server_server_id_functionalci`.`id` = `Server_server_id_physicaldevice`.`id`) ON `_lnkservertovolume`.`server_id` = `Server_server_id_functionalci`.`id` WHERE (COALESCE((`StorageSystem_storagesystem_id_functionalci`.`finalclass` IN (\'StorageSystem\')), 1) AND COALESCE((`Server_server_id_functionalci`.`finalclass` IN (\'Server\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_lnkservertovolume`.`id` AS `id`,`_lnkservertovolume`.`volume_id` AS `volume_id`,`LogicalVolume_volume_id_logicalvolume`.`name` AS `volume_name`,`_lnkservertovolume`.`server_id` AS `server_id`,`Server_server_id_functionalci`.`name` AS `server_name`,`_lnkservertovolume`.`size_used` AS `size_used`,cast(concat(coalesce(`_lnkservertovolume`.`volume_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`StorageSystem_storagesystem_id_functionalci`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`LogicalVolume_volume_id_logicalvolume`.`name`,\'\')) as char charset utf8mb4) AS `volume_id_friendlyname`,coalesce(coalesce((`StorageSystem_storagesystem_id_physicaldevice`.`status` = \'obsolete\'),0),0) AS `volume_id_obsolescence_flag`,cast(concat(coalesce(`Server_server_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `server_id_friendlyname`,coalesce((`Server_server_id_physicaldevice`.`status` = \'obsolete\'),0) AS `server_id_obsolescence_flag` from ((`itop`.`lnkservertovolume` `_lnkservertovolume` join (`itop`.`logicalvolume` `LogicalVolume_volume_id_logicalvolume` join (`itop`.`functionalci` `StorageSystem_storagesystem_id_functionalci` join `itop`.`physicaldevice` `StorageSystem_storagesystem_id_physicaldevice` on((`StorageSystem_storagesystem_id_functionalci`.`id` = `StorageSystem_storagesystem_id_physicaldevice`.`id`))) on((`LogicalVolume_volume_id_logicalvolume`.`storagesystem_id` = `StorageSystem_storagesystem_id_functionalci`.`id`))) on((`_lnkservertovolume`.`volume_id` = `LogicalVolume_volume_id_logicalvolume`.`id`))) join (`itop`.`functionalci` `Server_server_id_functionalci` join `itop`.`physicaldevice` `Server_server_id_physicaldevice` on((`Server_server_id_functionalci`.`id` = `Server_server_id_physicaldevice`.`id`))) on((`_lnkservertovolume`.`server_id` = `Server_server_id_functionalci`.`id`))) where (coalesce((`StorageSystem_storagesystem_id_functionalci`.`finalclass` = \'StorageSystem\'),1) and coalesce((`Server_server_id_functionalci`.`finalclass` = \'Server\'),1))
