TYPE=VIEW
query=select distinct `_group`.`id` AS `id`,`_group`.`name` AS `name`,`_group`.`status` AS `status`,`_group`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `owner_name`,`_group`.`description` AS `description`,`_group`.`type` AS `type`,`_group`.`parent_id` AS `parent_id`,`Group_parent_id_group`.`name` AS `parent_name`,cast(concat(coalesce(`_group`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`_group`.`status` = \'obsolete\'),0) AS `obsolescence_flag`,`_group`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Group_parent_id_group`.`name`,\'\')) as char charset utf8mb4) AS `parent_id_friendlyname`,coalesce((`Group_parent_id_group`.`status` = \'obsolete\'),0) AS `parent_id_obsolescence_flag` from ((`itop`.`group` `_group` join `itop`.`organization` `Organization_org_id_organization` on((`_group`.`org_id` = `Organization_org_id_organization`.`id`))) left join `itop`.`group` `Group_parent_id_group` on((`_group`.`parent_id` = `Group_parent_id_group`.`id`))) where 1
md5=5c578a55a9f60a50ffdf90e070b0a432
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:05
create-version=1
source=SELECT DISTINCT `_group`.`id` AS `id`, `_group`.`name` AS `name`, `_group`.`status` AS `status`, `_group`.`org_id` AS `org_id`, `Organization_org_id_organization`.`name` AS `owner_name`, `_group`.`description` AS `description`, `_group`.`type` AS `type`, `_group`.`parent_id` AS `parent_id`, `Group_parent_id_group`.`name` AS `parent_name`, CAST(CONCAT(COALESCE(`_group`.`name`, \'\')) AS CHAR) AS `friendlyname`, COALESCE((`_group`.`status` = \'obsolete\'), 0) AS `obsolescence_flag`, `_group`.`obsolescence_date` AS `obsolescence_date`, CAST(CONCAT(COALESCE(`Organization_org_id_organization`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`, COALESCE((`Organization_org_id_organization`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`Group_parent_id_group`.`name`, \'\')) AS CHAR) AS `parent_id_friendlyname`, COALESCE((`Group_parent_id_group`.`status` = \'obsolete\'), 0) AS `parent_id_obsolescence_flag` FROM `group` AS `_group`INNER JOIN `organization` AS `Organization_org_id_organization` ON `_group`.`org_id` = `Organization_org_id_organization`.`id`LEFT JOIN `group` AS `Group_parent_id_group` ON `_group`.`parent_id` = `Group_parent_id_group`.`id` WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_group`.`id` AS `id`,`_group`.`name` AS `name`,`_group`.`status` AS `status`,`_group`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `owner_name`,`_group`.`description` AS `description`,`_group`.`type` AS `type`,`_group`.`parent_id` AS `parent_id`,`Group_parent_id_group`.`name` AS `parent_name`,cast(concat(coalesce(`_group`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`_group`.`status` = \'obsolete\'),0) AS `obsolescence_flag`,`_group`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Group_parent_id_group`.`name`,\'\')) as char charset utf8mb4) AS `parent_id_friendlyname`,coalesce((`Group_parent_id_group`.`status` = \'obsolete\'),0) AS `parent_id_obsolescence_flag` from ((`itop`.`group` `_group` join `itop`.`organization` `Organization_org_id_organization` on((`_group`.`org_id` = `Organization_org_id_organization`.`id`))) left join `itop`.`group` `Group_parent_id_group` on((`_group`.`parent_id` = `Group_parent_id_group`.`id`))) where 1
