TYPE=VIEW
query=select distinct `_workorder`.`id` AS `id`,`_workorder`.`name` AS `name`,`_workorder`.`status` AS `status`,`_workorder`.`description` AS `description`,`_workorder`.`ticket_id` AS `ticket_id`,`Ticket_ticket_id_ticket`.`ref` AS `ticket_ref`,`_workorder`.`team_id` AS `team_id`,`Team_team_id_contact`.`email` AS `team_name`,`_workorder`.`owner_id` AS `agent_id`,`Person_agent_id_contact`.`email` AS `agent_email`,`_workorder`.`start_date` AS `start_date`,`_workorder`.`end_date` AS `end_date`,`_workorder`.`log` AS `log`,`_workorder`.`log_index` AS `log_index`,cast(concat(coalesce(`_workorder`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Ticket_ticket_id_ticket`.`ref`,\'\')) as char charset utf8mb4) AS `ticket_id_friendlyname`,`Ticket_ticket_id_ticket`.`finalclass` AS `ticket_id_finalclass_recall`,cast(concat(coalesce(`Team_team_id_contact`.`name`,\'\')) as char charset utf8mb4) AS `team_id_friendlyname`,coalesce((`Team_team_id_contact`.`status` = \'inactive\'),0) AS `team_id_obsolescence_flag`,cast(concat(coalesce(`Person_agent_id_person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Person_agent_id_contact`.`name`,\'\')) as char charset utf8mb4) AS `agent_id_friendlyname`,coalesce((`Person_agent_id_contact`.`status` = \'inactive\'),0) AS `agent_id_obsolescence_flag` from (((`itop`.`workorder` `_workorder` join `itop`.`ticket` `Ticket_ticket_id_ticket` on((`_workorder`.`ticket_id` = `Ticket_ticket_id_ticket`.`id`))) join `itop`.`contact` `Team_team_id_contact` on((`_workorder`.`team_id` = `Team_team_id_contact`.`id`))) left join (`itop`.`contact` `Person_agent_id_contact` join `itop`.`person` `Person_agent_id_person` on((`Person_agent_id_contact`.`id` = `Person_agent_id_person`.`id`))) on((`_workorder`.`owner_id` = `Person_agent_id_contact`.`id`))) where (coalesce((`Team_team_id_contact`.`finalclass` = \'Team\'),1) and coalesce((`Person_agent_id_contact`.`finalclass` = \'Person\'),1))
md5=08d4b3ebd10617d9229c043e3517fd93
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:06
create-version=1
source=SELECT DISTINCT `_workorder`.`id` AS `id`, `_workorder`.`name` AS `name`, `_workorder`.`status` AS `status`, `_workorder`.`description` AS `description`, `_workorder`.`ticket_id` AS `ticket_id`, `Ticket_ticket_id_ticket`.`ref` AS `ticket_ref`, `_workorder`.`team_id` AS `team_id`, `Team_team_id_contact`.`email` AS `team_name`, `_workorder`.`owner_id` AS `agent_id`, `Person_agent_id_contact`.`email` AS `agent_email`, `_workorder`.`start_date` AS `start_date`, `_workorder`.`end_date` AS `end_date`, `_workorder`.`log` AS `log`, `_workorder`.`log_index` AS `log_index`, CAST(CONCAT(COALESCE(`_workorder`.`name`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`Ticket_ticket_id_ticket`.`ref`, \'\')) AS CHAR) AS `ticket_id_friendlyname`, `Ticket_ticket_id_ticket`.`finalclass` AS `ticket_id_finalclass_recall`, CAST(CONCAT(COALESCE(`Team_team_id_contact`.`name`, \'\')) AS CHAR) AS `team_id_friendlyname`, COALESCE((`Team_team_id_contact`.`status` = \'inactive\'), 0) AS `team_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`Person_agent_id_person`.`first_name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Person_agent_id_contact`.`name`, \'\')) AS CHAR) AS `agent_id_friendlyname`, COALESCE((`Person_agent_id_contact`.`status` = \'inactive\'), 0) AS `agent_id_obsolescence_flag` FROM `workorder` AS `_workorder`INNER JOIN `ticket` AS `Ticket_ticket_id_ticket` ON `_workorder`.`ticket_id` = `Ticket_ticket_id_ticket`.`id`INNER JOIN `contact` AS `Team_team_id_contact` ON `_workorder`.`team_id` = `Team_team_id_contact`.`id`LEFT JOIN (`contact` AS `Person_agent_id_contact` INNER JOIN `person` AS `Person_agent_id_person` ON `Person_agent_id_contact`.`id` = `Person_agent_id_person`.`id`) ON `_workorder`.`owner_id` = `Person_agent_id_contact`.`id` WHERE (COALESCE((`Team_team_id_contact`.`finalclass` IN (\'Team\')), 1) AND COALESCE((`Person_agent_id_contact`.`finalclass` IN (\'Person\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_workorder`.`id` AS `id`,`_workorder`.`name` AS `name`,`_workorder`.`status` AS `status`,`_workorder`.`description` AS `description`,`_workorder`.`ticket_id` AS `ticket_id`,`Ticket_ticket_id_ticket`.`ref` AS `ticket_ref`,`_workorder`.`team_id` AS `team_id`,`Team_team_id_contact`.`email` AS `team_name`,`_workorder`.`owner_id` AS `agent_id`,`Person_agent_id_contact`.`email` AS `agent_email`,`_workorder`.`start_date` AS `start_date`,`_workorder`.`end_date` AS `end_date`,`_workorder`.`log` AS `log`,`_workorder`.`log_index` AS `log_index`,cast(concat(coalesce(`_workorder`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Ticket_ticket_id_ticket`.`ref`,\'\')) as char charset utf8mb4) AS `ticket_id_friendlyname`,`Ticket_ticket_id_ticket`.`finalclass` AS `ticket_id_finalclass_recall`,cast(concat(coalesce(`Team_team_id_contact`.`name`,\'\')) as char charset utf8mb4) AS `team_id_friendlyname`,coalesce((`Team_team_id_contact`.`status` = \'inactive\'),0) AS `team_id_obsolescence_flag`,cast(concat(coalesce(`Person_agent_id_person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Person_agent_id_contact`.`name`,\'\')) as char charset utf8mb4) AS `agent_id_friendlyname`,coalesce((`Person_agent_id_contact`.`status` = \'inactive\'),0) AS `agent_id_obsolescence_flag` from (((`itop`.`workorder` `_workorder` join `itop`.`ticket` `Ticket_ticket_id_ticket` on((`_workorder`.`ticket_id` = `Ticket_ticket_id_ticket`.`id`))) join `itop`.`contact` `Team_team_id_contact` on((`_workorder`.`team_id` = `Team_team_id_contact`.`id`))) left join (`itop`.`contact` `Person_agent_id_contact` join `itop`.`person` `Person_agent_id_person` on((`Person_agent_id_contact`.`id` = `Person_agent_id_person`.`id`))) on((`_workorder`.`owner_id` = `Person_agent_id_contact`.`id`))) where (coalesce((`Team_team_id_contact`.`finalclass` = \'Team\'),1) and coalesce((`Person_agent_id_contact`.`finalclass` = \'Person\'),1))
