TYPE=VIEW
query=select distinct `_contact`.`id` AS `id`,`_contact`.`name` AS `name`,`_contact`.`status` AS `status`,`_contact`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `org_name`,`_contact`.`email` AS `email`,`_contact`.`phone` AS `phone`,`_contact`.`notify` AS `notify`,`_contact`.`function` AS `function`,`_person`.`picture_mimetype` AS `picture`,`_person`.`picture_data` AS `picture_data`,`_person`.`picture_filename` AS `picture_filename`,`_person`.`first_name` AS `first_name`,`_person`.`employee_number` AS `employee_number`,`_person`.`mobile_phone` AS `mobile_phone`,`_person`.`location_id` AS `location_id`,`Location_location_id_location`.`name` AS `location_name`,`_person`.`manager_id` AS `manager_id`,`Person_manager_id_contact`.`name` AS `manager_name`,`_contact`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`_contact`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`_contact`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`_contact`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Location_location_id_location`.`name`,\'\')) as char charset utf8mb4) AS `location_id_friendlyname`,coalesce((`Location_location_id_location`.`status` = \'inactive\'),0) AS `location_id_obsolescence_flag`,cast(concat(coalesce(`Person_manager_id_person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Person_manager_id_contact`.`name`,\'\')) as char charset utf8mb4) AS `manager_id_friendlyname`,coalesce((`Person_manager_id_contact`.`status` = \'inactive\'),0) AS `manager_id_obsolescence_flag` from ((`itop`.`contact` `_contact` join `itop`.`organization` `Organization_org_id_organization` on((`_contact`.`org_id` = `Organization_org_id_organization`.`id`))) join ((`itop`.`person` `_person` left join `itop`.`location` `Location_location_id_location` on((`_person`.`location_id` = `Location_location_id_location`.`id`))) left join (`itop`.`contact` `Person_manager_id_contact` join `itop`.`person` `Person_manager_id_person` on((`Person_manager_id_contact`.`id` = `Person_manager_id_person`.`id`))) on((`_person`.`manager_id` = `Person_manager_id_contact`.`id`))) on((`_contact`.`id` = `_person`.`id`))) where (coalesce((`_contact`.`finalclass` = \'Person\'),1) and coalesce((`Person_manager_id_contact`.`finalclass` = \'Person\'),1))
md5=5c4acc8a22ae316125b7cf9693675f85
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:04
create-version=1
source=SELECT DISTINCT `_contact`.`id` AS `id`, `_contact`.`name` AS `name`, `_contact`.`status` AS `status`, `_contact`.`org_id` AS `org_id`, `Organization_org_id_organization`.`name` AS `org_name`, `_contact`.`email` AS `email`, `_contact`.`phone` AS `phone`, `_contact`.`notify` AS `notify`, `_contact`.`function` AS `function`, `_person`.`picture_mimetype` AS `picture`, `_person`.`picture_data` AS `picture_data`, `_person`.`picture_filename` AS `picture_filename`, `_person`.`first_name` AS `first_name`, `_person`.`employee_number` AS `employee_number`, `_person`.`mobile_phone` AS `mobile_phone`, `_person`.`location_id` AS `location_id`, `Location_location_id_location`.`name` AS `location_name`, `_person`.`manager_id` AS `manager_id`, `Person_manager_id_contact`.`name` AS `manager_name`, `_contact`.`finalclass` AS `finalclass`, CAST(CONCAT(COALESCE(`_person`.`first_name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`_contact`.`name`, \'\')) AS CHAR) AS `friendlyname`, COALESCE((`_contact`.`status` = \'inactive\'), 0) AS `obsolescence_flag`, `_contact`.`obsolescence_date` AS `obsolescence_date`, CAST(CONCAT(COALESCE(`Organization_org_id_organization`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`, COALESCE((`Organization_org_id_organization`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`Location_location_id_location`.`name`, \'\')) AS CHAR) AS `location_id_friendlyname`, COALESCE((`Location_location_id_location`.`status` = \'inactive\'), 0) AS `location_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`Person_manager_id_person`.`first_name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Person_manager_id_contact`.`name`, \'\')) AS CHAR) AS `manager_id_friendlyname`, COALESCE((`Person_manager_id_contact`.`status` = \'inactive\'), 0) AS `manager_id_obsolescence_flag` FROM `contact` AS `_contact`INNER JOIN `organization` AS `Organization_org_id_organization` ON `_contact`.`org_id` = `Organization_org_id_organization`.`id`INNER JOIN (`person` AS `_person` LEFT JOIN `location` AS `Location_location_id_location` ON `_person`.`location_id` = `Location_location_id_location`.`id`LEFT JOIN (`contact` AS `Person_manager_id_contact` INNER JOIN `person` AS `Person_manager_id_person` ON `Person_manager_id_contact`.`id` = `Person_manager_id_person`.`id`) ON `_person`.`manager_id` = `Person_manager_id_contact`.`id`) ON `_contact`.`id` = `_person`.`id` WHERE (COALESCE((`_contact`.`finalclass` IN (\'Person\')), 1) AND COALESCE((`Person_manager_id_contact`.`finalclass` IN (\'Person\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_contact`.`id` AS `id`,`_contact`.`name` AS `name`,`_contact`.`status` AS `status`,`_contact`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `org_name`,`_contact`.`email` AS `email`,`_contact`.`phone` AS `phone`,`_contact`.`notify` AS `notify`,`_contact`.`function` AS `function`,`_person`.`picture_mimetype` AS `picture`,`_person`.`picture_data` AS `picture_data`,`_person`.`picture_filename` AS `picture_filename`,`_person`.`first_name` AS `first_name`,`_person`.`employee_number` AS `employee_number`,`_person`.`mobile_phone` AS `mobile_phone`,`_person`.`location_id` AS `location_id`,`Location_location_id_location`.`name` AS `location_name`,`_person`.`manager_id` AS `manager_id`,`Person_manager_id_contact`.`name` AS `manager_name`,`_contact`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`_contact`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`_contact`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`_contact`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Location_location_id_location`.`name`,\'\')) as char charset utf8mb4) AS `location_id_friendlyname`,coalesce((`Location_location_id_location`.`status` = \'inactive\'),0) AS `location_id_obsolescence_flag`,cast(concat(coalesce(`Person_manager_id_person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Person_manager_id_contact`.`name`,\'\')) as char charset utf8mb4) AS `manager_id_friendlyname`,coalesce((`Person_manager_id_contact`.`status` = \'inactive\'),0) AS `manager_id_obsolescence_flag` from ((`itop`.`contact` `_contact` join `itop`.`organization` `Organization_org_id_organization` on((`_contact`.`org_id` = `Organization_org_id_organization`.`id`))) join ((`itop`.`person` `_person` left join `itop`.`location` `Location_location_id_location` on((`_person`.`location_id` = `Location_location_id_location`.`id`))) left join (`itop`.`contact` `Person_manager_id_contact` join `itop`.`person` `Person_manager_id_person` on((`Person_manager_id_contact`.`id` = `Person_manager_id_person`.`id`))) on((`_person`.`manager_id` = `Person_manager_id_contact`.`id`))) on((`_contact`.`id` = `_person`.`id`))) where (coalesce((`_contact`.`finalclass` = \'Person\'),1) and coalesce((`Person_manager_id_contact`.`finalclass` = \'Person\'),1))
