TYPE=VIEW
query=select distinct `_networkinterface`.`id` AS `id`,`_networkinterface`.`name` AS `name`,`_ipinterface`.`ipaddress` AS `ipaddress`,`_ipinterface`.`macaddress` AS `macaddress`,`_ipinterface`.`comment` AS `comment`,`_ipinterface`.`ipgateway` AS `ipgateway`,`_ipinterface`.`ipmask` AS `ipmask`,`_ipinterface`.`speed` AS `speed`,`_physicalinterface`.`connectableci_id` AS `connectableci_id`,`ConnectableCI_connectableci_id_functionalci`.`name` AS `connectableci_name`,`_networkinterface`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_networkinterface`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`ConnectableCI_connectableci_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`ConnectableCI_connectableci_id_physicaldevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`_networkinterface`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`ConnectableCI_connectableci_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `connectableci_id_friendlyname`,`ConnectableCI_connectableci_id_functionalci`.`finalclass` AS `connectableci_id_finalclass_recall`,coalesce((`ConnectableCI_connectableci_id_physicaldevice`.`status` = \'obsolete\'),0) AS `connectableci_id_obsolescence_flag` from ((`itop`.`networkinterface` `_networkinterface` join `itop`.`ipinterface` `_ipinterface` on((`_networkinterface`.`id` = `_ipinterface`.`id`))) join (`itop`.`physicalinterface` `_physicalinterface` join (`itop`.`functionalci` `ConnectableCI_connectableci_id_functionalci` join `itop`.`physicaldevice` `ConnectableCI_connectableci_id_physicaldevice` on((`ConnectableCI_connectableci_id_functionalci`.`id` = `ConnectableCI_connectableci_id_physicaldevice`.`id`))) on((`_physicalinterface`.`connectableci_id` = `ConnectableCI_connectableci_id_functionalci`.`id`))) on((`_networkinterface`.`id` = `_physicalinterface`.`id`))) where (coalesce((`_networkinterface`.`finalclass` = \'PhysicalInterface\'),1) and coalesce((`ConnectableCI_connectableci_id_functionalci`.`finalclass` in (\'DatacenterDevice\',\'NetworkDevice\',\'Server\',\'PC\',\'Printer\',\'StorageSystem\',\'SANSwitch\',\'TapeLibrary\',\'NAS\',\'ConnectableCI\')),1))
md5=ab316c4cf69824672b337d68e17b6b19
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:05
create-version=1
source=SELECT DISTINCT `_networkinterface`.`id` AS `id`, `_networkinterface`.`name` AS `name`, `_ipinterface`.`ipaddress` AS `ipaddress`, `_ipinterface`.`macaddress` AS `macaddress`, `_ipinterface`.`comment` AS `comment`, `_ipinterface`.`ipgateway` AS `ipgateway`, `_ipinterface`.`ipmask` AS `ipmask`, `_ipinterface`.`speed` AS `speed`, `_physicalinterface`.`connectableci_id` AS `connectableci_id`, `ConnectableCI_connectableci_id_functionalci`.`name` AS `connectableci_name`, `_networkinterface`.`finalclass` AS `finalclass`, CAST(CONCAT(COALESCE(`_networkinterface`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`ConnectableCI_connectableci_id_functionalci`.`name`, \'\')) AS CHAR) AS `friendlyname`, COALESCE(COALESCE((`ConnectableCI_connectableci_id_physicaldevice`.`status` = \'obsolete\'), 0), 0) AS `obsolescence_flag`, `_networkinterface`.`obsolescence_date` AS `obsolescence_date`, CAST(CONCAT(COALESCE(`ConnectableCI_connectableci_id_functionalci`.`name`, \'\')) AS CHAR) AS `connectableci_id_friendlyname`, `ConnectableCI_connectableci_id_functionalci`.`finalclass` AS `connectableci_id_finalclass_recall`, COALESCE((`ConnectableCI_connectableci_id_physicaldevice`.`status` = \'obsolete\'), 0) AS `connectableci_id_obsolescence_flag` FROM `networkinterface` AS `_networkinterface`INNER JOIN `ipinterface` AS `_ipinterface` ON `_networkinterface`.`id` = `_ipinterface`.`id`INNER JOIN (`physicalinterface` AS `_physicalinterface` INNER JOIN (`functionalci` AS `ConnectableCI_connectableci_id_functionalci` INNER JOIN `physicaldevice` AS `ConnectableCI_connectableci_id_physicaldevice` ON `ConnectableCI_connectableci_id_functionalci`.`id` = `ConnectableCI_connectableci_id_physicaldevice`.`id`) ON `_physicalinterface`.`connectableci_id` = `ConnectableCI_connectableci_id_functionalci`.`id`) ON `_networkinterface`.`id` = `_physicalinterface`.`id` WHERE (COALESCE((`_networkinterface`.`finalclass` IN (\'PhysicalInterface\')), 1) AND COALESCE((`ConnectableCI_connectableci_id_functionalci`.`finalclass` IN (\'DatacenterDevice\', \'NetworkDevice\', \'Server\', \'PC\', \'Printer\', \'StorageSystem\', \'SANSwitch\', \'TapeLibrary\', \'NAS\', \'ConnectableCI\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_networkinterface`.`id` AS `id`,`_networkinterface`.`name` AS `name`,`_ipinterface`.`ipaddress` AS `ipaddress`,`_ipinterface`.`macaddress` AS `macaddress`,`_ipinterface`.`comment` AS `comment`,`_ipinterface`.`ipgateway` AS `ipgateway`,`_ipinterface`.`ipmask` AS `ipmask`,`_ipinterface`.`speed` AS `speed`,`_physicalinterface`.`connectableci_id` AS `connectableci_id`,`ConnectableCI_connectableci_id_functionalci`.`name` AS `connectableci_name`,`_networkinterface`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_networkinterface`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`ConnectableCI_connectableci_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`ConnectableCI_connectableci_id_physicaldevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`_networkinterface`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`ConnectableCI_connectableci_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `connectableci_id_friendlyname`,`ConnectableCI_connectableci_id_functionalci`.`finalclass` AS `connectableci_id_finalclass_recall`,coalesce((`ConnectableCI_connectableci_id_physicaldevice`.`status` = \'obsolete\'),0) AS `connectableci_id_obsolescence_flag` from ((`itop`.`networkinterface` `_networkinterface` join `itop`.`ipinterface` `_ipinterface` on((`_networkinterface`.`id` = `_ipinterface`.`id`))) join (`itop`.`physicalinterface` `_physicalinterface` join (`itop`.`functionalci` `ConnectableCI_connectableci_id_functionalci` join `itop`.`physicaldevice` `ConnectableCI_connectableci_id_physicaldevice` on((`ConnectableCI_connectableci_id_functionalci`.`id` = `ConnectableCI_connectableci_id_physicaldevice`.`id`))) on((`_physicalinterface`.`connectableci_id` = `ConnectableCI_connectableci_id_functionalci`.`id`))) on((`_networkinterface`.`id` = `_physicalinterface`.`id`))) where (coalesce((`_networkinterface`.`finalclass` = \'PhysicalInterface\'),1) and coalesce((`ConnectableCI_connectableci_id_functionalci`.`finalclass` in (\'DatacenterDevice\',\'NetworkDevice\',\'Server\',\'PC\',\'Printer\',\'StorageSystem\',\'SANSwitch\',\'TapeLibrary\',\'NAS\',\'ConnectableCI\')),1))
