TYPE=VIEW
query=select distinct `_networkinterface`.`id` AS `id`,`_networkinterface`.`name` AS `name`,`_fiberchannelinterface`.`speed` AS `speed`,`_fiberchannelinterface`.`topology` AS `topology`,`_fiberchannelinterface`.`wwn` AS `wwn`,`_fiberchannelinterface`.`datacenterdevice_id` AS `datacenterdevice_id`,`DatacenterDevice_datacenterdevice_id_functionalci`.`name` AS `datacenterdevice_name`,`_networkinterface`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_networkinterface`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`DatacenterDevice_datacenterdevice_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`DatacenterDevice_datacenterdevice_id_physicaldevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`_networkinterface`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`DatacenterDevice_datacenterdevice_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `datacenterdevice_id_friendlyname`,`DatacenterDevice_datacenterdevice_id_functionalci`.`finalclass` AS `datacenterdevice_id_finalclass_recall`,coalesce((`DatacenterDevice_datacenterdevice_id_physicaldevice`.`status` = \'obsolete\'),0) AS `datacenterdevice_id_obsolescence_flag` from (`itop`.`networkinterface` `_networkinterface` join (`itop`.`fiberchannelinterface` `_fiberchannelinterface` join (`itop`.`functionalci` `DatacenterDevice_datacenterdevice_id_functionalci` join `itop`.`physicaldevice` `DatacenterDevice_datacenterdevice_id_physicaldevice` on((`DatacenterDevice_datacenterdevice_id_functionalci`.`id` = `DatacenterDevice_datacenterdevice_id_physicaldevice`.`id`))) on((`_fiberchannelinterface`.`datacenterdevice_id` = `DatacenterDevice_datacenterdevice_id_functionalci`.`id`))) on((`_networkinterface`.`id` = `_fiberchannelinterface`.`id`))) where (coalesce((`_networkinterface`.`finalclass` = \'FiberChannelInterface\'),1) and coalesce((`DatacenterDevice_datacenterdevice_id_functionalci`.`finalclass` in (\'NetworkDevice\',\'Server\',\'StorageSystem\',\'SANSwitch\',\'TapeLibrary\',\'NAS\',\'DatacenterDevice\')),1))
md5=64b363ba7cb25e90fd1064dad1640f57
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:06
create-version=1
source=SELECT DISTINCT `_networkinterface`.`id` AS `id`, `_networkinterface`.`name` AS `name`, `_fiberchannelinterface`.`speed` AS `speed`, `_fiberchannelinterface`.`topology` AS `topology`, `_fiberchannelinterface`.`wwn` AS `wwn`, `_fiberchannelinterface`.`datacenterdevice_id` AS `datacenterdevice_id`, `DatacenterDevice_datacenterdevice_id_functionalci`.`name` AS `datacenterdevice_name`, `_networkinterface`.`finalclass` AS `finalclass`, CAST(CONCAT(COALESCE(`_networkinterface`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`DatacenterDevice_datacenterdevice_id_functionalci`.`name`, \'\')) AS CHAR) AS `friendlyname`, COALESCE(COALESCE((`DatacenterDevice_datacenterdevice_id_physicaldevice`.`status` = \'obsolete\'), 0), 0) AS `obsolescence_flag`, `_networkinterface`.`obsolescence_date` AS `obsolescence_date`, CAST(CONCAT(COALESCE(`DatacenterDevice_datacenterdevice_id_functionalci`.`name`, \'\')) AS CHAR) AS `datacenterdevice_id_friendlyname`, `DatacenterDevice_datacenterdevice_id_functionalci`.`finalclass` AS `datacenterdevice_id_finalclass_recall`, COALESCE((`DatacenterDevice_datacenterdevice_id_physicaldevice`.`status` = \'obsolete\'), 0) AS `datacenterdevice_id_obsolescence_flag` FROM `networkinterface` AS `_networkinterface`INNER JOIN (`fiberchannelinterface` AS `_fiberchannelinterface` INNER JOIN (`functionalci` AS `DatacenterDevice_datacenterdevice_id_functionalci` INNER JOIN `physicaldevice` AS `DatacenterDevice_datacenterdevice_id_physicaldevice` ON `DatacenterDevice_datacenterdevice_id_functionalci`.`id` = `DatacenterDevice_datacenterdevice_id_physicaldevice`.`id`) ON `_fiberchannelinterface`.`datacenterdevice_id` = `DatacenterDevice_datacenterdevice_id_functionalci`.`id`) ON `_networkinterface`.`id` = `_fiberchannelinterface`.`id` WHERE (COALESCE((`_networkinterface`.`finalclass` IN (\'FiberChannelInterface\')), 1) AND COALESCE((`DatacenterDevice_datacenterdevice_id_functionalci`.`finalclass` IN (\'NetworkDevice\', \'Server\', \'StorageSystem\', \'SANSwitch\', \'TapeLibrary\', \'NAS\', \'DatacenterDevice\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_networkinterface`.`id` AS `id`,`_networkinterface`.`name` AS `name`,`_fiberchannelinterface`.`speed` AS `speed`,`_fiberchannelinterface`.`topology` AS `topology`,`_fiberchannelinterface`.`wwn` AS `wwn`,`_fiberchannelinterface`.`datacenterdevice_id` AS `datacenterdevice_id`,`DatacenterDevice_datacenterdevice_id_functionalci`.`name` AS `datacenterdevice_name`,`_networkinterface`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_networkinterface`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`DatacenterDevice_datacenterdevice_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`DatacenterDevice_datacenterdevice_id_physicaldevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`_networkinterface`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`DatacenterDevice_datacenterdevice_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `datacenterdevice_id_friendlyname`,`DatacenterDevice_datacenterdevice_id_functionalci`.`finalclass` AS `datacenterdevice_id_finalclass_recall`,coalesce((`DatacenterDevice_datacenterdevice_id_physicaldevice`.`status` = \'obsolete\'),0) AS `datacenterdevice_id_obsolescence_flag` from (`itop`.`networkinterface` `_networkinterface` join (`itop`.`fiberchannelinterface` `_fiberchannelinterface` join (`itop`.`functionalci` `DatacenterDevice_datacenterdevice_id_functionalci` join `itop`.`physicaldevice` `DatacenterDevice_datacenterdevice_id_physicaldevice` on((`DatacenterDevice_datacenterdevice_id_functionalci`.`id` = `DatacenterDevice_datacenterdevice_id_physicaldevice`.`id`))) on((`_fiberchannelinterface`.`datacenterdevice_id` = `DatacenterDevice_datacenterdevice_id_functionalci`.`id`))) on((`_networkinterface`.`id` = `_fiberchannelinterface`.`id`))) where (coalesce((`_networkinterface`.`finalclass` = \'FiberChannelInterface\'),1) and coalesce((`DatacenterDevice_datacenterdevice_id_functionalci`.`finalclass` in (\'NetworkDevice\',\'Server\',\'StorageSystem\',\'SANSwitch\',\'TapeLibrary\',\'NAS\',\'DatacenterDevice\')),1))
