TYPE=VIEW
query=select distinct `_lnkprovidercontracttoservice`.`id` AS `id`,`_lnkprovidercontracttoservice`.`service_id` AS `service_id`,`Service_service_id_service`.`name` AS `service_name`,`_lnkprovidercontracttoservice`.`providercontract_id` AS `providercontract_id`,`ProviderContract_providercontract_id_contract`.`name` AS `providercontract_name`,cast(concat(coalesce(`_lnkprovidercontracttoservice`.`service_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkprovidercontracttoservice`.`providercontract_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Service_service_id_service`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,cast(concat(coalesce(`ProviderContract_providercontract_id_contract`.`name`,\'\')) as char charset utf8mb4) AS `providercontract_id_friendlyname` from ((`itop`.`lnkprovidercontracttoservice` `_lnkprovidercontracttoservice` join `itop`.`service` `Service_service_id_service` on((`_lnkprovidercontracttoservice`.`service_id` = `Service_service_id_service`.`id`))) join `itop`.`contract` `ProviderContract_providercontract_id_contract` on((`_lnkprovidercontracttoservice`.`providercontract_id` = `ProviderContract_providercontract_id_contract`.`id`))) where coalesce((`ProviderContract_providercontract_id_contract`.`finalclass` = \'ProviderContract\'),1)
md5=68c98ce792321db4b8d060caffb22ed3
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:08
create-version=1
source=SELECT DISTINCT `_lnkprovidercontracttoservice`.`id` AS `id`, `_lnkprovidercontracttoservice`.`service_id` AS `service_id`, `Service_service_id_service`.`name` AS `service_name`, `_lnkprovidercontracttoservice`.`providercontract_id` AS `providercontract_id`, `ProviderContract_providercontract_id_contract`.`name` AS `providercontract_name`, CAST(CONCAT(COALESCE(`_lnkprovidercontracttoservice`.`service_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`_lnkprovidercontracttoservice`.`providercontract_id`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`Service_service_id_service`.`name`, \'\')) AS CHAR) AS `service_id_friendlyname`, CAST(CONCAT(COALESCE(`ProviderContract_providercontract_id_contract`.`name`, \'\')) AS CHAR) AS `providercontract_id_friendlyname` FROM `lnkprovidercontracttoservice` AS `_lnkprovidercontracttoservice`INNER JOIN `service` AS `Service_service_id_service` ON `_lnkprovidercontracttoservice`.`service_id` = `Service_service_id_service`.`id`INNER JOIN `contract` AS `ProviderContract_providercontract_id_contract` ON `_lnkprovidercontracttoservice`.`providercontract_id` = `ProviderContract_providercontract_id_contract`.`id` WHERE COALESCE((`ProviderContract_providercontract_id_contract`.`finalclass` IN (\'ProviderContract\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_lnkprovidercontracttoservice`.`id` AS `id`,`_lnkprovidercontracttoservice`.`service_id` AS `service_id`,`Service_service_id_service`.`name` AS `service_name`,`_lnkprovidercontracttoservice`.`providercontract_id` AS `providercontract_id`,`ProviderContract_providercontract_id_contract`.`name` AS `providercontract_name`,cast(concat(coalesce(`_lnkprovidercontracttoservice`.`service_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkprovidercontracttoservice`.`providercontract_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Service_service_id_service`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,cast(concat(coalesce(`ProviderContract_providercontract_id_contract`.`name`,\'\')) as char charset utf8mb4) AS `providercontract_id_friendlyname` from ((`itop`.`lnkprovidercontracttoservice` `_lnkprovidercontracttoservice` join `itop`.`service` `Service_service_id_service` on((`_lnkprovidercontracttoservice`.`service_id` = `Service_service_id_service`.`id`))) join `itop`.`contract` `ProviderContract_providercontract_id_contract` on((`_lnkprovidercontracttoservice`.`providercontract_id` = `ProviderContract_providercontract_id_contract`.`id`))) where coalesce((`ProviderContract_providercontract_id_contract`.`finalclass` = \'ProviderContract\'),1)
