TYPE=VIEW
query=select distinct `_lnkcustomercontracttoservice`.`id` AS `id`,`_lnkcustomercontracttoservice`.`customercontract_id` AS `customercontract_id`,`CustomerContract_customercontract_id_contract`.`name` AS `customercontract_name`,`_lnkcustomercontracttoservice`.`service_id` AS `service_id`,`Service_service_id_service`.`name` AS `service_name`,`_lnkcustomercontracttoservice`.`sla_id` AS `sla_id`,`SLA_sla_id_sla`.`name` AS `sla_name`,cast(concat(coalesce(`_lnkcustomercontracttoservice`.`customercontract_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkcustomercontracttoservice`.`service_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`CustomerContract_customercontract_id_contract`.`name`,\'\')) as char charset utf8mb4) AS `customercontract_id_friendlyname`,cast(concat(coalesce(`Service_service_id_service`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,cast(concat(coalesce(`SLA_sla_id_sla`.`name`,\'\')) as char charset utf8mb4) AS `sla_id_friendlyname` from (((`itop`.`lnkcustomercontracttoservice` `_lnkcustomercontracttoservice` join `itop`.`contract` `CustomerContract_customercontract_id_contract` on((`_lnkcustomercontracttoservice`.`customercontract_id` = `CustomerContract_customercontract_id_contract`.`id`))) join `itop`.`service` `Service_service_id_service` on((`_lnkcustomercontracttoservice`.`service_id` = `Service_service_id_service`.`id`))) left join `itop`.`sla` `SLA_sla_id_sla` on((`_lnkcustomercontracttoservice`.`sla_id` = `SLA_sla_id_sla`.`id`))) where coalesce((`CustomerContract_customercontract_id_contract`.`finalclass` = \'CustomerContract\'),1)
md5=000fe83319433c9f4bcd0f0c4c8700a9
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:08
create-version=1
source=SELECT DISTINCT `_lnkcustomercontracttoservice`.`id` AS `id`, `_lnkcustomercontracttoservice`.`customercontract_id` AS `customercontract_id`, `CustomerContract_customercontract_id_contract`.`name` AS `customercontract_name`, `_lnkcustomercontracttoservice`.`service_id` AS `service_id`, `Service_service_id_service`.`name` AS `service_name`, `_lnkcustomercontracttoservice`.`sla_id` AS `sla_id`, `SLA_sla_id_sla`.`name` AS `sla_name`, CAST(CONCAT(COALESCE(`_lnkcustomercontracttoservice`.`customercontract_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`_lnkcustomercontracttoservice`.`service_id`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`CustomerContract_customercontract_id_contract`.`name`, \'\')) AS CHAR) AS `customercontract_id_friendlyname`, CAST(CONCAT(COALESCE(`Service_service_id_service`.`name`, \'\')) AS CHAR) AS `service_id_friendlyname`, CAST(CONCAT(COALESCE(`SLA_sla_id_sla`.`name`, \'\')) AS CHAR) AS `sla_id_friendlyname` FROM `lnkcustomercontracttoservice` AS `_lnkcustomercontracttoservice`INNER JOIN `contract` AS `CustomerContract_customercontract_id_contract` ON `_lnkcustomercontracttoservice`.`customercontract_id` = `CustomerContract_customercontract_id_contract`.`id`INNER JOIN `service` AS `Service_service_id_service` ON `_lnkcustomercontracttoservice`.`service_id` = `Service_service_id_service`.`id`LEFT JOIN `sla` AS `SLA_sla_id_sla` ON `_lnkcustomercontracttoservice`.`sla_id` = `SLA_sla_id_sla`.`id` WHERE COALESCE((`CustomerContract_customercontract_id_contract`.`finalclass` IN (\'CustomerContract\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_lnkcustomercontracttoservice`.`id` AS `id`,`_lnkcustomercontracttoservice`.`customercontract_id` AS `customercontract_id`,`CustomerContract_customercontract_id_contract`.`name` AS `customercontract_name`,`_lnkcustomercontracttoservice`.`service_id` AS `service_id`,`Service_service_id_service`.`name` AS `service_name`,`_lnkcustomercontracttoservice`.`sla_id` AS `sla_id`,`SLA_sla_id_sla`.`name` AS `sla_name`,cast(concat(coalesce(`_lnkcustomercontracttoservice`.`customercontract_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkcustomercontracttoservice`.`service_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`CustomerContract_customercontract_id_contract`.`name`,\'\')) as char charset utf8mb4) AS `customercontract_id_friendlyname`,cast(concat(coalesce(`Service_service_id_service`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,cast(concat(coalesce(`SLA_sla_id_sla`.`name`,\'\')) as char charset utf8mb4) AS `sla_id_friendlyname` from (((`itop`.`lnkcustomercontracttoservice` `_lnkcustomercontracttoservice` join `itop`.`contract` `CustomerContract_customercontract_id_contract` on((`_lnkcustomercontracttoservice`.`customercontract_id` = `CustomerContract_customercontract_id_contract`.`id`))) join `itop`.`service` `Service_service_id_service` on((`_lnkcustomercontracttoservice`.`service_id` = `Service_service_id_service`.`id`))) left join `itop`.`sla` `SLA_sla_id_sla` on((`_lnkcustomercontracttoservice`.`sla_id` = `SLA_sla_id_sla`.`id`))) where coalesce((`CustomerContract_customercontract_id_contract`.`finalclass` = \'CustomerContract\'),1)
