TYPE=VIEW
query=select distinct `_nasfilesystem`.`id` AS `id`,`_nasfilesystem`.`name` AS `name`,`_nasfilesystem`.`description` AS `description`,`_nasfilesystem`.`raid_level` AS `raid_level`,`_nasfilesystem`.`size` AS `size`,`_nasfilesystem`.`nas_id` AS `nas_id`,`NAS_nas_id_functionalci`.`name` AS `nas_name`,cast(concat(coalesce(`_nasfilesystem`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`NAS_nas_id_physicaldevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`_nasfilesystem`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`NAS_nas_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `nas_id_friendlyname`,coalesce((`NAS_nas_id_physicaldevice`.`status` = \'obsolete\'),0) AS `nas_id_obsolescence_flag` from (`itop`.`nasfilesystem` `_nasfilesystem` join (`itop`.`functionalci` `NAS_nas_id_functionalci` join `itop`.`physicaldevice` `NAS_nas_id_physicaldevice` on((`NAS_nas_id_functionalci`.`id` = `NAS_nas_id_physicaldevice`.`id`))) on((`_nasfilesystem`.`nas_id` = `NAS_nas_id_functionalci`.`id`))) where coalesce((`NAS_nas_id_functionalci`.`finalclass` = \'NAS\'),1)
md5=19753adcd9e0d49e9ca09d8c6296c032
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:06
create-version=1
source=SELECT DISTINCT `_nasfilesystem`.`id` AS `id`, `_nasfilesystem`.`name` AS `name`, `_nasfilesystem`.`description` AS `description`, `_nasfilesystem`.`raid_level` AS `raid_level`, `_nasfilesystem`.`size` AS `size`, `_nasfilesystem`.`nas_id` AS `nas_id`, `NAS_nas_id_functionalci`.`name` AS `nas_name`, CAST(CONCAT(COALESCE(`_nasfilesystem`.`name`, \'\')) AS CHAR) AS `friendlyname`, COALESCE(COALESCE((`NAS_nas_id_physicaldevice`.`status` = \'obsolete\'), 0), 0) AS `obsolescence_flag`, `_nasfilesystem`.`obsolescence_date` AS `obsolescence_date`, CAST(CONCAT(COALESCE(`NAS_nas_id_functionalci`.`name`, \'\')) AS CHAR) AS `nas_id_friendlyname`, COALESCE((`NAS_nas_id_physicaldevice`.`status` = \'obsolete\'), 0) AS `nas_id_obsolescence_flag` FROM `nasfilesystem` AS `_nasfilesystem`INNER JOIN (`functionalci` AS `NAS_nas_id_functionalci` INNER JOIN `physicaldevice` AS `NAS_nas_id_physicaldevice` ON `NAS_nas_id_functionalci`.`id` = `NAS_nas_id_physicaldevice`.`id`) ON `_nasfilesystem`.`nas_id` = `NAS_nas_id_functionalci`.`id` WHERE COALESCE((`NAS_nas_id_functionalci`.`finalclass` IN (\'NAS\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_nasfilesystem`.`id` AS `id`,`_nasfilesystem`.`name` AS `name`,`_nasfilesystem`.`description` AS `description`,`_nasfilesystem`.`raid_level` AS `raid_level`,`_nasfilesystem`.`size` AS `size`,`_nasfilesystem`.`nas_id` AS `nas_id`,`NAS_nas_id_functionalci`.`name` AS `nas_name`,cast(concat(coalesce(`_nasfilesystem`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`NAS_nas_id_physicaldevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`_nasfilesystem`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`NAS_nas_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `nas_id_friendlyname`,coalesce((`NAS_nas_id_physicaldevice`.`status` = \'obsolete\'),0) AS `nas_id_obsolescence_flag` from (`itop`.`nasfilesystem` `_nasfilesystem` join (`itop`.`functionalci` `NAS_nas_id_functionalci` join `itop`.`physicaldevice` `NAS_nas_id_physicaldevice` on((`NAS_nas_id_functionalci`.`id` = `NAS_nas_id_physicaldevice`.`id`))) on((`_nasfilesystem`.`nas_id` = `NAS_nas_id_functionalci`.`id`))) where coalesce((`NAS_nas_id_functionalci`.`finalclass` = \'NAS\'),1)
