TYPE=VIEW
query=select distinct `_lnkpersontoteam`.`id` AS `id`,`_lnkpersontoteam`.`team_id` AS `team_id`,`Team_team_id_contact`.`name` AS `team_name`,`_lnkpersontoteam`.`person_id` AS `person_id`,`Person_person_id_contact`.`name` AS `person_name`,`_lnkpersontoteam`.`role_id` AS `role_id`,`ContactType_role_id_typology`.`name` AS `role_name`,cast(concat(coalesce(`_lnkpersontoteam`.`team_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkpersontoteam`.`person_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Team_team_id_contact`.`name`,\'\')) as char charset utf8mb4) AS `team_id_friendlyname`,coalesce((`Team_team_id_contact`.`status` = \'inactive\'),0) AS `team_id_obsolescence_flag`,cast(concat(coalesce(`Person_person_id_person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Person_person_id_contact`.`name`,\'\')) as char charset utf8mb4) AS `person_id_friendlyname`,coalesce((`Person_person_id_contact`.`status` = \'inactive\'),0) AS `person_id_obsolescence_flag`,cast(concat(coalesce(`ContactType_role_id_typology`.`name`,\'\')) as char charset utf8mb4) AS `role_id_friendlyname` from (((`itop`.`lnkpersontoteam` `_lnkpersontoteam` join `itop`.`contact` `Team_team_id_contact` on((`_lnkpersontoteam`.`team_id` = `Team_team_id_contact`.`id`))) join (`itop`.`contact` `Person_person_id_contact` join `itop`.`person` `Person_person_id_person` on((`Person_person_id_contact`.`id` = `Person_person_id_person`.`id`))) on((`_lnkpersontoteam`.`person_id` = `Person_person_id_contact`.`id`))) left join `itop`.`typology` `ContactType_role_id_typology` on((`_lnkpersontoteam`.`role_id` = `ContactType_role_id_typology`.`id`))) where (coalesce((`Team_team_id_contact`.`finalclass` = \'Team\'),1) and coalesce((`Person_person_id_contact`.`finalclass` = \'Person\'),1) and coalesce((`ContactType_role_id_typology`.`finalclass` = \'ContactType\'),1))
md5=1762ba7a5ef7d4e93e42f93e83c7f552
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:05
create-version=1
source=SELECT DISTINCT `_lnkpersontoteam`.`id` AS `id`, `_lnkpersontoteam`.`team_id` AS `team_id`, `Team_team_id_contact`.`name` AS `team_name`, `_lnkpersontoteam`.`person_id` AS `person_id`, `Person_person_id_contact`.`name` AS `person_name`, `_lnkpersontoteam`.`role_id` AS `role_id`, `ContactType_role_id_typology`.`name` AS `role_name`, CAST(CONCAT(COALESCE(`_lnkpersontoteam`.`team_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`_lnkpersontoteam`.`person_id`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`Team_team_id_contact`.`name`, \'\')) AS CHAR) AS `team_id_friendlyname`, COALESCE((`Team_team_id_contact`.`status` = \'inactive\'), 0) AS `team_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`Person_person_id_person`.`first_name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Person_person_id_contact`.`name`, \'\')) AS CHAR) AS `person_id_friendlyname`, COALESCE((`Person_person_id_contact`.`status` = \'inactive\'), 0) AS `person_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`ContactType_role_id_typology`.`name`, \'\')) AS CHAR) AS `role_id_friendlyname` FROM `lnkpersontoteam` AS `_lnkpersontoteam`INNER JOIN `contact` AS `Team_team_id_contact` ON `_lnkpersontoteam`.`team_id` = `Team_team_id_contact`.`id`INNER JOIN (`contact` AS `Person_person_id_contact` INNER JOIN `person` AS `Person_person_id_person` ON `Person_person_id_contact`.`id` = `Person_person_id_person`.`id`) ON `_lnkpersontoteam`.`person_id` = `Person_person_id_contact`.`id`LEFT JOIN `typology` AS `ContactType_role_id_typology` ON `_lnkpersontoteam`.`role_id` = `ContactType_role_id_typology`.`id` WHERE ((COALESCE((`Team_team_id_contact`.`finalclass` IN (\'Team\')), 1) AND COALESCE((`Person_person_id_contact`.`finalclass` IN (\'Person\')), 1)) AND COALESCE((`ContactType_role_id_typology`.`finalclass` IN (\'ContactType\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_lnkpersontoteam`.`id` AS `id`,`_lnkpersontoteam`.`team_id` AS `team_id`,`Team_team_id_contact`.`name` AS `team_name`,`_lnkpersontoteam`.`person_id` AS `person_id`,`Person_person_id_contact`.`name` AS `person_name`,`_lnkpersontoteam`.`role_id` AS `role_id`,`ContactType_role_id_typology`.`name` AS `role_name`,cast(concat(coalesce(`_lnkpersontoteam`.`team_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkpersontoteam`.`person_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Team_team_id_contact`.`name`,\'\')) as char charset utf8mb4) AS `team_id_friendlyname`,coalesce((`Team_team_id_contact`.`status` = \'inactive\'),0) AS `team_id_obsolescence_flag`,cast(concat(coalesce(`Person_person_id_person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Person_person_id_contact`.`name`,\'\')) as char charset utf8mb4) AS `person_id_friendlyname`,coalesce((`Person_person_id_contact`.`status` = \'inactive\'),0) AS `person_id_obsolescence_flag`,cast(concat(coalesce(`ContactType_role_id_typology`.`name`,\'\')) as char charset utf8mb4) AS `role_id_friendlyname` from (((`itop`.`lnkpersontoteam` `_lnkpersontoteam` join `itop`.`contact` `Team_team_id_contact` on((`_lnkpersontoteam`.`team_id` = `Team_team_id_contact`.`id`))) join (`itop`.`contact` `Person_person_id_contact` join `itop`.`person` `Person_person_id_person` on((`Person_person_id_contact`.`id` = `Person_person_id_person`.`id`))) on((`_lnkpersontoteam`.`person_id` = `Person_person_id_contact`.`id`))) left join `itop`.`typology` `ContactType_role_id_typology` on((`_lnkpersontoteam`.`role_id` = `ContactType_role_id_typology`.`id`))) where (coalesce((`Team_team_id_contact`.`finalclass` = \'Team\'),1) and coalesce((`Person_person_id_contact`.`finalclass` = \'Person\'),1) and coalesce((`ContactType_role_id_typology`.`finalclass` = \'ContactType\'),1))
