TYPE=VIEW
query=select distinct `_lnksoftwareinstancetosoftwarepatch`.`id` AS `id`,`_lnksoftwareinstancetosoftwarepatch`.`softwarepatch_id` AS `softwarepatch_id`,`SoftwarePatch_softwarepatch_id_patch`.`name` AS `softwarepatch_name`,`_lnksoftwareinstancetosoftwarepatch`.`softwareinstance_id` AS `softwareinstance_id`,`SoftwareInstance_softwareinstance_id_functionalci`.`name` AS `softwareinstance_name`,cast(concat(coalesce(`_lnksoftwareinstancetosoftwarepatch`.`softwarepatch_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnksoftwareinstancetosoftwarepatch`.`softwareinstance_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`SoftwarePatch_softwarepatch_id_patch`.`name`,\'\')) as char charset utf8mb4) AS `softwarepatch_id_friendlyname`,cast(concat(coalesce(`SoftwareInstance_softwareinstance_id_functionalci`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`FunctionalCI_system_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `softwareinstance_id_friendlyname`,`SoftwareInstance_softwareinstance_id_functionalci`.`finalclass` AS `softwareinstance_id_finalclass_recall`,coalesce((`SoftwareInstance_softwareinstance_id_softwareinstance`.`status` = \'inactive\'),0) AS `softwareinstance_id_obsolescence_flag` from ((`itop`.`lnksoftwareinstancetosoftwarepatch` `_lnksoftwareinstancetosoftwarepatch` join `itop`.`patch` `SoftwarePatch_softwarepatch_id_patch` on((`_lnksoftwareinstancetosoftwarepatch`.`softwarepatch_id` = `SoftwarePatch_softwarepatch_id_patch`.`id`))) join (`itop`.`functionalci` `SoftwareInstance_softwareinstance_id_functionalci` join (`itop`.`softwareinstance` `SoftwareInstance_softwareinstance_id_softwareinstance` join `itop`.`functionalci` `FunctionalCI_system_id_functionalci` on((`SoftwareInstance_softwareinstance_id_softwareinstance`.`functionalci_id` = `FunctionalCI_system_id_functionalci`.`id`))) on((`SoftwareInstance_softwareinstance_id_functionalci`.`id` = `SoftwareInstance_softwareinstance_id_softwareinstance`.`id`))) on((`_lnksoftwareinstancetosoftwarepatch`.`softwareinstance_id` = `SoftwareInstance_softwareinstance_id_functionalci`.`id`))) where (coalesce((`SoftwarePatch_softwarepatch_id_patch`.`finalclass` = \'SoftwarePatch\'),1) and coalesce((`SoftwareInstance_softwareinstance_id_functionalci`.`finalclass` in (\'Middleware\',\'DBServer\',\'WebServer\',\'PCSoftware\',\'OtherSoftware\',\'SoftwareInstance\')),1))
md5=e95506c15fc6d7cb2ee53fd860d26780
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:05
create-version=1
source=SELECT DISTINCT `_lnksoftwareinstancetosoftwarepatch`.`id` AS `id`, `_lnksoftwareinstancetosoftwarepatch`.`softwarepatch_id` AS `softwarepatch_id`, `SoftwarePatch_softwarepatch_id_patch`.`name` AS `softwarepatch_name`, `_lnksoftwareinstancetosoftwarepatch`.`softwareinstance_id` AS `softwareinstance_id`, `SoftwareInstance_softwareinstance_id_functionalci`.`name` AS `softwareinstance_name`, CAST(CONCAT(COALESCE(`_lnksoftwareinstancetosoftwarepatch`.`softwarepatch_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`_lnksoftwareinstancetosoftwarepatch`.`softwareinstance_id`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`SoftwarePatch_softwarepatch_id_patch`.`name`, \'\')) AS CHAR) AS `softwarepatch_id_friendlyname`, CAST(CONCAT(COALESCE(`SoftwareInstance_softwareinstance_id_functionalci`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`FunctionalCI_system_id_functionalci`.`name`, \'\')) AS CHAR) AS `softwareinstance_id_friendlyname`, `SoftwareInstance_softwareinstance_id_functionalci`.`finalclass` AS `softwareinstance_id_finalclass_recall`, COALESCE((`SoftwareInstance_softwareinstance_id_softwareinstance`.`status` = \'inactive\'), 0) AS `softwareinstance_id_obsolescence_flag` FROM `lnksoftwareinstancetosoftwarepatch` AS `_lnksoftwareinstancetosoftwarepatch`INNER JOIN `patch` AS `SoftwarePatch_softwarepatch_id_patch` ON `_lnksoftwareinstancetosoftwarepatch`.`softwarepatch_id` = `SoftwarePatch_softwarepatch_id_patch`.`id`INNER JOIN (`functionalci` AS `SoftwareInstance_softwareinstance_id_functionalci` INNER JOIN (`softwareinstance` AS `SoftwareInstance_softwareinstance_id_softwareinstance` INNER JOIN `functionalci` AS `FunctionalCI_system_id_functionalci` ON `SoftwareInstance_softwareinstance_id_softwareinstance`.`functionalci_id` = `FunctionalCI_system_id_functionalci`.`id`) ON `SoftwareInstance_softwareinstance_id_functionalci`.`id` = `SoftwareInstance_softwareinstance_id_softwareinstance`.`id`) ON `_lnksoftwareinstancetosoftwarepatch`.`softwareinstance_id` = `SoftwareInstance_softwareinstance_id_functionalci`.`id` WHERE (COALESCE((`SoftwarePatch_softwarepatch_id_patch`.`finalclass` IN (\'SoftwarePatch\')), 1) AND COALESCE((`SoftwareInstance_softwareinstance_id_functionalci`.`finalclass` IN (\'Middleware\', \'DBServer\', \'WebServer\', \'PCSoftware\', \'OtherSoftware\', \'SoftwareInstance\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_lnksoftwareinstancetosoftwarepatch`.`id` AS `id`,`_lnksoftwareinstancetosoftwarepatch`.`softwarepatch_id` AS `softwarepatch_id`,`SoftwarePatch_softwarepatch_id_patch`.`name` AS `softwarepatch_name`,`_lnksoftwareinstancetosoftwarepatch`.`softwareinstance_id` AS `softwareinstance_id`,`SoftwareInstance_softwareinstance_id_functionalci`.`name` AS `softwareinstance_name`,cast(concat(coalesce(`_lnksoftwareinstancetosoftwarepatch`.`softwarepatch_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnksoftwareinstancetosoftwarepatch`.`softwareinstance_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`SoftwarePatch_softwarepatch_id_patch`.`name`,\'\')) as char charset utf8mb4) AS `softwarepatch_id_friendlyname`,cast(concat(coalesce(`SoftwareInstance_softwareinstance_id_functionalci`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`FunctionalCI_system_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `softwareinstance_id_friendlyname`,`SoftwareInstance_softwareinstance_id_functionalci`.`finalclass` AS `softwareinstance_id_finalclass_recall`,coalesce((`SoftwareInstance_softwareinstance_id_softwareinstance`.`status` = \'inactive\'),0) AS `softwareinstance_id_obsolescence_flag` from ((`itop`.`lnksoftwareinstancetosoftwarepatch` `_lnksoftwareinstancetosoftwarepatch` join `itop`.`patch` `SoftwarePatch_softwarepatch_id_patch` on((`_lnksoftwareinstancetosoftwarepatch`.`softwarepatch_id` = `SoftwarePatch_softwarepatch_id_patch`.`id`))) join (`itop`.`functionalci` `SoftwareInstance_softwareinstance_id_functionalci` join (`itop`.`softwareinstance` `SoftwareInstance_softwareinstance_id_softwareinstance` join `itop`.`functionalci` `FunctionalCI_system_id_functionalci` on((`SoftwareInstance_softwareinstance_id_softwareinstance`.`functionalci_id` = `FunctionalCI_system_id_functionalci`.`id`))) on((`SoftwareInstance_softwareinstance_id_functionalci`.`id` = `SoftwareInstance_softwareinstance_id_softwareinstance`.`id`))) on((`_lnksoftwareinstancetosoftwarepatch`.`softwareinstance_id` = `SoftwareInstance_softwareinstance_id_functionalci`.`id`))) where (coalesce((`SoftwarePatch_softwarepatch_id_patch`.`finalclass` = \'SoftwarePatch\'),1) and coalesce((`SoftwareInstance_softwareinstance_id_functionalci`.`finalclass` in (\'Middleware\',\'DBServer\',\'WebServer\',\'PCSoftware\',\'OtherSoftware\',\'SoftwareInstance\')),1))
