TYPE=VIEW
query=select distinct `_lnkdeliverymodeltocontact`.`id` AS `id`,`_lnkdeliverymodeltocontact`.`deliverymodel_id` AS `deliverymodel_id`,`DeliveryModel_deliverymodel_id_deliverymodel`.`name` AS `deliverymodel_name`,`_lnkdeliverymodeltocontact`.`contact_id` AS `contact_id`,`Contact_contact_id_contact`.`name` AS `contact_name`,`_lnkdeliverymodeltocontact`.`role_id` AS `role_id`,`ContactType_role_id_typology`.`name` AS `role_name`,cast(concat(coalesce(`_lnkdeliverymodeltocontact`.`deliverymodel_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkdeliverymodeltocontact`.`contact_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`DeliveryModel_deliverymodel_id_deliverymodel`.`name`,\'\')) as char charset utf8mb4) AS `deliverymodel_id_friendlyname`,if((`Contact_contact_id_contact`.`finalclass` in (\'Team\',\'Contact\')),cast(concat(coalesce(`Contact_contact_id_contact`.`name`,\'\')) as char charset utf8mb4),cast(concat(coalesce(`Contact_contact_id_fn_Person_person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Contact_contact_id_contact`.`name`,\'\')) as char charset utf8mb4)) AS `contact_id_friendlyname`,`Contact_contact_id_contact`.`finalclass` AS `contact_id_finalclass_recall`,coalesce((`Contact_contact_id_contact`.`status` = \'inactive\'),0) AS `contact_id_obsolescence_flag`,cast(concat(coalesce(`ContactType_role_id_typology`.`name`,\'\')) as char charset utf8mb4) AS `role_id_friendlyname` from (((`itop`.`lnkdeliverymodeltocontact` `_lnkdeliverymodeltocontact` join `itop`.`deliverymodel` `DeliveryModel_deliverymodel_id_deliverymodel` on((`_lnkdeliverymodeltocontact`.`deliverymodel_id` = `DeliveryModel_deliverymodel_id_deliverymodel`.`id`))) join (`itop`.`contact` `Contact_contact_id_contact` left join `itop`.`person` `Contact_contact_id_fn_Person_person` on((`Contact_contact_id_contact`.`id` = `Contact_contact_id_fn_Person_person`.`id`))) on((`_lnkdeliverymodeltocontact`.`contact_id` = `Contact_contact_id_contact`.`id`))) left join `itop`.`typology` `ContactType_role_id_typology` on((`_lnkdeliverymodeltocontact`.`role_id` = `ContactType_role_id_typology`.`id`))) where coalesce((`ContactType_role_id_typology`.`finalclass` = \'ContactType\'),1)
md5=9b819ff537235d8555f12a7ee5d179d0
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:08
create-version=1
source=SELECT DISTINCT `_lnkdeliverymodeltocontact`.`id` AS `id`, `_lnkdeliverymodeltocontact`.`deliverymodel_id` AS `deliverymodel_id`, `DeliveryModel_deliverymodel_id_deliverymodel`.`name` AS `deliverymodel_name`, `_lnkdeliverymodeltocontact`.`contact_id` AS `contact_id`, `Contact_contact_id_contact`.`name` AS `contact_name`, `_lnkdeliverymodeltocontact`.`role_id` AS `role_id`, `ContactType_role_id_typology`.`name` AS `role_name`, CAST(CONCAT(COALESCE(`_lnkdeliverymodeltocontact`.`deliverymodel_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`_lnkdeliverymodeltocontact`.`contact_id`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`DeliveryModel_deliverymodel_id_deliverymodel`.`name`, \'\')) AS CHAR) AS `deliverymodel_id_friendlyname`, IF((`Contact_contact_id_contact`.`finalclass` IN (\'Team\', \'Contact\')), CAST(CONCAT(COALESCE(`Contact_contact_id_contact`.`name`, \'\')) AS CHAR), CAST(CONCAT(COALESCE(`Contact_contact_id_fn_Person_person`.`first_name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Contact_contact_id_contact`.`name`, \'\')) AS CHAR)) AS `contact_id_friendlyname`, `Contact_contact_id_contact`.`finalclass` AS `contact_id_finalclass_recall`, COALESCE((`Contact_contact_id_contact`.`status` = \'inactive\'), 0) AS `contact_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`ContactType_role_id_typology`.`name`, \'\')) AS CHAR) AS `role_id_friendlyname` FROM `lnkdeliverymodeltocontact` AS `_lnkdeliverymodeltocontact`INNER JOIN `deliverymodel` AS `DeliveryModel_deliverymodel_id_deliverymodel` ON `_lnkdeliverymodeltocontact`.`deliverymodel_id` = `DeliveryModel_deliverymodel_id_deliverymodel`.`id`INNER JOIN (`contact` AS `Contact_contact_id_contact` LEFT JOIN `person` AS `Contact_contact_id_fn_Person_person` ON `Contact_contact_id_contact`.`id` = `Contact_contact_id_fn_Person_person`.`id`) ON `_lnkdeliverymodeltocontact`.`contact_id` = `Contact_contact_id_contact`.`id`LEFT JOIN `typology` AS `ContactType_role_id_typology` ON `_lnkdeliverymodeltocontact`.`role_id` = `ContactType_role_id_typology`.`id` WHERE COALESCE((`ContactType_role_id_typology`.`finalclass` IN (\'ContactType\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_lnkdeliverymodeltocontact`.`id` AS `id`,`_lnkdeliverymodeltocontact`.`deliverymodel_id` AS `deliverymodel_id`,`DeliveryModel_deliverymodel_id_deliverymodel`.`name` AS `deliverymodel_name`,`_lnkdeliverymodeltocontact`.`contact_id` AS `contact_id`,`Contact_contact_id_contact`.`name` AS `contact_name`,`_lnkdeliverymodeltocontact`.`role_id` AS `role_id`,`ContactType_role_id_typology`.`name` AS `role_name`,cast(concat(coalesce(`_lnkdeliverymodeltocontact`.`deliverymodel_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkdeliverymodeltocontact`.`contact_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`DeliveryModel_deliverymodel_id_deliverymodel`.`name`,\'\')) as char charset utf8mb4) AS `deliverymodel_id_friendlyname`,if((`Contact_contact_id_contact`.`finalclass` in (\'Team\',\'Contact\')),cast(concat(coalesce(`Contact_contact_id_contact`.`name`,\'\')) as char charset utf8mb4),cast(concat(coalesce(`Contact_contact_id_fn_Person_person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Contact_contact_id_contact`.`name`,\'\')) as char charset utf8mb4)) AS `contact_id_friendlyname`,`Contact_contact_id_contact`.`finalclass` AS `contact_id_finalclass_recall`,coalesce((`Contact_contact_id_contact`.`status` = \'inactive\'),0) AS `contact_id_obsolescence_flag`,cast(concat(coalesce(`ContactType_role_id_typology`.`name`,\'\')) as char charset utf8mb4) AS `role_id_friendlyname` from (((`itop`.`lnkdeliverymodeltocontact` `_lnkdeliverymodeltocontact` join `itop`.`deliverymodel` `DeliveryModel_deliverymodel_id_deliverymodel` on((`_lnkdeliverymodeltocontact`.`deliverymodel_id` = `DeliveryModel_deliverymodel_id_deliverymodel`.`id`))) join (`itop`.`contact` `Contact_contact_id_contact` left join `itop`.`person` `Contact_contact_id_fn_Person_person` on((`Contact_contact_id_contact`.`id` = `Contact_contact_id_fn_Person_person`.`id`))) on((`_lnkdeliverymodeltocontact`.`contact_id` = `Contact_contact_id_contact`.`id`))) left join `itop`.`typology` `ContactType_role_id_typology` on((`_lnkdeliverymodeltocontact`.`role_id` = `ContactType_role_id_typology`.`id`))) where coalesce((`ContactType_role_id_typology`.`finalclass` = \'ContactType\'),1)
