TYPE=VIEW
query=select distinct `_lnkapplicationsolutiontobusinessprocess`.`id` AS `id`,`_lnkapplicationsolutiontobusinessprocess`.`businessprocess_id` AS `businessprocess_id`,`BusinessProcess_businessprocess_id_functionalci`.`name` AS `businessprocess_name`,`_lnkapplicationsolutiontobusinessprocess`.`applicationsolution_id` AS `applicationsolution_id`,`ApplicationSolution_applicationsolution_id_functionalci`.`name` AS `applicationsolution_name`,cast(concat(coalesce(`_lnkapplicationsolutiontobusinessprocess`.`businessprocess_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkapplicationsolutiontobusinessprocess`.`applicationsolution_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`BusinessProcess_businessprocess_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `businessprocess_id_friendlyname`,coalesce((`BusinessProcess_businessprocess_id_businessprocess`.`status` = \'inactive\'),0) AS `businessprocess_id_obsolescence_flag`,cast(concat(coalesce(`ApplicationSolution_applicationsolution_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `applicationsolution_id_friendlyname`,coalesce((`ApplicationSolution_applicationsolution_id_applicationsolution`.`status` = \'inactive\'),0) AS `applicationsolution_id_obsolescence_flag` from ((`itop`.`lnkapplicationsolutiontobusinessprocess` `_lnkapplicationsolutiontobusinessprocess` join (`itop`.`functionalci` `BusinessProcess_businessprocess_id_functionalci` join `itop`.`businessprocess` `BusinessProcess_businessprocess_id_businessprocess` on((`BusinessProcess_businessprocess_id_functionalci`.`id` = `BusinessProcess_businessprocess_id_businessprocess`.`id`))) on((`_lnkapplicationsolutiontobusinessprocess`.`businessprocess_id` = `BusinessProcess_businessprocess_id_functionalci`.`id`))) join (`itop`.`functionalci` `ApplicationSolution_applicationsolution_id_functionalci` join `itop`.`applicationsolution` `ApplicationSolution_applicationsolution_id_applicationsolution` on((`ApplicationSolution_applicationsolution_id_functionalci`.`id` = `ApplicationSolution_applicationsolution_id_applicationsolution`.`id`))) on((`_lnkapplicationsolutiontobusinessprocess`.`applicationsolution_id` = `ApplicationSolution_applicationsolution_id_functionalci`.`id`))) where (coalesce((`BusinessProcess_businessprocess_id_functionalci`.`finalclass` = \'BusinessProcess\'),1) and coalesce((`ApplicationSolution_applicationsolution_id_functionalci`.`finalclass` = \'ApplicationSolution\'),1))
md5=39ede7c9b04799b717d023713b30a6ec
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:05
create-version=1
source=SELECT DISTINCT `_lnkapplicationsolutiontobusinessprocess`.`id` AS `id`, `_lnkapplicationsolutiontobusinessprocess`.`businessprocess_id` AS `businessprocess_id`, `BusinessProcess_businessprocess_id_functionalci`.`name` AS `businessprocess_name`, `_lnkapplicationsolutiontobusinessprocess`.`applicationsolution_id` AS `applicationsolution_id`, `ApplicationSolution_applicationsolution_id_functionalci`.`name` AS `applicationsolution_name`, CAST(CONCAT(COALESCE(`_lnkapplicationsolutiontobusinessprocess`.`businessprocess_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`_lnkapplicationsolutiontobusinessprocess`.`applicationsolution_id`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`BusinessProcess_businessprocess_id_functionalci`.`name`, \'\')) AS CHAR) AS `businessprocess_id_friendlyname`, COALESCE((`BusinessProcess_businessprocess_id_businessprocess`.`status` = \'inactive\'), 0) AS `businessprocess_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`ApplicationSolution_applicationsolution_id_functionalci`.`name`, \'\')) AS CHAR) AS `applicationsolution_id_friendlyname`, COALESCE((`ApplicationSolution_applicationsolution_id_applicationsolution`.`status` = \'inactive\'), 0) AS `applicationsolution_id_obsolescence_flag` FROM `lnkapplicationsolutiontobusinessprocess` AS `_lnkapplicationsolutiontobusinessprocess`INNER JOIN (`functionalci` AS `BusinessProcess_businessprocess_id_functionalci` INNER JOIN `businessprocess` AS `BusinessProcess_businessprocess_id_businessprocess` ON `BusinessProcess_businessprocess_id_functionalci`.`id` = `BusinessProcess_businessprocess_id_businessprocess`.`id`) ON `_lnkapplicationsolutiontobusinessprocess`.`businessprocess_id` = `BusinessProcess_businessprocess_id_functionalci`.`id`INNER JOIN (`functionalci` AS `ApplicationSolution_applicationsolution_id_functionalci` INNER JOIN `applicationsolution` AS `ApplicationSolution_applicationsolution_id_applicationsolution` ON `ApplicationSolution_applicationsolution_id_functionalci`.`id` = `ApplicationSolution_applicationsolution_id_applicationsolution`.`id`) ON `_lnkapplicationsolutiontobusinessprocess`.`applicationsolution_id` = `ApplicationSolution_applicationsolution_id_functionalci`.`id` WHERE (COALESCE((`BusinessProcess_businessprocess_id_functionalci`.`finalclass` IN (\'BusinessProcess\')), 1) AND COALESCE((`ApplicationSolution_applicationsolution_id_functionalci`.`finalclass` IN (\'ApplicationSolution\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_lnkapplicationsolutiontobusinessprocess`.`id` AS `id`,`_lnkapplicationsolutiontobusinessprocess`.`businessprocess_id` AS `businessprocess_id`,`BusinessProcess_businessprocess_id_functionalci`.`name` AS `businessprocess_name`,`_lnkapplicationsolutiontobusinessprocess`.`applicationsolution_id` AS `applicationsolution_id`,`ApplicationSolution_applicationsolution_id_functionalci`.`name` AS `applicationsolution_name`,cast(concat(coalesce(`_lnkapplicationsolutiontobusinessprocess`.`businessprocess_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkapplicationsolutiontobusinessprocess`.`applicationsolution_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`BusinessProcess_businessprocess_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `businessprocess_id_friendlyname`,coalesce((`BusinessProcess_businessprocess_id_businessprocess`.`status` = \'inactive\'),0) AS `businessprocess_id_obsolescence_flag`,cast(concat(coalesce(`ApplicationSolution_applicationsolution_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `applicationsolution_id_friendlyname`,coalesce((`ApplicationSolution_applicationsolution_id_applicationsolution`.`status` = \'inactive\'),0) AS `applicationsolution_id_obsolescence_flag` from ((`itop`.`lnkapplicationsolutiontobusinessprocess` `_lnkapplicationsolutiontobusinessprocess` join (`itop`.`functionalci` `BusinessProcess_businessprocess_id_functionalci` join `itop`.`businessprocess` `BusinessProcess_businessprocess_id_businessprocess` on((`BusinessProcess_businessprocess_id_functionalci`.`id` = `BusinessProcess_businessprocess_id_businessprocess`.`id`))) on((`_lnkapplicationsolutiontobusinessprocess`.`businessprocess_id` = `BusinessProcess_businessprocess_id_functionalci`.`id`))) join (`itop`.`functionalci` `ApplicationSolution_applicationsolution_id_functionalci` join `itop`.`applicationsolution` `ApplicationSolution_applicationsolution_id_applicationsolution` on((`ApplicationSolution_applicationsolution_id_functionalci`.`id` = `ApplicationSolution_applicationsolution_id_applicationsolution`.`id`))) on((`_lnkapplicationsolutiontobusinessprocess`.`applicationsolution_id` = `ApplicationSolution_applicationsolution_id_functionalci`.`id`))) where (coalesce((`BusinessProcess_businessprocess_id_functionalci`.`finalclass` = \'BusinessProcess\'),1) and coalesce((`ApplicationSolution_applicationsolution_id_functionalci`.`finalclass` = \'ApplicationSolution\'),1))
