TYPE=VIEW
query=select distinct `_lnkdocumenttoservice`.`id` AS `id`,`_lnkdocumenttoservice`.`service_id` AS `service_id`,`Service_service_id_service`.`name` AS `service_name`,`_lnkdocumenttoservice`.`document_id` AS `document_id`,`Document_document_id_document`.`name` AS `document_name`,cast(concat(coalesce(`_lnkdocumenttoservice`.`service_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkdocumenttoservice`.`document_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Service_service_id_service`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,if((`Document_document_id_document`.`finalclass` = \'Document\'),cast(concat(coalesce(\'Document\',\'\')) as char charset utf8mb4),cast(concat(coalesce(`Document_document_id_document`.`name`,\'\')) as char charset utf8mb4)) AS `document_id_friendlyname`,`Document_document_id_document`.`finalclass` AS `document_id_finalclass_recall`,coalesce((`Document_document_id_document`.`status` = \'obsolete\'),0) AS `document_id_obsolescence_flag` from ((`itop`.`lnkdocumenttoservice` `_lnkdocumenttoservice` join `itop`.`service` `Service_service_id_service` on((`_lnkdocumenttoservice`.`service_id` = `Service_service_id_service`.`id`))) join `itop`.`document` `Document_document_id_document` on((`_lnkdocumenttoservice`.`document_id` = `Document_document_id_document`.`id`))) where 1
md5=99581e0ba4a9617af18be1c595e5ab26
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:07
create-version=1
source=SELECT DISTINCT `_lnkdocumenttoservice`.`id` AS `id`, `_lnkdocumenttoservice`.`service_id` AS `service_id`, `Service_service_id_service`.`name` AS `service_name`, `_lnkdocumenttoservice`.`document_id` AS `document_id`, `Document_document_id_document`.`name` AS `document_name`, CAST(CONCAT(COALESCE(`_lnkdocumenttoservice`.`service_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`_lnkdocumenttoservice`.`document_id`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`Service_service_id_service`.`name`, \'\')) AS CHAR) AS `service_id_friendlyname`, IF((`Document_document_id_document`.`finalclass` IN (\'Document\')), CAST(CONCAT(COALESCE(\'Document\', \'\')) AS CHAR), CAST(CONCAT(COALESCE(`Document_document_id_document`.`name`, \'\')) AS CHAR)) AS `document_id_friendlyname`, `Document_document_id_document`.`finalclass` AS `document_id_finalclass_recall`, COALESCE((`Document_document_id_document`.`status` = \'obsolete\'), 0) AS `document_id_obsolescence_flag` FROM `lnkdocumenttoservice` AS `_lnkdocumenttoservice`INNER JOIN `service` AS `Service_service_id_service` ON `_lnkdocumenttoservice`.`service_id` = `Service_service_id_service`.`id`INNER JOIN `document` AS `Document_document_id_document` ON `_lnkdocumenttoservice`.`document_id` = `Document_document_id_document`.`id` WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_lnkdocumenttoservice`.`id` AS `id`,`_lnkdocumenttoservice`.`service_id` AS `service_id`,`Service_service_id_service`.`name` AS `service_name`,`_lnkdocumenttoservice`.`document_id` AS `document_id`,`Document_document_id_document`.`name` AS `document_name`,cast(concat(coalesce(`_lnkdocumenttoservice`.`service_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkdocumenttoservice`.`document_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Service_service_id_service`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,if((`Document_document_id_document`.`finalclass` = \'Document\'),cast(concat(coalesce(\'Document\',\'\')) as char charset utf8mb4),cast(concat(coalesce(`Document_document_id_document`.`name`,\'\')) as char charset utf8mb4)) AS `document_id_friendlyname`,`Document_document_id_document`.`finalclass` AS `document_id_finalclass_recall`,coalesce((`Document_document_id_document`.`status` = \'obsolete\'),0) AS `document_id_obsolescence_flag` from ((`itop`.`lnkdocumenttoservice` `_lnkdocumenttoservice` join `itop`.`service` `Service_service_id_service` on((`_lnkdocumenttoservice`.`service_id` = `Service_service_id_service`.`id`))) join `itop`.`document` `Document_document_id_document` on((`_lnkdocumenttoservice`.`document_id` = `Document_document_id_document`.`id`))) where 1
