TYPE=VIEW
query=select distinct `_contact`.`id` AS `id`,`_contact`.`name` AS `name`,`_contact`.`status` AS `status`,`_contact`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `org_name`,`_contact`.`email` AS `email`,`_contact`.`phone` AS `phone`,`_contact`.`notify` AS `notify`,`_contact`.`function` AS `function`,`_contact`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_contact`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`_contact`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`_contact`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from (`itop`.`contact` `_contact` join `itop`.`organization` `Organization_org_id_organization` on((`_contact`.`org_id` = `Organization_org_id_organization`.`id`))) where coalesce((`_contact`.`finalclass` = \'Team\'),1)
md5=1f1ac15378d7b95bdafa02f7ea2d0a68
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:04
create-version=1
source=SELECT DISTINCT `_contact`.`id` AS `id`, `_contact`.`name` AS `name`, `_contact`.`status` AS `status`, `_contact`.`org_id` AS `org_id`, `Organization_org_id_organization`.`name` AS `org_name`, `_contact`.`email` AS `email`, `_contact`.`phone` AS `phone`, `_contact`.`notify` AS `notify`, `_contact`.`function` AS `function`, `_contact`.`finalclass` AS `finalclass`, CAST(CONCAT(COALESCE(`_contact`.`name`, \'\')) AS CHAR) AS `friendlyname`, COALESCE((`_contact`.`status` = \'inactive\'), 0) AS `obsolescence_flag`, `_contact`.`obsolescence_date` AS `obsolescence_date`, CAST(CONCAT(COALESCE(`Organization_org_id_organization`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`, COALESCE((`Organization_org_id_organization`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag` FROM `contact` AS `_contact`INNER JOIN `organization` AS `Organization_org_id_organization` ON `_contact`.`org_id` = `Organization_org_id_organization`.`id` WHERE COALESCE((`_contact`.`finalclass` IN (\'Team\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_contact`.`id` AS `id`,`_contact`.`name` AS `name`,`_contact`.`status` AS `status`,`_contact`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `org_name`,`_contact`.`email` AS `email`,`_contact`.`phone` AS `phone`,`_contact`.`notify` AS `notify`,`_contact`.`function` AS `function`,`_contact`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_contact`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`_contact`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`_contact`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from (`itop`.`contact` `_contact` join `itop`.`organization` `Organization_org_id_organization` on((`_contact`.`org_id` = `Organization_org_id_organization`.`id`))) where coalesce((`_contact`.`finalclass` = \'Team\'),1)
