TYPE=VIEW
query=select distinct `_networkinterface`.`id` AS `id`,`_networkinterface`.`name` AS `name`,`_ipinterface`.`ipaddress` AS `ipaddress`,`_ipinterface`.`macaddress` AS `macaddress`,`_ipinterface`.`comment` AS `comment`,`_ipinterface`.`ipgateway` AS `ipgateway`,`_ipinterface`.`ipmask` AS `ipmask`,`_ipinterface`.`speed` AS `speed`,`_logicalinterface`.`virtualmachine_id` AS `virtualmachine_id`,`VirtualMachine_virtualmachine_id_functionalci`.`name` AS `virtualmachine_name`,`_networkinterface`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_networkinterface`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`VirtualMachine_virtualmachine_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`VirtualMachine_virtualmachine_id_virtualdevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`_networkinterface`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`VirtualMachine_virtualmachine_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `virtualmachine_id_friendlyname`,coalesce((`VirtualMachine_virtualmachine_id_virtualdevice`.`status` = \'obsolete\'),0) AS `virtualmachine_id_obsolescence_flag` from ((`itop`.`networkinterface` `_networkinterface` join `itop`.`ipinterface` `_ipinterface` on((`_networkinterface`.`id` = `_ipinterface`.`id`))) join (`itop`.`logicalinterface` `_logicalinterface` join (`itop`.`functionalci` `VirtualMachine_virtualmachine_id_functionalci` join `itop`.`virtualdevice` `VirtualMachine_virtualmachine_id_virtualdevice` on((`VirtualMachine_virtualmachine_id_functionalci`.`id` = `VirtualMachine_virtualmachine_id_virtualdevice`.`id`))) on((`_logicalinterface`.`virtualmachine_id` = `VirtualMachine_virtualmachine_id_functionalci`.`id`))) on((`_networkinterface`.`id` = `_logicalinterface`.`id`))) where (coalesce((`_networkinterface`.`finalclass` = \'LogicalInterface\'),1) and coalesce((`VirtualMachine_virtualmachine_id_functionalci`.`finalclass` = \'VirtualMachine\'),1))
md5=bbc90532ebd417491af9c83937be0bc0
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:07
create-version=1
source=SELECT DISTINCT `_networkinterface`.`id` AS `id`, `_networkinterface`.`name` AS `name`, `_ipinterface`.`ipaddress` AS `ipaddress`, `_ipinterface`.`macaddress` AS `macaddress`, `_ipinterface`.`comment` AS `comment`, `_ipinterface`.`ipgateway` AS `ipgateway`, `_ipinterface`.`ipmask` AS `ipmask`, `_ipinterface`.`speed` AS `speed`, `_logicalinterface`.`virtualmachine_id` AS `virtualmachine_id`, `VirtualMachine_virtualmachine_id_functionalci`.`name` AS `virtualmachine_name`, `_networkinterface`.`finalclass` AS `finalclass`, CAST(CONCAT(COALESCE(`_networkinterface`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`VirtualMachine_virtualmachine_id_functionalci`.`name`, \'\')) AS CHAR) AS `friendlyname`, COALESCE(COALESCE((`VirtualMachine_virtualmachine_id_virtualdevice`.`status` = \'obsolete\'), 0), 0) AS `obsolescence_flag`, `_networkinterface`.`obsolescence_date` AS `obsolescence_date`, CAST(CONCAT(COALESCE(`VirtualMachine_virtualmachine_id_functionalci`.`name`, \'\')) AS CHAR) AS `virtualmachine_id_friendlyname`, COALESCE((`VirtualMachine_virtualmachine_id_virtualdevice`.`status` = \'obsolete\'), 0) AS `virtualmachine_id_obsolescence_flag` FROM `networkinterface` AS `_networkinterface`INNER JOIN `ipinterface` AS `_ipinterface` ON `_networkinterface`.`id` = `_ipinterface`.`id`INNER JOIN (`logicalinterface` AS `_logicalinterface` INNER JOIN (`functionalci` AS `VirtualMachine_virtualmachine_id_functionalci` INNER JOIN `virtualdevice` AS `VirtualMachine_virtualmachine_id_virtualdevice` ON `VirtualMachine_virtualmachine_id_functionalci`.`id` = `VirtualMachine_virtualmachine_id_virtualdevice`.`id`) ON `_logicalinterface`.`virtualmachine_id` = `VirtualMachine_virtualmachine_id_functionalci`.`id`) ON `_networkinterface`.`id` = `_logicalinterface`.`id` WHERE (COALESCE((`_networkinterface`.`finalclass` IN (\'LogicalInterface\')), 1) AND COALESCE((`VirtualMachine_virtualmachine_id_functionalci`.`finalclass` IN (\'VirtualMachine\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_networkinterface`.`id` AS `id`,`_networkinterface`.`name` AS `name`,`_ipinterface`.`ipaddress` AS `ipaddress`,`_ipinterface`.`macaddress` AS `macaddress`,`_ipinterface`.`comment` AS `comment`,`_ipinterface`.`ipgateway` AS `ipgateway`,`_ipinterface`.`ipmask` AS `ipmask`,`_ipinterface`.`speed` AS `speed`,`_logicalinterface`.`virtualmachine_id` AS `virtualmachine_id`,`VirtualMachine_virtualmachine_id_functionalci`.`name` AS `virtualmachine_name`,`_networkinterface`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_networkinterface`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`VirtualMachine_virtualmachine_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`VirtualMachine_virtualmachine_id_virtualdevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`_networkinterface`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`VirtualMachine_virtualmachine_id_functionalci`.`name`,\'\')) as char charset utf8mb4) AS `virtualmachine_id_friendlyname`,coalesce((`VirtualMachine_virtualmachine_id_virtualdevice`.`status` = \'obsolete\'),0) AS `virtualmachine_id_obsolescence_flag` from ((`itop`.`networkinterface` `_networkinterface` join `itop`.`ipinterface` `_ipinterface` on((`_networkinterface`.`id` = `_ipinterface`.`id`))) join (`itop`.`logicalinterface` `_logicalinterface` join (`itop`.`functionalci` `VirtualMachine_virtualmachine_id_functionalci` join `itop`.`virtualdevice` `VirtualMachine_virtualmachine_id_virtualdevice` on((`VirtualMachine_virtualmachine_id_functionalci`.`id` = `VirtualMachine_virtualmachine_id_virtualdevice`.`id`))) on((`_logicalinterface`.`virtualmachine_id` = `VirtualMachine_virtualmachine_id_functionalci`.`id`))) on((`_networkinterface`.`id` = `_logicalinterface`.`id`))) where (coalesce((`_networkinterface`.`finalclass` = \'LogicalInterface\'),1) and coalesce((`VirtualMachine_virtualmachine_id_functionalci`.`finalclass` = \'VirtualMachine\'),1))
