TYPE=VIEW
query=select distinct `_lnkcontacttoservice`.`id` AS `id`,`_lnkcontacttoservice`.`service_id` AS `service_id`,`Service_service_id_service`.`name` AS `service_name`,`_lnkcontacttoservice`.`contact_id` AS `contact_id`,`Contact_contact_id_contact`.`name` AS `contact_name`,cast(concat(coalesce(`_lnkcontacttoservice`.`service_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkcontacttoservice`.`contact_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Service_service_id_service`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,if((`Contact_contact_id_contact`.`finalclass` in (\'Team\',\'Contact\')),cast(concat(coalesce(`Contact_contact_id_contact`.`name`,\'\')) as char charset utf8mb4),cast(concat(coalesce(`Contact_contact_id_fn_Person_person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Contact_contact_id_contact`.`name`,\'\')) as char charset utf8mb4)) AS `contact_id_friendlyname`,`Contact_contact_id_contact`.`finalclass` AS `contact_id_finalclass_recall`,coalesce((`Contact_contact_id_contact`.`status` = \'inactive\'),0) AS `contact_id_obsolescence_flag` from ((`itop`.`lnkcontacttoservice` `_lnkcontacttoservice` join `itop`.`service` `Service_service_id_service` on((`_lnkcontacttoservice`.`service_id` = `Service_service_id_service`.`id`))) join (`itop`.`contact` `Contact_contact_id_contact` left join `itop`.`person` `Contact_contact_id_fn_Person_person` on((`Contact_contact_id_contact`.`id` = `Contact_contact_id_fn_Person_person`.`id`))) on((`_lnkcontacttoservice`.`contact_id` = `Contact_contact_id_contact`.`id`))) where 1
md5=356049512134ced4da7424971fcc093b
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:08
create-version=1
source=SELECT DISTINCT `_lnkcontacttoservice`.`id` AS `id`, `_lnkcontacttoservice`.`service_id` AS `service_id`, `Service_service_id_service`.`name` AS `service_name`, `_lnkcontacttoservice`.`contact_id` AS `contact_id`, `Contact_contact_id_contact`.`name` AS `contact_name`, CAST(CONCAT(COALESCE(`_lnkcontacttoservice`.`service_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`_lnkcontacttoservice`.`contact_id`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`Service_service_id_service`.`name`, \'\')) AS CHAR) AS `service_id_friendlyname`, IF((`Contact_contact_id_contact`.`finalclass` IN (\'Team\', \'Contact\')), CAST(CONCAT(COALESCE(`Contact_contact_id_contact`.`name`, \'\')) AS CHAR), CAST(CONCAT(COALESCE(`Contact_contact_id_fn_Person_person`.`first_name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Contact_contact_id_contact`.`name`, \'\')) AS CHAR)) AS `contact_id_friendlyname`, `Contact_contact_id_contact`.`finalclass` AS `contact_id_finalclass_recall`, COALESCE((`Contact_contact_id_contact`.`status` = \'inactive\'), 0) AS `contact_id_obsolescence_flag` FROM `lnkcontacttoservice` AS `_lnkcontacttoservice`INNER JOIN `service` AS `Service_service_id_service` ON `_lnkcontacttoservice`.`service_id` = `Service_service_id_service`.`id`INNER JOIN (`contact` AS `Contact_contact_id_contact` LEFT JOIN `person` AS `Contact_contact_id_fn_Person_person` ON `Contact_contact_id_contact`.`id` = `Contact_contact_id_fn_Person_person`.`id`) ON `_lnkcontacttoservice`.`contact_id` = `Contact_contact_id_contact`.`id` WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_lnkcontacttoservice`.`id` AS `id`,`_lnkcontacttoservice`.`service_id` AS `service_id`,`Service_service_id_service`.`name` AS `service_name`,`_lnkcontacttoservice`.`contact_id` AS `contact_id`,`Contact_contact_id_contact`.`name` AS `contact_name`,cast(concat(coalesce(`_lnkcontacttoservice`.`service_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkcontacttoservice`.`contact_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Service_service_id_service`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,if((`Contact_contact_id_contact`.`finalclass` in (\'Team\',\'Contact\')),cast(concat(coalesce(`Contact_contact_id_contact`.`name`,\'\')) as char charset utf8mb4),cast(concat(coalesce(`Contact_contact_id_fn_Person_person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Contact_contact_id_contact`.`name`,\'\')) as char charset utf8mb4)) AS `contact_id_friendlyname`,`Contact_contact_id_contact`.`finalclass` AS `contact_id_finalclass_recall`,coalesce((`Contact_contact_id_contact`.`status` = \'inactive\'),0) AS `contact_id_obsolescence_flag` from ((`itop`.`lnkcontacttoservice` `_lnkcontacttoservice` join `itop`.`service` `Service_service_id_service` on((`_lnkcontacttoservice`.`service_id` = `Service_service_id_service`.`id`))) join (`itop`.`contact` `Contact_contact_id_contact` left join `itop`.`person` `Contact_contact_id_fn_Person_person` on((`Contact_contact_id_contact`.`id` = `Contact_contact_id_fn_Person_person`.`id`))) on((`_lnkcontacttoservice`.`contact_id` = `Contact_contact_id_contact`.`id`))) where 1
