TYPE=VIEW
query=select distinct `_contract`.`id` AS `id`,`_contract`.`name` AS `name`,`_contract`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `organization_name`,`_contract`.`description` AS `description`,`_contract`.`start_date` AS `start_date`,`_contract`.`end_date` AS `end_date`,`_contract`.`cost` AS `cost`,`_contract`.`cost_currency` AS `cost_currency`,`_contract`.`contracttype_id` AS `contracttype_id`,`ContractType_contracttype_id_typology`.`name` AS `contracttype_name`,`_contract`.`billing_frequency` AS `billing_frequency`,`_contract`.`cost_unit` AS `cost_unit`,`_contract`.`provider_id` AS `provider_id`,`Organization_provider_id_organization`.`name` AS `provider_name`,`_contract`.`status` AS `status`,`_providercontract`.`sla` AS `sla`,`_providercontract`.`coverage` AS `coverage`,`_contract`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_contract`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`ContractType_contracttype_id_typology`.`name`,\'\')) as char charset utf8mb4) AS `contracttype_id_friendlyname`,cast(concat(coalesce(`Organization_provider_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `provider_id_friendlyname`,coalesce((`Organization_provider_id_organization`.`status` = \'inactive\'),0) AS `provider_id_obsolescence_flag` from ((((`itop`.`contract` `_contract` join `itop`.`organization` `Organization_org_id_organization` on((`_contract`.`org_id` = `Organization_org_id_organization`.`id`))) left join `itop`.`typology` `ContractType_contracttype_id_typology` on((`_contract`.`contracttype_id` = `ContractType_contracttype_id_typology`.`id`))) join `itop`.`organization` `Organization_provider_id_organization` on((`_contract`.`provider_id` = `Organization_provider_id_organization`.`id`))) join `itop`.`providercontract` `_providercontract` on((`_contract`.`id` = `_providercontract`.`id`))) where (coalesce((`ContractType_contracttype_id_typology`.`finalclass` = \'ContractType\'),1) and coalesce((`_contract`.`finalclass` = \'ProviderContract\'),1))
md5=4babfab05f40a530b989619be83c5f35
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2019-03-07 12:20:07
create-version=1
source=SELECT DISTINCT `_contract`.`id` AS `id`, `_contract`.`name` AS `name`, `_contract`.`org_id` AS `org_id`, `Organization_org_id_organization`.`name` AS `organization_name`, `_contract`.`description` AS `description`, `_contract`.`start_date` AS `start_date`, `_contract`.`end_date` AS `end_date`, `_contract`.`cost` AS `cost`, `_contract`.`cost_currency` AS `cost_currency`, `_contract`.`contracttype_id` AS `contracttype_id`, `ContractType_contracttype_id_typology`.`name` AS `contracttype_name`, `_contract`.`billing_frequency` AS `billing_frequency`, `_contract`.`cost_unit` AS `cost_unit`, `_contract`.`provider_id` AS `provider_id`, `Organization_provider_id_organization`.`name` AS `provider_name`, `_contract`.`status` AS `status`, `_providercontract`.`sla` AS `sla`, `_providercontract`.`coverage` AS `coverage`, `_contract`.`finalclass` AS `finalclass`, CAST(CONCAT(COALESCE(`_contract`.`name`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`Organization_org_id_organization`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`, COALESCE((`Organization_org_id_organization`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`, CAST(CONCAT(COALESCE(`ContractType_contracttype_id_typology`.`name`, \'\')) AS CHAR) AS `contracttype_id_friendlyname`, CAST(CONCAT(COALESCE(`Organization_provider_id_organization`.`name`, \'\')) AS CHAR) AS `provider_id_friendlyname`, COALESCE((`Organization_provider_id_organization`.`status` = \'inactive\'), 0) AS `provider_id_obsolescence_flag` FROM `contract` AS `_contract`INNER JOIN `organization` AS `Organization_org_id_organization` ON `_contract`.`org_id` = `Organization_org_id_organization`.`id`LEFT JOIN `typology` AS `ContractType_contracttype_id_typology` ON `_contract`.`contracttype_id` = `ContractType_contracttype_id_typology`.`id`INNER JOIN `organization` AS `Organization_provider_id_organization` ON `_contract`.`provider_id` = `Organization_provider_id_organization`.`id`INNER JOIN `providercontract` AS `_providercontract` ON `_contract`.`id` = `_providercontract`.`id` WHERE (COALESCE((`ContractType_contracttype_id_typology`.`finalclass` IN (\'ContractType\')), 1) AND COALESCE((`_contract`.`finalclass` IN (\'ProviderContract\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_contract`.`id` AS `id`,`_contract`.`name` AS `name`,`_contract`.`org_id` AS `org_id`,`Organization_org_id_organization`.`name` AS `organization_name`,`_contract`.`description` AS `description`,`_contract`.`start_date` AS `start_date`,`_contract`.`end_date` AS `end_date`,`_contract`.`cost` AS `cost`,`_contract`.`cost_currency` AS `cost_currency`,`_contract`.`contracttype_id` AS `contracttype_id`,`ContractType_contracttype_id_typology`.`name` AS `contracttype_name`,`_contract`.`billing_frequency` AS `billing_frequency`,`_contract`.`cost_unit` AS `cost_unit`,`_contract`.`provider_id` AS `provider_id`,`Organization_provider_id_organization`.`name` AS `provider_name`,`_contract`.`status` AS `status`,`_providercontract`.`sla` AS `sla`,`_providercontract`.`coverage` AS `coverage`,`_contract`.`finalclass` AS `finalclass`,cast(concat(coalesce(`_contract`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Organization_org_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id_organization`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`ContractType_contracttype_id_typology`.`name`,\'\')) as char charset utf8mb4) AS `contracttype_id_friendlyname`,cast(concat(coalesce(`Organization_provider_id_organization`.`name`,\'\')) as char charset utf8mb4) AS `provider_id_friendlyname`,coalesce((`Organization_provider_id_organization`.`status` = \'inactive\'),0) AS `provider_id_obsolescence_flag` from ((((`itop`.`contract` `_contract` join `itop`.`organization` `Organization_org_id_organization` on((`_contract`.`org_id` = `Organization_org_id_organization`.`id`))) left join `itop`.`typology` `ContractType_contracttype_id_typology` on((`_contract`.`contracttype_id` = `ContractType_contracttype_id_typology`.`id`))) join `itop`.`organization` `Organization_provider_id_organization` on((`_contract`.`provider_id` = `Organization_provider_id_organization`.`id`))) join `itop`.`providercontract` `_providercontract` on((`_contract`.`id` = `_providercontract`.`id`))) where (coalesce((`ContractType_contracttype_id_typology`.`finalclass` = \'ContractType\'),1) and coalesce((`_contract`.`finalclass` = \'ProviderContract\'),1))
