TYPE=VIEW
query=select distinct `lnkDeliveryModelToContact`.`id` AS `id`,`lnkDeliveryModelToContact`.`deliverymodel_id` AS `deliverymodel_id`,`DeliveryModel_deliverymodel_id`.`name` AS `deliverymodel_name`,`lnkDeliveryModelToContact`.`contact_id` AS `contact_id`,`Contact_contact_id`.`name` AS `contact_name`,`lnkDeliveryModelToContact`.`role_id` AS `role_id`,`ContactType_role_id_Typology`.`name` AS `role_name`,cast(concat(coalesce(`lnkDeliveryModelToContact`.`deliverymodel_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkDeliveryModelToContact`.`contact_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`DeliveryModel_deliverymodel_id`.`name`,\'\')) as char charset utf8mb4) AS `deliverymodel_id_friendlyname`,if((`Contact_contact_id`.`finalclass` in (\'Team\',\'Contact\')),cast(concat(coalesce(`Contact_contact_id`.`name`,\'\')) as char charset utf8mb4),cast(concat(coalesce(`Contact_contact_id_poly_Person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Contact_contact_id`.`name`,\'\')) as char charset utf8mb4)) AS `contact_id_friendlyname`,`Contact_contact_id`.`finalclass` AS `contact_id_finalclass_recall`,coalesce((`Contact_contact_id`.`status` = \'inactive\'),0) AS `contact_id_obsolescence_flag`,cast(concat(coalesce(`ContactType_role_id_Typology`.`name`,\'\')) as char charset utf8mb4) AS `role_id_friendlyname` from (((`itop27`.`lnkdeliverymodeltocontact` `lnkDeliveryModelToContact` join `itop27`.`deliverymodel` `DeliveryModel_deliverymodel_id` on((`lnkDeliveryModelToContact`.`deliverymodel_id` = `DeliveryModel_deliverymodel_id`.`id`))) join (`itop27`.`contact` `Contact_contact_id` left join `itop27`.`person` `Contact_contact_id_poly_Person` on((`Contact_contact_id`.`id` = `Contact_contact_id_poly_Person`.`id`))) on((`lnkDeliveryModelToContact`.`contact_id` = `Contact_contact_id`.`id`))) left join `itop27`.`typology` `ContactType_role_id_Typology` on((`lnkDeliveryModelToContact`.`role_id` = `ContactType_role_id_Typology`.`id`))) where coalesce((`ContactType_role_id_Typology`.`finalclass` = \'ContactType\'),1)
md5=aaa7483513c8e75c5ca0368adf99af4c
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `lnkDeliveryModelToContact`.`id` AS `id`,\n `lnkDeliveryModelToContact`.`deliverymodel_id` AS `deliverymodel_id`,\n `DeliveryModel_deliverymodel_id`.`name` AS `deliverymodel_name`,\n `lnkDeliveryModelToContact`.`contact_id` AS `contact_id`,\n `Contact_contact_id`.`name` AS `contact_name`,\n `lnkDeliveryModelToContact`.`role_id` AS `role_id`,\n `ContactType_role_id_Typology`.`name` AS `role_name`,\n CAST(CONCAT(COALESCE(`lnkDeliveryModelToContact`.`deliverymodel_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`lnkDeliveryModelToContact`.`contact_id`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`DeliveryModel_deliverymodel_id`.`name`, \'\')) AS CHAR) AS `deliverymodel_id_friendlyname`,\n IF((`Contact_contact_id`.`finalclass` IN (\'Team\', \'Contact\')), CAST(CONCAT(COALESCE(`Contact_contact_id`.`name`, \'\')) AS CHAR), CAST(CONCAT(COALESCE(`Contact_contact_id_poly_Person`.`first_name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Contact_contact_id`.`name`, \'\')) AS CHAR)) AS `contact_id_friendlyname`,\n `Contact_contact_id`.`finalclass` AS `contact_id_finalclass_recall`,\n COALESCE((`Contact_contact_id`.`status` = \'inactive\'), 0) AS `contact_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`ContactType_role_id_Typology`.`name`, \'\')) AS CHAR) AS `role_id_friendlyname`\n FROM \n   `lnkdeliverymodeltocontact` AS `lnkDeliveryModelToContact`\n   INNER JOIN \n      `deliverymodel` AS `DeliveryModel_deliverymodel_id`\n    ON `lnkDeliveryModelToContact`.`deliverymodel_id` = `DeliveryModel_deliverymodel_id`.`id`\n   INNER JOIN (\n      `contact` AS `Contact_contact_id` \n      LEFT JOIN \n         `person` AS `Contact_contact_id_poly_Person`\n       ON `Contact_contact_id`.`id` = `Contact_contact_id_poly_Person`.`id`\n   ) ON `lnkDeliveryModelToContact`.`contact_id` = `Contact_contact_id`.`id`\n   LEFT JOIN \n      `typology` AS `ContactType_role_id_Typology`\n    ON `lnkDeliveryModelToContact`.`role_id` = `ContactType_role_id_Typology`.`id`\n WHERE COALESCE((`ContactType_role_id_Typology`.`finalclass` IN (\'ContactType\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `lnkDeliveryModelToContact`.`id` AS `id`,`lnkDeliveryModelToContact`.`deliverymodel_id` AS `deliverymodel_id`,`DeliveryModel_deliverymodel_id`.`name` AS `deliverymodel_name`,`lnkDeliveryModelToContact`.`contact_id` AS `contact_id`,`Contact_contact_id`.`name` AS `contact_name`,`lnkDeliveryModelToContact`.`role_id` AS `role_id`,`ContactType_role_id_Typology`.`name` AS `role_name`,cast(concat(coalesce(`lnkDeliveryModelToContact`.`deliverymodel_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkDeliveryModelToContact`.`contact_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`DeliveryModel_deliverymodel_id`.`name`,\'\')) as char charset utf8mb4) AS `deliverymodel_id_friendlyname`,if((`Contact_contact_id`.`finalclass` in (\'Team\',\'Contact\')),cast(concat(coalesce(`Contact_contact_id`.`name`,\'\')) as char charset utf8mb4),cast(concat(coalesce(`Contact_contact_id_poly_Person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Contact_contact_id`.`name`,\'\')) as char charset utf8mb4)) AS `contact_id_friendlyname`,`Contact_contact_id`.`finalclass` AS `contact_id_finalclass_recall`,coalesce((`Contact_contact_id`.`status` = \'inactive\'),0) AS `contact_id_obsolescence_flag`,cast(concat(coalesce(`ContactType_role_id_Typology`.`name`,\'\')) as char charset utf8mb4) AS `role_id_friendlyname` from (((`itop27`.`lnkdeliverymodeltocontact` `lnkDeliveryModelToContact` join `itop27`.`deliverymodel` `DeliveryModel_deliverymodel_id` on((`lnkDeliveryModelToContact`.`deliverymodel_id` = `DeliveryModel_deliverymodel_id`.`id`))) join (`itop27`.`contact` `Contact_contact_id` left join `itop27`.`person` `Contact_contact_id_poly_Person` on((`Contact_contact_id`.`id` = `Contact_contact_id_poly_Person`.`id`))) on((`lnkDeliveryModelToContact`.`contact_id` = `Contact_contact_id`.`id`))) left join `itop27`.`typology` `ContactType_role_id_Typology` on((`lnkDeliveryModelToContact`.`role_id` = `ContactType_role_id_Typology`.`id`))) where coalesce((`ContactType_role_id_Typology`.`finalclass` = \'ContactType\'),1)
