TYPE=VIEW
query=select distinct `lnkContractToDocument`.`id` AS `id`,`lnkContractToDocument`.`contract_id` AS `contract_id`,`Contract_contract_id`.`name` AS `contract_name`,`lnkContractToDocument`.`document_id` AS `document_id`,`Document_document_id`.`name` AS `document_name`,cast(concat(coalesce(`lnkContractToDocument`.`contract_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkContractToDocument`.`document_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Contract_contract_id`.`name`,\'\')) as char charset utf8mb4) AS `contract_id_friendlyname`,`Contract_contract_id`.`finalclass` AS `contract_id_finalclass_recall`,if((`Document_document_id`.`finalclass` = \'Document\'),cast(concat(coalesce(\'Document\',\'\')) as char charset utf8mb4),cast(concat(coalesce(`Document_document_id`.`name`,\'\')) as char charset utf8mb4)) AS `document_id_friendlyname`,`Document_document_id`.`finalclass` AS `document_id_finalclass_recall`,coalesce((`Document_document_id`.`status` = \'obsolete\'),0) AS `document_id_obsolescence_flag` from ((`itop27`.`lnkcontracttodocument` `lnkContractToDocument` join `itop27`.`contract` `Contract_contract_id` on((`lnkContractToDocument`.`contract_id` = `Contract_contract_id`.`id`))) join `itop27`.`document` `Document_document_id` on((`lnkContractToDocument`.`document_id` = `Document_document_id`.`id`))) where 1
md5=5ae05682be87061411b567bf39f78042
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `lnkContractToDocument`.`id` AS `id`,\n `lnkContractToDocument`.`contract_id` AS `contract_id`,\n `Contract_contract_id`.`name` AS `contract_name`,\n `lnkContractToDocument`.`document_id` AS `document_id`,\n `Document_document_id`.`name` AS `document_name`,\n CAST(CONCAT(COALESCE(`lnkContractToDocument`.`contract_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`lnkContractToDocument`.`document_id`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`Contract_contract_id`.`name`, \'\')) AS CHAR) AS `contract_id_friendlyname`,\n `Contract_contract_id`.`finalclass` AS `contract_id_finalclass_recall`,\n IF((`Document_document_id`.`finalclass` IN (\'Document\')), CAST(CONCAT(COALESCE(\'Document\', \'\')) AS CHAR), CAST(CONCAT(COALESCE(`Document_document_id`.`name`, \'\')) AS CHAR)) AS `document_id_friendlyname`,\n `Document_document_id`.`finalclass` AS `document_id_finalclass_recall`,\n COALESCE((`Document_document_id`.`status` = \'obsolete\'), 0) AS `document_id_obsolescence_flag`\n FROM \n   `lnkcontracttodocument` AS `lnkContractToDocument`\n   INNER JOIN \n      `contract` AS `Contract_contract_id`\n    ON `lnkContractToDocument`.`contract_id` = `Contract_contract_id`.`id`\n   INNER JOIN \n      `document` AS `Document_document_id`\n    ON `lnkContractToDocument`.`document_id` = `Document_document_id`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `lnkContractToDocument`.`id` AS `id`,`lnkContractToDocument`.`contract_id` AS `contract_id`,`Contract_contract_id`.`name` AS `contract_name`,`lnkContractToDocument`.`document_id` AS `document_id`,`Document_document_id`.`name` AS `document_name`,cast(concat(coalesce(`lnkContractToDocument`.`contract_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkContractToDocument`.`document_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Contract_contract_id`.`name`,\'\')) as char charset utf8mb4) AS `contract_id_friendlyname`,`Contract_contract_id`.`finalclass` AS `contract_id_finalclass_recall`,if((`Document_document_id`.`finalclass` = \'Document\'),cast(concat(coalesce(\'Document\',\'\')) as char charset utf8mb4),cast(concat(coalesce(`Document_document_id`.`name`,\'\')) as char charset utf8mb4)) AS `document_id_friendlyname`,`Document_document_id`.`finalclass` AS `document_id_finalclass_recall`,coalesce((`Document_document_id`.`status` = \'obsolete\'),0) AS `document_id_obsolescence_flag` from ((`itop27`.`lnkcontracttodocument` `lnkContractToDocument` join `itop27`.`contract` `Contract_contract_id` on((`lnkContractToDocument`.`contract_id` = `Contract_contract_id`.`id`))) join `itop27`.`document` `Document_document_id` on((`lnkContractToDocument`.`document_id` = `Document_document_id`.`id`))) where 1
