TYPE=VIEW
query=select distinct `WebApplication`.`id` AS `id`,`WebApplication_FunctionalCI`.`name` AS `name`,`WebApplication_FunctionalCI`.`description` AS `description`,`WebApplication_FunctionalCI`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`WebApplication_FunctionalCI`.`business_criticity` AS `business_criticity`,`WebApplication_FunctionalCI`.`move2production` AS `move2production`,`WebApplication`.`webserver_id` AS `webserver_id`,`WebServer_webserver_id_FunctionalCI`.`name` AS `webserver_name`,`WebApplication`.`url` AS `url`,`WebApplication_FunctionalCI`.`finalclass` AS `finalclass`,cast(concat(coalesce(`WebApplication_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`WebServer_webserver_id_SoftwareInstance`.`status` = \'inactive\'),0),0) AS `obsolescence_flag`,`WebApplication_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`WebServer_webserver_id_FunctionalCI`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`FunctionalCI_system_id`.`name`,\'\')) as char charset utf8mb4) AS `webserver_id_friendlyname`,coalesce((`WebServer_webserver_id_SoftwareInstance`.`status` = \'inactive\'),0) AS `webserver_id_obsolescence_flag` from ((`itop27`.`webapplication` `WebApplication` join ((`itop27`.`softwareinstance` `WebServer_webserver_id_SoftwareInstance` join `itop27`.`functionalci` `FunctionalCI_system_id` on((`WebServer_webserver_id_SoftwareInstance`.`functionalci_id` = `FunctionalCI_system_id`.`id`))) join `itop27`.`functionalci` `WebServer_webserver_id_FunctionalCI` on((`WebServer_webserver_id_SoftwareInstance`.`id` = `WebServer_webserver_id_FunctionalCI`.`id`))) on((`WebApplication`.`webserver_id` = `WebServer_webserver_id_SoftwareInstance`.`id`))) join (`itop27`.`functionalci` `WebApplication_FunctionalCI` join `itop27`.`organization` `Organization_org_id` on((`WebApplication_FunctionalCI`.`org_id` = `Organization_org_id`.`id`))) on((`WebApplication`.`id` = `WebApplication_FunctionalCI`.`id`))) where coalesce((`WebServer_webserver_id_SoftwareInstance`.`finalclass` = \'WebServer\'),1)
md5=bf6c16a3c1590fc6d6661a95ef9ddcee
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `WebApplication`.`id` AS `id`,\n `WebApplication_FunctionalCI`.`name` AS `name`,\n `WebApplication_FunctionalCI`.`description` AS `description`,\n `WebApplication_FunctionalCI`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `organization_name`,\n `WebApplication_FunctionalCI`.`business_criticity` AS `business_criticity`,\n `WebApplication_FunctionalCI`.`move2production` AS `move2production`,\n `WebApplication`.`webserver_id` AS `webserver_id`,\n `WebServer_webserver_id_FunctionalCI`.`name` AS `webserver_name`,\n `WebApplication`.`url` AS `url`,\n `WebApplication_FunctionalCI`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`WebApplication_FunctionalCI`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE(COALESCE((`WebServer_webserver_id_SoftwareInstance`.`status` = \'inactive\'), 0), 0) AS `obsolescence_flag`,\n `WebApplication_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`WebServer_webserver_id_FunctionalCI`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`FunctionalCI_system_id`.`name`, \'\')) AS CHAR) AS `webserver_id_friendlyname`,\n COALESCE((`WebServer_webserver_id_SoftwareInstance`.`status` = \'inactive\'), 0) AS `webserver_id_obsolescence_flag`\n FROM \n   `webapplication` AS `WebApplication`\n   INNER JOIN (\n      `softwareinstance` AS `WebServer_webserver_id_SoftwareInstance` \n      INNER JOIN \n         `functionalci` AS `FunctionalCI_system_id`\n       ON `WebServer_webserver_id_SoftwareInstance`.`functionalci_id` = `FunctionalCI_system_id`.`id`\n      INNER JOIN \n         `functionalci` AS `WebServer_webserver_id_FunctionalCI`\n       ON `WebServer_webserver_id_SoftwareInstance`.`id` = `WebServer_webserver_id_FunctionalCI`.`id`\n   ) ON `WebApplication`.`webserver_id` = `WebServer_webserver_id_SoftwareInstance`.`id`\n   INNER JOIN (\n      `functionalci` AS `WebApplication_FunctionalCI` \n      INNER JOIN \n         `organization` AS `Organization_org_id`\n       ON `WebApplication_FunctionalCI`.`org_id` = `Organization_org_id`.`id`\n   ) ON `WebApplication`.`id` = `WebApplication_FunctionalCI`.`id`\n WHERE COALESCE((`WebServer_webserver_id_SoftwareInstance`.`finalclass` IN (\'WebServer\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `WebApplication`.`id` AS `id`,`WebApplication_FunctionalCI`.`name` AS `name`,`WebApplication_FunctionalCI`.`description` AS `description`,`WebApplication_FunctionalCI`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`WebApplication_FunctionalCI`.`business_criticity` AS `business_criticity`,`WebApplication_FunctionalCI`.`move2production` AS `move2production`,`WebApplication`.`webserver_id` AS `webserver_id`,`WebServer_webserver_id_FunctionalCI`.`name` AS `webserver_name`,`WebApplication`.`url` AS `url`,`WebApplication_FunctionalCI`.`finalclass` AS `finalclass`,cast(concat(coalesce(`WebApplication_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`WebServer_webserver_id_SoftwareInstance`.`status` = \'inactive\'),0),0) AS `obsolescence_flag`,`WebApplication_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`WebServer_webserver_id_FunctionalCI`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`FunctionalCI_system_id`.`name`,\'\')) as char charset utf8mb4) AS `webserver_id_friendlyname`,coalesce((`WebServer_webserver_id_SoftwareInstance`.`status` = \'inactive\'),0) AS `webserver_id_obsolescence_flag` from ((`itop27`.`webapplication` `WebApplication` join ((`itop27`.`softwareinstance` `WebServer_webserver_id_SoftwareInstance` join `itop27`.`functionalci` `FunctionalCI_system_id` on((`WebServer_webserver_id_SoftwareInstance`.`functionalci_id` = `FunctionalCI_system_id`.`id`))) join `itop27`.`functionalci` `WebServer_webserver_id_FunctionalCI` on((`WebServer_webserver_id_SoftwareInstance`.`id` = `WebServer_webserver_id_FunctionalCI`.`id`))) on((`WebApplication`.`webserver_id` = `WebServer_webserver_id_SoftwareInstance`.`id`))) join (`itop27`.`functionalci` `WebApplication_FunctionalCI` join `itop27`.`organization` `Organization_org_id` on((`WebApplication_FunctionalCI`.`org_id` = `Organization_org_id`.`id`))) on((`WebApplication`.`id` = `WebApplication_FunctionalCI`.`id`))) where coalesce((`WebServer_webserver_id_SoftwareInstance`.`finalclass` = \'WebServer\'),1)
