TYPE=VIEW
query=select distinct `Patch`.`id` AS `id`,`Patch`.`name` AS `name`,`Patch`.`description` AS `description`,`Patch`.`finalclass` AS `finalclass`,cast(concat(coalesce(`Patch`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname` from `itop27`.`patch` `Patch` where 1
md5=c459807d802b38aaad3363a18c374e30
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `Patch`.`id` AS `id`,\n `Patch`.`name` AS `name`,\n `Patch`.`description` AS `description`,\n `Patch`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`Patch`.`name`, \'\')) AS CHAR) AS `friendlyname`\n FROM \n   `patch` AS `Patch`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `Patch`.`id` AS `id`,`Patch`.`name` AS `name`,`Patch`.`description` AS `description`,`Patch`.`finalclass` AS `finalclass`,cast(concat(coalesce(`Patch`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname` from `itop27`.`patch` `Patch` where 1
