TYPE=VIEW
query=select distinct `lnkDocumentToError`.`link_id` AS `id`,`lnkDocumentToError`.`document_id` AS `document_id`,`Document_document_id`.`name` AS `document_name`,`lnkDocumentToError`.`error_id` AS `error_id`,`KnownError_error_id`.`name` AS `error_name`,`lnkDocumentToError`.`link_type` AS `link_type`,cast(concat(coalesce(`lnkDocumentToError`.`link_type`,\'\')) as char charset utf8mb4) AS `friendlyname`,if((`Document_document_id`.`finalclass` = \'Document\'),cast(concat(coalesce(\'Document\',\'\')) as char charset utf8mb4),cast(concat(coalesce(`Document_document_id`.`name`,\'\')) as char charset utf8mb4)) AS `document_id_friendlyname`,`Document_document_id`.`finalclass` AS `document_id_finalclass_recall`,coalesce((`Document_document_id`.`status` = \'obsolete\'),0) AS `document_id_obsolescence_flag`,cast(concat(coalesce(`KnownError_error_id`.`name`,\'\')) as char charset utf8mb4) AS `error_id_friendlyname` from ((`itop27`.`lnkdocumenttoerror` `lnkDocumentToError` join `itop27`.`document` `Document_document_id` on((`lnkDocumentToError`.`document_id` = `Document_document_id`.`id`))) join `itop27`.`knownerror` `KnownError_error_id` on((`lnkDocumentToError`.`error_id` = `KnownError_error_id`.`id`))) where 1
md5=d4512f616508d7530f653f81f86a833a
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `lnkDocumentToError`.`link_id` AS `id`,\n `lnkDocumentToError`.`document_id` AS `document_id`,\n `Document_document_id`.`name` AS `document_name`,\n `lnkDocumentToError`.`error_id` AS `error_id`,\n `KnownError_error_id`.`name` AS `error_name`,\n `lnkDocumentToError`.`link_type` AS `link_type`,\n CAST(CONCAT(COALESCE(`lnkDocumentToError`.`link_type`, \'\')) AS CHAR) AS `friendlyname`,\n IF((`Document_document_id`.`finalclass` IN (\'Document\')), CAST(CONCAT(COALESCE(\'Document\', \'\')) AS CHAR), CAST(CONCAT(COALESCE(`Document_document_id`.`name`, \'\')) AS CHAR)) AS `document_id_friendlyname`,\n `Document_document_id`.`finalclass` AS `document_id_finalclass_recall`,\n COALESCE((`Document_document_id`.`status` = \'obsolete\'), 0) AS `document_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`KnownError_error_id`.`name`, \'\')) AS CHAR) AS `error_id_friendlyname`\n FROM \n   `lnkdocumenttoerror` AS `lnkDocumentToError`\n   INNER JOIN \n      `document` AS `Document_document_id`\n    ON `lnkDocumentToError`.`document_id` = `Document_document_id`.`id`\n   INNER JOIN \n      `knownerror` AS `KnownError_error_id`\n    ON `lnkDocumentToError`.`error_id` = `KnownError_error_id`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `lnkDocumentToError`.`link_id` AS `id`,`lnkDocumentToError`.`document_id` AS `document_id`,`Document_document_id`.`name` AS `document_name`,`lnkDocumentToError`.`error_id` AS `error_id`,`KnownError_error_id`.`name` AS `error_name`,`lnkDocumentToError`.`link_type` AS `link_type`,cast(concat(coalesce(`lnkDocumentToError`.`link_type`,\'\')) as char charset utf8mb4) AS `friendlyname`,if((`Document_document_id`.`finalclass` = \'Document\'),cast(concat(coalesce(\'Document\',\'\')) as char charset utf8mb4),cast(concat(coalesce(`Document_document_id`.`name`,\'\')) as char charset utf8mb4)) AS `document_id_friendlyname`,`Document_document_id`.`finalclass` AS `document_id_finalclass_recall`,coalesce((`Document_document_id`.`status` = \'obsolete\'),0) AS `document_id_obsolescence_flag`,cast(concat(coalesce(`KnownError_error_id`.`name`,\'\')) as char charset utf8mb4) AS `error_id_friendlyname` from ((`itop27`.`lnkdocumenttoerror` `lnkDocumentToError` join `itop27`.`document` `Document_document_id` on((`lnkDocumentToError`.`document_id` = `Document_document_id`.`id`))) join `itop27`.`knownerror` `KnownError_error_id` on((`lnkDocumentToError`.`error_id` = `KnownError_error_id`.`id`))) where 1
