TYPE=VIEW
query=select distinct `lnkSLAToSLT`.`id` AS `id`,`lnkSLAToSLT`.`sla_id` AS `sla_id`,`SLA_sla_id`.`name` AS `sla_name`,`lnkSLAToSLT`.`slt_id` AS `slt_id`,`SLT_slt_id`.`name` AS `slt_name`,`SLT_slt_id`.`metric` AS `slt_metric`,`SLT_slt_id`.`request_type` AS `slt_request_type`,`SLT_slt_id`.`priority` AS `slt_ticket_priority`,`SLT_slt_id`.`value` AS `slt_value`,`SLT_slt_id`.`unit` AS `slt_value_unit`,cast(concat(coalesce(`lnkSLAToSLT`.`sla_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkSLAToSLT`.`slt_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`SLA_sla_id`.`name`,\'\')) as char charset utf8mb4) AS `sla_id_friendlyname`,cast(concat(coalesce(`SLT_slt_id`.`name`,\'\')) as char charset utf8mb4) AS `slt_id_friendlyname` from ((`itop27`.`lnkslatoslt` `lnkSLAToSLT` join `itop27`.`sla` `SLA_sla_id` on((`lnkSLAToSLT`.`sla_id` = `SLA_sla_id`.`id`))) join `itop27`.`slt` `SLT_slt_id` on((`lnkSLAToSLT`.`slt_id` = `SLT_slt_id`.`id`))) where 1
md5=389f4cf70e2f7dfe31e2f6f4d5a0ead9
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `lnkSLAToSLT`.`id` AS `id`,\n `lnkSLAToSLT`.`sla_id` AS `sla_id`,\n `SLA_sla_id`.`name` AS `sla_name`,\n `lnkSLAToSLT`.`slt_id` AS `slt_id`,\n `SLT_slt_id`.`name` AS `slt_name`,\n `SLT_slt_id`.`metric` AS `slt_metric`,\n `SLT_slt_id`.`request_type` AS `slt_request_type`,\n `SLT_slt_id`.`priority` AS `slt_ticket_priority`,\n `SLT_slt_id`.`value` AS `slt_value`,\n `SLT_slt_id`.`unit` AS `slt_value_unit`,\n CAST(CONCAT(COALESCE(`lnkSLAToSLT`.`sla_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`lnkSLAToSLT`.`slt_id`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`SLA_sla_id`.`name`, \'\')) AS CHAR) AS `sla_id_friendlyname`,\n CAST(CONCAT(COALESCE(`SLT_slt_id`.`name`, \'\')) AS CHAR) AS `slt_id_friendlyname`\n FROM \n   `lnkslatoslt` AS `lnkSLAToSLT`\n   INNER JOIN \n      `sla` AS `SLA_sla_id`\n    ON `lnkSLAToSLT`.`sla_id` = `SLA_sla_id`.`id`\n   INNER JOIN \n      `slt` AS `SLT_slt_id`\n    ON `lnkSLAToSLT`.`slt_id` = `SLT_slt_id`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `lnkSLAToSLT`.`id` AS `id`,`lnkSLAToSLT`.`sla_id` AS `sla_id`,`SLA_sla_id`.`name` AS `sla_name`,`lnkSLAToSLT`.`slt_id` AS `slt_id`,`SLT_slt_id`.`name` AS `slt_name`,`SLT_slt_id`.`metric` AS `slt_metric`,`SLT_slt_id`.`request_type` AS `slt_request_type`,`SLT_slt_id`.`priority` AS `slt_ticket_priority`,`SLT_slt_id`.`value` AS `slt_value`,`SLT_slt_id`.`unit` AS `slt_value_unit`,cast(concat(coalesce(`lnkSLAToSLT`.`sla_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkSLAToSLT`.`slt_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`SLA_sla_id`.`name`,\'\')) as char charset utf8mb4) AS `sla_id_friendlyname`,cast(concat(coalesce(`SLT_slt_id`.`name`,\'\')) as char charset utf8mb4) AS `slt_id_friendlyname` from ((`itop27`.`lnkslatoslt` `lnkSLAToSLT` join `itop27`.`sla` `SLA_sla_id` on((`lnkSLAToSLT`.`sla_id` = `SLA_sla_id`.`id`))) join `itop27`.`slt` `SLT_slt_id` on((`lnkSLAToSLT`.`slt_id` = `SLT_slt_id`.`id`))) where 1
