TYPE=VIEW
query=select distinct `SoftwareLicence`.`id` AS `id`,`SoftwareLicence_Licence`.`name` AS `name`,`SoftwareLicence_Licence`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`SoftwareLicence_Licence`.`usage_limit` AS `usage_limit`,`SoftwareLicence_Licence`.`description` AS `description`,`SoftwareLicence_Licence`.`start_date` AS `start_date`,`SoftwareLicence_Licence`.`end_date` AS `end_date`,`SoftwareLicence_Licence`.`licence_key` AS `licence_key`,`SoftwareLicence_Licence`.`perpetual` AS `perpetual`,`SoftwareLicence`.`software_id` AS `software_id`,`Software_software_id`.`name` AS `software_name`,`SoftwareLicence_Licence`.`finalclass` AS `finalclass`,cast(concat(coalesce(`SoftwareLicence_Licence`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(((`SoftwareLicence_Licence`.`perpetual` = \'no\') and (isnull(`SoftwareLicence_Licence`.`end_date`) = 0) and (`SoftwareLicence_Licence`.`end_date` < date_format((now() - interval 15 month),\'%Y-%m-%d 00:00:00\'))),0) AS `obsolescence_flag`,`SoftwareLicence_Licence`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Software_software_id`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`Software_software_id`.`version`,\'\')) as char charset utf8mb4) AS `software_id_friendlyname` from ((`itop27`.`softwarelicence` `SoftwareLicence` join `itop27`.`software` `Software_software_id` on((`SoftwareLicence`.`software_id` = `Software_software_id`.`id`))) join (`itop27`.`licence` `SoftwareLicence_Licence` join `itop27`.`organization` `Organization_org_id` on((`SoftwareLicence_Licence`.`org_id` = `Organization_org_id`.`id`))) on((`SoftwareLicence`.`id` = `SoftwareLicence_Licence`.`id`))) where 1
md5=99e574f045fc61488e61093ec042694a
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `SoftwareLicence`.`id` AS `id`,\n `SoftwareLicence_Licence`.`name` AS `name`,\n `SoftwareLicence_Licence`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `organization_name`,\n `SoftwareLicence_Licence`.`usage_limit` AS `usage_limit`,\n `SoftwareLicence_Licence`.`description` AS `description`,\n `SoftwareLicence_Licence`.`start_date` AS `start_date`,\n `SoftwareLicence_Licence`.`end_date` AS `end_date`,\n `SoftwareLicence_Licence`.`licence_key` AS `licence_key`,\n `SoftwareLicence_Licence`.`perpetual` AS `perpetual`,\n `SoftwareLicence`.`software_id` AS `software_id`,\n `Software_software_id`.`name` AS `software_name`,\n `SoftwareLicence_Licence`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`SoftwareLicence_Licence`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE((((`SoftwareLicence_Licence`.`perpetual` = \'no\') AND (ISNULL(`SoftwareLicence_Licence`.`end_date`) = 0)) AND (`SoftwareLicence_Licence`.`end_date` < DATE_FORMAT(DATE_SUB(NOW(), INTERVAL 15 MONTH), \'%Y-%m-%d 00:00:00\'))), 0) AS `obsolescence_flag`,\n `SoftwareLicence_Licence`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`Software_software_id`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Software_software_id`.`version`, \'\')) AS CHAR) AS `software_id_friendlyname`\n FROM \n   `softwarelicence` AS `SoftwareLicence`\n   INNER JOIN \n      `software` AS `Software_software_id`\n    ON `SoftwareLicence`.`software_id` = `Software_software_id`.`id`\n   INNER JOIN (\n      `licence` AS `SoftwareLicence_Licence` \n      INNER JOIN \n         `organization` AS `Organization_org_id`\n       ON `SoftwareLicence_Licence`.`org_id` = `Organization_org_id`.`id`\n   ) ON `SoftwareLicence`.`id` = `SoftwareLicence_Licence`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `SoftwareLicence`.`id` AS `id`,`SoftwareLicence_Licence`.`name` AS `name`,`SoftwareLicence_Licence`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`SoftwareLicence_Licence`.`usage_limit` AS `usage_limit`,`SoftwareLicence_Licence`.`description` AS `description`,`SoftwareLicence_Licence`.`start_date` AS `start_date`,`SoftwareLicence_Licence`.`end_date` AS `end_date`,`SoftwareLicence_Licence`.`licence_key` AS `licence_key`,`SoftwareLicence_Licence`.`perpetual` AS `perpetual`,`SoftwareLicence`.`software_id` AS `software_id`,`Software_software_id`.`name` AS `software_name`,`SoftwareLicence_Licence`.`finalclass` AS `finalclass`,cast(concat(coalesce(`SoftwareLicence_Licence`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(((`SoftwareLicence_Licence`.`perpetual` = \'no\') and (isnull(`SoftwareLicence_Licence`.`end_date`) = 0) and (`SoftwareLicence_Licence`.`end_date` < date_format((now() - interval 15 month),\'%Y-%m-%d 00:00:00\'))),0) AS `obsolescence_flag`,`SoftwareLicence_Licence`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Software_software_id`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`Software_software_id`.`version`,\'\')) as char charset utf8mb4) AS `software_id_friendlyname` from ((`itop27`.`softwarelicence` `SoftwareLicence` join `itop27`.`software` `Software_software_id` on((`SoftwareLicence`.`software_id` = `Software_software_id`.`id`))) join (`itop27`.`licence` `SoftwareLicence_Licence` join `itop27`.`organization` `Organization_org_id` on((`SoftwareLicence_Licence`.`org_id` = `Organization_org_id`.`id`))) on((`SoftwareLicence`.`id` = `SoftwareLicence_Licence`.`id`))) where 1
