TYPE=VIEW
query=select distinct `Contact`.`id` AS `id`,`Contact`.`name` AS `name`,`Contact`.`status` AS `status`,`Contact`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `org_name`,`Contact`.`email` AS `email`,`Contact`.`phone` AS `phone`,`Contact`.`notify` AS `notify`,`Contact`.`function` AS `function`,`Contact`.`finalclass` AS `finalclass`,if((`Contact`.`finalclass` in (\'Team\',\'Contact\')),cast(concat(coalesce(`Contact`.`name`,\'\')) as char charset utf8mb4),cast(concat(coalesce(`Contact_poly_Person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Contact`.`name`,\'\')) as char charset utf8mb4)) AS `friendlyname`,coalesce((`Contact`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`Contact`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from ((`itop27`.`contact` `Contact` join `itop27`.`organization` `Organization_org_id` on((`Contact`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`person` `Contact_poly_Person` on((`Contact`.`id` = `Contact_poly_Person`.`id`))) where 1
md5=3e7dfb027f41fb42860f8d57d68a0816
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `Contact`.`id` AS `id`,\n `Contact`.`name` AS `name`,\n `Contact`.`status` AS `status`,\n `Contact`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `org_name`,\n `Contact`.`email` AS `email`,\n `Contact`.`phone` AS `phone`,\n `Contact`.`notify` AS `notify`,\n `Contact`.`function` AS `function`,\n `Contact`.`finalclass` AS `finalclass`,\n IF((`Contact`.`finalclass` IN (\'Team\', \'Contact\')), CAST(CONCAT(COALESCE(`Contact`.`name`, \'\')) AS CHAR), CAST(CONCAT(COALESCE(`Contact_poly_Person`.`first_name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Contact`.`name`, \'\')) AS CHAR)) AS `friendlyname`,\n COALESCE((`Contact`.`status` = \'inactive\'), 0) AS `obsolescence_flag`,\n `Contact`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`\n FROM \n   `contact` AS `Contact`\n   INNER JOIN \n      `organization` AS `Organization_org_id`\n    ON `Contact`.`org_id` = `Organization_org_id`.`id`\n   LEFT JOIN \n      `person` AS `Contact_poly_Person`\n    ON `Contact`.`id` = `Contact_poly_Person`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `Contact`.`id` AS `id`,`Contact`.`name` AS `name`,`Contact`.`status` AS `status`,`Contact`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `org_name`,`Contact`.`email` AS `email`,`Contact`.`phone` AS `phone`,`Contact`.`notify` AS `notify`,`Contact`.`function` AS `function`,`Contact`.`finalclass` AS `finalclass`,if((`Contact`.`finalclass` in (\'Team\',\'Contact\')),cast(concat(coalesce(`Contact`.`name`,\'\')) as char charset utf8mb4),cast(concat(coalesce(`Contact_poly_Person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Contact`.`name`,\'\')) as char charset utf8mb4)) AS `friendlyname`,coalesce((`Contact`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`Contact`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from ((`itop27`.`contact` `Contact` join `itop27`.`organization` `Organization_org_id` on((`Contact`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`person` `Contact_poly_Person` on((`Contact`.`id` = `Contact_poly_Person`.`id`))) where 1
