TYPE=VIEW
query=select distinct `ProviderContract`.`id` AS `id`,`ProviderContract_Contract`.`name` AS `name`,`ProviderContract_Contract`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`ProviderContract_Contract`.`description` AS `description`,`ProviderContract_Contract`.`start_date` AS `start_date`,`ProviderContract_Contract`.`end_date` AS `end_date`,`ProviderContract_Contract`.`cost` AS `cost`,`ProviderContract_Contract`.`cost_currency` AS `cost_currency`,`ProviderContract_Contract`.`contracttype_id` AS `contracttype_id`,`ContractType_contracttype_id_Typology`.`name` AS `contracttype_name`,`ProviderContract_Contract`.`billing_frequency` AS `billing_frequency`,`ProviderContract_Contract`.`cost_unit` AS `cost_unit`,`ProviderContract_Contract`.`provider_id` AS `provider_id`,`Organization_provider_id`.`name` AS `provider_name`,`ProviderContract_Contract`.`status` AS `status`,`ProviderContract`.`sla` AS `sla`,`ProviderContract`.`coverage` AS `coverage`,`ProviderContract_Contract`.`finalclass` AS `finalclass`,cast(concat(coalesce(`ProviderContract_Contract`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`ContractType_contracttype_id_Typology`.`name`,\'\')) as char charset utf8mb4) AS `contracttype_id_friendlyname`,cast(concat(coalesce(`Organization_provider_id`.`name`,\'\')) as char charset utf8mb4) AS `provider_id_friendlyname`,coalesce((`Organization_provider_id`.`status` = \'inactive\'),0) AS `provider_id_obsolescence_flag` from (`itop27`.`providercontract` `ProviderContract` join (((`itop27`.`contract` `ProviderContract_Contract` join `itop27`.`organization` `Organization_org_id` on((`ProviderContract_Contract`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`typology` `ContractType_contracttype_id_Typology` on((`ProviderContract_Contract`.`contracttype_id` = `ContractType_contracttype_id_Typology`.`id`))) join `itop27`.`organization` `Organization_provider_id` on((`ProviderContract_Contract`.`provider_id` = `Organization_provider_id`.`id`))) on((`ProviderContract`.`id` = `ProviderContract_Contract`.`id`))) where coalesce((`ContractType_contracttype_id_Typology`.`finalclass` = \'ContractType\'),1)
md5=fc79a0b4115df33c08461ad3e1130007
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `ProviderContract`.`id` AS `id`,\n `ProviderContract_Contract`.`name` AS `name`,\n `ProviderContract_Contract`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `organization_name`,\n `ProviderContract_Contract`.`description` AS `description`,\n `ProviderContract_Contract`.`start_date` AS `start_date`,\n `ProviderContract_Contract`.`end_date` AS `end_date`,\n `ProviderContract_Contract`.`cost` AS `cost`,\n `ProviderContract_Contract`.`cost_currency` AS `cost_currency`,\n `ProviderContract_Contract`.`contracttype_id` AS `contracttype_id`,\n `ContractType_contracttype_id_Typology`.`name` AS `contracttype_name`,\n `ProviderContract_Contract`.`billing_frequency` AS `billing_frequency`,\n `ProviderContract_Contract`.`cost_unit` AS `cost_unit`,\n `ProviderContract_Contract`.`provider_id` AS `provider_id`,\n `Organization_provider_id`.`name` AS `provider_name`,\n `ProviderContract_Contract`.`status` AS `status`,\n `ProviderContract`.`sla` AS `sla`,\n `ProviderContract`.`coverage` AS `coverage`,\n `ProviderContract_Contract`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`ProviderContract_Contract`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`ContractType_contracttype_id_Typology`.`name`, \'\')) AS CHAR) AS `contracttype_id_friendlyname`,\n CAST(CONCAT(COALESCE(`Organization_provider_id`.`name`, \'\')) AS CHAR) AS `provider_id_friendlyname`,\n COALESCE((`Organization_provider_id`.`status` = \'inactive\'), 0) AS `provider_id_obsolescence_flag`\n FROM \n   `providercontract` AS `ProviderContract`\n   INNER JOIN (\n      `contract` AS `ProviderContract_Contract` \n      INNER JOIN \n         `organization` AS `Organization_org_id`\n       ON `ProviderContract_Contract`.`org_id` = `Organization_org_id`.`id`\n      LEFT JOIN \n         `typology` AS `ContractType_contracttype_id_Typology`\n       ON `ProviderContract_Contract`.`contracttype_id` = `ContractType_contracttype_id_Typology`.`id`\n      INNER JOIN \n         `organization` AS `Organization_provider_id`\n       ON `ProviderContract_Contract`.`provider_id` = `Organization_provider_id`.`id`\n   ) ON `ProviderContract`.`id` = `ProviderContract_Contract`.`id`\n WHERE COALESCE((`ContractType_contracttype_id_Typology`.`finalclass` IN (\'ContractType\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `ProviderContract`.`id` AS `id`,`ProviderContract_Contract`.`name` AS `name`,`ProviderContract_Contract`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`ProviderContract_Contract`.`description` AS `description`,`ProviderContract_Contract`.`start_date` AS `start_date`,`ProviderContract_Contract`.`end_date` AS `end_date`,`ProviderContract_Contract`.`cost` AS `cost`,`ProviderContract_Contract`.`cost_currency` AS `cost_currency`,`ProviderContract_Contract`.`contracttype_id` AS `contracttype_id`,`ContractType_contracttype_id_Typology`.`name` AS `contracttype_name`,`ProviderContract_Contract`.`billing_frequency` AS `billing_frequency`,`ProviderContract_Contract`.`cost_unit` AS `cost_unit`,`ProviderContract_Contract`.`provider_id` AS `provider_id`,`Organization_provider_id`.`name` AS `provider_name`,`ProviderContract_Contract`.`status` AS `status`,`ProviderContract`.`sla` AS `sla`,`ProviderContract`.`coverage` AS `coverage`,`ProviderContract_Contract`.`finalclass` AS `finalclass`,cast(concat(coalesce(`ProviderContract_Contract`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`ContractType_contracttype_id_Typology`.`name`,\'\')) as char charset utf8mb4) AS `contracttype_id_friendlyname`,cast(concat(coalesce(`Organization_provider_id`.`name`,\'\')) as char charset utf8mb4) AS `provider_id_friendlyname`,coalesce((`Organization_provider_id`.`status` = \'inactive\'),0) AS `provider_id_obsolescence_flag` from (`itop27`.`providercontract` `ProviderContract` join (((`itop27`.`contract` `ProviderContract_Contract` join `itop27`.`organization` `Organization_org_id` on((`ProviderContract_Contract`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`typology` `ContractType_contracttype_id_Typology` on((`ProviderContract_Contract`.`contracttype_id` = `ContractType_contracttype_id_Typology`.`id`))) join `itop27`.`organization` `Organization_provider_id` on((`ProviderContract_Contract`.`provider_id` = `Organization_provider_id`.`id`))) on((`ProviderContract`.`id` = `ProviderContract_Contract`.`id`))) where coalesce((`ContractType_contracttype_id_Typology`.`finalclass` = \'ContractType\'),1)
