TYPE=VIEW
query=select distinct `lnkSoftwareInstanceToSoftwarePatch`.`id` AS `id`,`lnkSoftwareInstanceToSoftwarePatch`.`softwarepatch_id` AS `softwarepatch_id`,`SoftwarePatch_softwarepatch_id_Patch`.`name` AS `softwarepatch_name`,`lnkSoftwareInstanceToSoftwarePatch`.`softwareinstance_id` AS `softwareinstance_id`,`SoftwareInstance_softwareinstance_id_FunctionalCI`.`name` AS `softwareinstance_name`,cast(concat(coalesce(`lnkSoftwareInstanceToSoftwarePatch`.`softwarepatch_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkSoftwareInstanceToSoftwarePatch`.`softwareinstance_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`SoftwarePatch_softwarepatch_id_Patch`.`name`,\'\')) as char charset utf8mb4) AS `softwarepatch_id_friendlyname`,cast(concat(coalesce(`SoftwareInstance_softwareinstance_id_FunctionalCI`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`FunctionalCI_system_id`.`name`,\'\')) as char charset utf8mb4) AS `softwareinstance_id_friendlyname`,`SoftwareInstance_softwareinstance_id_FunctionalCI`.`finalclass` AS `softwareinstance_id_finalclass_recall`,coalesce((`SoftwareInstance_softwareinstance_id`.`status` = \'inactive\'),0) AS `softwareinstance_id_obsolescence_flag` from ((`itop27`.`lnksoftwareinstancetosoftwarepatch` `lnkSoftwareInstanceToSoftwarePatch` join `itop27`.`patch` `SoftwarePatch_softwarepatch_id_Patch` on((`lnkSoftwareInstanceToSoftwarePatch`.`softwarepatch_id` = `SoftwarePatch_softwarepatch_id_Patch`.`id`))) join ((`itop27`.`softwareinstance` `SoftwareInstance_softwareinstance_id` join `itop27`.`functionalci` `FunctionalCI_system_id` on((`SoftwareInstance_softwareinstance_id`.`functionalci_id` = `FunctionalCI_system_id`.`id`))) join `itop27`.`functionalci` `SoftwareInstance_softwareinstance_id_FunctionalCI` on((`SoftwareInstance_softwareinstance_id`.`id` = `SoftwareInstance_softwareinstance_id_FunctionalCI`.`id`))) on((`lnkSoftwareInstanceToSoftwarePatch`.`softwareinstance_id` = `SoftwareInstance_softwareinstance_id`.`id`))) where coalesce((`SoftwarePatch_softwarepatch_id_Patch`.`finalclass` = \'SoftwarePatch\'),1)
md5=2c8d6f7944c956f16365b3ee5fb55d08
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `lnkSoftwareInstanceToSoftwarePatch`.`id` AS `id`,\n `lnkSoftwareInstanceToSoftwarePatch`.`softwarepatch_id` AS `softwarepatch_id`,\n `SoftwarePatch_softwarepatch_id_Patch`.`name` AS `softwarepatch_name`,\n `lnkSoftwareInstanceToSoftwarePatch`.`softwareinstance_id` AS `softwareinstance_id`,\n `SoftwareInstance_softwareinstance_id_FunctionalCI`.`name` AS `softwareinstance_name`,\n CAST(CONCAT(COALESCE(`lnkSoftwareInstanceToSoftwarePatch`.`softwarepatch_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`lnkSoftwareInstanceToSoftwarePatch`.`softwareinstance_id`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`SoftwarePatch_softwarepatch_id_Patch`.`name`, \'\')) AS CHAR) AS `softwarepatch_id_friendlyname`,\n CAST(CONCAT(COALESCE(`SoftwareInstance_softwareinstance_id_FunctionalCI`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`FunctionalCI_system_id`.`name`, \'\')) AS CHAR) AS `softwareinstance_id_friendlyname`,\n `SoftwareInstance_softwareinstance_id_FunctionalCI`.`finalclass` AS `softwareinstance_id_finalclass_recall`,\n COALESCE((`SoftwareInstance_softwareinstance_id`.`status` = \'inactive\'), 0) AS `softwareinstance_id_obsolescence_flag`\n FROM \n   `lnksoftwareinstancetosoftwarepatch` AS `lnkSoftwareInstanceToSoftwarePatch`\n   INNER JOIN \n      `patch` AS `SoftwarePatch_softwarepatch_id_Patch`\n    ON `lnkSoftwareInstanceToSoftwarePatch`.`softwarepatch_id` = `SoftwarePatch_softwarepatch_id_Patch`.`id`\n   INNER JOIN (\n      `softwareinstance` AS `SoftwareInstance_softwareinstance_id` \n      INNER JOIN \n         `functionalci` AS `FunctionalCI_system_id`\n       ON `SoftwareInstance_softwareinstance_id`.`functionalci_id` = `FunctionalCI_system_id`.`id`\n      INNER JOIN \n         `functionalci` AS `SoftwareInstance_softwareinstance_id_FunctionalCI`\n       ON `SoftwareInstance_softwareinstance_id`.`id` = `SoftwareInstance_softwareinstance_id_FunctionalCI`.`id`\n   ) ON `lnkSoftwareInstanceToSoftwarePatch`.`softwareinstance_id` = `SoftwareInstance_softwareinstance_id`.`id`\n WHERE COALESCE((`SoftwarePatch_softwarepatch_id_Patch`.`finalclass` IN (\'SoftwarePatch\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `lnkSoftwareInstanceToSoftwarePatch`.`id` AS `id`,`lnkSoftwareInstanceToSoftwarePatch`.`softwarepatch_id` AS `softwarepatch_id`,`SoftwarePatch_softwarepatch_id_Patch`.`name` AS `softwarepatch_name`,`lnkSoftwareInstanceToSoftwarePatch`.`softwareinstance_id` AS `softwareinstance_id`,`SoftwareInstance_softwareinstance_id_FunctionalCI`.`name` AS `softwareinstance_name`,cast(concat(coalesce(`lnkSoftwareInstanceToSoftwarePatch`.`softwarepatch_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkSoftwareInstanceToSoftwarePatch`.`softwareinstance_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`SoftwarePatch_softwarepatch_id_Patch`.`name`,\'\')) as char charset utf8mb4) AS `softwarepatch_id_friendlyname`,cast(concat(coalesce(`SoftwareInstance_softwareinstance_id_FunctionalCI`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`FunctionalCI_system_id`.`name`,\'\')) as char charset utf8mb4) AS `softwareinstance_id_friendlyname`,`SoftwareInstance_softwareinstance_id_FunctionalCI`.`finalclass` AS `softwareinstance_id_finalclass_recall`,coalesce((`SoftwareInstance_softwareinstance_id`.`status` = \'inactive\'),0) AS `softwareinstance_id_obsolescence_flag` from ((`itop27`.`lnksoftwareinstancetosoftwarepatch` `lnkSoftwareInstanceToSoftwarePatch` join `itop27`.`patch` `SoftwarePatch_softwarepatch_id_Patch` on((`lnkSoftwareInstanceToSoftwarePatch`.`softwarepatch_id` = `SoftwarePatch_softwarepatch_id_Patch`.`id`))) join ((`itop27`.`softwareinstance` `SoftwareInstance_softwareinstance_id` join `itop27`.`functionalci` `FunctionalCI_system_id` on((`SoftwareInstance_softwareinstance_id`.`functionalci_id` = `FunctionalCI_system_id`.`id`))) join `itop27`.`functionalci` `SoftwareInstance_softwareinstance_id_FunctionalCI` on((`SoftwareInstance_softwareinstance_id`.`id` = `SoftwareInstance_softwareinstance_id_FunctionalCI`.`id`))) on((`lnkSoftwareInstanceToSoftwarePatch`.`softwareinstance_id` = `SoftwareInstance_softwareinstance_id`.`id`))) where coalesce((`SoftwarePatch_softwarepatch_id_Patch`.`finalclass` = \'SoftwarePatch\'),1)
