TYPE=VIEW
query=select distinct `lnkDocumentToPatch`.`id` AS `id`,`lnkDocumentToPatch`.`patch_id` AS `patch_id`,`Patch_patch_id`.`name` AS `patch_name`,`lnkDocumentToPatch`.`document_id` AS `document_id`,`Document_document_id`.`name` AS `document_name`,cast(concat(coalesce(`lnkDocumentToPatch`.`patch_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkDocumentToPatch`.`document_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Patch_patch_id`.`name`,\'\')) as char charset utf8mb4) AS `patch_id_friendlyname`,`Patch_patch_id`.`finalclass` AS `patch_id_finalclass_recall`,if((`Document_document_id`.`finalclass` = \'Document\'),cast(concat(coalesce(\'Document\',\'\')) as char charset utf8mb4),cast(concat(coalesce(`Document_document_id`.`name`,\'\')) as char charset utf8mb4)) AS `document_id_friendlyname`,`Document_document_id`.`finalclass` AS `document_id_finalclass_recall`,coalesce((`Document_document_id`.`status` = \'obsolete\'),0) AS `document_id_obsolescence_flag` from ((`itop27`.`lnkdocumenttopatch` `lnkDocumentToPatch` join `itop27`.`patch` `Patch_patch_id` on((`lnkDocumentToPatch`.`patch_id` = `Patch_patch_id`.`id`))) join `itop27`.`document` `Document_document_id` on((`lnkDocumentToPatch`.`document_id` = `Document_document_id`.`id`))) where 1
md5=94888bdf71d61cbedc1376f914733c60
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `lnkDocumentToPatch`.`id` AS `id`,\n `lnkDocumentToPatch`.`patch_id` AS `patch_id`,\n `Patch_patch_id`.`name` AS `patch_name`,\n `lnkDocumentToPatch`.`document_id` AS `document_id`,\n `Document_document_id`.`name` AS `document_name`,\n CAST(CONCAT(COALESCE(`lnkDocumentToPatch`.`patch_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`lnkDocumentToPatch`.`document_id`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`Patch_patch_id`.`name`, \'\')) AS CHAR) AS `patch_id_friendlyname`,\n `Patch_patch_id`.`finalclass` AS `patch_id_finalclass_recall`,\n IF((`Document_document_id`.`finalclass` IN (\'Document\')), CAST(CONCAT(COALESCE(\'Document\', \'\')) AS CHAR), CAST(CONCAT(COALESCE(`Document_document_id`.`name`, \'\')) AS CHAR)) AS `document_id_friendlyname`,\n `Document_document_id`.`finalclass` AS `document_id_finalclass_recall`,\n COALESCE((`Document_document_id`.`status` = \'obsolete\'), 0) AS `document_id_obsolescence_flag`\n FROM \n   `lnkdocumenttopatch` AS `lnkDocumentToPatch`\n   INNER JOIN \n      `patch` AS `Patch_patch_id`\n    ON `lnkDocumentToPatch`.`patch_id` = `Patch_patch_id`.`id`\n   INNER JOIN \n      `document` AS `Document_document_id`\n    ON `lnkDocumentToPatch`.`document_id` = `Document_document_id`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `lnkDocumentToPatch`.`id` AS `id`,`lnkDocumentToPatch`.`patch_id` AS `patch_id`,`Patch_patch_id`.`name` AS `patch_name`,`lnkDocumentToPatch`.`document_id` AS `document_id`,`Document_document_id`.`name` AS `document_name`,cast(concat(coalesce(`lnkDocumentToPatch`.`patch_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkDocumentToPatch`.`document_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Patch_patch_id`.`name`,\'\')) as char charset utf8mb4) AS `patch_id_friendlyname`,`Patch_patch_id`.`finalclass` AS `patch_id_finalclass_recall`,if((`Document_document_id`.`finalclass` = \'Document\'),cast(concat(coalesce(\'Document\',\'\')) as char charset utf8mb4),cast(concat(coalesce(`Document_document_id`.`name`,\'\')) as char charset utf8mb4)) AS `document_id_friendlyname`,`Document_document_id`.`finalclass` AS `document_id_finalclass_recall`,coalesce((`Document_document_id`.`status` = \'obsolete\'),0) AS `document_id_obsolescence_flag` from ((`itop27`.`lnkdocumenttopatch` `lnkDocumentToPatch` join `itop27`.`patch` `Patch_patch_id` on((`lnkDocumentToPatch`.`patch_id` = `Patch_patch_id`.`id`))) join `itop27`.`document` `Document_document_id` on((`lnkDocumentToPatch`.`document_id` = `Document_document_id`.`id`))) where 1
