TYPE=VIEW
query=select distinct `MiddlewareInstance`.`id` AS `id`,`MiddlewareInstance_FunctionalCI`.`name` AS `name`,`MiddlewareInstance_FunctionalCI`.`description` AS `description`,`MiddlewareInstance_FunctionalCI`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`MiddlewareInstance_FunctionalCI`.`business_criticity` AS `business_criticity`,`MiddlewareInstance_FunctionalCI`.`move2production` AS `move2production`,`MiddlewareInstance`.`middleware_id` AS `middleware_id`,`Middleware_middleware_id_FunctionalCI`.`name` AS `middleware_name`,`MiddlewareInstance_FunctionalCI`.`finalclass` AS `finalclass`,cast(concat(coalesce(`MiddlewareInstance_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`Middleware_middleware_id_SoftwareInstance`.`status` = \'inactive\'),0),0) AS `obsolescence_flag`,`MiddlewareInstance_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Middleware_middleware_id_FunctionalCI`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`FunctionalCI_system_id`.`name`,\'\')) as char charset utf8mb4) AS `middleware_id_friendlyname`,coalesce((`Middleware_middleware_id_SoftwareInstance`.`status` = \'inactive\'),0) AS `middleware_id_obsolescence_flag` from ((`itop27`.`middlewareinstance` `MiddlewareInstance` join ((`itop27`.`softwareinstance` `Middleware_middleware_id_SoftwareInstance` join `itop27`.`functionalci` `FunctionalCI_system_id` on((`Middleware_middleware_id_SoftwareInstance`.`functionalci_id` = `FunctionalCI_system_id`.`id`))) join `itop27`.`functionalci` `Middleware_middleware_id_FunctionalCI` on((`Middleware_middleware_id_SoftwareInstance`.`id` = `Middleware_middleware_id_FunctionalCI`.`id`))) on((`MiddlewareInstance`.`middleware_id` = `Middleware_middleware_id_SoftwareInstance`.`id`))) join (`itop27`.`functionalci` `MiddlewareInstance_FunctionalCI` join `itop27`.`organization` `Organization_org_id` on((`MiddlewareInstance_FunctionalCI`.`org_id` = `Organization_org_id`.`id`))) on((`MiddlewareInstance`.`id` = `MiddlewareInstance_FunctionalCI`.`id`))) where coalesce((`Middleware_middleware_id_SoftwareInstance`.`finalclass` = \'Middleware\'),1)
md5=f475cd18f6e9b29ae4e5b0eb54fde177
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `MiddlewareInstance`.`id` AS `id`,\n `MiddlewareInstance_FunctionalCI`.`name` AS `name`,\n `MiddlewareInstance_FunctionalCI`.`description` AS `description`,\n `MiddlewareInstance_FunctionalCI`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `organization_name`,\n `MiddlewareInstance_FunctionalCI`.`business_criticity` AS `business_criticity`,\n `MiddlewareInstance_FunctionalCI`.`move2production` AS `move2production`,\n `MiddlewareInstance`.`middleware_id` AS `middleware_id`,\n `Middleware_middleware_id_FunctionalCI`.`name` AS `middleware_name`,\n `MiddlewareInstance_FunctionalCI`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`MiddlewareInstance_FunctionalCI`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE(COALESCE((`Middleware_middleware_id_SoftwareInstance`.`status` = \'inactive\'), 0), 0) AS `obsolescence_flag`,\n `MiddlewareInstance_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`Middleware_middleware_id_FunctionalCI`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`FunctionalCI_system_id`.`name`, \'\')) AS CHAR) AS `middleware_id_friendlyname`,\n COALESCE((`Middleware_middleware_id_SoftwareInstance`.`status` = \'inactive\'), 0) AS `middleware_id_obsolescence_flag`\n FROM \n   `middlewareinstance` AS `MiddlewareInstance`\n   INNER JOIN (\n      `softwareinstance` AS `Middleware_middleware_id_SoftwareInstance` \n      INNER JOIN \n         `functionalci` AS `FunctionalCI_system_id`\n       ON `Middleware_middleware_id_SoftwareInstance`.`functionalci_id` = `FunctionalCI_system_id`.`id`\n      INNER JOIN \n         `functionalci` AS `Middleware_middleware_id_FunctionalCI`\n       ON `Middleware_middleware_id_SoftwareInstance`.`id` = `Middleware_middleware_id_FunctionalCI`.`id`\n   ) ON `MiddlewareInstance`.`middleware_id` = `Middleware_middleware_id_SoftwareInstance`.`id`\n   INNER JOIN (\n      `functionalci` AS `MiddlewareInstance_FunctionalCI` \n      INNER JOIN \n         `organization` AS `Organization_org_id`\n       ON `MiddlewareInstance_FunctionalCI`.`org_id` = `Organization_org_id`.`id`\n   ) ON `MiddlewareInstance`.`id` = `MiddlewareInstance_FunctionalCI`.`id`\n WHERE COALESCE((`Middleware_middleware_id_SoftwareInstance`.`finalclass` IN (\'Middleware\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `MiddlewareInstance`.`id` AS `id`,`MiddlewareInstance_FunctionalCI`.`name` AS `name`,`MiddlewareInstance_FunctionalCI`.`description` AS `description`,`MiddlewareInstance_FunctionalCI`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`MiddlewareInstance_FunctionalCI`.`business_criticity` AS `business_criticity`,`MiddlewareInstance_FunctionalCI`.`move2production` AS `move2production`,`MiddlewareInstance`.`middleware_id` AS `middleware_id`,`Middleware_middleware_id_FunctionalCI`.`name` AS `middleware_name`,`MiddlewareInstance_FunctionalCI`.`finalclass` AS `finalclass`,cast(concat(coalesce(`MiddlewareInstance_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`Middleware_middleware_id_SoftwareInstance`.`status` = \'inactive\'),0),0) AS `obsolescence_flag`,`MiddlewareInstance_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Middleware_middleware_id_FunctionalCI`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`FunctionalCI_system_id`.`name`,\'\')) as char charset utf8mb4) AS `middleware_id_friendlyname`,coalesce((`Middleware_middleware_id_SoftwareInstance`.`status` = \'inactive\'),0) AS `middleware_id_obsolescence_flag` from ((`itop27`.`middlewareinstance` `MiddlewareInstance` join ((`itop27`.`softwareinstance` `Middleware_middleware_id_SoftwareInstance` join `itop27`.`functionalci` `FunctionalCI_system_id` on((`Middleware_middleware_id_SoftwareInstance`.`functionalci_id` = `FunctionalCI_system_id`.`id`))) join `itop27`.`functionalci` `Middleware_middleware_id_FunctionalCI` on((`Middleware_middleware_id_SoftwareInstance`.`id` = `Middleware_middleware_id_FunctionalCI`.`id`))) on((`MiddlewareInstance`.`middleware_id` = `Middleware_middleware_id_SoftwareInstance`.`id`))) join (`itop27`.`functionalci` `MiddlewareInstance_FunctionalCI` join `itop27`.`organization` `Organization_org_id` on((`MiddlewareInstance_FunctionalCI`.`org_id` = `Organization_org_id`.`id`))) on((`MiddlewareInstance`.`id` = `MiddlewareInstance_FunctionalCI`.`id`))) where coalesce((`Middleware_middleware_id_SoftwareInstance`.`finalclass` = \'Middleware\'),1)
