TYPE=VIEW
query=select distinct `lnkContactToTicket`.`id` AS `id`,`lnkContactToTicket`.`ticket_id` AS `ticket_id`,`Ticket_ticket_id`.`ref` AS `ticket_ref`,`lnkContactToTicket`.`contact_id` AS `contact_id`,`Contact_contact_id`.`email` AS `contact_email`,`lnkContactToTicket`.`role` AS `role`,`lnkContactToTicket`.`impact_code` AS `role_code`,cast(concat(coalesce(`lnkContactToTicket`.`ticket_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkContactToTicket`.`contact_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Ticket_ticket_id`.`ref`,\'\')) as char charset utf8mb4) AS `ticket_id_friendlyname`,`Ticket_ticket_id`.`finalclass` AS `ticket_id_finalclass_recall`,if((`Contact_contact_id`.`finalclass` in (\'Team\',\'Contact\')),cast(concat(coalesce(`Contact_contact_id`.`name`,\'\')) as char charset utf8mb4),cast(concat(coalesce(`Contact_contact_id_poly_Person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Contact_contact_id`.`name`,\'\')) as char charset utf8mb4)) AS `contact_id_friendlyname`,`Contact_contact_id`.`finalclass` AS `contact_id_finalclass_recall`,coalesce((`Contact_contact_id`.`status` = \'inactive\'),0) AS `contact_id_obsolescence_flag` from ((`itop27`.`lnkcontacttoticket` `lnkContactToTicket` join `itop27`.`ticket` `Ticket_ticket_id` on((`lnkContactToTicket`.`ticket_id` = `Ticket_ticket_id`.`id`))) join (`itop27`.`contact` `Contact_contact_id` left join `itop27`.`person` `Contact_contact_id_poly_Person` on((`Contact_contact_id`.`id` = `Contact_contact_id_poly_Person`.`id`))) on((`lnkContactToTicket`.`contact_id` = `Contact_contact_id`.`id`))) where 1
md5=1823d8ef4871942f81766f8df649090c
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `lnkContactToTicket`.`id` AS `id`,\n `lnkContactToTicket`.`ticket_id` AS `ticket_id`,\n `Ticket_ticket_id`.`ref` AS `ticket_ref`,\n `lnkContactToTicket`.`contact_id` AS `contact_id`,\n `Contact_contact_id`.`email` AS `contact_email`,\n `lnkContactToTicket`.`role` AS `role`,\n `lnkContactToTicket`.`impact_code` AS `role_code`,\n CAST(CONCAT(COALESCE(`lnkContactToTicket`.`ticket_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`lnkContactToTicket`.`contact_id`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`Ticket_ticket_id`.`ref`, \'\')) AS CHAR) AS `ticket_id_friendlyname`,\n `Ticket_ticket_id`.`finalclass` AS `ticket_id_finalclass_recall`,\n IF((`Contact_contact_id`.`finalclass` IN (\'Team\', \'Contact\')), CAST(CONCAT(COALESCE(`Contact_contact_id`.`name`, \'\')) AS CHAR), CAST(CONCAT(COALESCE(`Contact_contact_id_poly_Person`.`first_name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Contact_contact_id`.`name`, \'\')) AS CHAR)) AS `contact_id_friendlyname`,\n `Contact_contact_id`.`finalclass` AS `contact_id_finalclass_recall`,\n COALESCE((`Contact_contact_id`.`status` = \'inactive\'), 0) AS `contact_id_obsolescence_flag`\n FROM \n   `lnkcontacttoticket` AS `lnkContactToTicket`\n   INNER JOIN \n      `ticket` AS `Ticket_ticket_id`\n    ON `lnkContactToTicket`.`ticket_id` = `Ticket_ticket_id`.`id`\n   INNER JOIN (\n      `contact` AS `Contact_contact_id` \n      LEFT JOIN \n         `person` AS `Contact_contact_id_poly_Person`\n       ON `Contact_contact_id`.`id` = `Contact_contact_id_poly_Person`.`id`\n   ) ON `lnkContactToTicket`.`contact_id` = `Contact_contact_id`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `lnkContactToTicket`.`id` AS `id`,`lnkContactToTicket`.`ticket_id` AS `ticket_id`,`Ticket_ticket_id`.`ref` AS `ticket_ref`,`lnkContactToTicket`.`contact_id` AS `contact_id`,`Contact_contact_id`.`email` AS `contact_email`,`lnkContactToTicket`.`role` AS `role`,`lnkContactToTicket`.`impact_code` AS `role_code`,cast(concat(coalesce(`lnkContactToTicket`.`ticket_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkContactToTicket`.`contact_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Ticket_ticket_id`.`ref`,\'\')) as char charset utf8mb4) AS `ticket_id_friendlyname`,`Ticket_ticket_id`.`finalclass` AS `ticket_id_finalclass_recall`,if((`Contact_contact_id`.`finalclass` in (\'Team\',\'Contact\')),cast(concat(coalesce(`Contact_contact_id`.`name`,\'\')) as char charset utf8mb4),cast(concat(coalesce(`Contact_contact_id_poly_Person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Contact_contact_id`.`name`,\'\')) as char charset utf8mb4)) AS `contact_id_friendlyname`,`Contact_contact_id`.`finalclass` AS `contact_id_finalclass_recall`,coalesce((`Contact_contact_id`.`status` = \'inactive\'),0) AS `contact_id_obsolescence_flag` from ((`itop27`.`lnkcontacttoticket` `lnkContactToTicket` join `itop27`.`ticket` `Ticket_ticket_id` on((`lnkContactToTicket`.`ticket_id` = `Ticket_ticket_id`.`id`))) join (`itop27`.`contact` `Contact_contact_id` left join `itop27`.`person` `Contact_contact_id_poly_Person` on((`Contact_contact_id`.`id` = `Contact_contact_id_poly_Person`.`id`))) on((`lnkContactToTicket`.`contact_id` = `Contact_contact_id`.`id`))) where 1
