TYPE=VIEW
query=select distinct `lnkSubnetToVLAN`.`id` AS `id`,`lnkSubnetToVLAN`.`subnet_id` AS `subnet_id`,`Subnet_subnet_id`.`ip` AS `subnet_ip`,`Subnet_subnet_id`.`subnet_name` AS `subnet_name`,`lnkSubnetToVLAN`.`vlan_id` AS `vlan_id`,`VLAN_vlan_id`.`vlan_tag` AS `vlan_tag`,cast(concat(coalesce(`lnkSubnetToVLAN`.`subnet_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkSubnetToVLAN`.`vlan_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Subnet_subnet_id`.`ip`,\'\'),coalesce(\' \',\'\'),coalesce(`Subnet_subnet_id`.`ip_mask`,\'\')) as char charset utf8mb4) AS `subnet_id_friendlyname`,cast(concat(coalesce(`VLAN_vlan_id`.`vlan_tag`,\'\')) as char charset utf8mb4) AS `vlan_id_friendlyname` from ((`itop27`.`lnksubnettovlan` `lnkSubnetToVLAN` join `itop27`.`subnet` `Subnet_subnet_id` on((`lnkSubnetToVLAN`.`subnet_id` = `Subnet_subnet_id`.`id`))) join `itop27`.`vlan` `VLAN_vlan_id` on((`lnkSubnetToVLAN`.`vlan_id` = `VLAN_vlan_id`.`id`))) where 1
md5=c6b0a9bdb4ba08e6cda02d55dea7cc04
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `lnkSubnetToVLAN`.`id` AS `id`,\n `lnkSubnetToVLAN`.`subnet_id` AS `subnet_id`,\n `Subnet_subnet_id`.`ip` AS `subnet_ip`,\n `Subnet_subnet_id`.`subnet_name` AS `subnet_name`,\n `lnkSubnetToVLAN`.`vlan_id` AS `vlan_id`,\n `VLAN_vlan_id`.`vlan_tag` AS `vlan_tag`,\n CAST(CONCAT(COALESCE(`lnkSubnetToVLAN`.`subnet_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`lnkSubnetToVLAN`.`vlan_id`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`Subnet_subnet_id`.`ip`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Subnet_subnet_id`.`ip_mask`, \'\')) AS CHAR) AS `subnet_id_friendlyname`,\n CAST(CONCAT(COALESCE(`VLAN_vlan_id`.`vlan_tag`, \'\')) AS CHAR) AS `vlan_id_friendlyname`\n FROM \n   `lnksubnettovlan` AS `lnkSubnetToVLAN`\n   INNER JOIN \n      `subnet` AS `Subnet_subnet_id`\n    ON `lnkSubnetToVLAN`.`subnet_id` = `Subnet_subnet_id`.`id`\n   INNER JOIN \n      `vlan` AS `VLAN_vlan_id`\n    ON `lnkSubnetToVLAN`.`vlan_id` = `VLAN_vlan_id`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `lnkSubnetToVLAN`.`id` AS `id`,`lnkSubnetToVLAN`.`subnet_id` AS `subnet_id`,`Subnet_subnet_id`.`ip` AS `subnet_ip`,`Subnet_subnet_id`.`subnet_name` AS `subnet_name`,`lnkSubnetToVLAN`.`vlan_id` AS `vlan_id`,`VLAN_vlan_id`.`vlan_tag` AS `vlan_tag`,cast(concat(coalesce(`lnkSubnetToVLAN`.`subnet_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkSubnetToVLAN`.`vlan_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Subnet_subnet_id`.`ip`,\'\'),coalesce(\' \',\'\'),coalesce(`Subnet_subnet_id`.`ip_mask`,\'\')) as char charset utf8mb4) AS `subnet_id_friendlyname`,cast(concat(coalesce(`VLAN_vlan_id`.`vlan_tag`,\'\')) as char charset utf8mb4) AS `vlan_id_friendlyname` from ((`itop27`.`lnksubnettovlan` `lnkSubnetToVLAN` join `itop27`.`subnet` `Subnet_subnet_id` on((`lnkSubnetToVLAN`.`subnet_id` = `Subnet_subnet_id`.`id`))) join `itop27`.`vlan` `VLAN_vlan_id` on((`lnkSubnetToVLAN`.`vlan_id` = `VLAN_vlan_id`.`id`))) where 1
