TYPE=VIEW
query=select distinct `Team_Contact`.`id` AS `id`,`Team_Contact`.`name` AS `name`,`Team_Contact`.`status` AS `status`,`Team_Contact`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `org_name`,`Team_Contact`.`email` AS `email`,`Team_Contact`.`phone` AS `phone`,`Team_Contact`.`notify` AS `notify`,`Team_Contact`.`function` AS `function`,`Team_Contact`.`finalclass` AS `finalclass`,cast(concat(coalesce(`Team_Contact`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`Team_Contact`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`Team_Contact`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from (`itop27`.`contact` `Team_Contact` join `itop27`.`organization` `Organization_org_id` on((`Team_Contact`.`org_id` = `Organization_org_id`.`id`))) where coalesce((`Team_Contact`.`finalclass` = \'Team\'),1)
md5=43b0d27e9845be6edf8914555a736d8a
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `Team_Contact`.`id` AS `id`,\n `Team_Contact`.`name` AS `name`,\n `Team_Contact`.`status` AS `status`,\n `Team_Contact`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `org_name`,\n `Team_Contact`.`email` AS `email`,\n `Team_Contact`.`phone` AS `phone`,\n `Team_Contact`.`notify` AS `notify`,\n `Team_Contact`.`function` AS `function`,\n `Team_Contact`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`Team_Contact`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE((`Team_Contact`.`status` = \'inactive\'), 0) AS `obsolescence_flag`,\n `Team_Contact`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`\n FROM \n   `contact` AS `Team_Contact`\n   INNER JOIN \n      `organization` AS `Organization_org_id`\n    ON `Team_Contact`.`org_id` = `Organization_org_id`.`id`\n WHERE COALESCE((`Team_Contact`.`finalclass` IN (\'Team\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `Team_Contact`.`id` AS `id`,`Team_Contact`.`name` AS `name`,`Team_Contact`.`status` AS `status`,`Team_Contact`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `org_name`,`Team_Contact`.`email` AS `email`,`Team_Contact`.`phone` AS `phone`,`Team_Contact`.`notify` AS `notify`,`Team_Contact`.`function` AS `function`,`Team_Contact`.`finalclass` AS `finalclass`,cast(concat(coalesce(`Team_Contact`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`Team_Contact`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`Team_Contact`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from (`itop27`.`contact` `Team_Contact` join `itop27`.`organization` `Organization_org_id` on((`Team_Contact`.`org_id` = `Organization_org_id`.`id`))) where coalesce((`Team_Contact`.`finalclass` = \'Team\'),1)
