TYPE=VIEW
query=select distinct `lnkDocumentToSoftware`.`id` AS `id`,`lnkDocumentToSoftware`.`software_id` AS `software_id`,`Software_software_id`.`name` AS `software_name`,`lnkDocumentToSoftware`.`document_id` AS `document_id`,`Document_document_id`.`name` AS `document_name`,cast(concat(coalesce(`lnkDocumentToSoftware`.`software_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkDocumentToSoftware`.`document_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Software_software_id`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`Software_software_id`.`version`,\'\')) as char charset utf8mb4) AS `software_id_friendlyname`,if((`Document_document_id`.`finalclass` = \'Document\'),cast(concat(coalesce(\'Document\',\'\')) as char charset utf8mb4),cast(concat(coalesce(`Document_document_id`.`name`,\'\')) as char charset utf8mb4)) AS `document_id_friendlyname`,`Document_document_id`.`finalclass` AS `document_id_finalclass_recall`,coalesce((`Document_document_id`.`status` = \'obsolete\'),0) AS `document_id_obsolescence_flag` from ((`itop27`.`lnkdocumenttosoftware` `lnkDocumentToSoftware` join `itop27`.`software` `Software_software_id` on((`lnkDocumentToSoftware`.`software_id` = `Software_software_id`.`id`))) join `itop27`.`document` `Document_document_id` on((`lnkDocumentToSoftware`.`document_id` = `Document_document_id`.`id`))) where 1
md5=2e61fc082b929e2da93660021f9b0280
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `lnkDocumentToSoftware`.`id` AS `id`,\n `lnkDocumentToSoftware`.`software_id` AS `software_id`,\n `Software_software_id`.`name` AS `software_name`,\n `lnkDocumentToSoftware`.`document_id` AS `document_id`,\n `Document_document_id`.`name` AS `document_name`,\n CAST(CONCAT(COALESCE(`lnkDocumentToSoftware`.`software_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`lnkDocumentToSoftware`.`document_id`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`Software_software_id`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Software_software_id`.`version`, \'\')) AS CHAR) AS `software_id_friendlyname`,\n IF((`Document_document_id`.`finalclass` IN (\'Document\')), CAST(CONCAT(COALESCE(\'Document\', \'\')) AS CHAR), CAST(CONCAT(COALESCE(`Document_document_id`.`name`, \'\')) AS CHAR)) AS `document_id_friendlyname`,\n `Document_document_id`.`finalclass` AS `document_id_finalclass_recall`,\n COALESCE((`Document_document_id`.`status` = \'obsolete\'), 0) AS `document_id_obsolescence_flag`\n FROM \n   `lnkdocumenttosoftware` AS `lnkDocumentToSoftware`\n   INNER JOIN \n      `software` AS `Software_software_id`\n    ON `lnkDocumentToSoftware`.`software_id` = `Software_software_id`.`id`\n   INNER JOIN \n      `document` AS `Document_document_id`\n    ON `lnkDocumentToSoftware`.`document_id` = `Document_document_id`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `lnkDocumentToSoftware`.`id` AS `id`,`lnkDocumentToSoftware`.`software_id` AS `software_id`,`Software_software_id`.`name` AS `software_name`,`lnkDocumentToSoftware`.`document_id` AS `document_id`,`Document_document_id`.`name` AS `document_name`,cast(concat(coalesce(`lnkDocumentToSoftware`.`software_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkDocumentToSoftware`.`document_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Software_software_id`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`Software_software_id`.`version`,\'\')) as char charset utf8mb4) AS `software_id_friendlyname`,if((`Document_document_id`.`finalclass` = \'Document\'),cast(concat(coalesce(\'Document\',\'\')) as char charset utf8mb4),cast(concat(coalesce(`Document_document_id`.`name`,\'\')) as char charset utf8mb4)) AS `document_id_friendlyname`,`Document_document_id`.`finalclass` AS `document_id_finalclass_recall`,coalesce((`Document_document_id`.`status` = \'obsolete\'),0) AS `document_id_obsolescence_flag` from ((`itop27`.`lnkdocumenttosoftware` `lnkDocumentToSoftware` join `itop27`.`software` `Software_software_id` on((`lnkDocumentToSoftware`.`software_id` = `Software_software_id`.`id`))) join `itop27`.`document` `Document_document_id` on((`lnkDocumentToSoftware`.`document_id` = `Document_document_id`.`id`))) where 1
