TYPE=VIEW
query=select distinct `FiberChannelInterface`.`id` AS `id`,`FiberChannelInterface_NetworkInterface`.`name` AS `name`,`FiberChannelInterface`.`speed` AS `speed`,`FiberChannelInterface`.`topology` AS `topology`,`FiberChannelInterface`.`wwn` AS `wwn`,`FiberChannelInterface`.`datacenterdevice_id` AS `datacenterdevice_id`,`DatacenterDevice_datacenterdevice_id_FunctionalCI`.`name` AS `datacenterdevice_name`,`FiberChannelInterface_NetworkInterface`.`finalclass` AS `finalclass`,cast(concat(coalesce(`FiberChannelInterface_NetworkInterface`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`DatacenterDevice_datacenterdevice_id_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`DatacenterDevice_datacenterdevice_id_PhysicalDevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`FiberChannelInterface_NetworkInterface`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`DatacenterDevice_datacenterdevice_id_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `datacenterdevice_id_friendlyname`,`DatacenterDevice_datacenterdevice_id_FunctionalCI`.`finalclass` AS `datacenterdevice_id_finalclass_recall`,coalesce((`DatacenterDevice_datacenterdevice_id_PhysicalDevice`.`status` = \'obsolete\'),0) AS `datacenterdevice_id_obsolescence_flag` from ((`itop27`.`fiberchannelinterface` `FiberChannelInterface` join (`itop27`.`physicaldevice` `DatacenterDevice_datacenterdevice_id_PhysicalDevice` join `itop27`.`functionalci` `DatacenterDevice_datacenterdevice_id_FunctionalCI` on((`DatacenterDevice_datacenterdevice_id_PhysicalDevice`.`id` = `DatacenterDevice_datacenterdevice_id_FunctionalCI`.`id`))) on((`FiberChannelInterface`.`datacenterdevice_id` = `DatacenterDevice_datacenterdevice_id_PhysicalDevice`.`id`))) join `itop27`.`networkinterface` `FiberChannelInterface_NetworkInterface` on((`FiberChannelInterface`.`id` = `FiberChannelInterface_NetworkInterface`.`id`))) where coalesce((`DatacenterDevice_datacenterdevice_id_PhysicalDevice`.`finalclass` in (\'NetworkDevice\',\'Server\',\'StorageSystem\',\'SANSwitch\',\'TapeLibrary\',\'NAS\',\'DatacenterDevice\')),1)
md5=808469d926d2feed4c0df380993b502f
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `FiberChannelInterface`.`id` AS `id`,\n `FiberChannelInterface_NetworkInterface`.`name` AS `name`,\n `FiberChannelInterface`.`speed` AS `speed`,\n `FiberChannelInterface`.`topology` AS `topology`,\n `FiberChannelInterface`.`wwn` AS `wwn`,\n `FiberChannelInterface`.`datacenterdevice_id` AS `datacenterdevice_id`,\n `DatacenterDevice_datacenterdevice_id_FunctionalCI`.`name` AS `datacenterdevice_name`,\n `FiberChannelInterface_NetworkInterface`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`FiberChannelInterface_NetworkInterface`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`DatacenterDevice_datacenterdevice_id_FunctionalCI`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE(COALESCE((`DatacenterDevice_datacenterdevice_id_PhysicalDevice`.`status` = \'obsolete\'), 0), 0) AS `obsolescence_flag`,\n `FiberChannelInterface_NetworkInterface`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`DatacenterDevice_datacenterdevice_id_FunctionalCI`.`name`, \'\')) AS CHAR) AS `datacenterdevice_id_friendlyname`,\n `DatacenterDevice_datacenterdevice_id_FunctionalCI`.`finalclass` AS `datacenterdevice_id_finalclass_recall`,\n COALESCE((`DatacenterDevice_datacenterdevice_id_PhysicalDevice`.`status` = \'obsolete\'), 0) AS `datacenterdevice_id_obsolescence_flag`\n FROM \n   `fiberchannelinterface` AS `FiberChannelInterface`\n   INNER JOIN (\n      `physicaldevice` AS `DatacenterDevice_datacenterdevice_id_PhysicalDevice` \n      INNER JOIN \n         `functionalci` AS `DatacenterDevice_datacenterdevice_id_FunctionalCI`\n       ON `DatacenterDevice_datacenterdevice_id_PhysicalDevice`.`id` = `DatacenterDevice_datacenterdevice_id_FunctionalCI`.`id`\n   ) ON `FiberChannelInterface`.`datacenterdevice_id` = `DatacenterDevice_datacenterdevice_id_PhysicalDevice`.`id`\n   INNER JOIN \n      `networkinterface` AS `FiberChannelInterface_NetworkInterface`\n    ON `FiberChannelInterface`.`id` = `FiberChannelInterface_NetworkInterface`.`id`\n WHERE COALESCE((`DatacenterDevice_datacenterdevice_id_PhysicalDevice`.`finalclass` IN (\'NetworkDevice\', \'Server\', \'StorageSystem\', \'SANSwitch\', \'TapeLibrary\', \'NAS\', \'DatacenterDevice\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `FiberChannelInterface`.`id` AS `id`,`FiberChannelInterface_NetworkInterface`.`name` AS `name`,`FiberChannelInterface`.`speed` AS `speed`,`FiberChannelInterface`.`topology` AS `topology`,`FiberChannelInterface`.`wwn` AS `wwn`,`FiberChannelInterface`.`datacenterdevice_id` AS `datacenterdevice_id`,`DatacenterDevice_datacenterdevice_id_FunctionalCI`.`name` AS `datacenterdevice_name`,`FiberChannelInterface_NetworkInterface`.`finalclass` AS `finalclass`,cast(concat(coalesce(`FiberChannelInterface_NetworkInterface`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`DatacenterDevice_datacenterdevice_id_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`DatacenterDevice_datacenterdevice_id_PhysicalDevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`FiberChannelInterface_NetworkInterface`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`DatacenterDevice_datacenterdevice_id_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `datacenterdevice_id_friendlyname`,`DatacenterDevice_datacenterdevice_id_FunctionalCI`.`finalclass` AS `datacenterdevice_id_finalclass_recall`,coalesce((`DatacenterDevice_datacenterdevice_id_PhysicalDevice`.`status` = \'obsolete\'),0) AS `datacenterdevice_id_obsolescence_flag` from ((`itop27`.`fiberchannelinterface` `FiberChannelInterface` join (`itop27`.`physicaldevice` `DatacenterDevice_datacenterdevice_id_PhysicalDevice` join `itop27`.`functionalci` `DatacenterDevice_datacenterdevice_id_FunctionalCI` on((`DatacenterDevice_datacenterdevice_id_PhysicalDevice`.`id` = `DatacenterDevice_datacenterdevice_id_FunctionalCI`.`id`))) on((`FiberChannelInterface`.`datacenterdevice_id` = `DatacenterDevice_datacenterdevice_id_PhysicalDevice`.`id`))) join `itop27`.`networkinterface` `FiberChannelInterface_NetworkInterface` on((`FiberChannelInterface`.`id` = `FiberChannelInterface_NetworkInterface`.`id`))) where coalesce((`DatacenterDevice_datacenterdevice_id_PhysicalDevice`.`finalclass` in (\'NetworkDevice\',\'Server\',\'StorageSystem\',\'SANSwitch\',\'TapeLibrary\',\'NAS\',\'DatacenterDevice\')),1)
