TYPE=VIEW
query=select distinct `DocumentFile`.`id` AS `id`,`DocumentFile_Document`.`name` AS `name`,`DocumentFile_Document`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `org_name`,`DocumentFile_Document`.`documenttype_id` AS `documenttype_id`,`DocumentType_documenttype_id_Typology`.`name` AS `documenttype_name`,`DocumentFile_Document`.`version` AS `version`,`DocumentFile_Document`.`description` AS `description`,`DocumentFile_Document`.`status` AS `status`,`DocumentFile`.`file_mimetype` AS `file`,`DocumentFile_Document`.`finalclass` AS `finalclass`,cast(concat(coalesce(`DocumentFile_Document`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`DocumentFile_Document`.`status` = \'obsolete\'),0) AS `obsolescence_flag`,`DocumentFile_Document`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`DocumentType_documenttype_id_Typology`.`name`,\'\')) as char charset utf8mb4) AS `documenttype_id_friendlyname`,`DocumentFile`.`file_data` AS `DocumentFilefile_data`,`DocumentFile`.`file_filename` AS `DocumentFilefile_filename` from (`itop27`.`documentfile` `DocumentFile` join ((`itop27`.`document` `DocumentFile_Document` join `itop27`.`organization` `Organization_org_id` on((`DocumentFile_Document`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`typology` `DocumentType_documenttype_id_Typology` on((`DocumentFile_Document`.`documenttype_id` = `DocumentType_documenttype_id_Typology`.`id`))) on((`DocumentFile`.`id` = `DocumentFile_Document`.`id`))) where coalesce((`DocumentType_documenttype_id_Typology`.`finalclass` = \'DocumentType\'),1)
md5=8e218ac74b654ada0112771b1d058709
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `DocumentFile`.`id` AS `id`,\n `DocumentFile_Document`.`name` AS `name`,\n `DocumentFile_Document`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `org_name`,\n `DocumentFile_Document`.`documenttype_id` AS `documenttype_id`,\n `DocumentType_documenttype_id_Typology`.`name` AS `documenttype_name`,\n `DocumentFile_Document`.`version` AS `version`,\n `DocumentFile_Document`.`description` AS `description`,\n `DocumentFile_Document`.`status` AS `status`,\n `DocumentFile`.`file_mimetype` AS `file`,\n `DocumentFile_Document`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`DocumentFile_Document`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE((`DocumentFile_Document`.`status` = \'obsolete\'), 0) AS `obsolescence_flag`,\n `DocumentFile_Document`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`DocumentType_documenttype_id_Typology`.`name`, \'\')) AS CHAR) AS `documenttype_id_friendlyname`,\n `DocumentFile`.`file_data` AS `DocumentFilefile_data`,\n `DocumentFile`.`file_filename` AS `DocumentFilefile_filename`\n FROM \n   `documentfile` AS `DocumentFile`\n   INNER JOIN (\n      `document` AS `DocumentFile_Document` \n      INNER JOIN \n         `organization` AS `Organization_org_id`\n       ON `DocumentFile_Document`.`org_id` = `Organization_org_id`.`id`\n      LEFT JOIN \n         `typology` AS `DocumentType_documenttype_id_Typology`\n       ON `DocumentFile_Document`.`documenttype_id` = `DocumentType_documenttype_id_Typology`.`id`\n   ) ON `DocumentFile`.`id` = `DocumentFile_Document`.`id`\n WHERE COALESCE((`DocumentType_documenttype_id_Typology`.`finalclass` IN (\'DocumentType\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `DocumentFile`.`id` AS `id`,`DocumentFile_Document`.`name` AS `name`,`DocumentFile_Document`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `org_name`,`DocumentFile_Document`.`documenttype_id` AS `documenttype_id`,`DocumentType_documenttype_id_Typology`.`name` AS `documenttype_name`,`DocumentFile_Document`.`version` AS `version`,`DocumentFile_Document`.`description` AS `description`,`DocumentFile_Document`.`status` AS `status`,`DocumentFile`.`file_mimetype` AS `file`,`DocumentFile_Document`.`finalclass` AS `finalclass`,cast(concat(coalesce(`DocumentFile_Document`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`DocumentFile_Document`.`status` = \'obsolete\'),0) AS `obsolescence_flag`,`DocumentFile_Document`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`DocumentType_documenttype_id_Typology`.`name`,\'\')) as char charset utf8mb4) AS `documenttype_id_friendlyname`,`DocumentFile`.`file_data` AS `DocumentFilefile_data`,`DocumentFile`.`file_filename` AS `DocumentFilefile_filename` from (`itop27`.`documentfile` `DocumentFile` join ((`itop27`.`document` `DocumentFile_Document` join `itop27`.`organization` `Organization_org_id` on((`DocumentFile_Document`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`typology` `DocumentType_documenttype_id_Typology` on((`DocumentFile_Document`.`documenttype_id` = `DocumentType_documenttype_id_Typology`.`id`))) on((`DocumentFile`.`id` = `DocumentFile_Document`.`id`))) where coalesce((`DocumentType_documenttype_id_Typology`.`finalclass` = \'DocumentType\'),1)
