TYPE=VIEW
query=select distinct `CustomerContract_Contract`.`id` AS `id`,`CustomerContract_Contract`.`name` AS `name`,`CustomerContract_Contract`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`CustomerContract_Contract`.`description` AS `description`,`CustomerContract_Contract`.`start_date` AS `start_date`,`CustomerContract_Contract`.`end_date` AS `end_date`,`CustomerContract_Contract`.`cost` AS `cost`,`CustomerContract_Contract`.`cost_currency` AS `cost_currency`,`CustomerContract_Contract`.`contracttype_id` AS `contracttype_id`,`ContractType_contracttype_id_Typology`.`name` AS `contracttype_name`,`CustomerContract_Contract`.`billing_frequency` AS `billing_frequency`,`CustomerContract_Contract`.`cost_unit` AS `cost_unit`,`CustomerContract_Contract`.`provider_id` AS `provider_id`,`Organization_provider_id`.`name` AS `provider_name`,`CustomerContract_Contract`.`status` AS `status`,`CustomerContract_Contract`.`finalclass` AS `finalclass`,cast(concat(coalesce(`CustomerContract_Contract`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`ContractType_contracttype_id_Typology`.`name`,\'\')) as char charset utf8mb4) AS `contracttype_id_friendlyname`,cast(concat(coalesce(`Organization_provider_id`.`name`,\'\')) as char charset utf8mb4) AS `provider_id_friendlyname`,coalesce((`Organization_provider_id`.`status` = \'inactive\'),0) AS `provider_id_obsolescence_flag` from (((`itop27`.`contract` `CustomerContract_Contract` join `itop27`.`organization` `Organization_org_id` on((`CustomerContract_Contract`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`typology` `ContractType_contracttype_id_Typology` on((`CustomerContract_Contract`.`contracttype_id` = `ContractType_contracttype_id_Typology`.`id`))) join `itop27`.`organization` `Organization_provider_id` on((`CustomerContract_Contract`.`provider_id` = `Organization_provider_id`.`id`))) where (coalesce((`ContractType_contracttype_id_Typology`.`finalclass` = \'ContractType\'),1) and coalesce((`CustomerContract_Contract`.`finalclass` = \'CustomerContract\'),1))
md5=07422de409dd2095da5d493c79b0622e
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `CustomerContract_Contract`.`id` AS `id`,\n `CustomerContract_Contract`.`name` AS `name`,\n `CustomerContract_Contract`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `organization_name`,\n `CustomerContract_Contract`.`description` AS `description`,\n `CustomerContract_Contract`.`start_date` AS `start_date`,\n `CustomerContract_Contract`.`end_date` AS `end_date`,\n `CustomerContract_Contract`.`cost` AS `cost`,\n `CustomerContract_Contract`.`cost_currency` AS `cost_currency`,\n `CustomerContract_Contract`.`contracttype_id` AS `contracttype_id`,\n `ContractType_contracttype_id_Typology`.`name` AS `contracttype_name`,\n `CustomerContract_Contract`.`billing_frequency` AS `billing_frequency`,\n `CustomerContract_Contract`.`cost_unit` AS `cost_unit`,\n `CustomerContract_Contract`.`provider_id` AS `provider_id`,\n `Organization_provider_id`.`name` AS `provider_name`,\n `CustomerContract_Contract`.`status` AS `status`,\n `CustomerContract_Contract`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`CustomerContract_Contract`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`ContractType_contracttype_id_Typology`.`name`, \'\')) AS CHAR) AS `contracttype_id_friendlyname`,\n CAST(CONCAT(COALESCE(`Organization_provider_id`.`name`, \'\')) AS CHAR) AS `provider_id_friendlyname`,\n COALESCE((`Organization_provider_id`.`status` = \'inactive\'), 0) AS `provider_id_obsolescence_flag`\n FROM \n   `contract` AS `CustomerContract_Contract`\n   INNER JOIN \n      `organization` AS `Organization_org_id`\n    ON `CustomerContract_Contract`.`org_id` = `Organization_org_id`.`id`\n   LEFT JOIN \n      `typology` AS `ContractType_contracttype_id_Typology`\n    ON `CustomerContract_Contract`.`contracttype_id` = `ContractType_contracttype_id_Typology`.`id`\n   INNER JOIN \n      `organization` AS `Organization_provider_id`\n    ON `CustomerContract_Contract`.`provider_id` = `Organization_provider_id`.`id`\n WHERE (COALESCE((`ContractType_contracttype_id_Typology`.`finalclass` IN (\'ContractType\')), 1) AND COALESCE((`CustomerContract_Contract`.`finalclass` IN (\'CustomerContract\')), 1))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `CustomerContract_Contract`.`id` AS `id`,`CustomerContract_Contract`.`name` AS `name`,`CustomerContract_Contract`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`CustomerContract_Contract`.`description` AS `description`,`CustomerContract_Contract`.`start_date` AS `start_date`,`CustomerContract_Contract`.`end_date` AS `end_date`,`CustomerContract_Contract`.`cost` AS `cost`,`CustomerContract_Contract`.`cost_currency` AS `cost_currency`,`CustomerContract_Contract`.`contracttype_id` AS `contracttype_id`,`ContractType_contracttype_id_Typology`.`name` AS `contracttype_name`,`CustomerContract_Contract`.`billing_frequency` AS `billing_frequency`,`CustomerContract_Contract`.`cost_unit` AS `cost_unit`,`CustomerContract_Contract`.`provider_id` AS `provider_id`,`Organization_provider_id`.`name` AS `provider_name`,`CustomerContract_Contract`.`status` AS `status`,`CustomerContract_Contract`.`finalclass` AS `finalclass`,cast(concat(coalesce(`CustomerContract_Contract`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`ContractType_contracttype_id_Typology`.`name`,\'\')) as char charset utf8mb4) AS `contracttype_id_friendlyname`,cast(concat(coalesce(`Organization_provider_id`.`name`,\'\')) as char charset utf8mb4) AS `provider_id_friendlyname`,coalesce((`Organization_provider_id`.`status` = \'inactive\'),0) AS `provider_id_obsolescence_flag` from (((`itop27`.`contract` `CustomerContract_Contract` join `itop27`.`organization` `Organization_org_id` on((`CustomerContract_Contract`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`typology` `ContractType_contracttype_id_Typology` on((`CustomerContract_Contract`.`contracttype_id` = `ContractType_contracttype_id_Typology`.`id`))) join `itop27`.`organization` `Organization_provider_id` on((`CustomerContract_Contract`.`provider_id` = `Organization_provider_id`.`id`))) where (coalesce((`ContractType_contracttype_id_Typology`.`finalclass` = \'ContractType\'),1) and coalesce((`CustomerContract_Contract`.`finalclass` = \'CustomerContract\'),1))
