TYPE=VIEW
query=select distinct `lnkApplicationSolutionToBusinessProcess`.`id` AS `id`,`lnkApplicationSolutionToBusinessProcess`.`businessprocess_id` AS `businessprocess_id`,`BusinessProcess_businessprocess_id_FunctionalCI`.`name` AS `businessprocess_name`,`lnkApplicationSolutionToBusinessProcess`.`applicationsolution_id` AS `applicationsolution_id`,`ApplicationSolution_applicationsolution_id_FunctionalCI`.`name` AS `applicationsolution_name`,cast(concat(coalesce(`lnkApplicationSolutionToBusinessProcess`.`businessprocess_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkApplicationSolutionToBusinessProcess`.`applicationsolution_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`BusinessProcess_businessprocess_id_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `businessprocess_id_friendlyname`,coalesce((`BusinessProcess_businessprocess_id`.`status` = \'inactive\'),0) AS `businessprocess_id_obsolescence_flag`,cast(concat(coalesce(`ApplicationSolution_applicationsolution_id_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `applicationsolution_id_friendlyname`,coalesce((`ApplicationSolution_applicationsolution_id`.`status` = \'inactive\'),0) AS `applicationsolution_id_obsolescence_flag` from ((`itop27`.`lnkapplicationsolutiontobusinessprocess` `lnkApplicationSolutionToBusinessProcess` join (`itop27`.`businessprocess` `BusinessProcess_businessprocess_id` join `itop27`.`functionalci` `BusinessProcess_businessprocess_id_FunctionalCI` on((`BusinessProcess_businessprocess_id`.`id` = `BusinessProcess_businessprocess_id_FunctionalCI`.`id`))) on((`lnkApplicationSolutionToBusinessProcess`.`businessprocess_id` = `BusinessProcess_businessprocess_id`.`id`))) join (`itop27`.`applicationsolution` `ApplicationSolution_applicationsolution_id` join `itop27`.`functionalci` `ApplicationSolution_applicationsolution_id_FunctionalCI` on((`ApplicationSolution_applicationsolution_id`.`id` = `ApplicationSolution_applicationsolution_id_FunctionalCI`.`id`))) on((`lnkApplicationSolutionToBusinessProcess`.`applicationsolution_id` = `ApplicationSolution_applicationsolution_id`.`id`))) where 1
md5=facb0644c6fb10af5b4046ba90d42199
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `lnkApplicationSolutionToBusinessProcess`.`id` AS `id`,\n `lnkApplicationSolutionToBusinessProcess`.`businessprocess_id` AS `businessprocess_id`,\n `BusinessProcess_businessprocess_id_FunctionalCI`.`name` AS `businessprocess_name`,\n `lnkApplicationSolutionToBusinessProcess`.`applicationsolution_id` AS `applicationsolution_id`,\n `ApplicationSolution_applicationsolution_id_FunctionalCI`.`name` AS `applicationsolution_name`,\n CAST(CONCAT(COALESCE(`lnkApplicationSolutionToBusinessProcess`.`businessprocess_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`lnkApplicationSolutionToBusinessProcess`.`applicationsolution_id`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`BusinessProcess_businessprocess_id_FunctionalCI`.`name`, \'\')) AS CHAR) AS `businessprocess_id_friendlyname`,\n COALESCE((`BusinessProcess_businessprocess_id`.`status` = \'inactive\'), 0) AS `businessprocess_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`ApplicationSolution_applicationsolution_id_FunctionalCI`.`name`, \'\')) AS CHAR) AS `applicationsolution_id_friendlyname`,\n COALESCE((`ApplicationSolution_applicationsolution_id`.`status` = \'inactive\'), 0) AS `applicationsolution_id_obsolescence_flag`\n FROM \n   `lnkapplicationsolutiontobusinessprocess` AS `lnkApplicationSolutionToBusinessProcess`\n   INNER JOIN (\n      `businessprocess` AS `BusinessProcess_businessprocess_id` \n      INNER JOIN \n         `functionalci` AS `BusinessProcess_businessprocess_id_FunctionalCI`\n       ON `BusinessProcess_businessprocess_id`.`id` = `BusinessProcess_businessprocess_id_FunctionalCI`.`id`\n   ) ON `lnkApplicationSolutionToBusinessProcess`.`businessprocess_id` = `BusinessProcess_businessprocess_id`.`id`\n   INNER JOIN (\n      `applicationsolution` AS `ApplicationSolution_applicationsolution_id` \n      INNER JOIN \n         `functionalci` AS `ApplicationSolution_applicationsolution_id_FunctionalCI`\n       ON `ApplicationSolution_applicationsolution_id`.`id` = `ApplicationSolution_applicationsolution_id_FunctionalCI`.`id`\n   ) ON `lnkApplicationSolutionToBusinessProcess`.`applicationsolution_id` = `ApplicationSolution_applicationsolution_id`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `lnkApplicationSolutionToBusinessProcess`.`id` AS `id`,`lnkApplicationSolutionToBusinessProcess`.`businessprocess_id` AS `businessprocess_id`,`BusinessProcess_businessprocess_id_FunctionalCI`.`name` AS `businessprocess_name`,`lnkApplicationSolutionToBusinessProcess`.`applicationsolution_id` AS `applicationsolution_id`,`ApplicationSolution_applicationsolution_id_FunctionalCI`.`name` AS `applicationsolution_name`,cast(concat(coalesce(`lnkApplicationSolutionToBusinessProcess`.`businessprocess_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkApplicationSolutionToBusinessProcess`.`applicationsolution_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`BusinessProcess_businessprocess_id_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `businessprocess_id_friendlyname`,coalesce((`BusinessProcess_businessprocess_id`.`status` = \'inactive\'),0) AS `businessprocess_id_obsolescence_flag`,cast(concat(coalesce(`ApplicationSolution_applicationsolution_id_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `applicationsolution_id_friendlyname`,coalesce((`ApplicationSolution_applicationsolution_id`.`status` = \'inactive\'),0) AS `applicationsolution_id_obsolescence_flag` from ((`itop27`.`lnkapplicationsolutiontobusinessprocess` `lnkApplicationSolutionToBusinessProcess` join (`itop27`.`businessprocess` `BusinessProcess_businessprocess_id` join `itop27`.`functionalci` `BusinessProcess_businessprocess_id_FunctionalCI` on((`BusinessProcess_businessprocess_id`.`id` = `BusinessProcess_businessprocess_id_FunctionalCI`.`id`))) on((`lnkApplicationSolutionToBusinessProcess`.`businessprocess_id` = `BusinessProcess_businessprocess_id`.`id`))) join (`itop27`.`applicationsolution` `ApplicationSolution_applicationsolution_id` join `itop27`.`functionalci` `ApplicationSolution_applicationsolution_id_FunctionalCI` on((`ApplicationSolution_applicationsolution_id`.`id` = `ApplicationSolution_applicationsolution_id_FunctionalCI`.`id`))) on((`lnkApplicationSolutionToBusinessProcess`.`applicationsolution_id` = `ApplicationSolution_applicationsolution_id`.`id`))) where 1
