TYPE=VIEW
query=select distinct `Organization`.`id` AS `id`,`Organization`.`name` AS `name`,`Organization`.`code` AS `code`,`Organization`.`status` AS `status`,`Organization`.`parent_id` AS `parent_id`,`Organization_parent_id`.`name` AS `parent_name`,`Organization`.`deliverymodel_id` AS `deliverymodel_id`,`DeliveryModel_deliverymodel_id`.`name` AS `deliverymodel_name`,cast(concat(coalesce(`Organization`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`Organization`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`Organization`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_parent_id`.`name`,\'\')) as char charset utf8mb4) AS `parent_id_friendlyname`,coalesce((`Organization_parent_id`.`status` = \'inactive\'),0) AS `parent_id_obsolescence_flag`,cast(concat(coalesce(`DeliveryModel_deliverymodel_id`.`name`,\'\')) as char charset utf8mb4) AS `deliverymodel_id_friendlyname` from ((`itop27`.`organization` `Organization` left join `itop27`.`organization` `Organization_parent_id` on((`Organization`.`parent_id` = `Organization_parent_id`.`id`))) left join `itop27`.`deliverymodel` `DeliveryModel_deliverymodel_id` on((`Organization`.`deliverymodel_id` = `DeliveryModel_deliverymodel_id`.`id`))) where 1
md5=33016aee11e438b5022bb85598a3b775
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `Organization`.`id` AS `id`,\n `Organization`.`name` AS `name`,\n `Organization`.`code` AS `code`,\n `Organization`.`status` AS `status`,\n `Organization`.`parent_id` AS `parent_id`,\n `Organization_parent_id`.`name` AS `parent_name`,\n `Organization`.`deliverymodel_id` AS `deliverymodel_id`,\n `DeliveryModel_deliverymodel_id`.`name` AS `deliverymodel_name`,\n CAST(CONCAT(COALESCE(`Organization`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE((`Organization`.`status` = \'inactive\'), 0) AS `obsolescence_flag`,\n `Organization`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_parent_id`.`name`, \'\')) AS CHAR) AS `parent_id_friendlyname`,\n COALESCE((`Organization_parent_id`.`status` = \'inactive\'), 0) AS `parent_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`DeliveryModel_deliverymodel_id`.`name`, \'\')) AS CHAR) AS `deliverymodel_id_friendlyname`\n FROM \n   `organization` AS `Organization`\n   LEFT JOIN \n      `organization` AS `Organization_parent_id`\n    ON `Organization`.`parent_id` = `Organization_parent_id`.`id`\n   LEFT JOIN \n      `deliverymodel` AS `DeliveryModel_deliverymodel_id`\n    ON `Organization`.`deliverymodel_id` = `DeliveryModel_deliverymodel_id`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `Organization`.`id` AS `id`,`Organization`.`name` AS `name`,`Organization`.`code` AS `code`,`Organization`.`status` AS `status`,`Organization`.`parent_id` AS `parent_id`,`Organization_parent_id`.`name` AS `parent_name`,`Organization`.`deliverymodel_id` AS `deliverymodel_id`,`DeliveryModel_deliverymodel_id`.`name` AS `deliverymodel_name`,cast(concat(coalesce(`Organization`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`Organization`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`Organization`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_parent_id`.`name`,\'\')) as char charset utf8mb4) AS `parent_id_friendlyname`,coalesce((`Organization_parent_id`.`status` = \'inactive\'),0) AS `parent_id_obsolescence_flag`,cast(concat(coalesce(`DeliveryModel_deliverymodel_id`.`name`,\'\')) as char charset utf8mb4) AS `deliverymodel_id_friendlyname` from ((`itop27`.`organization` `Organization` left join `itop27`.`organization` `Organization_parent_id` on((`Organization`.`parent_id` = `Organization_parent_id`.`id`))) left join `itop27`.`deliverymodel` `DeliveryModel_deliverymodel_id` on((`Organization`.`deliverymodel_id` = `DeliveryModel_deliverymodel_id`.`id`))) where 1
