TYPE=VIEW
query=select distinct `Person`.`id` AS `id`,`Person_Contact`.`name` AS `name`,`Person_Contact`.`status` AS `status`,`Person_Contact`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `org_name`,`Person_Contact`.`email` AS `email`,`Person_Contact`.`phone` AS `phone`,`Person_Contact`.`notify` AS `notify`,`Person_Contact`.`function` AS `function`,`Person`.`picture_mimetype` AS `picture`,`Person`.`first_name` AS `first_name`,`Person`.`employee_number` AS `employee_number`,`Person`.`mobile_phone` AS `mobile_phone`,`Person`.`location_id` AS `location_id`,`Location_location_id`.`name` AS `location_name`,`Person`.`manager_id` AS `manager_id`,`Person_manager_id_Contact`.`name` AS `manager_name`,`Person_Contact`.`finalclass` AS `finalclass`,cast(concat(coalesce(`Person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Person_Contact`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`Person_Contact`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`Person_Contact`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Location_location_id`.`name`,\'\')) as char charset utf8mb4) AS `location_id_friendlyname`,coalesce((`Location_location_id`.`status` = \'inactive\'),0) AS `location_id_obsolescence_flag`,cast(concat(coalesce(`Person_manager_id`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Person_manager_id_Contact`.`name`,\'\')) as char charset utf8mb4) AS `manager_id_friendlyname`,coalesce((`Person_manager_id_Contact`.`status` = \'inactive\'),0) AS `manager_id_obsolescence_flag`,`Person`.`picture_data` AS `Personpicture_data`,`Person`.`picture_filename` AS `Personpicture_filename` from (((`itop27`.`person` `Person` left join `itop27`.`location` `Location_location_id` on((`Person`.`location_id` = `Location_location_id`.`id`))) left join (`itop27`.`person` `Person_manager_id` join `itop27`.`contact` `Person_manager_id_Contact` on((`Person_manager_id`.`id` = `Person_manager_id_Contact`.`id`))) on((`Person`.`manager_id` = `Person_manager_id`.`id`))) join (`itop27`.`contact` `Person_Contact` join `itop27`.`organization` `Organization_org_id` on((`Person_Contact`.`org_id` = `Organization_org_id`.`id`))) on((`Person`.`id` = `Person_Contact`.`id`))) where 1
md5=5c7010a1c8b798c141781c1da001d604
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `Person`.`id` AS `id`,\n `Person_Contact`.`name` AS `name`,\n `Person_Contact`.`status` AS `status`,\n `Person_Contact`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `org_name`,\n `Person_Contact`.`email` AS `email`,\n `Person_Contact`.`phone` AS `phone`,\n `Person_Contact`.`notify` AS `notify`,\n `Person_Contact`.`function` AS `function`,\n `Person`.`picture_mimetype` AS `picture`,\n `Person`.`first_name` AS `first_name`,\n `Person`.`employee_number` AS `employee_number`,\n `Person`.`mobile_phone` AS `mobile_phone`,\n `Person`.`location_id` AS `location_id`,\n `Location_location_id`.`name` AS `location_name`,\n `Person`.`manager_id` AS `manager_id`,\n `Person_manager_id_Contact`.`name` AS `manager_name`,\n `Person_Contact`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`Person`.`first_name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Person_Contact`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE((`Person_Contact`.`status` = \'inactive\'), 0) AS `obsolescence_flag`,\n `Person_Contact`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`Location_location_id`.`name`, \'\')) AS CHAR) AS `location_id_friendlyname`,\n COALESCE((`Location_location_id`.`status` = \'inactive\'), 0) AS `location_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`Person_manager_id`.`first_name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Person_manager_id_Contact`.`name`, \'\')) AS CHAR) AS `manager_id_friendlyname`,\n COALESCE((`Person_manager_id_Contact`.`status` = \'inactive\'), 0) AS `manager_id_obsolescence_flag`,\n `Person`.`picture_data` AS `Personpicture_data`,\n `Person`.`picture_filename` AS `Personpicture_filename`\n FROM \n   `person` AS `Person`\n   LEFT JOIN \n      `location` AS `Location_location_id`\n    ON `Person`.`location_id` = `Location_location_id`.`id`\n   LEFT JOIN (\n      `person` AS `Person_manager_id` \n      INNER JOIN \n         `contact` AS `Person_manager_id_Contact`\n       ON `Person_manager_id`.`id` = `Person_manager_id_Contact`.`id`\n   ) ON `Person`.`manager_id` = `Person_manager_id`.`id`\n   INNER JOIN (\n      `contact` AS `Person_Contact` \n      INNER JOIN \n         `organization` AS `Organization_org_id`\n       ON `Person_Contact`.`org_id` = `Organization_org_id`.`id`\n   ) ON `Person`.`id` = `Person_Contact`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `Person`.`id` AS `id`,`Person_Contact`.`name` AS `name`,`Person_Contact`.`status` AS `status`,`Person_Contact`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `org_name`,`Person_Contact`.`email` AS `email`,`Person_Contact`.`phone` AS `phone`,`Person_Contact`.`notify` AS `notify`,`Person_Contact`.`function` AS `function`,`Person`.`picture_mimetype` AS `picture`,`Person`.`first_name` AS `first_name`,`Person`.`employee_number` AS `employee_number`,`Person`.`mobile_phone` AS `mobile_phone`,`Person`.`location_id` AS `location_id`,`Location_location_id`.`name` AS `location_name`,`Person`.`manager_id` AS `manager_id`,`Person_manager_id_Contact`.`name` AS `manager_name`,`Person_Contact`.`finalclass` AS `finalclass`,cast(concat(coalesce(`Person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Person_Contact`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`Person_Contact`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`Person_Contact`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Location_location_id`.`name`,\'\')) as char charset utf8mb4) AS `location_id_friendlyname`,coalesce((`Location_location_id`.`status` = \'inactive\'),0) AS `location_id_obsolescence_flag`,cast(concat(coalesce(`Person_manager_id`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Person_manager_id_Contact`.`name`,\'\')) as char charset utf8mb4) AS `manager_id_friendlyname`,coalesce((`Person_manager_id_Contact`.`status` = \'inactive\'),0) AS `manager_id_obsolescence_flag`,`Person`.`picture_data` AS `Personpicture_data`,`Person`.`picture_filename` AS `Personpicture_filename` from (((`itop27`.`person` `Person` left join `itop27`.`location` `Location_location_id` on((`Person`.`location_id` = `Location_location_id`.`id`))) left join (`itop27`.`person` `Person_manager_id` join `itop27`.`contact` `Person_manager_id_Contact` on((`Person_manager_id`.`id` = `Person_manager_id_Contact`.`id`))) on((`Person`.`manager_id` = `Person_manager_id`.`id`))) join (`itop27`.`contact` `Person_Contact` join `itop27`.`organization` `Organization_org_id` on((`Person_Contact`.`org_id` = `Organization_org_id`.`id`))) on((`Person`.`id` = `Person_Contact`.`id`))) where 1
