TYPE=VIEW
query=select distinct `Service`.`id` AS `id`,`Service`.`name` AS `name`,`Service`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`Service`.`servicefamily_id` AS `servicefamily_id`,`ServiceFamily_servicefamily_id`.`name` AS `servicefamily_name`,`Service`.`description` AS `description`,`Service`.`status` AS `status`,`Service`.`icon_mimetype` AS `icon`,cast(concat(coalesce(`Service`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`ServiceFamily_servicefamily_id`.`name`,\'\')) as char charset utf8mb4) AS `servicefamily_id_friendlyname`,`Service`.`icon_data` AS `Serviceicon_data`,`Service`.`icon_filename` AS `Serviceicon_filename` from ((`itop27`.`service` `Service` join `itop27`.`organization` `Organization_org_id` on((`Service`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`servicefamily` `ServiceFamily_servicefamily_id` on((`Service`.`servicefamily_id` = `ServiceFamily_servicefamily_id`.`id`))) where 1
md5=94331ed3c0d2fb44f92ef5756344592e
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `Service`.`id` AS `id`,\n `Service`.`name` AS `name`,\n `Service`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `organization_name`,\n `Service`.`servicefamily_id` AS `servicefamily_id`,\n `ServiceFamily_servicefamily_id`.`name` AS `servicefamily_name`,\n `Service`.`description` AS `description`,\n `Service`.`status` AS `status`,\n `Service`.`icon_mimetype` AS `icon`,\n CAST(CONCAT(COALESCE(`Service`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`ServiceFamily_servicefamily_id`.`name`, \'\')) AS CHAR) AS `servicefamily_id_friendlyname`,\n `Service`.`icon_data` AS `Serviceicon_data`,\n `Service`.`icon_filename` AS `Serviceicon_filename`\n FROM \n   `service` AS `Service`\n   INNER JOIN \n      `organization` AS `Organization_org_id`\n    ON `Service`.`org_id` = `Organization_org_id`.`id`\n   LEFT JOIN \n      `servicefamily` AS `ServiceFamily_servicefamily_id`\n    ON `Service`.`servicefamily_id` = `ServiceFamily_servicefamily_id`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `Service`.`id` AS `id`,`Service`.`name` AS `name`,`Service`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`Service`.`servicefamily_id` AS `servicefamily_id`,`ServiceFamily_servicefamily_id`.`name` AS `servicefamily_name`,`Service`.`description` AS `description`,`Service`.`status` AS `status`,`Service`.`icon_mimetype` AS `icon`,cast(concat(coalesce(`Service`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`ServiceFamily_servicefamily_id`.`name`,\'\')) as char charset utf8mb4) AS `servicefamily_id_friendlyname`,`Service`.`icon_data` AS `Serviceicon_data`,`Service`.`icon_filename` AS `Serviceicon_filename` from ((`itop27`.`service` `Service` join `itop27`.`organization` `Organization_org_id` on((`Service`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`servicefamily` `ServiceFamily_servicefamily_id` on((`Service`.`servicefamily_id` = `ServiceFamily_servicefamily_id`.`id`))) where 1
