TYPE=VIEW
query=select distinct `Licence`.`id` AS `id`,`Licence`.`name` AS `name`,`Licence`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`Licence`.`usage_limit` AS `usage_limit`,`Licence`.`description` AS `description`,`Licence`.`start_date` AS `start_date`,`Licence`.`end_date` AS `end_date`,`Licence`.`licence_key` AS `licence_key`,`Licence`.`perpetual` AS `perpetual`,`Licence`.`finalclass` AS `finalclass`,cast(concat(coalesce(`Licence`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(((`Licence`.`perpetual` = \'no\') and (isnull(`Licence`.`end_date`) = 0) and (`Licence`.`end_date` < date_format((now() - interval 15 month),\'%Y-%m-%d 00:00:00\'))),0) AS `obsolescence_flag`,`Licence`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from (`itop27`.`licence` `Licence` join `itop27`.`organization` `Organization_org_id` on((`Licence`.`org_id` = `Organization_org_id`.`id`))) where 1
md5=45bdb61785e5d0e6f4aeae3e65b26118
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `Licence`.`id` AS `id`,\n `Licence`.`name` AS `name`,\n `Licence`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `organization_name`,\n `Licence`.`usage_limit` AS `usage_limit`,\n `Licence`.`description` AS `description`,\n `Licence`.`start_date` AS `start_date`,\n `Licence`.`end_date` AS `end_date`,\n `Licence`.`licence_key` AS `licence_key`,\n `Licence`.`perpetual` AS `perpetual`,\n `Licence`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`Licence`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE((((`Licence`.`perpetual` = \'no\') AND (ISNULL(`Licence`.`end_date`) = 0)) AND (`Licence`.`end_date` < DATE_FORMAT(DATE_SUB(NOW(), INTERVAL 15 MONTH), \'%Y-%m-%d 00:00:00\'))), 0) AS `obsolescence_flag`,\n `Licence`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`\n FROM \n   `licence` AS `Licence`\n   INNER JOIN \n      `organization` AS `Organization_org_id`\n    ON `Licence`.`org_id` = `Organization_org_id`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `Licence`.`id` AS `id`,`Licence`.`name` AS `name`,`Licence`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`Licence`.`usage_limit` AS `usage_limit`,`Licence`.`description` AS `description`,`Licence`.`start_date` AS `start_date`,`Licence`.`end_date` AS `end_date`,`Licence`.`licence_key` AS `licence_key`,`Licence`.`perpetual` AS `perpetual`,`Licence`.`finalclass` AS `finalclass`,cast(concat(coalesce(`Licence`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(((`Licence`.`perpetual` = \'no\') and (isnull(`Licence`.`end_date`) = 0) and (`Licence`.`end_date` < date_format((now() - interval 15 month),\'%Y-%m-%d 00:00:00\'))),0) AS `obsolescence_flag`,`Licence`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from (`itop27`.`licence` `Licence` join `itop27`.`organization` `Organization_org_id` on((`Licence`.`org_id` = `Organization_org_id`.`id`))) where 1
