TYPE=VIEW
query=select distinct `TagSetFieldData`.`id` AS `id`,`TagSetFieldData`.`code` AS `code`,`TagSetFieldData`.`label` AS `label`,`TagSetFieldData`.`description` AS `description`,`TagSetFieldData`.`obj_class` AS `obj_class`,`TagSetFieldData`.`obj_attcode` AS `obj_attcode`,`TagSetFieldData`.`finalclass` AS `finalclass`,cast(concat(coalesce(`TagSetFieldData`.`label`,\'\')) as char charset utf8mb4) AS `friendlyname` from `itop27`.`priv_tagfielddata` `TagSetFieldData` where 1
md5=3e0c76e292380b827247cb4d98858a38
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `TagSetFieldData`.`id` AS `id`,\n `TagSetFieldData`.`code` AS `code`,\n `TagSetFieldData`.`label` AS `label`,\n `TagSetFieldData`.`description` AS `description`,\n `TagSetFieldData`.`obj_class` AS `obj_class`,\n `TagSetFieldData`.`obj_attcode` AS `obj_attcode`,\n `TagSetFieldData`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`TagSetFieldData`.`label`, \'\')) AS CHAR) AS `friendlyname`\n FROM \n   `priv_tagfielddata` AS `TagSetFieldData`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `TagSetFieldData`.`id` AS `id`,`TagSetFieldData`.`code` AS `code`,`TagSetFieldData`.`label` AS `label`,`TagSetFieldData`.`description` AS `description`,`TagSetFieldData`.`obj_class` AS `obj_class`,`TagSetFieldData`.`obj_attcode` AS `obj_attcode`,`TagSetFieldData`.`finalclass` AS `finalclass`,cast(concat(coalesce(`TagSetFieldData`.`label`,\'\')) as char charset utf8mb4) AS `friendlyname` from `itop27`.`priv_tagfielddata` `TagSetFieldData` where 1
