TYPE=VIEW
query=select distinct `WorkOrder`.`id` AS `id`,`WorkOrder`.`name` AS `name`,`WorkOrder`.`status` AS `status`,`WorkOrder`.`description` AS `description`,`WorkOrder`.`ticket_id` AS `ticket_id`,`Ticket_ticket_id`.`ref` AS `ticket_ref`,`WorkOrder`.`team_id` AS `team_id`,`Team_team_id_Contact`.`email` AS `team_name`,`WorkOrder`.`owner_id` AS `agent_id`,`Person_agent_id_Contact`.`email` AS `agent_email`,`WorkOrder`.`start_date` AS `start_date`,`WorkOrder`.`end_date` AS `end_date`,`WorkOrder`.`log` AS `log`,cast(concat(coalesce(`WorkOrder`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Ticket_ticket_id`.`ref`,\'\')) as char charset utf8mb4) AS `ticket_id_friendlyname`,`Ticket_ticket_id`.`finalclass` AS `ticket_id_finalclass_recall`,cast(concat(coalesce(`Team_team_id_Contact`.`name`,\'\')) as char charset utf8mb4) AS `team_id_friendlyname`,coalesce((`Team_team_id_Contact`.`status` = \'inactive\'),0) AS `team_id_obsolescence_flag`,cast(concat(coalesce(`Person_agent_id`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Person_agent_id_Contact`.`name`,\'\')) as char charset utf8mb4) AS `agent_id_friendlyname`,coalesce((`Person_agent_id_Contact`.`status` = \'inactive\'),0) AS `agent_id_obsolescence_flag`,`WorkOrder`.`log_index` AS `WorkOrderlog_index` from (((`itop27`.`workorder` `WorkOrder` join `itop27`.`ticket` `Ticket_ticket_id` on((`WorkOrder`.`ticket_id` = `Ticket_ticket_id`.`id`))) join `itop27`.`contact` `Team_team_id_Contact` on((`WorkOrder`.`team_id` = `Team_team_id_Contact`.`id`))) left join (`itop27`.`person` `Person_agent_id` join `itop27`.`contact` `Person_agent_id_Contact` on((`Person_agent_id`.`id` = `Person_agent_id_Contact`.`id`))) on((`WorkOrder`.`owner_id` = `Person_agent_id`.`id`))) where coalesce((`Team_team_id_Contact`.`finalclass` = \'Team\'),1)
md5=4dd83bb885fa4d0db19fd47ef82e5b59
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `WorkOrder`.`id` AS `id`,\n `WorkOrder`.`name` AS `name`,\n `WorkOrder`.`status` AS `status`,\n `WorkOrder`.`description` AS `description`,\n `WorkOrder`.`ticket_id` AS `ticket_id`,\n `Ticket_ticket_id`.`ref` AS `ticket_ref`,\n `WorkOrder`.`team_id` AS `team_id`,\n `Team_team_id_Contact`.`email` AS `team_name`,\n `WorkOrder`.`owner_id` AS `agent_id`,\n `Person_agent_id_Contact`.`email` AS `agent_email`,\n `WorkOrder`.`start_date` AS `start_date`,\n `WorkOrder`.`end_date` AS `end_date`,\n `WorkOrder`.`log` AS `log`,\n CAST(CONCAT(COALESCE(`WorkOrder`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`Ticket_ticket_id`.`ref`, \'\')) AS CHAR) AS `ticket_id_friendlyname`,\n `Ticket_ticket_id`.`finalclass` AS `ticket_id_finalclass_recall`,\n CAST(CONCAT(COALESCE(`Team_team_id_Contact`.`name`, \'\')) AS CHAR) AS `team_id_friendlyname`,\n COALESCE((`Team_team_id_Contact`.`status` = \'inactive\'), 0) AS `team_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`Person_agent_id`.`first_name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Person_agent_id_Contact`.`name`, \'\')) AS CHAR) AS `agent_id_friendlyname`,\n COALESCE((`Person_agent_id_Contact`.`status` = \'inactive\'), 0) AS `agent_id_obsolescence_flag`,\n `WorkOrder`.`log_index` AS `WorkOrderlog_index`\n FROM \n   `workorder` AS `WorkOrder`\n   INNER JOIN \n      `ticket` AS `Ticket_ticket_id`\n    ON `WorkOrder`.`ticket_id` = `Ticket_ticket_id`.`id`\n   INNER JOIN \n      `contact` AS `Team_team_id_Contact`\n    ON `WorkOrder`.`team_id` = `Team_team_id_Contact`.`id`\n   LEFT JOIN (\n      `person` AS `Person_agent_id` \n      INNER JOIN \n         `contact` AS `Person_agent_id_Contact`\n       ON `Person_agent_id`.`id` = `Person_agent_id_Contact`.`id`\n   ) ON `WorkOrder`.`owner_id` = `Person_agent_id`.`id`\n WHERE COALESCE((`Team_team_id_Contact`.`finalclass` IN (\'Team\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `WorkOrder`.`id` AS `id`,`WorkOrder`.`name` AS `name`,`WorkOrder`.`status` AS `status`,`WorkOrder`.`description` AS `description`,`WorkOrder`.`ticket_id` AS `ticket_id`,`Ticket_ticket_id`.`ref` AS `ticket_ref`,`WorkOrder`.`team_id` AS `team_id`,`Team_team_id_Contact`.`email` AS `team_name`,`WorkOrder`.`owner_id` AS `agent_id`,`Person_agent_id_Contact`.`email` AS `agent_email`,`WorkOrder`.`start_date` AS `start_date`,`WorkOrder`.`end_date` AS `end_date`,`WorkOrder`.`log` AS `log`,cast(concat(coalesce(`WorkOrder`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Ticket_ticket_id`.`ref`,\'\')) as char charset utf8mb4) AS `ticket_id_friendlyname`,`Ticket_ticket_id`.`finalclass` AS `ticket_id_finalclass_recall`,cast(concat(coalesce(`Team_team_id_Contact`.`name`,\'\')) as char charset utf8mb4) AS `team_id_friendlyname`,coalesce((`Team_team_id_Contact`.`status` = \'inactive\'),0) AS `team_id_obsolescence_flag`,cast(concat(coalesce(`Person_agent_id`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Person_agent_id_Contact`.`name`,\'\')) as char charset utf8mb4) AS `agent_id_friendlyname`,coalesce((`Person_agent_id_Contact`.`status` = \'inactive\'),0) AS `agent_id_obsolescence_flag`,`WorkOrder`.`log_index` AS `WorkOrderlog_index` from (((`itop27`.`workorder` `WorkOrder` join `itop27`.`ticket` `Ticket_ticket_id` on((`WorkOrder`.`ticket_id` = `Ticket_ticket_id`.`id`))) join `itop27`.`contact` `Team_team_id_Contact` on((`WorkOrder`.`team_id` = `Team_team_id_Contact`.`id`))) left join (`itop27`.`person` `Person_agent_id` join `itop27`.`contact` `Person_agent_id_Contact` on((`Person_agent_id`.`id` = `Person_agent_id_Contact`.`id`))) on((`WorkOrder`.`owner_id` = `Person_agent_id`.`id`))) where coalesce((`Team_team_id_Contact`.`finalclass` = \'Team\'),1)
