TYPE=VIEW
query=select distinct `LogicalVolume`.`id` AS `id`,`LogicalVolume`.`name` AS `name`,`LogicalVolume`.`lun_id` AS `lun_id`,`LogicalVolume`.`description` AS `description`,`LogicalVolume`.`raid_level` AS `raid_level`,`LogicalVolume`.`size` AS `size`,`LogicalVolume`.`storagesystem_id` AS `storagesystem_id`,`StorageSystem_storagesystem_id_FunctionalCI`.`name` AS `storagesystem_name`,cast(concat(coalesce(`StorageSystem_storagesystem_id_FunctionalCI`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`LogicalVolume`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`StorageSystem_storagesystem_id_PhysicalDevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`LogicalVolume`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`StorageSystem_storagesystem_id_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `storagesystem_id_friendlyname`,coalesce((`StorageSystem_storagesystem_id_PhysicalDevice`.`status` = \'obsolete\'),0) AS `storagesystem_id_obsolescence_flag` from (`itop27`.`logicalvolume` `LogicalVolume` join (`itop27`.`physicaldevice` `StorageSystem_storagesystem_id_PhysicalDevice` join `itop27`.`functionalci` `StorageSystem_storagesystem_id_FunctionalCI` on((`StorageSystem_storagesystem_id_PhysicalDevice`.`id` = `StorageSystem_storagesystem_id_FunctionalCI`.`id`))) on((`LogicalVolume`.`storagesystem_id` = `StorageSystem_storagesystem_id_PhysicalDevice`.`id`))) where coalesce((`StorageSystem_storagesystem_id_PhysicalDevice`.`finalclass` = \'StorageSystem\'),1)
md5=d25c777ecbfa2665aaad0858808ee13b
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `LogicalVolume`.`id` AS `id`,\n `LogicalVolume`.`name` AS `name`,\n `LogicalVolume`.`lun_id` AS `lun_id`,\n `LogicalVolume`.`description` AS `description`,\n `LogicalVolume`.`raid_level` AS `raid_level`,\n `LogicalVolume`.`size` AS `size`,\n `LogicalVolume`.`storagesystem_id` AS `storagesystem_id`,\n `StorageSystem_storagesystem_id_FunctionalCI`.`name` AS `storagesystem_name`,\n CAST(CONCAT(COALESCE(`StorageSystem_storagesystem_id_FunctionalCI`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`LogicalVolume`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE(COALESCE((`StorageSystem_storagesystem_id_PhysicalDevice`.`status` = \'obsolete\'), 0), 0) AS `obsolescence_flag`,\n `LogicalVolume`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`StorageSystem_storagesystem_id_FunctionalCI`.`name`, \'\')) AS CHAR) AS `storagesystem_id_friendlyname`,\n COALESCE((`StorageSystem_storagesystem_id_PhysicalDevice`.`status` = \'obsolete\'), 0) AS `storagesystem_id_obsolescence_flag`\n FROM \n   `logicalvolume` AS `LogicalVolume`\n   INNER JOIN (\n      `physicaldevice` AS `StorageSystem_storagesystem_id_PhysicalDevice` \n      INNER JOIN \n         `functionalci` AS `StorageSystem_storagesystem_id_FunctionalCI`\n       ON `StorageSystem_storagesystem_id_PhysicalDevice`.`id` = `StorageSystem_storagesystem_id_FunctionalCI`.`id`\n   ) ON `LogicalVolume`.`storagesystem_id` = `StorageSystem_storagesystem_id_PhysicalDevice`.`id`\n WHERE COALESCE((`StorageSystem_storagesystem_id_PhysicalDevice`.`finalclass` IN (\'StorageSystem\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `LogicalVolume`.`id` AS `id`,`LogicalVolume`.`name` AS `name`,`LogicalVolume`.`lun_id` AS `lun_id`,`LogicalVolume`.`description` AS `description`,`LogicalVolume`.`raid_level` AS `raid_level`,`LogicalVolume`.`size` AS `size`,`LogicalVolume`.`storagesystem_id` AS `storagesystem_id`,`StorageSystem_storagesystem_id_FunctionalCI`.`name` AS `storagesystem_name`,cast(concat(coalesce(`StorageSystem_storagesystem_id_FunctionalCI`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`LogicalVolume`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`StorageSystem_storagesystem_id_PhysicalDevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`LogicalVolume`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`StorageSystem_storagesystem_id_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `storagesystem_id_friendlyname`,coalesce((`StorageSystem_storagesystem_id_PhysicalDevice`.`status` = \'obsolete\'),0) AS `storagesystem_id_obsolescence_flag` from (`itop27`.`logicalvolume` `LogicalVolume` join (`itop27`.`physicaldevice` `StorageSystem_storagesystem_id_PhysicalDevice` join `itop27`.`functionalci` `StorageSystem_storagesystem_id_FunctionalCI` on((`StorageSystem_storagesystem_id_PhysicalDevice`.`id` = `StorageSystem_storagesystem_id_FunctionalCI`.`id`))) on((`LogicalVolume`.`storagesystem_id` = `StorageSystem_storagesystem_id_PhysicalDevice`.`id`))) where coalesce((`StorageSystem_storagesystem_id_PhysicalDevice`.`finalclass` = \'StorageSystem\'),1)
