TYPE=VIEW
query=select distinct `lnkDocumentToService`.`id` AS `id`,`lnkDocumentToService`.`service_id` AS `service_id`,`Service_service_id`.`name` AS `service_name`,`lnkDocumentToService`.`document_id` AS `document_id`,`Document_document_id`.`name` AS `document_name`,cast(concat(coalesce(`lnkDocumentToService`.`service_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkDocumentToService`.`document_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Service_service_id`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,if((`Document_document_id`.`finalclass` = \'Document\'),cast(concat(coalesce(\'Document\',\'\')) as char charset utf8mb4),cast(concat(coalesce(`Document_document_id`.`name`,\'\')) as char charset utf8mb4)) AS `document_id_friendlyname`,`Document_document_id`.`finalclass` AS `document_id_finalclass_recall`,coalesce((`Document_document_id`.`status` = \'obsolete\'),0) AS `document_id_obsolescence_flag` from ((`itop27`.`lnkdocumenttoservice` `lnkDocumentToService` join `itop27`.`service` `Service_service_id` on((`lnkDocumentToService`.`service_id` = `Service_service_id`.`id`))) join `itop27`.`document` `Document_document_id` on((`lnkDocumentToService`.`document_id` = `Document_document_id`.`id`))) where 1
md5=fa598299fe2da101bb87cce881207019
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `lnkDocumentToService`.`id` AS `id`,\n `lnkDocumentToService`.`service_id` AS `service_id`,\n `Service_service_id`.`name` AS `service_name`,\n `lnkDocumentToService`.`document_id` AS `document_id`,\n `Document_document_id`.`name` AS `document_name`,\n CAST(CONCAT(COALESCE(`lnkDocumentToService`.`service_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`lnkDocumentToService`.`document_id`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`Service_service_id`.`name`, \'\')) AS CHAR) AS `service_id_friendlyname`,\n IF((`Document_document_id`.`finalclass` IN (\'Document\')), CAST(CONCAT(COALESCE(\'Document\', \'\')) AS CHAR), CAST(CONCAT(COALESCE(`Document_document_id`.`name`, \'\')) AS CHAR)) AS `document_id_friendlyname`,\n `Document_document_id`.`finalclass` AS `document_id_finalclass_recall`,\n COALESCE((`Document_document_id`.`status` = \'obsolete\'), 0) AS `document_id_obsolescence_flag`\n FROM \n   `lnkdocumenttoservice` AS `lnkDocumentToService`\n   INNER JOIN \n      `service` AS `Service_service_id`\n    ON `lnkDocumentToService`.`service_id` = `Service_service_id`.`id`\n   INNER JOIN \n      `document` AS `Document_document_id`\n    ON `lnkDocumentToService`.`document_id` = `Document_document_id`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `lnkDocumentToService`.`id` AS `id`,`lnkDocumentToService`.`service_id` AS `service_id`,`Service_service_id`.`name` AS `service_name`,`lnkDocumentToService`.`document_id` AS `document_id`,`Document_document_id`.`name` AS `document_name`,cast(concat(coalesce(`lnkDocumentToService`.`service_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkDocumentToService`.`document_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Service_service_id`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,if((`Document_document_id`.`finalclass` = \'Document\'),cast(concat(coalesce(\'Document\',\'\')) as char charset utf8mb4),cast(concat(coalesce(`Document_document_id`.`name`,\'\')) as char charset utf8mb4)) AS `document_id_friendlyname`,`Document_document_id`.`finalclass` AS `document_id_finalclass_recall`,coalesce((`Document_document_id`.`status` = \'obsolete\'),0) AS `document_id_obsolescence_flag` from ((`itop27`.`lnkdocumenttoservice` `lnkDocumentToService` join `itop27`.`service` `Service_service_id` on((`lnkDocumentToService`.`service_id` = `Service_service_id`.`id`))) join `itop27`.`document` `Document_document_id` on((`lnkDocumentToService`.`document_id` = `Document_document_id`.`id`))) where 1
