TYPE=VIEW
query=select distinct `DocumentNote`.`id` AS `id`,`DocumentNote_Document`.`name` AS `name`,`DocumentNote_Document`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `org_name`,`DocumentNote_Document`.`documenttype_id` AS `documenttype_id`,`DocumentType_documenttype_id_Typology`.`name` AS `documenttype_name`,`DocumentNote_Document`.`version` AS `version`,`DocumentNote_Document`.`description` AS `description`,`DocumentNote_Document`.`status` AS `status`,`DocumentNote`.`text` AS `text`,`DocumentNote_Document`.`finalclass` AS `finalclass`,cast(concat(coalesce(`DocumentNote_Document`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`DocumentNote_Document`.`status` = \'obsolete\'),0) AS `obsolescence_flag`,`DocumentNote_Document`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`DocumentType_documenttype_id_Typology`.`name`,\'\')) as char charset utf8mb4) AS `documenttype_id_friendlyname` from (`itop27`.`documentnote` `DocumentNote` join ((`itop27`.`document` `DocumentNote_Document` join `itop27`.`organization` `Organization_org_id` on((`DocumentNote_Document`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`typology` `DocumentType_documenttype_id_Typology` on((`DocumentNote_Document`.`documenttype_id` = `DocumentType_documenttype_id_Typology`.`id`))) on((`DocumentNote`.`id` = `DocumentNote_Document`.`id`))) where coalesce((`DocumentType_documenttype_id_Typology`.`finalclass` = \'DocumentType\'),1)
md5=9976216dd8f5c77046a2d015eb70f3cd
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `DocumentNote`.`id` AS `id`,\n `DocumentNote_Document`.`name` AS `name`,\n `DocumentNote_Document`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `org_name`,\n `DocumentNote_Document`.`documenttype_id` AS `documenttype_id`,\n `DocumentType_documenttype_id_Typology`.`name` AS `documenttype_name`,\n `DocumentNote_Document`.`version` AS `version`,\n `DocumentNote_Document`.`description` AS `description`,\n `DocumentNote_Document`.`status` AS `status`,\n `DocumentNote`.`text` AS `text`,\n `DocumentNote_Document`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`DocumentNote_Document`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE((`DocumentNote_Document`.`status` = \'obsolete\'), 0) AS `obsolescence_flag`,\n `DocumentNote_Document`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`DocumentType_documenttype_id_Typology`.`name`, \'\')) AS CHAR) AS `documenttype_id_friendlyname`\n FROM \n   `documentnote` AS `DocumentNote`\n   INNER JOIN (\n      `document` AS `DocumentNote_Document` \n      INNER JOIN \n         `organization` AS `Organization_org_id`\n       ON `DocumentNote_Document`.`org_id` = `Organization_org_id`.`id`\n      LEFT JOIN \n         `typology` AS `DocumentType_documenttype_id_Typology`\n       ON `DocumentNote_Document`.`documenttype_id` = `DocumentType_documenttype_id_Typology`.`id`\n   ) ON `DocumentNote`.`id` = `DocumentNote_Document`.`id`\n WHERE COALESCE((`DocumentType_documenttype_id_Typology`.`finalclass` IN (\'DocumentType\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `DocumentNote`.`id` AS `id`,`DocumentNote_Document`.`name` AS `name`,`DocumentNote_Document`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `org_name`,`DocumentNote_Document`.`documenttype_id` AS `documenttype_id`,`DocumentType_documenttype_id_Typology`.`name` AS `documenttype_name`,`DocumentNote_Document`.`version` AS `version`,`DocumentNote_Document`.`description` AS `description`,`DocumentNote_Document`.`status` AS `status`,`DocumentNote`.`text` AS `text`,`DocumentNote_Document`.`finalclass` AS `finalclass`,cast(concat(coalesce(`DocumentNote_Document`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`DocumentNote_Document`.`status` = \'obsolete\'),0) AS `obsolescence_flag`,`DocumentNote_Document`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`DocumentType_documenttype_id_Typology`.`name`,\'\')) as char charset utf8mb4) AS `documenttype_id_friendlyname` from (`itop27`.`documentnote` `DocumentNote` join ((`itop27`.`document` `DocumentNote_Document` join `itop27`.`organization` `Organization_org_id` on((`DocumentNote_Document`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`typology` `DocumentType_documenttype_id_Typology` on((`DocumentNote_Document`.`documenttype_id` = `DocumentType_documenttype_id_Typology`.`id`))) on((`DocumentNote`.`id` = `DocumentNote_Document`.`id`))) where coalesce((`DocumentType_documenttype_id_Typology`.`finalclass` = \'DocumentType\'),1)
