TYPE=VIEW
query=select distinct `Contract`.`id` AS `id`,`Contract`.`name` AS `name`,`Contract`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`Contract`.`description` AS `description`,`Contract`.`start_date` AS `start_date`,`Contract`.`end_date` AS `end_date`,`Contract`.`cost` AS `cost`,`Contract`.`cost_currency` AS `cost_currency`,`Contract`.`contracttype_id` AS `contracttype_id`,`ContractType_contracttype_id_Typology`.`name` AS `contracttype_name`,`Contract`.`billing_frequency` AS `billing_frequency`,`Contract`.`cost_unit` AS `cost_unit`,`Contract`.`provider_id` AS `provider_id`,`Organization_provider_id`.`name` AS `provider_name`,`Contract`.`status` AS `status`,`Contract`.`finalclass` AS `finalclass`,cast(concat(coalesce(`Contract`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`ContractType_contracttype_id_Typology`.`name`,\'\')) as char charset utf8mb4) AS `contracttype_id_friendlyname`,cast(concat(coalesce(`Organization_provider_id`.`name`,\'\')) as char charset utf8mb4) AS `provider_id_friendlyname`,coalesce((`Organization_provider_id`.`status` = \'inactive\'),0) AS `provider_id_obsolescence_flag` from (((`itop27`.`contract` `Contract` join `itop27`.`organization` `Organization_org_id` on((`Contract`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`typology` `ContractType_contracttype_id_Typology` on((`Contract`.`contracttype_id` = `ContractType_contracttype_id_Typology`.`id`))) join `itop27`.`organization` `Organization_provider_id` on((`Contract`.`provider_id` = `Organization_provider_id`.`id`))) where coalesce((`ContractType_contracttype_id_Typology`.`finalclass` = \'ContractType\'),1)
md5=38ce1b728abe967558ec0996ee38c939
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `Contract`.`id` AS `id`,\n `Contract`.`name` AS `name`,\n `Contract`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `organization_name`,\n `Contract`.`description` AS `description`,\n `Contract`.`start_date` AS `start_date`,\n `Contract`.`end_date` AS `end_date`,\n `Contract`.`cost` AS `cost`,\n `Contract`.`cost_currency` AS `cost_currency`,\n `Contract`.`contracttype_id` AS `contracttype_id`,\n `ContractType_contracttype_id_Typology`.`name` AS `contracttype_name`,\n `Contract`.`billing_frequency` AS `billing_frequency`,\n `Contract`.`cost_unit` AS `cost_unit`,\n `Contract`.`provider_id` AS `provider_id`,\n `Organization_provider_id`.`name` AS `provider_name`,\n `Contract`.`status` AS `status`,\n `Contract`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`Contract`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`ContractType_contracttype_id_Typology`.`name`, \'\')) AS CHAR) AS `contracttype_id_friendlyname`,\n CAST(CONCAT(COALESCE(`Organization_provider_id`.`name`, \'\')) AS CHAR) AS `provider_id_friendlyname`,\n COALESCE((`Organization_provider_id`.`status` = \'inactive\'), 0) AS `provider_id_obsolescence_flag`\n FROM \n   `contract` AS `Contract`\n   INNER JOIN \n      `organization` AS `Organization_org_id`\n    ON `Contract`.`org_id` = `Organization_org_id`.`id`\n   LEFT JOIN \n      `typology` AS `ContractType_contracttype_id_Typology`\n    ON `Contract`.`contracttype_id` = `ContractType_contracttype_id_Typology`.`id`\n   INNER JOIN \n      `organization` AS `Organization_provider_id`\n    ON `Contract`.`provider_id` = `Organization_provider_id`.`id`\n WHERE COALESCE((`ContractType_contracttype_id_Typology`.`finalclass` IN (\'ContractType\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `Contract`.`id` AS `id`,`Contract`.`name` AS `name`,`Contract`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`Contract`.`description` AS `description`,`Contract`.`start_date` AS `start_date`,`Contract`.`end_date` AS `end_date`,`Contract`.`cost` AS `cost`,`Contract`.`cost_currency` AS `cost_currency`,`Contract`.`contracttype_id` AS `contracttype_id`,`ContractType_contracttype_id_Typology`.`name` AS `contracttype_name`,`Contract`.`billing_frequency` AS `billing_frequency`,`Contract`.`cost_unit` AS `cost_unit`,`Contract`.`provider_id` AS `provider_id`,`Organization_provider_id`.`name` AS `provider_name`,`Contract`.`status` AS `status`,`Contract`.`finalclass` AS `finalclass`,cast(concat(coalesce(`Contract`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`ContractType_contracttype_id_Typology`.`name`,\'\')) as char charset utf8mb4) AS `contracttype_id_friendlyname`,cast(concat(coalesce(`Organization_provider_id`.`name`,\'\')) as char charset utf8mb4) AS `provider_id_friendlyname`,coalesce((`Organization_provider_id`.`status` = \'inactive\'),0) AS `provider_id_obsolescence_flag` from (((`itop27`.`contract` `Contract` join `itop27`.`organization` `Organization_org_id` on((`Contract`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`typology` `ContractType_contracttype_id_Typology` on((`Contract`.`contracttype_id` = `ContractType_contracttype_id_Typology`.`id`))) join `itop27`.`organization` `Organization_provider_id` on((`Contract`.`provider_id` = `Organization_provider_id`.`id`))) where coalesce((`ContractType_contracttype_id_Typology`.`finalclass` = \'ContractType\'),1)
