TYPE=VIEW
query=select distinct `ServiceSubcategory`.`id` AS `id`,`ServiceSubcategory`.`name` AS `name`,`ServiceSubcategory`.`description` AS `description`,`ServiceSubcategory`.`service_id` AS `service_id`,`Service_service_id`.`org_id` AS `service_org_id`,`Service_service_id`.`name` AS `service_name`,`Organization_org_id`.`name` AS `service_provider`,`ServiceSubcategory`.`request_type` AS `request_type`,`ServiceSubcategory`.`status` AS `status`,cast(concat(coalesce(`ServiceSubcategory`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Service_service_id`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `service_org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `service_org_id_obsolescence_flag` from (`itop27`.`servicesubcategory` `ServiceSubcategory` join (`itop27`.`service` `Service_service_id` join `itop27`.`organization` `Organization_org_id` on((`Service_service_id`.`org_id` = `Organization_org_id`.`id`))) on((`ServiceSubcategory`.`service_id` = `Service_service_id`.`id`))) where 1
md5=74200574f2f7a40c5c979e2cfb01409e
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `ServiceSubcategory`.`id` AS `id`,\n `ServiceSubcategory`.`name` AS `name`,\n `ServiceSubcategory`.`description` AS `description`,\n `ServiceSubcategory`.`service_id` AS `service_id`,\n `Service_service_id`.`org_id` AS `service_org_id`,\n `Service_service_id`.`name` AS `service_name`,\n `Organization_org_id`.`name` AS `service_provider`,\n `ServiceSubcategory`.`request_type` AS `request_type`,\n `ServiceSubcategory`.`status` AS `status`,\n CAST(CONCAT(COALESCE(`ServiceSubcategory`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`Service_service_id`.`name`, \'\')) AS CHAR) AS `service_id_friendlyname`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `service_org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `service_org_id_obsolescence_flag`\n FROM \n   `servicesubcategory` AS `ServiceSubcategory`\n   INNER JOIN (\n      `service` AS `Service_service_id` \n      INNER JOIN \n         `organization` AS `Organization_org_id`\n       ON `Service_service_id`.`org_id` = `Organization_org_id`.`id`\n   ) ON `ServiceSubcategory`.`service_id` = `Service_service_id`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `ServiceSubcategory`.`id` AS `id`,`ServiceSubcategory`.`name` AS `name`,`ServiceSubcategory`.`description` AS `description`,`ServiceSubcategory`.`service_id` AS `service_id`,`Service_service_id`.`org_id` AS `service_org_id`,`Service_service_id`.`name` AS `service_name`,`Organization_org_id`.`name` AS `service_provider`,`ServiceSubcategory`.`request_type` AS `request_type`,`ServiceSubcategory`.`status` AS `status`,cast(concat(coalesce(`ServiceSubcategory`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Service_service_id`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `service_org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `service_org_id_obsolescence_flag` from (`itop27`.`servicesubcategory` `ServiceSubcategory` join (`itop27`.`service` `Service_service_id` join `itop27`.`organization` `Organization_org_id` on((`Service_service_id`.`org_id` = `Organization_org_id`.`id`))) on((`ServiceSubcategory`.`service_id` = `Service_service_id`.`id`))) where 1
