TYPE=VIEW
query=select distinct `BusinessProcess`.`id` AS `id`,`BusinessProcess_FunctionalCI`.`name` AS `name`,`BusinessProcess_FunctionalCI`.`description` AS `description`,`BusinessProcess_FunctionalCI`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`BusinessProcess_FunctionalCI`.`business_criticity` AS `business_criticity`,`BusinessProcess_FunctionalCI`.`move2production` AS `move2production`,`BusinessProcess`.`status` AS `status`,`BusinessProcess_FunctionalCI`.`finalclass` AS `finalclass`,cast(concat(coalesce(`BusinessProcess_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`BusinessProcess`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`BusinessProcess_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from (`itop27`.`businessprocess` `BusinessProcess` join (`itop27`.`functionalci` `BusinessProcess_FunctionalCI` join `itop27`.`organization` `Organization_org_id` on((`BusinessProcess_FunctionalCI`.`org_id` = `Organization_org_id`.`id`))) on((`BusinessProcess`.`id` = `BusinessProcess_FunctionalCI`.`id`))) where 1
md5=2b29e2b90bbcacb3f56cae6c7b1e859c
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `BusinessProcess`.`id` AS `id`,\n `BusinessProcess_FunctionalCI`.`name` AS `name`,\n `BusinessProcess_FunctionalCI`.`description` AS `description`,\n `BusinessProcess_FunctionalCI`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `organization_name`,\n `BusinessProcess_FunctionalCI`.`business_criticity` AS `business_criticity`,\n `BusinessProcess_FunctionalCI`.`move2production` AS `move2production`,\n `BusinessProcess`.`status` AS `status`,\n `BusinessProcess_FunctionalCI`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`BusinessProcess_FunctionalCI`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE((`BusinessProcess`.`status` = \'inactive\'), 0) AS `obsolescence_flag`,\n `BusinessProcess_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`\n FROM \n   `businessprocess` AS `BusinessProcess`\n   INNER JOIN (\n      `functionalci` AS `BusinessProcess_FunctionalCI` \n      INNER JOIN \n         `organization` AS `Organization_org_id`\n       ON `BusinessProcess_FunctionalCI`.`org_id` = `Organization_org_id`.`id`\n   ) ON `BusinessProcess`.`id` = `BusinessProcess_FunctionalCI`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `BusinessProcess`.`id` AS `id`,`BusinessProcess_FunctionalCI`.`name` AS `name`,`BusinessProcess_FunctionalCI`.`description` AS `description`,`BusinessProcess_FunctionalCI`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`BusinessProcess_FunctionalCI`.`business_criticity` AS `business_criticity`,`BusinessProcess_FunctionalCI`.`move2production` AS `move2production`,`BusinessProcess`.`status` AS `status`,`BusinessProcess_FunctionalCI`.`finalclass` AS `finalclass`,cast(concat(coalesce(`BusinessProcess_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`BusinessProcess`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`BusinessProcess_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from (`itop27`.`businessprocess` `BusinessProcess` join (`itop27`.`functionalci` `BusinessProcess_FunctionalCI` join `itop27`.`organization` `Organization_org_id` on((`BusinessProcess_FunctionalCI`.`org_id` = `Organization_org_id`.`id`))) on((`BusinessProcess`.`id` = `BusinessProcess_FunctionalCI`.`id`))) where 1
