TYPE=VIEW
query=select distinct `OSLicence`.`id` AS `id`,`OSLicence_Licence`.`name` AS `name`,`OSLicence_Licence`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`OSLicence_Licence`.`usage_limit` AS `usage_limit`,`OSLicence_Licence`.`description` AS `description`,`OSLicence_Licence`.`start_date` AS `start_date`,`OSLicence_Licence`.`end_date` AS `end_date`,`OSLicence_Licence`.`licence_key` AS `licence_key`,`OSLicence_Licence`.`perpetual` AS `perpetual`,`OSLicence`.`osversion_id` AS `osversion_id`,`OSVersion_osversion_id_Typology`.`name` AS `osversion_name`,`OSLicence_Licence`.`finalclass` AS `finalclass`,cast(concat(coalesce(`OSLicence_Licence`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(((`OSLicence_Licence`.`perpetual` = \'no\') and (isnull(`OSLicence_Licence`.`end_date`) = 0) and (`OSLicence_Licence`.`end_date` < date_format((now() - interval 15 month),\'%Y-%m-%d 00:00:00\'))),0) AS `obsolescence_flag`,`OSLicence_Licence`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`OSVersion_osversion_id_Typology`.`name`,\'\')) as char charset utf8mb4) AS `osversion_id_friendlyname` from ((`itop27`.`oslicence` `OSLicence` join `itop27`.`typology` `OSVersion_osversion_id_Typology` on((`OSLicence`.`osversion_id` = `OSVersion_osversion_id_Typology`.`id`))) join (`itop27`.`licence` `OSLicence_Licence` join `itop27`.`organization` `Organization_org_id` on((`OSLicence_Licence`.`org_id` = `Organization_org_id`.`id`))) on((`OSLicence`.`id` = `OSLicence_Licence`.`id`))) where coalesce((`OSVersion_osversion_id_Typology`.`finalclass` = \'OSVersion\'),1)
md5=e3840928f70bffad3ffabcc4594f4797
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `OSLicence`.`id` AS `id`,\n `OSLicence_Licence`.`name` AS `name`,\n `OSLicence_Licence`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `organization_name`,\n `OSLicence_Licence`.`usage_limit` AS `usage_limit`,\n `OSLicence_Licence`.`description` AS `description`,\n `OSLicence_Licence`.`start_date` AS `start_date`,\n `OSLicence_Licence`.`end_date` AS `end_date`,\n `OSLicence_Licence`.`licence_key` AS `licence_key`,\n `OSLicence_Licence`.`perpetual` AS `perpetual`,\n `OSLicence`.`osversion_id` AS `osversion_id`,\n `OSVersion_osversion_id_Typology`.`name` AS `osversion_name`,\n `OSLicence_Licence`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`OSLicence_Licence`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE((((`OSLicence_Licence`.`perpetual` = \'no\') AND (ISNULL(`OSLicence_Licence`.`end_date`) = 0)) AND (`OSLicence_Licence`.`end_date` < DATE_FORMAT(DATE_SUB(NOW(), INTERVAL 15 MONTH), \'%Y-%m-%d 00:00:00\'))), 0) AS `obsolescence_flag`,\n `OSLicence_Licence`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`OSVersion_osversion_id_Typology`.`name`, \'\')) AS CHAR) AS `osversion_id_friendlyname`\n FROM \n   `oslicence` AS `OSLicence`\n   INNER JOIN \n      `typology` AS `OSVersion_osversion_id_Typology`\n    ON `OSLicence`.`osversion_id` = `OSVersion_osversion_id_Typology`.`id`\n   INNER JOIN (\n      `licence` AS `OSLicence_Licence` \n      INNER JOIN \n         `organization` AS `Organization_org_id`\n       ON `OSLicence_Licence`.`org_id` = `Organization_org_id`.`id`\n   ) ON `OSLicence`.`id` = `OSLicence_Licence`.`id`\n WHERE COALESCE((`OSVersion_osversion_id_Typology`.`finalclass` IN (\'OSVersion\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `OSLicence`.`id` AS `id`,`OSLicence_Licence`.`name` AS `name`,`OSLicence_Licence`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`OSLicence_Licence`.`usage_limit` AS `usage_limit`,`OSLicence_Licence`.`description` AS `description`,`OSLicence_Licence`.`start_date` AS `start_date`,`OSLicence_Licence`.`end_date` AS `end_date`,`OSLicence_Licence`.`licence_key` AS `licence_key`,`OSLicence_Licence`.`perpetual` AS `perpetual`,`OSLicence`.`osversion_id` AS `osversion_id`,`OSVersion_osversion_id_Typology`.`name` AS `osversion_name`,`OSLicence_Licence`.`finalclass` AS `finalclass`,cast(concat(coalesce(`OSLicence_Licence`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(((`OSLicence_Licence`.`perpetual` = \'no\') and (isnull(`OSLicence_Licence`.`end_date`) = 0) and (`OSLicence_Licence`.`end_date` < date_format((now() - interval 15 month),\'%Y-%m-%d 00:00:00\'))),0) AS `obsolescence_flag`,`OSLicence_Licence`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`OSVersion_osversion_id_Typology`.`name`,\'\')) as char charset utf8mb4) AS `osversion_id_friendlyname` from ((`itop27`.`oslicence` `OSLicence` join `itop27`.`typology` `OSVersion_osversion_id_Typology` on((`OSLicence`.`osversion_id` = `OSVersion_osversion_id_Typology`.`id`))) join (`itop27`.`licence` `OSLicence_Licence` join `itop27`.`organization` `Organization_org_id` on((`OSLicence_Licence`.`org_id` = `Organization_org_id`.`id`))) on((`OSLicence`.`id` = `OSLicence_Licence`.`id`))) where coalesce((`OSVersion_osversion_id_Typology`.`finalclass` = \'OSVersion\'),1)
