TYPE=VIEW
query=select distinct `VirtualHost_VirtualDevice`.`id` AS `id`,`VirtualHost_FunctionalCI`.`name` AS `name`,`VirtualHost_FunctionalCI`.`description` AS `description`,`VirtualHost_FunctionalCI`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`VirtualHost_FunctionalCI`.`business_criticity` AS `business_criticity`,`VirtualHost_FunctionalCI`.`move2production` AS `move2production`,`VirtualHost_VirtualDevice`.`status` AS `status`,`VirtualHost_FunctionalCI`.`finalclass` AS `finalclass`,cast(concat(coalesce(`VirtualHost_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`VirtualHost_VirtualDevice`.`status` = \'obsolete\'),0) AS `obsolescence_flag`,`VirtualHost_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from (`itop27`.`virtualdevice` `VirtualHost_VirtualDevice` join (`itop27`.`functionalci` `VirtualHost_FunctionalCI` join `itop27`.`organization` `Organization_org_id` on((`VirtualHost_FunctionalCI`.`org_id` = `Organization_org_id`.`id`))) on((`VirtualHost_VirtualDevice`.`id` = `VirtualHost_FunctionalCI`.`id`))) where coalesce((`VirtualHost_VirtualDevice`.`finalclass` in (\'Hypervisor\',\'Farm\',\'VirtualHost\')),1)
md5=e66b263bcc09a9ca90d0605dad61cfa4
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `VirtualHost_VirtualDevice`.`id` AS `id`,\n `VirtualHost_FunctionalCI`.`name` AS `name`,\n `VirtualHost_FunctionalCI`.`description` AS `description`,\n `VirtualHost_FunctionalCI`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `organization_name`,\n `VirtualHost_FunctionalCI`.`business_criticity` AS `business_criticity`,\n `VirtualHost_FunctionalCI`.`move2production` AS `move2production`,\n `VirtualHost_VirtualDevice`.`status` AS `status`,\n `VirtualHost_FunctionalCI`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`VirtualHost_FunctionalCI`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE((`VirtualHost_VirtualDevice`.`status` = \'obsolete\'), 0) AS `obsolescence_flag`,\n `VirtualHost_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`\n FROM \n   `virtualdevice` AS `VirtualHost_VirtualDevice`\n   INNER JOIN (\n      `functionalci` AS `VirtualHost_FunctionalCI` \n      INNER JOIN \n         `organization` AS `Organization_org_id`\n       ON `VirtualHost_FunctionalCI`.`org_id` = `Organization_org_id`.`id`\n   ) ON `VirtualHost_VirtualDevice`.`id` = `VirtualHost_FunctionalCI`.`id`\n WHERE COALESCE((`VirtualHost_VirtualDevice`.`finalclass` IN (\'Hypervisor\', \'Farm\', \'VirtualHost\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `VirtualHost_VirtualDevice`.`id` AS `id`,`VirtualHost_FunctionalCI`.`name` AS `name`,`VirtualHost_FunctionalCI`.`description` AS `description`,`VirtualHost_FunctionalCI`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`VirtualHost_FunctionalCI`.`business_criticity` AS `business_criticity`,`VirtualHost_FunctionalCI`.`move2production` AS `move2production`,`VirtualHost_VirtualDevice`.`status` AS `status`,`VirtualHost_FunctionalCI`.`finalclass` AS `finalclass`,cast(concat(coalesce(`VirtualHost_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`VirtualHost_VirtualDevice`.`status` = \'obsolete\'),0) AS `obsolescence_flag`,`VirtualHost_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from (`itop27`.`virtualdevice` `VirtualHost_VirtualDevice` join (`itop27`.`functionalci` `VirtualHost_FunctionalCI` join `itop27`.`organization` `Organization_org_id` on((`VirtualHost_FunctionalCI`.`org_id` = `Organization_org_id`.`id`))) on((`VirtualHost_VirtualDevice`.`id` = `VirtualHost_FunctionalCI`.`id`))) where coalesce((`VirtualHost_VirtualDevice`.`finalclass` in (\'Hypervisor\',\'Farm\',\'VirtualHost\')),1)
