TYPE=VIEW
query=select distinct `NASFileSystem`.`id` AS `id`,`NASFileSystem`.`name` AS `name`,`NASFileSystem`.`description` AS `description`,`NASFileSystem`.`raid_level` AS `raid_level`,`NASFileSystem`.`size` AS `size`,`NASFileSystem`.`nas_id` AS `nas_id`,`NAS_nas_id_FunctionalCI`.`name` AS `nas_name`,cast(concat(coalesce(`NASFileSystem`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`NAS_nas_id_PhysicalDevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`NASFileSystem`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`NAS_nas_id_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `nas_id_friendlyname`,coalesce((`NAS_nas_id_PhysicalDevice`.`status` = \'obsolete\'),0) AS `nas_id_obsolescence_flag` from (`itop27`.`nasfilesystem` `NASFileSystem` join (`itop27`.`physicaldevice` `NAS_nas_id_PhysicalDevice` join `itop27`.`functionalci` `NAS_nas_id_FunctionalCI` on((`NAS_nas_id_PhysicalDevice`.`id` = `NAS_nas_id_FunctionalCI`.`id`))) on((`NASFileSystem`.`nas_id` = `NAS_nas_id_PhysicalDevice`.`id`))) where coalesce((`NAS_nas_id_PhysicalDevice`.`finalclass` = \'NAS\'),1)
md5=e62001b8adc89ed139a697f63c05edc3
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `NASFileSystem`.`id` AS `id`,\n `NASFileSystem`.`name` AS `name`,\n `NASFileSystem`.`description` AS `description`,\n `NASFileSystem`.`raid_level` AS `raid_level`,\n `NASFileSystem`.`size` AS `size`,\n `NASFileSystem`.`nas_id` AS `nas_id`,\n `NAS_nas_id_FunctionalCI`.`name` AS `nas_name`,\n CAST(CONCAT(COALESCE(`NASFileSystem`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE(COALESCE((`NAS_nas_id_PhysicalDevice`.`status` = \'obsolete\'), 0), 0) AS `obsolescence_flag`,\n `NASFileSystem`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`NAS_nas_id_FunctionalCI`.`name`, \'\')) AS CHAR) AS `nas_id_friendlyname`,\n COALESCE((`NAS_nas_id_PhysicalDevice`.`status` = \'obsolete\'), 0) AS `nas_id_obsolescence_flag`\n FROM \n   `nasfilesystem` AS `NASFileSystem`\n   INNER JOIN (\n      `physicaldevice` AS `NAS_nas_id_PhysicalDevice` \n      INNER JOIN \n         `functionalci` AS `NAS_nas_id_FunctionalCI`\n       ON `NAS_nas_id_PhysicalDevice`.`id` = `NAS_nas_id_FunctionalCI`.`id`\n   ) ON `NASFileSystem`.`nas_id` = `NAS_nas_id_PhysicalDevice`.`id`\n WHERE COALESCE((`NAS_nas_id_PhysicalDevice`.`finalclass` IN (\'NAS\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `NASFileSystem`.`id` AS `id`,`NASFileSystem`.`name` AS `name`,`NASFileSystem`.`description` AS `description`,`NASFileSystem`.`raid_level` AS `raid_level`,`NASFileSystem`.`size` AS `size`,`NASFileSystem`.`nas_id` AS `nas_id`,`NAS_nas_id_FunctionalCI`.`name` AS `nas_name`,cast(concat(coalesce(`NASFileSystem`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`NAS_nas_id_PhysicalDevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`NASFileSystem`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`NAS_nas_id_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `nas_id_friendlyname`,coalesce((`NAS_nas_id_PhysicalDevice`.`status` = \'obsolete\'),0) AS `nas_id_obsolescence_flag` from (`itop27`.`nasfilesystem` `NASFileSystem` join (`itop27`.`physicaldevice` `NAS_nas_id_PhysicalDevice` join `itop27`.`functionalci` `NAS_nas_id_FunctionalCI` on((`NAS_nas_id_PhysicalDevice`.`id` = `NAS_nas_id_FunctionalCI`.`id`))) on((`NASFileSystem`.`nas_id` = `NAS_nas_id_PhysicalDevice`.`id`))) where coalesce((`NAS_nas_id_PhysicalDevice`.`finalclass` = \'NAS\'),1)
