TYPE=VIEW
query=select distinct `Group`.`id` AS `id`,`Group`.`name` AS `name`,`Group`.`status` AS `status`,`Group`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `owner_name`,`Group`.`description` AS `description`,`Group`.`type` AS `type`,`Group`.`parent_id` AS `parent_id`,`Group_parent_id`.`name` AS `parent_name`,cast(concat(coalesce(`Group`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`Group`.`status` = \'obsolete\'),0) AS `obsolescence_flag`,`Group`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Group_parent_id`.`name`,\'\')) as char charset utf8mb4) AS `parent_id_friendlyname`,coalesce((`Group_parent_id`.`status` = \'obsolete\'),0) AS `parent_id_obsolescence_flag` from ((`itop27`.`group` `Group` join `itop27`.`organization` `Organization_org_id` on((`Group`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`group` `Group_parent_id` on((`Group`.`parent_id` = `Group_parent_id`.`id`))) where 1
md5=83180e6014f329b795b7f735e0769e64
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `Group`.`id` AS `id`,\n `Group`.`name` AS `name`,\n `Group`.`status` AS `status`,\n `Group`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `owner_name`,\n `Group`.`description` AS `description`,\n `Group`.`type` AS `type`,\n `Group`.`parent_id` AS `parent_id`,\n `Group_parent_id`.`name` AS `parent_name`,\n CAST(CONCAT(COALESCE(`Group`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE((`Group`.`status` = \'obsolete\'), 0) AS `obsolescence_flag`,\n `Group`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`Group_parent_id`.`name`, \'\')) AS CHAR) AS `parent_id_friendlyname`,\n COALESCE((`Group_parent_id`.`status` = \'obsolete\'), 0) AS `parent_id_obsolescence_flag`\n FROM \n   `group` AS `Group`\n   INNER JOIN \n      `organization` AS `Organization_org_id`\n    ON `Group`.`org_id` = `Organization_org_id`.`id`\n   LEFT JOIN \n      `group` AS `Group_parent_id`\n    ON `Group`.`parent_id` = `Group_parent_id`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `Group`.`id` AS `id`,`Group`.`name` AS `name`,`Group`.`status` AS `status`,`Group`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `owner_name`,`Group`.`description` AS `description`,`Group`.`type` AS `type`,`Group`.`parent_id` AS `parent_id`,`Group_parent_id`.`name` AS `parent_name`,cast(concat(coalesce(`Group`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`Group`.`status` = \'obsolete\'),0) AS `obsolescence_flag`,`Group`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`Group_parent_id`.`name`,\'\')) as char charset utf8mb4) AS `parent_id_friendlyname`,coalesce((`Group_parent_id`.`status` = \'obsolete\'),0) AS `parent_id_obsolescence_flag` from ((`itop27`.`group` `Group` join `itop27`.`organization` `Organization_org_id` on((`Group`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`group` `Group_parent_id` on((`Group`.`parent_id` = `Group_parent_id`.`id`))) where 1
