TYPE=VIEW
query=select distinct `lnkCustomerContractToService`.`id` AS `id`,`lnkCustomerContractToService`.`customercontract_id` AS `customercontract_id`,`CustomerContract_customercontract_id_Contract`.`name` AS `customercontract_name`,`lnkCustomerContractToService`.`service_id` AS `service_id`,`Service_service_id`.`name` AS `service_name`,`lnkCustomerContractToService`.`sla_id` AS `sla_id`,`SLA_sla_id`.`name` AS `sla_name`,cast(concat(coalesce(`lnkCustomerContractToService`.`customercontract_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkCustomerContractToService`.`service_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`CustomerContract_customercontract_id_Contract`.`name`,\'\')) as char charset utf8mb4) AS `customercontract_id_friendlyname`,cast(concat(coalesce(`Service_service_id`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,cast(concat(coalesce(`SLA_sla_id`.`name`,\'\')) as char charset utf8mb4) AS `sla_id_friendlyname` from (((`itop27`.`lnkcustomercontracttoservice` `lnkCustomerContractToService` join `itop27`.`contract` `CustomerContract_customercontract_id_Contract` on((`lnkCustomerContractToService`.`customercontract_id` = `CustomerContract_customercontract_id_Contract`.`id`))) join `itop27`.`service` `Service_service_id` on((`lnkCustomerContractToService`.`service_id` = `Service_service_id`.`id`))) left join `itop27`.`sla` `SLA_sla_id` on((`lnkCustomerContractToService`.`sla_id` = `SLA_sla_id`.`id`))) where coalesce((`CustomerContract_customercontract_id_Contract`.`finalclass` = \'CustomerContract\'),1)
md5=32322d23265ae7d60e9e48ce2a969233
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `lnkCustomerContractToService`.`id` AS `id`,\n `lnkCustomerContractToService`.`customercontract_id` AS `customercontract_id`,\n `CustomerContract_customercontract_id_Contract`.`name` AS `customercontract_name`,\n `lnkCustomerContractToService`.`service_id` AS `service_id`,\n `Service_service_id`.`name` AS `service_name`,\n `lnkCustomerContractToService`.`sla_id` AS `sla_id`,\n `SLA_sla_id`.`name` AS `sla_name`,\n CAST(CONCAT(COALESCE(`lnkCustomerContractToService`.`customercontract_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`lnkCustomerContractToService`.`service_id`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`CustomerContract_customercontract_id_Contract`.`name`, \'\')) AS CHAR) AS `customercontract_id_friendlyname`,\n CAST(CONCAT(COALESCE(`Service_service_id`.`name`, \'\')) AS CHAR) AS `service_id_friendlyname`,\n CAST(CONCAT(COALESCE(`SLA_sla_id`.`name`, \'\')) AS CHAR) AS `sla_id_friendlyname`\n FROM \n   `lnkcustomercontracttoservice` AS `lnkCustomerContractToService`\n   INNER JOIN \n      `contract` AS `CustomerContract_customercontract_id_Contract`\n    ON `lnkCustomerContractToService`.`customercontract_id` = `CustomerContract_customercontract_id_Contract`.`id`\n   INNER JOIN \n      `service` AS `Service_service_id`\n    ON `lnkCustomerContractToService`.`service_id` = `Service_service_id`.`id`\n   LEFT JOIN \n      `sla` AS `SLA_sla_id`\n    ON `lnkCustomerContractToService`.`sla_id` = `SLA_sla_id`.`id`\n WHERE COALESCE((`CustomerContract_customercontract_id_Contract`.`finalclass` IN (\'CustomerContract\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `lnkCustomerContractToService`.`id` AS `id`,`lnkCustomerContractToService`.`customercontract_id` AS `customercontract_id`,`CustomerContract_customercontract_id_Contract`.`name` AS `customercontract_name`,`lnkCustomerContractToService`.`service_id` AS `service_id`,`Service_service_id`.`name` AS `service_name`,`lnkCustomerContractToService`.`sla_id` AS `sla_id`,`SLA_sla_id`.`name` AS `sla_name`,cast(concat(coalesce(`lnkCustomerContractToService`.`customercontract_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkCustomerContractToService`.`service_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`CustomerContract_customercontract_id_Contract`.`name`,\'\')) as char charset utf8mb4) AS `customercontract_id_friendlyname`,cast(concat(coalesce(`Service_service_id`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,cast(concat(coalesce(`SLA_sla_id`.`name`,\'\')) as char charset utf8mb4) AS `sla_id_friendlyname` from (((`itop27`.`lnkcustomercontracttoservice` `lnkCustomerContractToService` join `itop27`.`contract` `CustomerContract_customercontract_id_Contract` on((`lnkCustomerContractToService`.`customercontract_id` = `CustomerContract_customercontract_id_Contract`.`id`))) join `itop27`.`service` `Service_service_id` on((`lnkCustomerContractToService`.`service_id` = `Service_service_id`.`id`))) left join `itop27`.`sla` `SLA_sla_id` on((`lnkCustomerContractToService`.`sla_id` = `SLA_sla_id`.`id`))) where coalesce((`CustomerContract_customercontract_id_Contract`.`finalclass` = \'CustomerContract\'),1)
