TYPE=VIEW
query=select distinct `DatabaseSchema`.`id` AS `id`,`DatabaseSchema_FunctionalCI`.`name` AS `name`,`DatabaseSchema_FunctionalCI`.`description` AS `description`,`DatabaseSchema_FunctionalCI`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`DatabaseSchema_FunctionalCI`.`business_criticity` AS `business_criticity`,`DatabaseSchema_FunctionalCI`.`move2production` AS `move2production`,`DatabaseSchema`.`dbserver_id` AS `dbserver_id`,`DBServer_dbserver_id_FunctionalCI`.`name` AS `dbserver_name`,`DatabaseSchema_FunctionalCI`.`finalclass` AS `finalclass`,cast(concat(coalesce(`DatabaseSchema_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`DBServer_dbserver_id_SoftwareInstance`.`status` = \'inactive\'),0),0) AS `obsolescence_flag`,`DatabaseSchema_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`DBServer_dbserver_id_FunctionalCI`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`FunctionalCI_system_id`.`name`,\'\')) as char charset utf8mb4) AS `dbserver_id_friendlyname`,coalesce((`DBServer_dbserver_id_SoftwareInstance`.`status` = \'inactive\'),0) AS `dbserver_id_obsolescence_flag` from ((`itop27`.`databaseschema` `DatabaseSchema` join ((`itop27`.`softwareinstance` `DBServer_dbserver_id_SoftwareInstance` join `itop27`.`functionalci` `FunctionalCI_system_id` on((`DBServer_dbserver_id_SoftwareInstance`.`functionalci_id` = `FunctionalCI_system_id`.`id`))) join `itop27`.`functionalci` `DBServer_dbserver_id_FunctionalCI` on((`DBServer_dbserver_id_SoftwareInstance`.`id` = `DBServer_dbserver_id_FunctionalCI`.`id`))) on((`DatabaseSchema`.`dbserver_id` = `DBServer_dbserver_id_SoftwareInstance`.`id`))) join (`itop27`.`functionalci` `DatabaseSchema_FunctionalCI` join `itop27`.`organization` `Organization_org_id` on((`DatabaseSchema_FunctionalCI`.`org_id` = `Organization_org_id`.`id`))) on((`DatabaseSchema`.`id` = `DatabaseSchema_FunctionalCI`.`id`))) where coalesce((`DBServer_dbserver_id_SoftwareInstance`.`finalclass` = \'DBServer\'),1)
md5=1ef123a923dd26f26631eafd3f0412bd
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `DatabaseSchema`.`id` AS `id`,\n `DatabaseSchema_FunctionalCI`.`name` AS `name`,\n `DatabaseSchema_FunctionalCI`.`description` AS `description`,\n `DatabaseSchema_FunctionalCI`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `organization_name`,\n `DatabaseSchema_FunctionalCI`.`business_criticity` AS `business_criticity`,\n `DatabaseSchema_FunctionalCI`.`move2production` AS `move2production`,\n `DatabaseSchema`.`dbserver_id` AS `dbserver_id`,\n `DBServer_dbserver_id_FunctionalCI`.`name` AS `dbserver_name`,\n `DatabaseSchema_FunctionalCI`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`DatabaseSchema_FunctionalCI`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE(COALESCE((`DBServer_dbserver_id_SoftwareInstance`.`status` = \'inactive\'), 0), 0) AS `obsolescence_flag`,\n `DatabaseSchema_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`DBServer_dbserver_id_FunctionalCI`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`FunctionalCI_system_id`.`name`, \'\')) AS CHAR) AS `dbserver_id_friendlyname`,\n COALESCE((`DBServer_dbserver_id_SoftwareInstance`.`status` = \'inactive\'), 0) AS `dbserver_id_obsolescence_flag`\n FROM \n   `databaseschema` AS `DatabaseSchema`\n   INNER JOIN (\n      `softwareinstance` AS `DBServer_dbserver_id_SoftwareInstance` \n      INNER JOIN \n         `functionalci` AS `FunctionalCI_system_id`\n       ON `DBServer_dbserver_id_SoftwareInstance`.`functionalci_id` = `FunctionalCI_system_id`.`id`\n      INNER JOIN \n         `functionalci` AS `DBServer_dbserver_id_FunctionalCI`\n       ON `DBServer_dbserver_id_SoftwareInstance`.`id` = `DBServer_dbserver_id_FunctionalCI`.`id`\n   ) ON `DatabaseSchema`.`dbserver_id` = `DBServer_dbserver_id_SoftwareInstance`.`id`\n   INNER JOIN (\n      `functionalci` AS `DatabaseSchema_FunctionalCI` \n      INNER JOIN \n         `organization` AS `Organization_org_id`\n       ON `DatabaseSchema_FunctionalCI`.`org_id` = `Organization_org_id`.`id`\n   ) ON `DatabaseSchema`.`id` = `DatabaseSchema_FunctionalCI`.`id`\n WHERE COALESCE((`DBServer_dbserver_id_SoftwareInstance`.`finalclass` IN (\'DBServer\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `DatabaseSchema`.`id` AS `id`,`DatabaseSchema_FunctionalCI`.`name` AS `name`,`DatabaseSchema_FunctionalCI`.`description` AS `description`,`DatabaseSchema_FunctionalCI`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`DatabaseSchema_FunctionalCI`.`business_criticity` AS `business_criticity`,`DatabaseSchema_FunctionalCI`.`move2production` AS `move2production`,`DatabaseSchema`.`dbserver_id` AS `dbserver_id`,`DBServer_dbserver_id_FunctionalCI`.`name` AS `dbserver_name`,`DatabaseSchema_FunctionalCI`.`finalclass` AS `finalclass`,cast(concat(coalesce(`DatabaseSchema_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`DBServer_dbserver_id_SoftwareInstance`.`status` = \'inactive\'),0),0) AS `obsolescence_flag`,`DatabaseSchema_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`DBServer_dbserver_id_FunctionalCI`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`FunctionalCI_system_id`.`name`,\'\')) as char charset utf8mb4) AS `dbserver_id_friendlyname`,coalesce((`DBServer_dbserver_id_SoftwareInstance`.`status` = \'inactive\'),0) AS `dbserver_id_obsolescence_flag` from ((`itop27`.`databaseschema` `DatabaseSchema` join ((`itop27`.`softwareinstance` `DBServer_dbserver_id_SoftwareInstance` join `itop27`.`functionalci` `FunctionalCI_system_id` on((`DBServer_dbserver_id_SoftwareInstance`.`functionalci_id` = `FunctionalCI_system_id`.`id`))) join `itop27`.`functionalci` `DBServer_dbserver_id_FunctionalCI` on((`DBServer_dbserver_id_SoftwareInstance`.`id` = `DBServer_dbserver_id_FunctionalCI`.`id`))) on((`DatabaseSchema`.`dbserver_id` = `DBServer_dbserver_id_SoftwareInstance`.`id`))) join (`itop27`.`functionalci` `DatabaseSchema_FunctionalCI` join `itop27`.`organization` `Organization_org_id` on((`DatabaseSchema_FunctionalCI`.`org_id` = `Organization_org_id`.`id`))) on((`DatabaseSchema`.`id` = `DatabaseSchema_FunctionalCI`.`id`))) where coalesce((`DBServer_dbserver_id_SoftwareInstance`.`finalclass` = \'DBServer\'),1)
