TYPE=VIEW
query=select distinct `ApplicationSolution`.`id` AS `id`,`ApplicationSolution_FunctionalCI`.`name` AS `name`,`ApplicationSolution_FunctionalCI`.`description` AS `description`,`ApplicationSolution_FunctionalCI`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`ApplicationSolution_FunctionalCI`.`business_criticity` AS `business_criticity`,`ApplicationSolution_FunctionalCI`.`move2production` AS `move2production`,`ApplicationSolution`.`status` AS `status`,`ApplicationSolution`.`redundancy` AS `redundancy`,`ApplicationSolution_FunctionalCI`.`finalclass` AS `finalclass`,cast(concat(coalesce(`ApplicationSolution_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`ApplicationSolution`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`ApplicationSolution_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from (`itop27`.`applicationsolution` `ApplicationSolution` join (`itop27`.`functionalci` `ApplicationSolution_FunctionalCI` join `itop27`.`organization` `Organization_org_id` on((`ApplicationSolution_FunctionalCI`.`org_id` = `Organization_org_id`.`id`))) on((`ApplicationSolution`.`id` = `ApplicationSolution_FunctionalCI`.`id`))) where 1
md5=f565ffacfd17c8449bcdaabed02ec569
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `ApplicationSolution`.`id` AS `id`,\n `ApplicationSolution_FunctionalCI`.`name` AS `name`,\n `ApplicationSolution_FunctionalCI`.`description` AS `description`,\n `ApplicationSolution_FunctionalCI`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `organization_name`,\n `ApplicationSolution_FunctionalCI`.`business_criticity` AS `business_criticity`,\n `ApplicationSolution_FunctionalCI`.`move2production` AS `move2production`,\n `ApplicationSolution`.`status` AS `status`,\n `ApplicationSolution`.`redundancy` AS `redundancy`,\n `ApplicationSolution_FunctionalCI`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`ApplicationSolution_FunctionalCI`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE((`ApplicationSolution`.`status` = \'inactive\'), 0) AS `obsolescence_flag`,\n `ApplicationSolution_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`\n FROM \n   `applicationsolution` AS `ApplicationSolution`\n   INNER JOIN (\n      `functionalci` AS `ApplicationSolution_FunctionalCI` \n      INNER JOIN \n         `organization` AS `Organization_org_id`\n       ON `ApplicationSolution_FunctionalCI`.`org_id` = `Organization_org_id`.`id`\n   ) ON `ApplicationSolution`.`id` = `ApplicationSolution_FunctionalCI`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `ApplicationSolution`.`id` AS `id`,`ApplicationSolution_FunctionalCI`.`name` AS `name`,`ApplicationSolution_FunctionalCI`.`description` AS `description`,`ApplicationSolution_FunctionalCI`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`ApplicationSolution_FunctionalCI`.`business_criticity` AS `business_criticity`,`ApplicationSolution_FunctionalCI`.`move2production` AS `move2production`,`ApplicationSolution`.`status` AS `status`,`ApplicationSolution`.`redundancy` AS `redundancy`,`ApplicationSolution_FunctionalCI`.`finalclass` AS `finalclass`,cast(concat(coalesce(`ApplicationSolution_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`ApplicationSolution`.`status` = \'inactive\'),0) AS `obsolescence_flag`,`ApplicationSolution_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from (`itop27`.`applicationsolution` `ApplicationSolution` join (`itop27`.`functionalci` `ApplicationSolution_FunctionalCI` join `itop27`.`organization` `Organization_org_id` on((`ApplicationSolution_FunctionalCI`.`org_id` = `Organization_org_id`.`id`))) on((`ApplicationSolution`.`id` = `ApplicationSolution_FunctionalCI`.`id`))) where 1
