TYPE=VIEW
query=select distinct `PhysicalInterface`.`id` AS `id`,`PhysicalInterface_NetworkInterface`.`name` AS `name`,`PhysicalInterface_IPInterface`.`ipaddress` AS `ipaddress`,`PhysicalInterface_IPInterface`.`macaddress` AS `macaddress`,`PhysicalInterface_IPInterface`.`comment` AS `comment`,`PhysicalInterface_IPInterface`.`ipgateway` AS `ipgateway`,`PhysicalInterface_IPInterface`.`ipmask` AS `ipmask`,`PhysicalInterface_IPInterface`.`speed` AS `speed`,`PhysicalInterface`.`connectableci_id` AS `connectableci_id`,`ConnectableCI_connectableci_id_FunctionalCI`.`name` AS `connectableci_name`,`PhysicalInterface_NetworkInterface`.`finalclass` AS `finalclass`,cast(concat(coalesce(`PhysicalInterface_NetworkInterface`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`ConnectableCI_connectableci_id_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`ConnectableCI_connectableci_id_PhysicalDevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`PhysicalInterface_NetworkInterface`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`ConnectableCI_connectableci_id_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `connectableci_id_friendlyname`,`ConnectableCI_connectableci_id_FunctionalCI`.`finalclass` AS `connectableci_id_finalclass_recall`,coalesce((`ConnectableCI_connectableci_id_PhysicalDevice`.`status` = \'obsolete\'),0) AS `connectableci_id_obsolescence_flag` from (((`itop27`.`physicalinterface` `PhysicalInterface` join (`itop27`.`physicaldevice` `ConnectableCI_connectableci_id_PhysicalDevice` join `itop27`.`functionalci` `ConnectableCI_connectableci_id_FunctionalCI` on((`ConnectableCI_connectableci_id_PhysicalDevice`.`id` = `ConnectableCI_connectableci_id_FunctionalCI`.`id`))) on((`PhysicalInterface`.`connectableci_id` = `ConnectableCI_connectableci_id_PhysicalDevice`.`id`))) join `itop27`.`ipinterface` `PhysicalInterface_IPInterface` on((`PhysicalInterface`.`id` = `PhysicalInterface_IPInterface`.`id`))) join `itop27`.`networkinterface` `PhysicalInterface_NetworkInterface` on((`PhysicalInterface`.`id` = `PhysicalInterface_NetworkInterface`.`id`))) where coalesce((`ConnectableCI_connectableci_id_PhysicalDevice`.`finalclass` in (\'DatacenterDevice\',\'NetworkDevice\',\'Server\',\'PC\',\'Printer\',\'StorageSystem\',\'SANSwitch\',\'TapeLibrary\',\'NAS\',\'ConnectableCI\')),1)
md5=f895e1899bab6a6ccc4adff31b6f9dda
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `PhysicalInterface`.`id` AS `id`,\n `PhysicalInterface_NetworkInterface`.`name` AS `name`,\n `PhysicalInterface_IPInterface`.`ipaddress` AS `ipaddress`,\n `PhysicalInterface_IPInterface`.`macaddress` AS `macaddress`,\n `PhysicalInterface_IPInterface`.`comment` AS `comment`,\n `PhysicalInterface_IPInterface`.`ipgateway` AS `ipgateway`,\n `PhysicalInterface_IPInterface`.`ipmask` AS `ipmask`,\n `PhysicalInterface_IPInterface`.`speed` AS `speed`,\n `PhysicalInterface`.`connectableci_id` AS `connectableci_id`,\n `ConnectableCI_connectableci_id_FunctionalCI`.`name` AS `connectableci_name`,\n `PhysicalInterface_NetworkInterface`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`PhysicalInterface_NetworkInterface`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`ConnectableCI_connectableci_id_FunctionalCI`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE(COALESCE((`ConnectableCI_connectableci_id_PhysicalDevice`.`status` = \'obsolete\'), 0), 0) AS `obsolescence_flag`,\n `PhysicalInterface_NetworkInterface`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`ConnectableCI_connectableci_id_FunctionalCI`.`name`, \'\')) AS CHAR) AS `connectableci_id_friendlyname`,\n `ConnectableCI_connectableci_id_FunctionalCI`.`finalclass` AS `connectableci_id_finalclass_recall`,\n COALESCE((`ConnectableCI_connectableci_id_PhysicalDevice`.`status` = \'obsolete\'), 0) AS `connectableci_id_obsolescence_flag`\n FROM \n   `physicalinterface` AS `PhysicalInterface`\n   INNER JOIN (\n      `physicaldevice` AS `ConnectableCI_connectableci_id_PhysicalDevice` \n      INNER JOIN \n         `functionalci` AS `ConnectableCI_connectableci_id_FunctionalCI`\n       ON `ConnectableCI_connectableci_id_PhysicalDevice`.`id` = `ConnectableCI_connectableci_id_FunctionalCI`.`id`\n   ) ON `PhysicalInterface`.`connectableci_id` = `ConnectableCI_connectableci_id_PhysicalDevice`.`id`\n   INNER JOIN \n      `ipinterface` AS `PhysicalInterface_IPInterface`\n    ON `PhysicalInterface`.`id` = `PhysicalInterface_IPInterface`.`id`\n   INNER JOIN \n      `networkinterface` AS `PhysicalInterface_NetworkInterface`\n    ON `PhysicalInterface`.`id` = `PhysicalInterface_NetworkInterface`.`id`\n WHERE COALESCE((`ConnectableCI_connectableci_id_PhysicalDevice`.`finalclass` IN (\'DatacenterDevice\', \'NetworkDevice\', \'Server\', \'PC\', \'Printer\', \'StorageSystem\', \'SANSwitch\', \'TapeLibrary\', \'NAS\', \'ConnectableCI\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `PhysicalInterface`.`id` AS `id`,`PhysicalInterface_NetworkInterface`.`name` AS `name`,`PhysicalInterface_IPInterface`.`ipaddress` AS `ipaddress`,`PhysicalInterface_IPInterface`.`macaddress` AS `macaddress`,`PhysicalInterface_IPInterface`.`comment` AS `comment`,`PhysicalInterface_IPInterface`.`ipgateway` AS `ipgateway`,`PhysicalInterface_IPInterface`.`ipmask` AS `ipmask`,`PhysicalInterface_IPInterface`.`speed` AS `speed`,`PhysicalInterface`.`connectableci_id` AS `connectableci_id`,`ConnectableCI_connectableci_id_FunctionalCI`.`name` AS `connectableci_name`,`PhysicalInterface_NetworkInterface`.`finalclass` AS `finalclass`,cast(concat(coalesce(`PhysicalInterface_NetworkInterface`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`ConnectableCI_connectableci_id_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce(coalesce((`ConnectableCI_connectableci_id_PhysicalDevice`.`status` = \'obsolete\'),0),0) AS `obsolescence_flag`,`PhysicalInterface_NetworkInterface`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`ConnectableCI_connectableci_id_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `connectableci_id_friendlyname`,`ConnectableCI_connectableci_id_FunctionalCI`.`finalclass` AS `connectableci_id_finalclass_recall`,coalesce((`ConnectableCI_connectableci_id_PhysicalDevice`.`status` = \'obsolete\'),0) AS `connectableci_id_obsolescence_flag` from (((`itop27`.`physicalinterface` `PhysicalInterface` join (`itop27`.`physicaldevice` `ConnectableCI_connectableci_id_PhysicalDevice` join `itop27`.`functionalci` `ConnectableCI_connectableci_id_FunctionalCI` on((`ConnectableCI_connectableci_id_PhysicalDevice`.`id` = `ConnectableCI_connectableci_id_FunctionalCI`.`id`))) on((`PhysicalInterface`.`connectableci_id` = `ConnectableCI_connectableci_id_PhysicalDevice`.`id`))) join `itop27`.`ipinterface` `PhysicalInterface_IPInterface` on((`PhysicalInterface`.`id` = `PhysicalInterface_IPInterface`.`id`))) join `itop27`.`networkinterface` `PhysicalInterface_NetworkInterface` on((`PhysicalInterface`.`id` = `PhysicalInterface_NetworkInterface`.`id`))) where coalesce((`ConnectableCI_connectableci_id_PhysicalDevice`.`finalclass` in (\'DatacenterDevice\',\'NetworkDevice\',\'Server\',\'PC\',\'Printer\',\'StorageSystem\',\'SANSwitch\',\'TapeLibrary\',\'NAS\',\'ConnectableCI\')),1)
