TYPE=VIEW
query=select distinct `Attachment`.`id` AS `id`,`Attachment`.`expire` AS `expire`,`Attachment`.`temp_id` AS `temp_id`,`Attachment`.`item_class` AS `item_class`,`Attachment`.`item_id` AS `item_id`,`Attachment`.`item_org_id` AS `item_org_id`,`Attachment`.`contents_mimetype` AS `contents`,`Attachment`.`creation_date` AS `creation_date`,`Attachment`.`user_id` AS `user_id`,`User_user_id`.`contactid` AS `contact_id`,cast(concat(coalesce(`Attachment`.`item_class`,\'\'),coalesce(\' \',\'\'),coalesce(`Attachment`.`temp_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`User_user_id`.`login`,\'\')) as char charset utf8mb4) AS `user_id_friendlyname`,`User_user_id`.`finalclass` AS `user_id_finalclass_recall`,cast(concat(coalesce(`Person_contactid`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Person_contactid_Contact`.`name`,\'\')) as char charset utf8mb4) AS `contact_id_friendlyname`,coalesce((`Person_contactid_Contact`.`status` = \'inactive\'),0) AS `contact_id_obsolescence_flag`,`Attachment`.`contents_data` AS `Attachmentcontents_data`,`Attachment`.`contents_filename` AS `Attachmentcontents_filename` from (`itop27`.`attachment` `Attachment` left join (`itop27`.`priv_user` `User_user_id` left join (`itop27`.`person` `Person_contactid` join `itop27`.`contact` `Person_contactid_Contact` on((`Person_contactid`.`id` = `Person_contactid_Contact`.`id`))) on((`User_user_id`.`contactid` = `Person_contactid`.`id`))) on((`Attachment`.`user_id` = `User_user_id`.`id`))) where 1
md5=c08b75c87fe24adf75f6ed33294fdd5b
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `Attachment`.`id` AS `id`,\n `Attachment`.`expire` AS `expire`,\n `Attachment`.`temp_id` AS `temp_id`,\n `Attachment`.`item_class` AS `item_class`,\n `Attachment`.`item_id` AS `item_id`,\n `Attachment`.`item_org_id` AS `item_org_id`,\n `Attachment`.`contents_mimetype` AS `contents`,\n `Attachment`.`creation_date` AS `creation_date`,\n `Attachment`.`user_id` AS `user_id`,\n `User_user_id`.`contactid` AS `contact_id`,\n CAST(CONCAT(COALESCE(`Attachment`.`item_class`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Attachment`.`temp_id`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`User_user_id`.`login`, \'\')) AS CHAR) AS `user_id_friendlyname`,\n `User_user_id`.`finalclass` AS `user_id_finalclass_recall`,\n CAST(CONCAT(COALESCE(`Person_contactid`.`first_name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Person_contactid_Contact`.`name`, \'\')) AS CHAR) AS `contact_id_friendlyname`,\n COALESCE((`Person_contactid_Contact`.`status` = \'inactive\'), 0) AS `contact_id_obsolescence_flag`,\n `Attachment`.`contents_data` AS `Attachmentcontents_data`,\n `Attachment`.`contents_filename` AS `Attachmentcontents_filename`\n FROM \n   `attachment` AS `Attachment`\n   LEFT JOIN (\n      `priv_user` AS `User_user_id` \n      LEFT JOIN (\n         `person` AS `Person_contactid` \n         INNER JOIN \n            `contact` AS `Person_contactid_Contact`\n          ON `Person_contactid`.`id` = `Person_contactid_Contact`.`id`\n      ) ON `User_user_id`.`contactid` = `Person_contactid`.`id`\n   ) ON `Attachment`.`user_id` = `User_user_id`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `Attachment`.`id` AS `id`,`Attachment`.`expire` AS `expire`,`Attachment`.`temp_id` AS `temp_id`,`Attachment`.`item_class` AS `item_class`,`Attachment`.`item_id` AS `item_id`,`Attachment`.`item_org_id` AS `item_org_id`,`Attachment`.`contents_mimetype` AS `contents`,`Attachment`.`creation_date` AS `creation_date`,`Attachment`.`user_id` AS `user_id`,`User_user_id`.`contactid` AS `contact_id`,cast(concat(coalesce(`Attachment`.`item_class`,\'\'),coalesce(\' \',\'\'),coalesce(`Attachment`.`temp_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`User_user_id`.`login`,\'\')) as char charset utf8mb4) AS `user_id_friendlyname`,`User_user_id`.`finalclass` AS `user_id_finalclass_recall`,cast(concat(coalesce(`Person_contactid`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Person_contactid_Contact`.`name`,\'\')) as char charset utf8mb4) AS `contact_id_friendlyname`,coalesce((`Person_contactid_Contact`.`status` = \'inactive\'),0) AS `contact_id_obsolescence_flag`,`Attachment`.`contents_data` AS `Attachmentcontents_data`,`Attachment`.`contents_filename` AS `Attachmentcontents_filename` from (`itop27`.`attachment` `Attachment` left join (`itop27`.`priv_user` `User_user_id` left join (`itop27`.`person` `Person_contactid` join `itop27`.`contact` `Person_contactid_Contact` on((`Person_contactid`.`id` = `Person_contactid_Contact`.`id`))) on((`User_user_id`.`contactid` = `Person_contactid`.`id`))) on((`Attachment`.`user_id` = `User_user_id`.`id`))) where 1
