TYPE=VIEW
query=select distinct `DocumentWeb`.`id` AS `id`,`DocumentWeb_Document`.`name` AS `name`,`DocumentWeb_Document`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `org_name`,`DocumentWeb_Document`.`documenttype_id` AS `documenttype_id`,`DocumentType_documenttype_id_Typology`.`name` AS `documenttype_name`,`DocumentWeb_Document`.`version` AS `version`,`DocumentWeb_Document`.`description` AS `description`,`DocumentWeb_Document`.`status` AS `status`,`DocumentWeb`.`url` AS `url`,`DocumentWeb_Document`.`finalclass` AS `finalclass`,cast(concat(coalesce(`DocumentWeb_Document`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`DocumentWeb_Document`.`status` = \'obsolete\'),0) AS `obsolescence_flag`,`DocumentWeb_Document`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`DocumentType_documenttype_id_Typology`.`name`,\'\')) as char charset utf8mb4) AS `documenttype_id_friendlyname` from (`itop27`.`documentweb` `DocumentWeb` join ((`itop27`.`document` `DocumentWeb_Document` join `itop27`.`organization` `Organization_org_id` on((`DocumentWeb_Document`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`typology` `DocumentType_documenttype_id_Typology` on((`DocumentWeb_Document`.`documenttype_id` = `DocumentType_documenttype_id_Typology`.`id`))) on((`DocumentWeb`.`id` = `DocumentWeb_Document`.`id`))) where coalesce((`DocumentType_documenttype_id_Typology`.`finalclass` = \'DocumentType\'),1)
md5=7dd0370ae9ea0e802152789acbc34cd9
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:54
create-version=1
source=SELECT\n DISTINCT `DocumentWeb`.`id` AS `id`,\n `DocumentWeb_Document`.`name` AS `name`,\n `DocumentWeb_Document`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `org_name`,\n `DocumentWeb_Document`.`documenttype_id` AS `documenttype_id`,\n `DocumentType_documenttype_id_Typology`.`name` AS `documenttype_name`,\n `DocumentWeb_Document`.`version` AS `version`,\n `DocumentWeb_Document`.`description` AS `description`,\n `DocumentWeb_Document`.`status` AS `status`,\n `DocumentWeb`.`url` AS `url`,\n `DocumentWeb_Document`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`DocumentWeb_Document`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE((`DocumentWeb_Document`.`status` = \'obsolete\'), 0) AS `obsolescence_flag`,\n `DocumentWeb_Document`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`,\n CAST(CONCAT(COALESCE(`DocumentType_documenttype_id_Typology`.`name`, \'\')) AS CHAR) AS `documenttype_id_friendlyname`\n FROM \n   `documentweb` AS `DocumentWeb`\n   INNER JOIN (\n      `document` AS `DocumentWeb_Document` \n      INNER JOIN \n         `organization` AS `Organization_org_id`\n       ON `DocumentWeb_Document`.`org_id` = `Organization_org_id`.`id`\n      LEFT JOIN \n         `typology` AS `DocumentType_documenttype_id_Typology`\n       ON `DocumentWeb_Document`.`documenttype_id` = `DocumentType_documenttype_id_Typology`.`id`\n   ) ON `DocumentWeb`.`id` = `DocumentWeb_Document`.`id`\n WHERE COALESCE((`DocumentType_documenttype_id_Typology`.`finalclass` IN (\'DocumentType\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `DocumentWeb`.`id` AS `id`,`DocumentWeb_Document`.`name` AS `name`,`DocumentWeb_Document`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `org_name`,`DocumentWeb_Document`.`documenttype_id` AS `documenttype_id`,`DocumentType_documenttype_id_Typology`.`name` AS `documenttype_name`,`DocumentWeb_Document`.`version` AS `version`,`DocumentWeb_Document`.`description` AS `description`,`DocumentWeb_Document`.`status` AS `status`,`DocumentWeb`.`url` AS `url`,`DocumentWeb_Document`.`finalclass` AS `finalclass`,cast(concat(coalesce(`DocumentWeb_Document`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`DocumentWeb_Document`.`status` = \'obsolete\'),0) AS `obsolescence_flag`,`DocumentWeb_Document`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag`,cast(concat(coalesce(`DocumentType_documenttype_id_Typology`.`name`,\'\')) as char charset utf8mb4) AS `documenttype_id_friendlyname` from (`itop27`.`documentweb` `DocumentWeb` join ((`itop27`.`document` `DocumentWeb_Document` join `itop27`.`organization` `Organization_org_id` on((`DocumentWeb_Document`.`org_id` = `Organization_org_id`.`id`))) left join `itop27`.`typology` `DocumentType_documenttype_id_Typology` on((`DocumentWeb_Document`.`documenttype_id` = `DocumentType_documenttype_id_Typology`.`id`))) on((`DocumentWeb`.`id` = `DocumentWeb_Document`.`id`))) where coalesce((`DocumentType_documenttype_id_Typology`.`finalclass` = \'DocumentType\'),1)
