TYPE=VIEW
query=select distinct `lnkContactToService`.`id` AS `id`,`lnkContactToService`.`service_id` AS `service_id`,`Service_service_id`.`name` AS `service_name`,`lnkContactToService`.`contact_id` AS `contact_id`,`Contact_contact_id`.`name` AS `contact_name`,cast(concat(coalesce(`lnkContactToService`.`service_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkContactToService`.`contact_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Service_service_id`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,if((`Contact_contact_id`.`finalclass` in (\'Team\',\'Contact\')),cast(concat(coalesce(`Contact_contact_id`.`name`,\'\')) as char charset utf8mb4),cast(concat(coalesce(`Contact_contact_id_poly_Person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Contact_contact_id`.`name`,\'\')) as char charset utf8mb4)) AS `contact_id_friendlyname`,`Contact_contact_id`.`finalclass` AS `contact_id_finalclass_recall`,coalesce((`Contact_contact_id`.`status` = \'inactive\'),0) AS `contact_id_obsolescence_flag` from ((`itop27`.`lnkcontacttoservice` `lnkContactToService` join `itop27`.`service` `Service_service_id` on((`lnkContactToService`.`service_id` = `Service_service_id`.`id`))) join (`itop27`.`contact` `Contact_contact_id` left join `itop27`.`person` `Contact_contact_id_poly_Person` on((`Contact_contact_id`.`id` = `Contact_contact_id_poly_Person`.`id`))) on((`lnkContactToService`.`contact_id` = `Contact_contact_id`.`id`))) where 1
md5=172c807b6e4b19f3d635b8a3b7237327
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `lnkContactToService`.`id` AS `id`,\n `lnkContactToService`.`service_id` AS `service_id`,\n `Service_service_id`.`name` AS `service_name`,\n `lnkContactToService`.`contact_id` AS `contact_id`,\n `Contact_contact_id`.`name` AS `contact_name`,\n CAST(CONCAT(COALESCE(`lnkContactToService`.`service_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`lnkContactToService`.`contact_id`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`Service_service_id`.`name`, \'\')) AS CHAR) AS `service_id_friendlyname`,\n IF((`Contact_contact_id`.`finalclass` IN (\'Team\', \'Contact\')), CAST(CONCAT(COALESCE(`Contact_contact_id`.`name`, \'\')) AS CHAR), CAST(CONCAT(COALESCE(`Contact_contact_id_poly_Person`.`first_name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Contact_contact_id`.`name`, \'\')) AS CHAR)) AS `contact_id_friendlyname`,\n `Contact_contact_id`.`finalclass` AS `contact_id_finalclass_recall`,\n COALESCE((`Contact_contact_id`.`status` = \'inactive\'), 0) AS `contact_id_obsolescence_flag`\n FROM \n   `lnkcontacttoservice` AS `lnkContactToService`\n   INNER JOIN \n      `service` AS `Service_service_id`\n    ON `lnkContactToService`.`service_id` = `Service_service_id`.`id`\n   INNER JOIN (\n      `contact` AS `Contact_contact_id` \n      LEFT JOIN \n         `person` AS `Contact_contact_id_poly_Person`\n       ON `Contact_contact_id`.`id` = `Contact_contact_id_poly_Person`.`id`\n   ) ON `lnkContactToService`.`contact_id` = `Contact_contact_id`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `lnkContactToService`.`id` AS `id`,`lnkContactToService`.`service_id` AS `service_id`,`Service_service_id`.`name` AS `service_name`,`lnkContactToService`.`contact_id` AS `contact_id`,`Contact_contact_id`.`name` AS `contact_name`,cast(concat(coalesce(`lnkContactToService`.`service_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkContactToService`.`contact_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Service_service_id`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,if((`Contact_contact_id`.`finalclass` in (\'Team\',\'Contact\')),cast(concat(coalesce(`Contact_contact_id`.`name`,\'\')) as char charset utf8mb4),cast(concat(coalesce(`Contact_contact_id_poly_Person`.`first_name`,\'\'),coalesce(\' \',\'\'),coalesce(`Contact_contact_id`.`name`,\'\')) as char charset utf8mb4)) AS `contact_id_friendlyname`,`Contact_contact_id`.`finalclass` AS `contact_id_finalclass_recall`,coalesce((`Contact_contact_id`.`status` = \'inactive\'),0) AS `contact_id_obsolescence_flag` from ((`itop27`.`lnkcontacttoservice` `lnkContactToService` join `itop27`.`service` `Service_service_id` on((`lnkContactToService`.`service_id` = `Service_service_id`.`id`))) join (`itop27`.`contact` `Contact_contact_id` left join `itop27`.`person` `Contact_contact_id_poly_Person` on((`Contact_contact_id`.`id` = `Contact_contact_id_poly_Person`.`id`))) on((`lnkContactToService`.`contact_id` = `Contact_contact_id`.`id`))) where 1
