TYPE=VIEW
query=select distinct `lnkProviderContractToService`.`id` AS `id`,`lnkProviderContractToService`.`service_id` AS `service_id`,`Service_service_id`.`name` AS `service_name`,`lnkProviderContractToService`.`providercontract_id` AS `providercontract_id`,`ProviderContract_providercontract_id_Contract`.`name` AS `providercontract_name`,cast(concat(coalesce(`lnkProviderContractToService`.`service_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkProviderContractToService`.`providercontract_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Service_service_id`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,cast(concat(coalesce(`ProviderContract_providercontract_id_Contract`.`name`,\'\')) as char charset utf8mb4) AS `providercontract_id_friendlyname` from ((`itop27`.`lnkprovidercontracttoservice` `lnkProviderContractToService` join `itop27`.`service` `Service_service_id` on((`lnkProviderContractToService`.`service_id` = `Service_service_id`.`id`))) join `itop27`.`contract` `ProviderContract_providercontract_id_Contract` on((`lnkProviderContractToService`.`providercontract_id` = `ProviderContract_providercontract_id_Contract`.`id`))) where coalesce((`ProviderContract_providercontract_id_Contract`.`finalclass` = \'ProviderContract\'),1)
md5=415c38a529b92a9ed2e85b1dcabd3911
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `lnkProviderContractToService`.`id` AS `id`,\n `lnkProviderContractToService`.`service_id` AS `service_id`,\n `Service_service_id`.`name` AS `service_name`,\n `lnkProviderContractToService`.`providercontract_id` AS `providercontract_id`,\n `ProviderContract_providercontract_id_Contract`.`name` AS `providercontract_name`,\n CAST(CONCAT(COALESCE(`lnkProviderContractToService`.`service_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`lnkProviderContractToService`.`providercontract_id`, \'\')) AS CHAR) AS `friendlyname`,\n CAST(CONCAT(COALESCE(`Service_service_id`.`name`, \'\')) AS CHAR) AS `service_id_friendlyname`,\n CAST(CONCAT(COALESCE(`ProviderContract_providercontract_id_Contract`.`name`, \'\')) AS CHAR) AS `providercontract_id_friendlyname`\n FROM \n   `lnkprovidercontracttoservice` AS `lnkProviderContractToService`\n   INNER JOIN \n      `service` AS `Service_service_id`\n    ON `lnkProviderContractToService`.`service_id` = `Service_service_id`.`id`\n   INNER JOIN \n      `contract` AS `ProviderContract_providercontract_id_Contract`\n    ON `lnkProviderContractToService`.`providercontract_id` = `ProviderContract_providercontract_id_Contract`.`id`\n WHERE COALESCE((`ProviderContract_providercontract_id_Contract`.`finalclass` IN (\'ProviderContract\')), 1)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `lnkProviderContractToService`.`id` AS `id`,`lnkProviderContractToService`.`service_id` AS `service_id`,`Service_service_id`.`name` AS `service_name`,`lnkProviderContractToService`.`providercontract_id` AS `providercontract_id`,`ProviderContract_providercontract_id_Contract`.`name` AS `providercontract_name`,cast(concat(coalesce(`lnkProviderContractToService`.`service_id`,\'\'),coalesce(\' \',\'\'),coalesce(`lnkProviderContractToService`.`providercontract_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Service_service_id`.`name`,\'\')) as char charset utf8mb4) AS `service_id_friendlyname`,cast(concat(coalesce(`ProviderContract_providercontract_id_Contract`.`name`,\'\')) as char charset utf8mb4) AS `providercontract_id_friendlyname` from ((`itop27`.`lnkprovidercontracttoservice` `lnkProviderContractToService` join `itop27`.`service` `Service_service_id` on((`lnkProviderContractToService`.`service_id` = `Service_service_id`.`id`))) join `itop27`.`contract` `ProviderContract_providercontract_id_Contract` on((`lnkProviderContractToService`.`providercontract_id` = `ProviderContract_providercontract_id_Contract`.`id`))) where coalesce((`ProviderContract_providercontract_id_Contract`.`finalclass` = \'ProviderContract\'),1)
