TYPE=VIEW
query=select distinct `VirtualDevice`.`id` AS `id`,`VirtualDevice_FunctionalCI`.`name` AS `name`,`VirtualDevice_FunctionalCI`.`description` AS `description`,`VirtualDevice_FunctionalCI`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`VirtualDevice_FunctionalCI`.`business_criticity` AS `business_criticity`,`VirtualDevice_FunctionalCI`.`move2production` AS `move2production`,`VirtualDevice`.`status` AS `status`,`VirtualDevice_FunctionalCI`.`finalclass` AS `finalclass`,cast(concat(coalesce(`VirtualDevice_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`VirtualDevice`.`status` = \'obsolete\'),0) AS `obsolescence_flag`,`VirtualDevice_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from (`itop27`.`virtualdevice` `VirtualDevice` join (`itop27`.`functionalci` `VirtualDevice_FunctionalCI` join `itop27`.`organization` `Organization_org_id` on((`VirtualDevice_FunctionalCI`.`org_id` = `Organization_org_id`.`id`))) on((`VirtualDevice`.`id` = `VirtualDevice_FunctionalCI`.`id`))) where 1
md5=ddd5dc9fe1557c344460ad6d7eebdcb8
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-02 08:14:55
create-version=1
source=SELECT\n DISTINCT `VirtualDevice`.`id` AS `id`,\n `VirtualDevice_FunctionalCI`.`name` AS `name`,\n `VirtualDevice_FunctionalCI`.`description` AS `description`,\n `VirtualDevice_FunctionalCI`.`org_id` AS `org_id`,\n `Organization_org_id`.`name` AS `organization_name`,\n `VirtualDevice_FunctionalCI`.`business_criticity` AS `business_criticity`,\n `VirtualDevice_FunctionalCI`.`move2production` AS `move2production`,\n `VirtualDevice`.`status` AS `status`,\n `VirtualDevice_FunctionalCI`.`finalclass` AS `finalclass`,\n CAST(CONCAT(COALESCE(`VirtualDevice_FunctionalCI`.`name`, \'\')) AS CHAR) AS `friendlyname`,\n COALESCE((`VirtualDevice`.`status` = \'obsolete\'), 0) AS `obsolescence_flag`,\n `VirtualDevice_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,\n CAST(CONCAT(COALESCE(`Organization_org_id`.`name`, \'\')) AS CHAR) AS `org_id_friendlyname`,\n COALESCE((`Organization_org_id`.`status` = \'inactive\'), 0) AS `org_id_obsolescence_flag`\n FROM \n   `virtualdevice` AS `VirtualDevice`\n   INNER JOIN (\n      `functionalci` AS `VirtualDevice_FunctionalCI` \n      INNER JOIN \n         `organization` AS `Organization_org_id`\n       ON `VirtualDevice_FunctionalCI`.`org_id` = `Organization_org_id`.`id`\n   ) ON `VirtualDevice`.`id` = `VirtualDevice_FunctionalCI`.`id`\n WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `VirtualDevice`.`id` AS `id`,`VirtualDevice_FunctionalCI`.`name` AS `name`,`VirtualDevice_FunctionalCI`.`description` AS `description`,`VirtualDevice_FunctionalCI`.`org_id` AS `org_id`,`Organization_org_id`.`name` AS `organization_name`,`VirtualDevice_FunctionalCI`.`business_criticity` AS `business_criticity`,`VirtualDevice_FunctionalCI`.`move2production` AS `move2production`,`VirtualDevice`.`status` AS `status`,`VirtualDevice_FunctionalCI`.`finalclass` AS `finalclass`,cast(concat(coalesce(`VirtualDevice_FunctionalCI`.`name`,\'\')) as char charset utf8mb4) AS `friendlyname`,coalesce((`VirtualDevice`.`status` = \'obsolete\'),0) AS `obsolescence_flag`,`VirtualDevice_FunctionalCI`.`obsolescence_date` AS `obsolescence_date`,cast(concat(coalesce(`Organization_org_id`.`name`,\'\')) as char charset utf8mb4) AS `org_id_friendlyname`,coalesce((`Organization_org_id`.`status` = \'inactive\'),0) AS `org_id_obsolescence_flag` from (`itop27`.`virtualdevice` `VirtualDevice` join (`itop27`.`functionalci` `VirtualDevice_FunctionalCI` join `itop27`.`organization` `Organization_org_id` on((`VirtualDevice_FunctionalCI`.`org_id` = `Organization_org_id`.`id`))) on((`VirtualDevice`.`id` = `VirtualDevice_FunctionalCI`.`id`))) where 1
